#---No Comment---
#this file is used to define the filter parameters of all replaceable parts for access devices, such as optical modules.
# the replaceable parts object type, such as optical modules
# one of the enumeration: opticalmodule(must)
object_type=opticalmodule

# NE type, blank by default (optional)
ne_type=

#================ non-standard electronic label. The following fields together make up hardware information: ================
# vendor's name, blank by default (optional)
vender_name=

# vendor's PN code, blank by default (optional)
vender_PN=

# vendor's SN code, blank by default (optional)
vender_SN=

# manufacture date, blank by default (optional)
# YYYY-MM-DD format
# If you enter Year A-Year B, parts manufactured within that period will be searched out. If you enter Year A/Month A-Year B/Month B, parts manufactured within that period will be searched out. If you enter Year A/Month A/Day A-Year B/Month B/Day B, parts manufactured within that period will be searched out.
# Enter a date in one of the following formats: (1), 2012 (2), 2012/03 (3), 2013/03/01 (4), 2012-2013 (5), 2012/01-2013/02 (6), 2012/01/03-2013/02/10
date=
