#---No Comment---
#This file is used to define the filter parameters of all replaceable parts for access devices, such as boards.
# the replaceable parts object type, such as board, emu, cabinet
# one of the enumeration: board/emu/cabinet (must)
object_type=cabinet

# NE type, blank by default (optional)
ne_type=

#================ electronic bar code. The entire code is optional. However, if the code has data, all the following fields must be combined:================
#================ There are two types of bar codes for boards. One is a 16-character code for manufactured boards, such as 021BQW10B5000139. The other is a 20-character code for modules, such as 21980305223GD3000026. ================
# type code, blank by default (optional)
type_code=
# P/N code, blank by default (optional)
pn_code=
# EMS code, blank by default (optional)
#EMS code, 10 for Huawei
ems_code=
# date, blank by default (optional)
# YYYY/MM format.
# If you enter Year A, parts manufactured in that year will be searched out. If you enter Year A/Month A, parts manufactured in that year and that month will be searched out.
# If you enter Year A-Year B, parts manufactured within that period will be searched out. If you enter Year A/Month A-Year B/Month B, parts manufactured within that period will be searched out.
# Enter a date in one of the following formats: (1), A (2), A2 (3), A-C (4), A1-C2
date=
