Title = Backup is in progress... Please wait.
CheckParam=Check command line parameters
CheckRemoteRerver=Check remote server parameters
BackupDataModel=Backup data model
AnalyzeStaticData=Analyze static data
CheckDatabaseConnection=Check database connection
PreBackupFileScript=Execute pre backup file scripts
BackupFiles=Backup files for component {1} on node {0}
BackupFilesEnd=Backup files for component
PostBackupFileScript=Execute post backup file scripts
PreBackupDBScript=Execute pre backup database scripts
BackupDatabase=Backup database:{0}
BackupDatabaseEnd=Backup database
PostBackupDBScript=Execute post backup database scripts
CompressData=Put all files in a zip file
Checksum=Check sign for backup files
TransferData=Transfer files to remote server
BackupSuccess=Backup finished
BackupFailed=Backup failed:{0}
Progress=Progressing
Finish=OK
DumpFailedDetails=Failed database names:{0} @nCheck the log to get details: {1}
MissXmlfileDetails=Install/etc/database floder miss xml files,names :{0}
BcpFailedDetails=Failed database names:{0}  @nFailed table names:{1} @nCheck the log to get details: {2}
