<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT COMMINIDATA ( AREADESC+ ) >

<!ELEMENT AREADESC ( DESC* ) >
<!ATTLIST AREADESC areaname CDATA #IMPLIED >

<!ELEMENT DESC ( PARAS, DESC* ) >
<!ATTLIST DESC descname CDATA #IMPLIED >


<!ELEMENT PARAS ( PARA* ) >


<!ELEMENT PARA ( VALUE* ) >
<!ATTLIST PARA name CDATA #REQUIRED >
<!ATTLIST PARA type CDATA #IMPLIED >
<!ATTLIST PARA value CDATA #IMPLIED >

<!ELEMENT VALUE EMPTY >
<!ATTLIST VALUE type CDATA #IMPLIED >
<!ATTLIST VALUE value CDATA #REQUIRED >

