#License check and ClientUpgrade
#copy license file to target place
TargetLicenseFile=server/etc/conf/license/

#read this path for gui
SourceLicenseFile=

#whether not allow to modify the install dir. Yes - can not modify, No - can modify
IsFixedInstallFolder=no

##set the preserve space(MB)
SpaceRequiredForInstall=1024

#reuse db or not. U2000-false, M2000-true
ReuseDBMode=false

##default OSS folder permission
DefaultOSSPermission=750
###check slave/standby already start the deam process or not. If value is yes,then it will prompt to user reuse old jars or not,
###If value is no, then it will kill the slave/standby or new node process and transfer the master package to nodes
isNotUpdateInstallDaem=no

##Incremental installation/Add node mode, whether need to keep the slave/standby process
##if value is yes,means don't need kill slave process when failed.Otherwise will kill
isKeepInstallDaem=no
##exec script timeout
ScriptTimeOut=3600

LastErrorInfoFile=logs/InstallDiskErrorInfo.log 

#IF Not Auto Create DbUser option. false-if dbuser not exist, then create it.  true-if dbuser not exist, then report error.
#only used for sybase and sql server
isNotAutoCreateDbUser= false

#IF Not Reset DbUserPwd option. false-will reset the dbuser pwd during installation  true-if user input is not right pwd, then report error
#only used for sybase and sql server
isNotResetDbUserPwd=false

#if force check the db server name,only used for distribute sybase.
#false - force check the db server name is correct or not
isNotCheckDbServer=false

# default is 1 , and range is [1,50]
Unzip7zThread=1


# If this configuration item is true, then the installation, incremental installation process begins,
# The first task will copy the installation disk to install and engineering directory file oss / engr directory
#(Must exclude 7z files and install the framework program files, 
#just copy the package description files and solutions customized content)
CopyEngrFiles=true

#script retry times , if the script execution is success and log size is 0, will retry to configured.
ExecScriptNoMsgRetryTime=0

#when 126 errorcode, retry exec time.default value is 3
SCRIPT_ERROR_RETRY_TIME=3

#when 126 errorcode, sleep time, unit is second
SCRIPT_ERROR_SLEEP_TIME=120

#false - check remote db trust.		true - not  check remote db trust
NotCheckRemoteDBTrust=false

#down zip file from package source node retry times.the default value is 60.the min value is 1, the max value is 100
retryDownZipFileTimes=60

#login the slave node times
retryLoginSlaveTimes=300

#down zip file from package source node,wait time,the davelu value is 1 second.
#the min value is 1, the max value is 100.unit is second.
retryDownZipFileSleep=1

#master compress the ./server/oss file time.
maxCompress7zTimeout=3600

#addNode wait time from master node tar.gz file.
maxWait7ztarTimeout=7200

#when copy /opt/ossCompressTmp.tar from master node more than maxCopyTarNodeNumber, it will wait in queue.the default value is 20
#the min value is 1.
maxCopyTarNodeNumber=20

#optional.when all node finish, it will call this script.it support only one script file.it will support macro.
TotalExitScript=

#optional.when all node finish, it will call this script.it support only one script file.it will support macro.
AddNodeExitHandleScript=

#the default value is false means uniep don't refresh static file permission ,U2000 will do it.
NotRefreshPermission=false

#only add the DB node or dbinfo need read the flag ,means not run addnode workflow ,M2000 will do it.
RunWorkflowOnlyForAddDB=false

#precheck script timeout
precheckTimeout=900

SUDOBINPATH=/opt/sudobin/
OSSUSER_NAME=ossuser
DBUSER_NAME=dbuser

#DefaultDBIPEditFlag default value is true(ip text can edit)，,false(can't edit)
#this param just effect U2000 single install。
DefaultDBIPEditFlag=true

#before split ha , execute check data status is up-to-date or not , default value is 2 minutes
HASplitRepstatusTimeout=2