# Define is a serious error during installation error code range. The format xx-yy, multiple ranges separated by a carriage return.
# Solaris and linux because the shell can only return error codes 0-255. Of which there are 1 - 2 126 - 165 and 255 have a special meaning, can not be used.
# So only the domain assigned to each error code 20.
# Mounting frame and deployment tools to perform product deployment script, if the script returns an error code defined here will terminate the installation.
# Error code of the fields required by the scope of the definition and scope of the following discretionary.
# Engineering Platform: 50-69
# IMAP Platform: 70-89
# Network :90-109
# Wireless :170-189
# CMC :190-209
# NBI :210-229
# Non-serious errors can be returned directly one (or the other is not in the range of non-zero value), these error codes will not cause the installation to terminate only in engineering logging.

50-51

#script timeout error code
1509002-1509002