about.version=$U2000Component_Client_VersionName
about.desc=Provides the function of configuring centralized security policies,anti-attack and nat funciton. 
secpolicymgr = Security Policy  Management