# 
#Mon Jul 03 17:29:34 BRT 2023
key.cache.jws=C\:\\ProgramData\\cache
isNormalShortcut=true
isCreateShortcutonDesktop=true
current.shortcut.parent.folder.name=Network Management System
cau.binded.url.base=https\://192.168.10.107\:443/
jnlp.cau.dir.root.name=NMSROOT
