#---No Comment---
# this file is used to define the filter parameters of all replaceable parts for access devices, such as boards, optical modules and ONT.

# the replaceable parts object type, such as boards, optical modules and ONT
# one of the enumeration: ont, board, olt_opticalmodule, backboard  (must)
object_type=ont

# ONT type (max 32 byte), blank by default (optional)
ne_type=

# ONT software version (max 32 byte), blank by default (optional)
ne_software_version=

# ONT hardware version (max 16 byte), blank by default (optional)
ne_hardware_version=

# ONT vendor (integer), blank by default (optional)
ne_vendor=

# Extended field of description (max 256 byte), blank by default (optional)
description_extend_1=

# Extended field of description (max 256 byte), blank by default (optional)
description_extend_2=

#================ 21 bar code. The entire code is optional. However, if the code has data, all the following fields must be combined.================
# Type code (2 byte), 21 generally    (must)
barcode_type_code=

# P/N code (8 byte), blank by default (must)
barcode_pn_code=

# EMS code (2 byte), blank by default (optional)
barcode_ems_code=

# date (2 byte), blank by default (optional)
# Y/M format; Year (1 byte) A-Z, A-2010; Month (1 byte) 1-C.
# If you enter Year A, parts manufactured in that year will be searched out. If you enter Year A/Month A, parts manufactured in that year and that month will be searched out.
# If you enter Year A-Year B, parts manufactured within that period will be searched out. If you enter Year A/Month A-Year B/Month B, parts manufactured within that period will be searched out.
barcode_date=
