RC_AdvancedSwitchService_CN=com.swimap.cmc.domain;com.swimap.cmc.dualhome
#RC_CBB_3rdTools=
RC_CBB_CN=com.swimap.omc.common.cn
RC_CBB_Comm=com.swimap.omc.common;com.swimap.omc.dynamicupgrade;com.swimap.omc.ftp;com.swimap.omc.itm;com.swimap.omc.omctest
RC_CmDcService_CN=com.swimap.cmc.synchronize
RC_CMEngine_CN=com.swimap.cmc.devsearch
RC_CMEngine_Comm=com.swimap.omc.cm;com.swimap.omc.springscript
RC_CMServer_Comm=com.swimap.omc.mml;com.swimap.omc.topoclient
RC_DevDocService_Comm=com.swimap.omc.devDoc
RC_FarsService_CN=com.swimap.omc.trace.cn
RC_FarsService_Comm=com.swimap.omc.trace
RC_FaultService_Comm=com.swimap.omc.fm
#RC_NeUserService_CN=
RC_NeUserService_Comm=com.swimap.omc.sm
RC_NGNFullFillService_CN=com.swimap.cmc.service
RC_NGNTestManageService_CN=com.swimap.cmc.linetest;com.swimap.cmc.testplatform
RC_NHCService_CN=com.swimap.cmc.nhc;nhc
RC_NIMServer_Comm=com.swimap.omc.devmap
RC_PMService_Comm=com.swimap.omc.pm;com.swimap.omc.rtb
RC_ProxyServer_Comm=com.swimap.omc.lmt
RC_ScriptServer_Comm=com.swimap.iscript.app
RC_SWMService_CN=com.swimap.cmc.swm
RC_SWMService_Comm=com.swimap.omc.nelog;com.swimap.omc.swm
RC_UAPService_CN=com.swimap.cmc.lmt
RC_XFTPService_Comm=com.swimap.omc.xftp
