################################################################
#
#         subsystemmapping.properties变更流程:
#       http://10.71.227.166/index.php?doc-view-264
#
################################################################


#===============================================================
#        1. 默认加载 
#===============================================================
basic=base;cbb;


#===============================================================
#        2. 按域加载 
#===============================================================
trans=ason_otn;ason_sdh;cmdclient;trans_common;nemgr_trans;nemgr_ext;nemgr_marine;nemgr_naotn;nemgr_rtn;nemgr_otn;nemgr_sdh;nemgr_wdm;nemgr_ptn;nemgr_cnm;mds_wdm_cms;health_check;

ip=ip_base;ip_common;ip_gcli;ip_gctl;nemgr_router;pnp;seccomm;secvpnmgr;secpolicymgr;secnemgr;nemgr_vmf;nemgr_switch;ip_pathviewer;nemgr_ip;

access=access;ip_common;nemgr_switch;ip_gctl;



#===============================================================
#        3. 按子系统加载 
#===============================================================
# V1R5C00 BBIT2 2011-2-22 Access wangfeng 00109164 新增 nemgr_bits
subsystem=env;dc;pm;nml_common;xftp;unitedmgr;im_phy;nml_eth;nml_cps;nml_ip;nml_otn;nml_sdh;nml_vlan;nemgr_bits;trans_fault_diag;