# This service must use a thread-per-connection model to enable the
# server to block in a dedicated thread, i.e., one for each client.
# The concurrency service will not run in the reactive model.
static Server_Strategy_Factory "-ORBconcurrency thread-per-connection"
static Client_Strategy_Factory "-ORBTransportMuxStrategy exclusive -ORBConnectStrategy blocked" 
static Resource_Factory "-ORBProtocolFactory SSLIOP_Factory -ORBFlushingStrategy blocking"
dynamic SSLIOP_Factory Service_Object * TAO_SSLIOP:_make_TAO_SSLIOP_Protocol_Factory() 
"-SSLAuthenticate NONE 
-SSLCApath ..\client\style\defaultstyle\conf\ssl/trust/PEM/
-SSLVersion TLSvx
-SSLCipherSuiteList HIGH:!ADH
-SSLCAfile PEM:..\client\style\defaultstyle\conf\ssl\trust/PEM/trust.cer
"
static Resource_Factory "-ORBConnectionPurgingStrategy lru -ORBConnectionCacheMax 200 -ORBConnectionCachePurgePercentage 20"