log4j.logger.com=INFO,B
log4j.appender.B=org.apache.log4j.RollingFileAppender
log4j.appender.B.File=logs/rpc.log
log4j.appender.B.layout=org.apache.log4j.PatternLayout
log4j.appender.B.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS 'UTC'Z}[%5p][%C.java:%L %M()][%t] - %m%n
log4j.appender.B.FILE.MaxFileSize=10MB
