###### standard #########
@{CPUNUMBER}=
@{GroupName}=
@{INSDBPORT}=
@{INSDBSERVERNAME}=
@{INSDBADMINUSR}=
@{INSDBADMINPAD}=^{INSDBADMINPADSEC}
@{INSDBADMINPADSEC}=
@{INSDBTYPE}=
@{INSNMSDBUSER}=
@{INSNMSDBUSERPWD}=^{INSNMSDBUSERPADSEC}
@{INSNMSDBUSERPADSEC}=
@{INSTALLROOT}=
@{LicenseProductName}=
@{LicenseProductVersion}=
@{OS}=
@{OSMAJORVER}=
@{OSMINORVER}=
@{OSPRODUCTTYPE}=
@{PHYSICSMEMORY}=
@{UserHomeDir}=
@{UserName}=
@{OSSENGRROOT}=
@{OSSJRE}=
@{IMAP_ROOT}=
@{INSDBSERVERIP}=
@{INSLANGUAGE}=
@{LocalIP}=
@{LocalFloatIP}=
@{MasterFloatIP}=
@{INSFILEENCODING}=
@{INSTALLDISKROOT}=
@{InstallMode}=
@{LocalHostname}=
@{LocalPrivateIP}=
@{MasterHostname}=
@{MasterIP}=
@{MasterPrivateIP}=
@{MasterID}=HOST01
@{LocalID}=HOST01
@{NodeType}=
@{OSDBUserName}=
@{DBINSTALLROOT}=
@{LOCAL_DBSERVERNAME}=
@{BusinessType}=
@{NodeChangeType}=
@{OSS_OS_TYPE}=
@{DBDEVICEPATH}=
@{OSDBUserGroup}=
@{HAType}=
@{REMOTE_HAIP}=
@{OnlyLocalIPFlag}=
#### castoff ########
@{DBPassword}=^{INSNMSDBUSERPADSEC}
@{DBServerName}=
@{DBServerPort}=
@{DBAdminPAD}=^{INSDBADMINPADSEC}
@{DBAdminUSR}=
@{DBTYPE}=
@{DBUser}=
@{DISKSPACE}=
@{DistMode}=
@{domainName}=
@{OSSICMRROOT}=
@{IMAPNAME_LCT}=
@{IMAPROOT}= 
@{INSCLIENTCOUNTRY}=US
@{INSCLIENTLANG}=en
@{INSDBMSINSTALLDIR}=
@{INSHOSTNAME}=
@{INSIMAPLANG}=
@{INSMDPIP}=
@{INSSERVERLANG}=
@{INSTALL_LIBROOT}= 
@{LOCALIP}=
@{MASTERPUBLICIP}=
@{NODE_NAME}=
@{NODE_PASSWORE}=
@{NODE_PRIVATE_IP}=
@{NODE_PUBLIC_IP}=
@{NODE_TYPE}=@{NodeType}
@{PATCHPKGDIRPATH}=
@{PROFILELANG}=
@{SCRIPTLANGUAGE}= 
@{ServerSetupMode}=
@{USER_INPUT_DIR}=
@{UserRoot}=
@{SOURCEVERSION}=
@{UPGRADETOOL_BACKUPPATH}=
@{CURRENTPATH}=
@{LANG_COUNTRY}=
@{OLDINSTALLPATH}=
@{ISGUI}=
@{mode}=
@{UserRoot}=
@{isDual}=

##patch
@{OSS_ROOT}=
@{LOCAL_HOSTTAGNAME}=
@{MASTER_HOSTTAGNAME}=
@{LOCAL_DBSERVERNAME}=
@{MASTER_DBSERVERNAME}=
@{ALL_DBSERVERNAMES}=
@{MASTER_FLOATIP}=
@{HOST_TYPE}=
@{SWAP_DIR}=
@{BACKUP_FILE_PATH}=
@{COMMON_ENV_SCRIPT}=
@{BACKUP_PATH_PACKAGE}=
@{TMP_PLUGIN_DIR}=
@{INSLANGUAGE}=
@{DEPLOY_TYPE}=
@{BACKUPDIR}=
