# MSuite server version
version = UniEP
# TCP port
port = 12214
# Large File Transfer port
lport = 12215
# SiteID
siteid=0
serverid=82151023582
#minimum unit of datatransfer 0.5MB
chunksize=512384
connection_share_count=1
connection_count=20
