<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="tLic">
	    <xs:sequence>
	        <xs:element name="LSN" type="xs:string"/>
			<xs:element name="Esn" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="tInfo">
		<xs:attribute name="createTime" type="xs:dateTime" use="required"/>
        <xs:attribute name="operator" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="tIndex">
		<xs:sequence>
		    <xs:element name="Info" type="tInfo"/>
			<xs:element name="Lic" type="tLic" maxOccurs="unbounded"/>
		</xs:sequence>
        <xs:attribute name="formatVersion" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:element name="Index" type="tIndex"/>
	
</xs:schema>