about.version=$U2000Component_Client_VersionName
about.desc=Provides the performance management, involving monitoring performance, managing thresholds, querying performance data, and managing performance reports.
pm=Performance Management System
