## 部署工具 资源文件
# 命令行接口的资源
[CMDLINE]
CMDLINE_EXAMPLE_DEPLOYDOMAIN=按域部署：deploy -ip 127.0.0.1 -port 12212 -username admin deploydomain -domain Access
CMDLINE_EXAMPLE_UNDEPLOYDOMAIN=按域去部署：deploy -ip 127.0.0.1 -port 12212 -username admin undeploydomain -domain Access
CMDLINE_DEPLOY_DOMAIN=域名称
CMDLINE_DOMAIN_DEPLOY=按域部署
CMDLINE_UNDEPLOY_DOMAIN=域名称
CMDLINE_DOMAIN_UNDEPLOY=按域去部署
CMDLINE_QUOTE_DOMAINNAME=域名称，其中可选值包括Access，Trans，IP(分别表示接入域，传送域，IP域)
CMDLINE_EXAMPLE_DEPLOYDOMAIN_BT=按域部署：deploy deploydomain -domain Access
CMDLINE_EXAMPLE_UNDEPLOYDOMAIN_BT=按域去部署：deploy undeploydomain -domain Access
CMDLINE_QUOTE_CONFIGFILE=配置文件路径
