 ### This is used for the  IviewLogger to log messages to file. Don't change the file###
 ### file appender
 ### If someone wants to trace to console only then he can write 
 ### log4j.rootLogger=trace,stdout
 ### If someone wants to trace to both console and file, he can write 
 ### log4j.rootLogger=trace,stdout,file
 ### Don't change.
log4j.rootLogger=all,file

### File appender it Don't change.
log4j.appender.file=com.swimap.tool.common.util.ToolRollingFileAppender

### Max file size. Don't change.
log4j.appender.file.maxFileSize=5MB

### Back up files 20 by default.
log4j.appender.file.maxBackupIndex=60

### Folder name and file name. By default tracefile is the folder and 
### Debugtrace.txt is file. Business module can edit these two properties.
### Don't change.
log4j.appender.file.File=tracefile/DebugTrace.txt

### Lay Don't edit.
log4j.appender.file.layout=org.apache.log4j.PatternLayout
## Set the format of the log file.Don't change.
log4j.appender.file.layout.ConversionPattern=[%t%x]%d{M-d-yyyy HH:mm:ss} | %-5p | %c | %M | %m  %n

### Consloe appender.Don't change.
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern= [%t%x]%d{M-d-yyyy HH:mm:ss} | %-5p | %c | %M | %m  %n
