Title = 备份正在进行中，请您稍候...
CheckParam=校验命令参数
CheckRemoteRerver=校验远程服务器参数
BackupDataModel=备份数据模型
AnalyzeStaticData=分析静态数据
CheckDatabaseConnection=检查数据库服务是否运行
PreBackupFileScript=执行备份文件前置脚本
BackupFiles=备份节点{0}的组件{1}的配置文件
BackupFilesEnd=备份组件配置文件
PostBackupFileScript=执行备份文件后置脚本
PreBackupDBScript=执行备份数据库前置脚本
BackupDatabase=备份数据库：{0}
BackupDatabaseEnd=备份数据库
PostBackupDBScript=执行备份数据库后置脚本
CompressData=生成压缩包
Checksum=对备份压缩包进行签名
TransferData=传输备份文件
BackupSuccess=备份完成
BackupFailed=备份失败：{0}
Progress=进行中
Finish=完成
DumpFailedDetails=备份失败的数据库：{0} @n具体信息请查看日志： {1}
MissXmlfileDetails=Install/etc/database 目录丢失数据库描述文件 :{0}
BcpFailedDetails=备份失败的数据库：{0} @n备份失败的表：{1} @n具体信息请查看日志： {2}
