#
#Wed Aug 05 05:39:55 GMT+05:30 2009
RemoteLogFileName=product_debug_log.log
InstallDiskFile=imapinstall.zip
SybaseInterfacesFile=engineering/DeployOutput/interfaces
UpgradeOrPatchFile=/tmp/UpgradeScriptWithFolder.zip
ConfigExport=engineering/conf/config/ConfigExport.xml
SSHUserName=root
NMSDir=/opt/oss
SybaseUserName=sa
SSHSessionTimeOut=900
isShowUpgradeOrPatch=false
OracleUserName=system
InstallSpace=4000
FTPUserName=ftpuser
isFTPUserNameEditable=true
CopyToDir=/tmp/DeployTool
OracleRACFile=engineering/DeployOutput/tnsnames.ora
OracleRacPath=/etc/config
MaxDeployThreads=5
SybaseInterfacesPath=/etc/config
ftpFileDir=/version/update
isOffLine=false
DeployMode=0
