
#####Menu List#####
[SystemMenu]

#Menu Item: Enable Switch 2101
EnableSwitchMenuAction.MenuOrder=2101
EnableSwitchMenuAction.Mnemonic=U
EnableSwitchMenuAction.isDisplayOnMenu=true
EnableSwitchMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Disable Switch 2102
DisableSwitchMenuAction.MenuOrder=2102
DisableSwitchMenuAction.Mnemonic=F
DisableSwitchMenuAction.isDisplayOnMenu=true
DisableSwitchMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Refresh OSS Data 2103
RefreshNMSMenuAction.MenuOrder=2103
RefreshNMSMenuAction.Mnemonic=R
RefreshNMSMenuAction.isDisplayOnMenu=false
RefreshNMSMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Synchronize OSS Data 2104
SyncNMSMenuAction.MenuOrder=2104
SyncNMSMenuAction.Mnemonic=S
SyncNMSMenuAction.isDisplayOnMenu=false
SyncNMSMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Add Slave Server 2105
AddSlaveNodeMenuAction.MenuOrder=2105
AddSlaveNodeMenuAction.Mnemonic=A
AddSlaveNodeMenuAction.isDisplayOnMenu=false
AddSlaveNodeMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Remove Slave Server 2106
RmSlaveNodeMenuAction.MenuOrder=2106
RmSlaveNodeMenuAction.Mnemonic=M
RmSlaveNodeMenuAction.isDisplayOnMenu=false
RmSlaveNodeMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Initialize OSS  2107
InitalMenuAction.MenuOrder=2107
InitalMenuAction.Mnemonic=I
InitalMenuAction.isDisplayOnMenu=true
InitalMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Change Password 2108
ChangeDTClientPWDMenuAction.MenuOrder=2108
ChangeDTClientPWDMenuAction.Mnemonic=C
ChangeDTClientPWDMenuAction.isDisplayOnMenu=true
ChangeDTClientPWDMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Screen Lock 2109
LockScreenMenuAction.MenuOrder=2109
LockScreenMenuAction.Mnemonic=L
LockScreenMenuAction.isDisplayOnMenu=true
LockScreenMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Logout 2110
LogoutMenuAction.MenuOrder=2110
LogoutMenuAction.Mnemonic=O
LogoutMenuAction.isDisplayOnMenu=true
LogoutMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Exit 2111
ExitDTMenuAction.MenuOrder=2111
ExitDTMenuAction.Mnemonic=E
ExitDTMenuAction.isDisplayOnMenu=true
ExitDTMenuAction.isDisplayOnPopupMenu=false

[/SystemMenu]

#####Deploy Menu#####
[DeployMenu]
#Menu Item: Add Component 2201
AddComponentMenuAction.MenuOrder=2201
AddComponentMenuAction.Mnemonic=A
AddComponentMenuAction.isDisplayOnMenu=false
AddComponentMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Remove Component 2202
DelComponentMenuAction.MenuOrder=2202
DelComponentMenuAction.Mnemonic=R
DelComponentMenuAction.isDisplayOnMenu=false
DelComponentMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Add Instance 2203
AddInstanceMenuAction.MenuOrder=2203
AddInstanceMenuAction.Mnemonic=I
AddInstanceMenuAction.isDisplayOnMenu=false
AddInstanceMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Remove Instance 2204
RmInstanceMenuAction.MenuOrder=2204
RmInstanceMenuAction.Mnemonic=D
RmInstanceMenuAction.isDisplayOnMenu=false
RmInstanceMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Move Instance 2205
MoveInstanceMenuAction.MenuOrder=2205
MoveInstanceMenuAction.Mnemonic=M
MoveInstanceMenuAction.isDisplayOnMenu=false
MoveInstanceMenuAction.isDisplayOnPopupMenu=false

#Menu Item: License Deployment 2206
LicenseDeployMenuAction.MenuOrder=2206
LicenseDeployMenuAction.Mnemonic=Y
LicenseDeployMenuAction.isDisplayOnMenu=false
LicenseDeployMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Modify Instance Information 2207
ChangeInsInfoMenuAction.MenuOrder=2207
ChangeInsInfoMenuAction.Mnemonic=F
ChangeInsInfoMenuAction.isDisplayOnMenu=false
ChangeInsInfoMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Change Database Administrator Password 2208
ChangeDBSaPWDMenuAction.MenuOrder=2208
ChangeDBSaPWDMenuAction.Mnemonic=S
ChangeDBSaPWDMenuAction.isDisplayOnMenu=true
ChangeDBSaPWDMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Change Database User Password 2209
ChangeDBOSSUserPWDMenuAction.MenuOrder=2209
ChangeDBOSSUserPWDMenuAction.Mnemonic=P
ChangeDBOSSUserPWDMenuAction.isDisplayOnMenu=true
ChangeDBOSSUserPWDMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Change Time Zone 2210
ChangeTimeZoneMenuAction.MenuOrder=2210
ChangeTimeZoneMenuAction.Mnemonic=T
ChangeTimeZoneMenuAction.isDisplayOnMenu=true
ChangeTimeZoneMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Configure NTP 2211
ConfigNTPMenuAction.MenuOrder=2211
ConfigNTPMenuAction.Mnemonic=C
ConfigNTPMenuAction.isDisplayOnMenu=true
ConfigNTPMenuAction.isDisplayOnPopupMenu=true

#Menu Item: Synchronize Primary and Secondary Sites 2212
JoinHAMenuAction.MenuOrder=2212
JoinHAMenuAction.Mnemonic=H
JoinHAMenuAction.isDisplayOnMenu=true
JoinHAMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Separate Primary Site from Secondary Site 2213
SplitHAMenuAction.MenuOrder=2213
SplitHAMenuAction.Mnemonic=E
SplitHAMenuAction.isDisplayOnMenu=true
SplitHAMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Force Active of Local Site 2214
ForcePrimaryMenuAction.MenuOrder=2214
ForcePrimaryMenuAction.Mnemonic=O
ForcePrimaryMenuAction.isDisplayOnMenu=true
ForcePrimaryMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Delete Replication 2215
DeleteRepMenuAction.MenuOrder=2215
DeleteRepMenuAction.Mnemonic=L
DeleteRepMenuAction.isDisplayOnMenu=false
DeleteRepMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Dual Primary 2216
DualPrimaryMenuAction.MenuOrder=2216
DualPrimaryMenuAction.Mnemonic=N
DualPrimaryMenuAction.isDisplayOnMenu=false
DualPrimaryMenuAction.isDisplayOnPopupMenu=false

[/DeployMenu]

#####NBI Menu#####
[NBIMenu]
#Menu Item: Config CORBA Interface Instance 2301
#Menu Item: Config SNMP Interface Instance 2302
#Menu Item: Config XML Interface Instance 2303
#Menu Item: Config TEXT Interface Instance 2304
[/NBIMenu]

#####Storage Menu#####
[StorageMenu]
#Menu Item: Back Up System Data 2401
BackupMenuAction.MenuOrder=2401
BackupMenuAction.Mnemonic=B
BackupMenuAction.isDisplayOnMenu=true
BackupMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Restore System Data 2402
RestoreMenuAction.MenuOrder=2402
RestoreMenuAction.Mnemonic=R
RestoreMenuAction.isDisplayOnMenu=true
RestoreMenuAction.isDisplayOnPopupMenu=false
[/StorageMenu]

#####Certificate Replacement Menu#####
[CertReplaceMenu]
#Menu Item: Certificate Replacement 2501
CertReplaceEngrMenuAction.MenuOrder=2501
CertReplaceEngrMenuAction.Mnemonic=M
CertReplaceEngrMenuAction.isDisplayOnMenu=true
CertReplaceEngrMenuAction.isDisplayOnPopupMenu=false
[/CertReplaceMenu]

#####Tools Mesnu#####
[CommissioningTool]
#Menu Item: Commissioning Tool 2601
CommissioningMenuAction.MenuOrder=2601
CommissioningMenuAction.Mnemonic=C
CommissioningMenuAction.isDisplayOnMenu=true
CommissioningMenuAction.isDisplayOnPopupMenu=false
[/CommissioningTool]

#####Help Menu#####
[HelpMenu]
#Menu Item: Help Topic 2801
HelpMenuAction.MenuOrder=2801
HelpMenuAction.Mnemonic=H
HelpMenuAction.isDisplayOnMenu=true
HelpMenuAction.isDisplayOnPopupMenu=false

#Menu Item: About 2802
AboutMenuAction.MenuOrder=2802
AboutMenuAction.Mnemonic=A
AboutMenuAction.isDisplayOnMenu=true
AboutMenuAction.isDisplayOnPopupMenu=false
[/HelpMenu]


#####Popup Menu#####
[PopupMenu]
#Menu Item: Change IP Address and Hostname
ConfigNetworkMenuAction.MenuOrder=2901
ConfigNetworkMenuAction.Mnemonic=H
ConfigNetworkMenuAction.isDisplayOnMenu=false
ConfigNetworkMenuAction.isDisplayOnPopupMenu=true

#Menu Item: Configure Route
ConfigRouterMenuAction.MenuOrder=2902
ConfigRouterMenuAction.Mnemonic=R
ConfigRouterMenuAction.isDisplayOnMenu=false
ConfigRouterMenuAction.isDisplayOnPopupMenu=true

#Menu Item: Recover Node
RecoverNodeMenuAction.MenuOrder=2903
RecoverNodeMenuAction.Mnemonic=S
RecoverNodeMenuAction.isDisplayOnMenu=false
RecoverNodeMenuAction.isDisplayOnPopupMenu=false

#Menu Item: Synchronize Network Configuration
SyncNetworkConfigMenuAction.MenuOrder=2904
SyncNetworkConfigMenuAction.Mnemonic=N
SyncNetworkConfigMenuAction.isDisplayOnMenu=false
SyncNetworkConfigMenuAction.isDisplayOnPopupMenu=true

[/PopupMenu]