about.version=$U2000Component_Client_VersionName
about.desc=Provides basic shortcut menu items in the Main Topology, color codes for alarms, and client skins.
U2000_EM=U2000 Solution Function Management 