[VM_Paras]
#ClassLoader which will take care loading the jars to class path
-Djava.system.class.loader=com.swimap.startup.StartupClassLoader

#Keep the system property "ExtesionRegistry.cacheLazyLoading"
-DExtesnionRigestry.debug=true

#Keep the system property "ExtesionRegistry.cacheUse"
-DExtesionRegistry.cacheUse=true

#Keep the system property "ExtesionRegistry.cacheLazyLoading"
-DExtesionRegistry.cacheLazyLoading=true

#Enable the OSGI help for logger
-Diview.help.osgi=true

#Parameter define the parser type
-Dparsertype=2

#Serialization folder to which iview perform serialization
-DserFolder=

-Dfile.encoding=UTF-8

[Application Arguments]
-debuglevel=1
-showtrace=false
-enabledebug=true
-tracefile=tracefile/DebugTrace.txt


