#
#Mon Jul 03 17:29:34 BRT 2023
install=cauverify
configJRE=true
tempjrelocation=U2000_1574513174638_nmswindowsjre_1038490216/OSSJRE/jre_win
Windowsjresize=169715519
Windowsjreversion=1038490216
resourceprefix=U2000_1574513174638_
JRE_ENV_KEY=IMAP_JAVA_HOME
backup.path.exclude=jre/bin/trace
Windowsfilegroupname=U2000_1574513174638_nmswindowsjre
targetConfigJRE=jre
WindowsconfigJRE=OSSJRE/jre_win
