BACKUP_ERR_DB_STATUS_TITLE = Failed to execute the pre-processing script for database backup
BACKUP_ERR_DB_STATUS_DETAIL= The server\tools\backDbInfo\checkDBstatus.bat script for checking the database status fails to be executed. The database status may be abnormal. For details, see server\tools\logs\checkDBstatus.pyc_$date.log.
