############################################################################
#调测工具资源文件
############################################################################
#4. 主机名
[customize]
ModifyHostnameInstruction=If Windows Server 2008 system is used,Please refer to the U2000 Single-Server System Software Installation and Commissioning Guide (Windows) \n on "How to Change the Host Name of the Single-Server System (Windows 2008)" \nIf Windows 7 system is used,Please refer to the U2000 Single-Server System Software Installation and Commissioning Guide (Windows 7) \n on "How to Change the Host Name of the Single-Server System (Windows 7)" \nIf Windows 10 system is used,Please refer to the U2000 Single-Server System Software Installation and Commissioning Guide (Windows 10) \n on "How to Change the Host Name of the Single-Server System (Windows 10)" \n
[/customize]

#5. 控制卡
[Controller]
SC.Title=Control Card Config Instruction
SC.Info.Win=If Windows Server 2008 system is used,Please refer to the "Configuring the IMM IP Address of IBM server" or "Configuring the iMana IP Address of Huawei server" in U2000 Single-Server System Software Installation and Commissioning Guide (Windows) for more details.\nIf Windows 7 system is used,Please refer to the "Configuring the IMM IP Address of IBM server" or "Configuring the iMana IP Address of Huawei server" in U2000 Single-Server System Software Installation and Commissioning Guide (Windows 7) for more details.\nIf Windows 10 system is used,Please refer to the "Configuring the IMM IP Address of IBM server" or "Configuring the iMana IP Address of Huawei server" in U2000 Single-Server System Software Installation and Commissioning Guide (Windows 10) for more details.\n
SC.Info=If Solaris Single-Server system is used, see "Configuring Controller IP Address" in U2000 Single-Server System Software Installation and Commissioning Guide (Solaris).\nIf Solaris high availability system is used, see "Configuring Controller IP Address" in U2000 HA System (Veritas) Software Installation and Commissioning Guide (Solaris).\nIf Linux Single-Server system is used, see "Configuring Controller IP Address" in U2000 Single-Server System Software Installation and Commissioning Guide (SUSE Linux, PC Server).\nIf Linux local high availability system is used, see "Configuring Controller IP Address" in U2000 Local HA System (Veritas) Software Installation and Commissioning Guide (SUSE Linux, PC Server).\nIf Linux remote high availability system is used, see "Configuring Controller IP Address" in U2000 Remote HA System (Veritas) Software Installation and Commissioning Guide (SUSE Linux, PC Server).\n
DateTimeZone.Info=If Windows Server 2008 system is used,See How to Change the System Time and Time Zone of the Single-Server System on Windows in U2000 Single-Server System Software Installation and Commissioning Guide (Windows).\nIf Windows 7 system is used,See How to Change the System Time and Time Zone of the Single-Server System on Windows in U2000 Single-Server System Software Installation and Commissioning Guide (Windows 7).\nIf Windows 10 system is used,See How to Change the System Time and Time Zone of the Single-Server System on Windows in U2000 Single-Server System Software Installation and Commissioning Guide (Windows 10).\n
[/Controller]

#6. 防病毒软件
[VirusSoft]
VirusSoftCheck.Title=Tendence Anti-Virus Software
VirusSoftCheckPage.unintalled=uninstalled
VirusSoftCheckPage.intalled=installed
VirusSoftCheckPage.officeScanVer=Anti-Virus Software Version: 
VirusSoftCheckPage.virusVer=viruslib Version: 
VirusSoftCheckPage.Info=Please refer to the U2000 AntiVirus Software Deployment Guide (OfficeScan11.0) for more details.
[/VirusSoft]

#7. 修改密码
[PValue]
PValueReference=The Password Configuration tool supports password modification for the database administrator, database user, and MSuite administrator. For details about how to modify the system password, see chapter "How to Change the Password of the OS Administrator" in the Installation and Commissioning Guide.
VNC_ROOT=VNC Administrator
VNC_NMS=VNC NMS user
VCS_ADMIN=VCS Administrator
VNC_ROOT_PValue_RULE=
VNC_NMS_PValue_RULE=
VCS_ADMIN_PValue_RULE=<html>Password requirements:<br>&nbsp;1. Password must be 8-30 characters long,<br>&nbsp;2. Password must contain a combination of the following four characters:<br>&nbsp;&nbsp;&nbsp;&nbsp;at least a capital letters; <br>&nbsp;&nbsp;&nbsp;&nbsp;at least a small letters; <br>&nbsp;&nbsp;&nbsp;&nbsp;at least a digital;<br>&nbsp;&nbsp;&nbsp;&nbsp;at least a special characters. <br>&nbsp;&nbsp;&nbsp;&nbsp;Special characters only supports these characters: ~@#^*-_+[{}]:./? <br>&nbsp;3. Password and account or reverse account can't same.<br>&nbsp;</html>
PValue.83=Operate failed, have enabled security enhance, refer to Installation and Commissioning Guide "How to modify the operating system user password"
[/PValue]

#8. 告警配置
[Alarm]
Commissioning.Page.AlarmConfig=Alarm Configuration
AlarmConfigInstruction_lin=If the server or disk array does not function properly, an alarm is reported to the U2000.\n1: Check whether the controller IP address displayed on the GUI is the same as the actual controller IP address.\n2: Configure the IP addresses of the workstation controller and disk array controller. For details, see chapter "Configuring the Controller IP Address" in the U2000 Single-Server System Software Installation and Commissioning Guide (SUSE Linux) or U2000 Local HA System (Veritas) Software Installation and Commissioning Guide (SUSE Linux, PC Server).\n3: For the S3900 disk array, S2600 disk array, and OceanStor 5500 V3 disk array, you must configure the hardware alarm monitoring function. For details, see chapter "Configuring Hardware Alarm Monitoring" in the U2000 Single-Server System Software Installation and Commissioning Guide (SUSE Linux) or U2000 Local HA System (Veritas) Software Installation and Commissioning Guide (SUSE Linux, PC Server).
AlarmConfigInstruction=If the server or disk array does not function properly, an alarm is reported to the U2000.\n1: Check whether the controller IP address displayed on the GUI is the same as the actual controller IP address.\n2: Configure the IP addresses of the workstation controller and disk array controller. For details, see chapter "Configuring the Controller IP Address" in the U2000 Single-Server Software Installation and Commissioning Guide (Solaris) or U2000 High Availability System (Veritas) Installation and Commissioning Guide (Solaris).\n3: For the M4000/M5000 server, S3900 disk array, S2600 disk array, and OceanStor 5500 V3 disk array, you must configure the hardware alarm monitoring function. For details, see chapter "Configuring Hardware Alarm Monitoring" in the U2000 Single-Server Software Installation and Commissioning Guide (Solaris) or U2000 High Availability System (Veritas) Installation and Commissioning Guide (Solaris).
Server.ControlIP=Control IP
Disk.ArrayA.ControlIP=TrapA IP
Disk.ArrayB.ControlIP=TrapB IP
INPUT_IP_IS_NULL=Input IP is null.
INPUT_IP_ERROR=Input IP is invalid.
ALARM_CONFIG_SUCCESS=Alarm configuration succeed.
ALARM_CONFIG_FAILED=Alarm configuration failed.
[/Alarm]

#9. 网管证书
[NMSLicense]
Commissioning.Page.NMSLicense=OSS License
NMSLicense_Content_Win=Please refer the chapter of "Loading a U2000 License" in U2000 Single-Server System Software Installation and Commissioning Guide (Windows).\n
NMSLicense_Content=If Solaris Single-Server system is used, see "Loading a U2000 License" in U2000 Single-Server System Software Installation and Commissioning Guide (Solaris) to load the U2000 license in CLI mode.\nIf Solaris high availability system is used, see "Loading a U2000 License" in U2000 HA System (Veritas) Software Installation and Commissioning Guide (Solaris) to load the U2000 license in CLI mode.\nIf Linux Single-Server system is used, see "Loading a U2000 License" in U2000 Single-Server System Software Installation and Commissioning Guide (SUSE Linux, PC Server) to load the U2000 license in CLI mode.\nIf Linux local high availability system is used, see "Loading a U2000 License" in U2000 Local HA System (Veritas) Software Installation and Commissioning Guide (SUSE Linux, PC Server) to load the U2000 license in CLI mode.\nIf Linux remote high availability system is used, see "Loading a U2000 License" in U2000 Remote HA System (Veritas) Software Installation and Commissioning Guide (SUSE Linux, PC Server) to load the U2000 license in CLI mode.\n
[/NMSLicense]

#10. VCS许可证
[VCSLicense]
VCSLicense.Title=Set Veritas License
VCSLicense.Stand=VRTS STORAGE FOUNDATION:
VCSLicense.Option=VRTS REPLICATOR:
VCSLicense.HADR=VRTS CLUSTER SERVER:
VCSLicense.HighVersion=VRTS License:
VCSLicense.warm=A complete Veritas license includes VRTS STORAGE FOUNDATION, VRTS REPLICATOR, and VRTS CLUSTER SERVER. \nObtain the complete Veritas license. \nIf your license is incomplete, the HA system cannot work properly after registration. 
VCSLicense.warmTheSameKey=Duplicated keys. Enter again. 
VCSLicense.completeCheckfailed=License update failure. The license is incomplete.
VCSLicense.versionCheckfailed=License update failure. The license and Veritas versions do not match.
VCSLicense.workCheckfailed=License update failure. The license is invalid. 
VCSLicense.permissionCheckfailed=Failed to refresh license file permissions. 
VCSLicense.updateLicenseFailed=Update{0}failed!
VCSLicense.standlicense=The current VCS license is formal.
VCSLicense.templicense=The current VCS license is temporary.
VCSLicense.Failed=Update Veritas License failed.
VCSLicense.backupLicensefailed=Backup License failed.
VCSLicense.typeerror=Get Veritas License type failed.
VCSLicense.Succeed=Modification succeeded. It will take effect after restart the computer.
MACHINECTRL_UPDATELICENSE_SUCCESS=The update VRTS Licenses operation is successfully completed.
MACHINECTRL_UPDATELICENSE_FAILED=The update VRTS Licenses operation is failed.
VCSLicense.setlicense=set standard VCS License
INPUT_NOT_FULL=Please input all the license.
[/VCSLicense]

#11. 更新网管证书
[ReplaceNMSLicense]
Commissioning.Page.ReplaceNMSLicense=Set SSL Certificate
CertManage_Browse=Browse
CertManage_LIST_FILES=List of files
List_CERT_FILES_FAILED=Failed to list certificate files.
CertManage_Title=Certificate Configuration

CertManage_IdentityCertDesc=<html>An identity certificate is a digital document that identifies the identity of an entity, such as a user, a computer, or a service.<br/>A private key is an asymmetric cryptographic key that corresponds to the public key of an identity certificate.<br/>PKCS#12 is a Personal Information Exchange Syntax Standard. This standard format defines how the information on the private key and certificate of an entity is stored.<br/><b><font color='aa0000'>NOTE: </font>After updating identity certificates, update the associated trust certificate and reboot the MSuite server and client. Otherwise, you will be unable to log in to the MSuite client.</b></html>
CertManage_IdentityCertClientGroup=SSL Client Certificate
CertManage_IdentityCertServerGroup=SSL Server Certificate
CertManage_IdentityCertFile=File Name: 
CertManage_IdentityCertPwd=PFX Password: 

CertManage_Tab_IdentityCert=Identity Certificate
CertManage_ProvidePWD=Please provide certificate password.

CertManage_Tab_TrustCert=Trust Certificate
CertManage_TrustCert_Info=<html>The Certificate Rovocation List (CRL) is a list of certificates that have been revoked. The CRL is published and maintained by a certificate authority.</html>
CertManage_Tbl_IssueTo=Issued to
CertManage_Tbl_Issuer=Issued by
CertManage_Tbl_StartDate=Valid from
CertManage_Tbl_EndDate=Valid to
CertManage_Btn_Add=Add
CertManage_Btn_Del=Delete
CertManage_Btn_Confirm=OK
CertManage_Btn_Cancel=Cancel

CertManage_ConfirmToUpdate=Are you sure to update the trust certificate files?
CertManage_ConfirmToDelete=Are you sure to delete the trust certificate files?
CertManage_ConfirmTitle=Confirm
CertManage_ProvideFilePath=Please input the file path.

CertManage_SucceedUpdateTrustCert=Succeeded in updating trust certificate files.
CertManage_FailUpdateTrustCert=Fail to update trust certficate files.
CertManage_Fail=Error

CertManage_Code_1000=Succeeded in updating MSuite Client certificate.
CertManage_Code_1001=Succeeded in updating MSuite Server certificate.
CertManage_Code_1002=Succeeded in updating MSuite Trust certificate.
CertManage_Code_1004=After updating certficate it will rebuild cau, it will take about 15 minutes,\nPlease do not update certficate again during this time.
CertManage_Code_1005=Please update MSuite Client certificate and Trust certificate if have not updated.
CertManage_Code_1006=Please update MSuite Server certificate and Trust certificate if have not updated.
CertManage_Code_1007=Please update MSuite Trust certificate if have not updated.
CertManage_Code_1008=Please update MSuite Client and Server certificate if have not updated.

CertManage_Code_2000=Failed to update MSuite Client certificate.
CertManage_Code_2001=Failed to update MSuite Server certificate.
CertManage_Code_2002=Failed to update MSuite Trust certificate.
CertManage_Code_2003=Failed to update local Client Certificate as certificate file reading error.
CertManage_Code_2004=Failed to update local MSuite Client certificate.
CertManage_Code_2005=Failed to update local MSuite Client certificate as file not existing.

CertManage_Code_2010=Certificate file does not exist.
CertManage_Code_2011=The password is incorrect, please input again.
CertManage_Code_2013=Input parameter error, please input again.
CertManage_Code_2014=Failed to read certificate file.
CertManage_Code_2015=Trust Certificate file does not exist.
CertManage_Code_2016=The certificate content planned to add have been contained in the current certficate.
CertManage_Code_2017=Failed to updae certificate file on the following slave node.
CertManage_Code_2018=Failed to change permission on the following slave node.
CertManage_Code_2019=Failed to communicate between the primary node and the following slave node(s).
CertManage_PathOnServer=Please provide the absolute path of the Certificate on the NMS Server

CertManage_ProvideP12=The Identity Certificate should end with p12, please provide the right certificate.
CertManage_ProvideCer=The Trust Certificate should end with cer, please provide the right certificate.
The_following_Node_Not_Running=The following node(s) service is not running.
CertManage_Exit_Confirm_Msg=Certificate update does not complete, are you sure you want to exit update certificate?

START_CAU=Executing CAU, it will take about 15 minutes.
EXECUTE_CAU_SUCCEED=Execute CAU succeed.
EXECUTE_CAU_FAILED=Execute CAU failed.
CAU_RPC_INVOKE_FAILED=CAU Rpc invoke failed.

#Confirm button
BTN_CANCLE=Cancel
BTN_CONFIRM=OK
BTN_ADD=Add
BTN_DEL=Delete
BTN_YES=Yes
BTN_NO=No
TITLE_MSGDIG_INFORMATION=Information
TITLE_MSGDIG_SEVERE=Error
TITLE_MSGDIG_WARNING=Warning
[/ReplaceNMSLicense]

#13. 组网配置
[Network]
ONE_NIC=Single-NIC
TWO_NIC=Double-NIC
TWO_NIC_IPMP=Double-NIC(IPMP)
THREE_NIC=Three-NIC
FOUR_NIC=Four-NIC
SIX_NIC=Six-NIC
NetworkReference=If it is Windows Server 2008 system,please refer the chapter of "Configuring the IP Address(Windows 2008)" to set in Commissioning Guide.\nIf it is Windows 7 system,please refer the chapter of "Configuring the IP Address(Windows 7)" to set in Commissioning Guide.\nIf it is Windows 10 system,please refer the chapter of "Configuring the IP Address(Windows 10)" to set in Commissioning Guide.\n
GetNetSolutionErr=Failed to obtain network information.
NetworkSolution=Set network solution
CheckChangeSolution=Current is "{0}",Are you sure you want to switch to "{1}"?
Commissioning.Page.ConfigNetwork=Set network and config IP
INPUT_NIC_SAME=The NIC "{0}" is duplicated
INPUT_IP_SAME=The IP "{0}" is duplicated
INPUT_NETMASK_ERROR=Input netmask "{0}" is not correct
Solaris_Single=(Solaris single-server system)
Solaris_HA=(Solaris HA system)
Linux_Single=(Linux single-server system)
Linux_Localdual=(Linux local HA system)
Linux_Remotedual=(Linux remote HA system)
CURRENT_SULUTION_ISNOTFORMAL=No matching network solution is found in the current environment. Switch to the default network solution.
COL_NAME_INTERFACE=NIC TYPE
COL_NAME_NIC=NIC
COL_NAME_IPADDRESS=IP Adress
COL_NAME_NETMASK=Netmask
COL_NAME_IPTYPE=IP Type
MasterInterface={0} Master
SlaveInterface={0} Standby
FloatInterface={0} Float
NO_CHANGE_IS_THERE=Input network configuration is the same with system's configuration, please check.
EXECUTE_SCRIPT_FAILED=Script executed failed :"{0}"
MODIFY_NETWORK_FAILED=Config network failed.
Config_network_succeed=Config network successed.
MODIFY_NETWORK_SUCCESSED=Config network successed. It will take effect after restart the computer.
StartConfigNetwork=It will take about 10 minutes to config network.
INPUT_IP_USED=The entered IP address "{0}" is invalid. Check whether the IP address is used.
ConfigNetwrok_NEXT_STEP_PROMPT=Are you sure to execute config network?
INPUT_NIC_ISEMPTY=Inputed nic is not correct.
ModifyRebootSystem=The system configuration has been changed, please reboot the system first to take effect,can not modify the network configuration before the configuration takes effect.
CoinfgNetwork_NetworkCard_failure=Server NICs or NIC configurations are abnormal. Restore faulty NICs and try again.
[/Network]

#15. 安全加固
[SecuritySet]
Commissioning.Page.SecuritySet=Security Hardening
RunSecuritySet=Run the Security Set
RunSecuritySet_Running=Run the Security Set (Running)
RunSecuritySet_Not_Running=Run the Security Set (Not Running)
RunSecuritySet_installed=Run the Security Set (installed)
RunSecuritySet_uninstalled=Run the Security Set (uninstalled)
SecuritySet_installed=Security Set is installed
SecuritySet_uninstalled=Security Set is not installed
SecuritySetInstruction_Win=Please refer to the Windows OS Security Hardening Operation Guide for more details.\n
SecuritySetInstruction=Please enable the option to enhance the system.\n
SecuritySetWarning=There are risks if the Security Set is canceled, continue?
StartSecuritySet_Win=It will take about 20 minutes to execute security set.
StartSecuritySet=It will take about 10 minutes to execute security set.
SECURITY_SET_SUCCEED=Security Set succeed. It will take effect after restart the computer.
SECURITY_SET_SUCCEED_IN_MS=Security Set succeed.
SECURITY_SET_FAILED=Security Set failed.
SECURITY_SET_PROMPT=Security Set is already running, execute Security Set again?
SecuritySet_NEXT_STEP_PROMPT=Security Set is not running, execute it?
[/SecuritySet]

#16. 激活网卡
[ActiveNic]
CONFIG_NIC_PROCESS_DLG=Activating nic,please wait...
TOOLTIPTXT_CONFIGNICSUCCESS=active nic success. It will take effect after restart the computer.
TOOLTIPTXT_CONFIGNICFAILED=active nic failed.
Commissioning.Page.ActiveNic=Active Nic
INPUT_HOSTNAME_USED=The hostname "{0}" is duplicated.
INPUT_HOSTNAME_ERROR=Input hostname "{0}" is not correct
COL_NAME_HOSTNAME=Host Name
sec_activenic=Nic Config
[/ActiveNic]

#17.部署域状态
[WelcomPage]
deployState=Deploy State
Access=Access:
IP=IP:
Trans=Trans:
Undeployed=Undeployed
deployed=deployed
[/WelcomPage]

#18. VRTS版本
[VRTSVersion]
VRTSVersion.Failed=Get VRTS Version failed.
[/VRTSVersion]
