################################################################################
# 
#           定制工程维护工具前台界面资源 InstallDisk.properties (en_US)
#
#
################################################################################

# 定制维护工具显示安装类型
Locale_HA=Local HA System
Remote_HA=Remote HA System
Distribute_HA=Remote High Availability System (SUSE Linux-Distributed)
Distribute_Single=Single-Server System (SUSE Linux-Distributed)
Single=Single-Server System
