WelcomePage=Information Preview
DateTimeZonePage=Set Date Time Zone
ChangeNTPPage=Set NTP
ModifyHostnamePage=Set Host Name
ControllerPage=Set Controller
VirusSoftCheckPage=Anti-Virus Software
ChangePValuePage=Set Password
AlarmConfigPage=Set Hardware Alarm
NMSLicensePage=OSS License
VCSLicensePage=Set Veritas License
ReplaceNMSLicensePage=Set SSL Certificate
AddInstancePage=Add Instance
ConfigNetworkPage=Set Network
ConfigRoutePage=Set Route
SecuritySetPage=Security Hardening
ActiveNicPage=Active Nic
DeployPage=Deploy
UnDeployPage=Undeploy
SummaryPage=Finish
DeployNbiInstancePage=NBI
UMSSLGUIWizardPage=Internal NMS Certificate
TransSSLTestMS=Set SBI Certificate
MMLSSLTestMS=Set U2100 Certificate
PMSCertificatePage=Set Other Certificate
CommissionAfterTreatmentPage=Post-commissioning Processing
