
state=状态
hostid=节点标识：
hosttype=节点类型：
fixHostName=固定IP地址：
des=描述信息
usingDB=使用数据库：
addButton=增加(A)...
removeButton=删除(R)...
modifyButton=修改(M)...
finishedButton=完成(F)...
hostInfoPageTitle=管理节点信息
ftpUserName=FTP用户名
ftpUserPwd=FTP用户密码
installFolder=安装路径：
SingleMode=非分布式安装
DistributeMode=分布式安装
ftpType=FTP类型
ftpTypeOne=FTP
ftpTypeTwo=SFTP
FtpValidationFailed=FTP验证失败。
Host_Fixed_IP=主机固定IP：
InstallDirectoryValidationFailed =确认安装目录已经失败。
FrameWorkDirectoryValidationFailed = 验证安装框架目录失败。
FTPLoginFailed = FTP登录失败。
ftpUserNameLabelCMD=FTP用户名

addHostInfoDlg=增加
modifyHostInfoDlg=修改
hostidLabel=主机标识：
hosttypeLabel=节点类型：
isDBServerLabel=是否是数据库服务器：
hostFixIPLabel=固定IP地址：
hostFloatIPLabel=浮动IP地址：
usingDBLabel=使用数据库：
sshUserNameLabel=SSH用户名：
sshUserPwdLabel=SSH用户密码：
desLabel=描述信息：
okButton=确定
cancelButton=取消
yes=是
no=否
nodeIDLabel=节点标识：
rootPasswdlabel=管理员密码：
installDirLabel=安装路径：
masterHost=主机
slaveHost=从机
standbyHost=备机
single=单机
activeHASystem=双机主节点
standbyHASystem=双机备节点
watchmanSystem=异地双机节点
ftptypeLabel=FTP类型：
ftpUserNameLabel=FTP用户名：
ftpUserPwdLabel=FTP用户密码：
FTP_ErrorCannotConnection = 连接FTP/SFTP服务器失败。
FTP_portNotListening = FTP/SFTP服务器没有运行。


dbServerInfoPageTitle=管理数据库服务信息
dbid=标识
dbservername=数据库服务名称
dbserverport= 数据库端口
dbtype= 数据库类型
dbaddress=数据库服务器IP


createDBInfoDlgTitle=增加
modifyDBInfoDlgTitle=修改
dbIDLabel=标识：
dbServerNameLabel=数据库服务名称：
dbServerPortLabel=数据库端口：
dbServerAddressLabel=数据库服务器IP：
dbTypeLabel=数据库类型：
dbUserNameLabel=数据库管理员用户名称：
dbUserPwdLabel=数据库管理员用户密码：
nmsDBUserNameLabel=数据库网管用户名：
nmsDBUserPwdLabel=数据库网管用户密码：
nmsDBUserPwdConfirmLabel=数据库网管用户密码确认：
racCheckBoxLabel = Oracle RAC 模式
racAddress1Label = Oracle RAC 地址1：
racAddress2Label = Oracle RAC 地址2：
racAddress3Label = Oracle RAC 地址3：
racAddress4Label = Oracle RAC 地址4：
OSType = 操作系统类型：


HostID_null=主机标识为空。
HostFixName_null=固定主机名为空。
HostFixIP_null=固定主机地址为空。
HostFloatName_null=浮动主机名为空。
HostFloatIP_null=浮动主机地址为空。
HostInfo_exist=主机信息已经存在。
SSHUserName_null=SSH用户名为空。
SSHUser_invalid=SSH用户名或密码错误。
HostInfo_hostfixipnouser=无法与指定的主机建立连接。
TooManyHostsToDeploy=主机数量过多，将无法全部部署。
HostInfo_repeated=列表中有重复的主机，请删除。
HostInfo_Multi_Master = 列表中包含多台主机。
HostInfo_CantPing = 无法连接到如下主机，是否继续？
HostInfo_SSH_Invalid = 如下主机SSH用户名或密码错误，是否继续？
HoatInfo_ChineseChars = 主机标识包含中文字符。
HostInfo_Multi_StandBy_Master = 列表中包含多台主机备机。
HostInfo_StandBySlave_No_Master = 如果添加了从机备机，则必须添加主机备机。
HostInfo_StandByShared_Master_Slave = 只能部署一个备机。
HostInfo_No_Master = 必须添加一台主机。
HostInfo_No_DB = 如下主机使用数据库不存在，请重新选择。
HostInfo_FTPUserPasswdWrong = FTP用户名或者密码错误。
FTPUserName_null = FTP用户名为空。
HostInfo_PortNotListen = 无法连接FTP端口。
HostInfo_SFTPUserPasswdWrong = SFTP用户名或者密码错误。
HostInfo_WrongAdminPwd = 管理员密码错误。
ErrorNullInstallPath = 安装目录为空。
AdminPwd_null = 管理员密码不合法。
HostIP_NamingIP_Same = 在安装从机时，命名服务地址不能和本机地址相同。
uploadFrameworkMessage = 是否上传框架？
frameworkFileNotExist = 框架文件没有找到。
invalidRemotePath=框架远端路径不合法。
NoSSH_Service=该主机没有运行SSH服务。
Host_Ip_Invalid = 主机IP地址非法。
Host_IP_LocaleIP=主机节点IP地址必须是本机IP地址。
Host_IP_notLocaleIP=非主机节点IP地址不能是本机IP地址。
DirectoryMustBeCharAndNum = 目录名必须是绝对路径，且是英文字母，中文字符和数字以及\'_\'和\'-\'的组合，且长度不能超过60个字符，\n'\\'或'/'或':'前不能有空格。


ErrorInstallPath = 安装路径不合法，请重新输入。
InstallDirNotEmpty = 如下节点的安装路径不为空。请选择其它路径。
CheckSpaceFailed = 检查安装空间失败。
NoSpace = 下列节点没有足够的空间。\n请先清理磁盘。

DBConnected_fail=数据库服务连接失败。
DBID_null=数据库服务标识为空。
DBServerName_null=数据库服务名称为空。
DBServerPort_null=数据库服务端口为空。
DBUserName_null=数据库实例名称不能为空。
DBUserPwd_null=数据库密码为空。
NMSDBUserName_null=数据库网管用户名为空。
NMSDBUserPwd_null=数据库网管用户密码为空。
NMSDBUserPwdConfirm_null=数据库网管确认密码为空。
DBInfo_exist=IP地址或者服务名称已经存在。
NMSDBUserPwd_differ=数据库网管用户密码和确认密码不一致。
DB2_DBUSERNAME_PWD_WRONG = 数据库实例名称或数据库实例密码错误。
DB2_SERVER_NAME_WRONG = 指定主机上找不到名称为imapdb的数据库服务。
DB2_PORT_NUMBER_WRONG = 连接数据库失败，可能是如下原因导致：\n数据库端口错误；\n数据库不在线。
DB2_FIX_HOST_NAME_WRONG = 无法连接数据库服务器。
DB_SUSERNAME_PASSWORD_WRONG = 数据库管理员用户名或密码错误。
DB_SERVERNAME_INVALID=连接数据库失败，可能是由于如下原因导致的：\n1. 数据库服务器不在线。\n2. 数据库服务名错误。\n3. IP或端口错误。\n4. 数据库管理员用户名称错误。\n5. 数据库管理员用户密码错误。
DB_ChineseChars = 数据库服务标识包含中文字符。
DBInfo_repeated=列表中有重复的数据库服务，请删除。
ORACLE_IP_PORT_WRONG = 无法连接数据库服务器。\n数据库主机地址、端口号或服务名错误。
ORACLE_RAC_HOST_NOT_ENOUTH = Oracle RAC模式最少需要2个RAC地址。
ORACLE_RAC_IP_WRONG = Oracle RAC地址格式不正确。
ORACLE_RAC_IP_CONFLICT = Oracle RAC地址不能重复。
DB_Databases_Empty = 所需数据库不存在。
SERVER_IP_INVALID = 数据库IP地址非法。
SQLPLUS_NOT_RUNNING = SQLPLUS命令不在path路径中。

STANDBY_MASTER=主机备机
STANDBY_SLAVE=从机备机
STANDBY_COMMON=通用备机


uninstallHostInfoPageTitle = 主机信息
modifyUninstallHostInfoDlg = 修改主机信息
DirNotExistCreateIt = 路径 {0} \n不存在。是否创建？
UnistallFileError = 指定路径中没有卸载脚本。请检查安装路径是否正确。
InstallPath_Null = 安装路径为空。

remoteFrameworkError = 无法连接到框架。
remoteServerError=远端计算机不支持文件浏览操作。\n请手工输入安装路径。
uploadHint = 正在上传
uploadWaitMessage = 正在上传文件到远端机器，请稍候...
Float_Ip_Invalid = 浮动IP地址无效。
HostTitle = 节点信息
DBTitle = 数据库服务器信息
addMoreDBInfos = 是否需要进行操作？
selectOperation = 操作类型：
selectHost = 选择ID：
EmptyHostDetails = 节点信息不存在。
EmptyDBDetails= 数据库信息不存在。
uploadWaitCompress = 压缩文件中，请稍候...
HostInfoPage.CheckingDlgTitle=参数检测中
HostInfoPage.CheckingParameters=正在对输入参数进行检测，请稍候...
HostInfoPage.InstallDirNotWritable = 创建安装目录失败或该目录不可写。
HostInfoPage.FrameWorkDirNotWritable= 创建安装框架目录失败。\n 或者安装框架目录无写权限。
HostIDnotmatched=  DefaultValues.properties中配置的主机ID在{0}中不存在。
NotLocalIP = IP地址必须是本地IP。
HostInfoPage.DifferentInstallDir=所以节点上的安装目录必须一致。
invalidConfigExport=主机的SSH信息检查失败。\n请检查 ConfigExport.xml后重试。
InvalidConfig=不可用的 {0}。
InvalidHostID=无效的 StandAloneHOSTID。
ScriptFileNotFound=配置文件{0}不存在，在静默安装前，请做脱机安装。
InvalidConfigHostID={0}中配置了非法的主机ID。
PackageFile.Empty =  无组件描述文件，安装程序将退出。

Host_Fixed_Ip=主机固定IP：
FTPUser=FTP用户
InstallDir=安装目录
ftptypeLabelCMD=FTP
HostInfoPage.upload.error=传包发生未知异常。
hostname_not_same=固定主机地址和浮动主机地址不在同一台机器上。

DBServerInfoPage.NMDBUserPassword=数据库网管用户密码：
DBServerInfoPage.NMDBUserPasswordConfirm=数据库网管用户密码确认：

ConfigDBServer.ConnectInfoCheckEmpty=所有数据库配置信息不能为空。
DBServerInfoPage.NMDBUserPWDNULL=数据库网管用户密码不能为空。
DBServerInfoPage.NMDBUserRePWDNULL=数据库网管用户确认密码不能为空。
DBServerInfoPage.NMDBUserPWDNOTSAME=网管数据库用户密码输入不一致。
DBServerInfoPage.OSSUserPWDRuleSQL2008=网管数据库用户密码必须同时满足下列条件：  \n 1：密码长度必需8个字符以上，且不超过30个字符。 \n 2：密码字符只能是(A-Z、a-z、0-9、_)。  \n 3：密码至少满足下列四个条件中的三个：    \n必须包含大写字母（A－Z）；    \n必须包含小写字母（a－z）；    \n必须包含数字（0－9）；    \n必须包含下划线。
DBSVR_NAME_ERROR=数据库服务名称 {0} 错误。
ConfigDBServer.dbname.password.error=网管数据库用户 {0} 密码校验失败。
ConfigDBServer.Oracle.dbname.password.error=校验网管数据库用户失败，\n单击“详细信息”按钮查看网管数据库用户列表。