BackupMediumPage.Introduction=选择备份介质。
BackupMediumPage.Attention=备份数据库操作会将数据库的数据文件直接备份，该数据文件中存在口令、客户隐私信息等敏感数据，\n您有义务遵从所适用国家的法律制定必要的用户隐私政策，并采取足够的措施以确保用户的个人数据\n受到充分的保护。
BackupMediumPage.Introduce=请选择您要采用的备份介质，然后单击<下一步>继续。
BackupMediumPage.LocalBackupPath=本地服务器备份路径：
BackupMediumPage.RemoteBackupPath=远程服务器备份路径：
BackupMediumPage.IP=服务器IP：
BackupMediumPage.TransferMode=传输方式：
BackupMediumPage.UserName=用户名：
BackupMediumPage.Password=密码：
BackupMediumPage.Browse=浏览(B)...
BackupMediumPage.PromptInputError=备份信息输入不完整，请重新输入。
BackupMediumPage.DirNotExistCreateIt=目录 {0} 不存在，请确认是否创建？
BackupMediumPage.error=错误
BackupMediumPage.invalidPath=1.要求必须是相对路径，且是英文字母，数字以及'_'，'-'的组合。\n2.完整路径长度不能超过60个字符，且路径中不能包含空格。
BackupMediumPage.PATH_HAVE_NO_PERMISSION=目标路径权限不足。
BackupMediumPage.DatabaseConnectionFailed=检查数据库失败，可能原因：\n1.数据库未运行。\n2.数据库运行状态不正常。
BackupMediumPage.ConnectionFailed=连接远程服务器失败。
BackupMediumPage.setGlobalSettingInfoFailed=备份失败。
BackupMediumPage.LoginFailed=登录服务器失败。检查用户名/密码。
BackupMediumPage.prompt=提示
BackupMediumPage.readingDataModel=正在初始化备份任务，请稍候...
BackupMediumPage.AllFolders=所有文件夹
BackupMediumPage.SelectPolicy=备份策略：
BackupMediumPage.pathNameInvalid =路径无效。

BackupMediumPage.BackupServerNotRuuning=数据库备份服务没有运行，不能备份数据库。
BackupMediumPage.DBInfoFileInvalid=sysconfigure.xml文件或者数据库描述文件异常。
BackupMediumPage.BackupCountLabel=备份文件保留数量：
BackupMediumPage.PromptInvalidBackupCount=错误的备份份数。
BackupMediumPage.PromptZeroBackupCount=备份份数应在1~9999之间。
BackupMediumPage.BackupFileDelete=如果最终备份操作成功，下列备份文件将会被删除，请确认是否继续？
BackupMediumPage.InputError=备份信息输入不完整，请重新输入。
BackupMediumPage.IsLocalIp=不允许使用本地服务器作为FTP/SFTP服务器。

BackupMediumPage.InCompleteIP=远程服务器IP为空。\n
BackupMediumPage.InCompleteUserName=用户名为空。\n
BackupMediumPage.InCompletePath=备份路径为空。\n
BackupMediumPage.InCompletePassword=密码为空。\n
BackupMediumPage.PasswordMismatch=密码长度不能超过60个字符，并且只能包含以下字符：\n

BackupMediumPage.BackupCountToolTip=（说明：当备份文件达到该数量时，最早的备份文件将被自动删除。）
BackupMediumPage.INVALID_LOCAL_BACKUP_PATH=选择的备份路径不正确。
BackupMediumPage.INVALID_REMOTE_BACKUP_PATH=选择的备份路径不正确。\n1.必须选择该服务器的磁盘驱动器。\n2.要求目录名必须是相对FTP/SFTP用户根目录的相对路径，且是英文字母，数字以及'_'，'-'的组合，长度不能超过60个字符，且路径中不能包含空格。
BackupMediumPage.CREATE_PATH_FAIL=创建备份路径失败。
BackupMediumPage.CREATE_PATH_FAIL_REASON=可能原因：目标路径的权限不足。
BackupMediumPage.DetailError=可能原因：\n 1. IP地址不正确。\n 2. 用户名或密码错误。\n 3. 远程服务未启动。

BackupMediumPage.IpInvalid=IP地址不正确。\n
BackupMediumPage.LocalBackup=备份到本地服务器
BackupMediumPage.RemoteBackup=备份到远程服务器
BackupMediumPage.Solution=由于上次操作异常工程后台无法正常运行，请重启工程后台。
BackupMediumPage.NMSALIVE=网管正在运行，请确保网管没有进行配置操作，否则会导致数据库备份不完整，是否继续？
BackupMediumPage.NMSALIVEMSG=网管正在以下主机上运行：
BackupMediumPage.BrowseWindowLookIn=查看
BackupMediumPage.BrowseWindowFileName=文件名称：
BackupMediumPage.BrowseWindowOpen=打开
BackupMediumPage.BrowseWindowCancel=取消
BackupMediumPage.NMSALIVEMSGCMD=选择(Y)，备份将继续。\n选择(N)，备份将退出。
BackupMediumPage.DISK_NOT_ENOUGH=磁盘空间不足。
BackupMediumPage.REMOTEDB_DISK_NOT_ENOUGH=远程数据库服务器可用的磁盘空间不足。

BackupMediumPage.FailedToGetDBLogonInfoFromDatamodel=从数据模型中获取数据库登录信息失败。
BackupMediumPage.SelectFTPWarning=当前采用FTP协议，传输的内容没有加密，\n存在安全隐患，强烈建议采用安全的SFTP\n传输协议。请确认是否继续？
BackupMediumPage.SelectFTPOk=确认
BackupMediumPage.SelectFTPCancel=取消
BackupWizardPage.SSHConnectionFailed=使用SSH连接远程数据库失败。