BackupExitPage.Title=备份操作成功。
BackupExitPage.Note=请单击<完成>结束备份向导。
BackupExitPage.ErrorTitle=备份操作失败
BackupExitPage.ERRORNote=请单击<退出>结束备份向导。
BackupExitPage.BackupSuccess=备份操作成功。
BackupExitPage.BackupFailed=备份操作失败。