BackupDBProgress.DB_INUSE=数据库正在被使用，请重试。
UninstallApplicationTaskService.FailedTODELETE=删除安装目录{name}失败。
AutoRollbackservice.FAILEDDELETE=删除安装目录{name}失败。请手工删除并继续自动回滚。
Check.FolderAccessUpgrade= 无法访问安装目录"{installPath}"。请确认此目录是否可以访问。单击 <重试> 继续。\n 单击<取消>停止升级。
Check.FolderAccessRollback= 无法访问安装目录"{installPath}"。请确认此目录是否可以访问。单击 <重试> 继续。\n 单击<取消>停止回滚。
UpgradeTablesFailed=脚本执行过程中发生错误。请检查日志获取更多细节。
UPGRADE_Table_FAIL=升级表。
UPGRADE_Table_FAIL_rollback=升级表失败，系统自动回滚完成。
UPGRADE_Table_FAIL_rollback_cmd=升级失败，应用程序将回滚，请稍候...
ExecuteScriptAction.SCRIPTNOTFOUND=脚本未找到，是否继续？

BACKUP_SUCCEED=备份成功。
BACKUP_ERR_NODE_STOP=从节点没有启动。
BACKUP_ERR_PATH_READONLY=备份路径只有只读权限。
BACKUP_ERR_COPY_FAILED=拷贝文件失败。                     
BACKUP_ERR_NOT_MASTER_NODE=当前登录的节点不是主节点。
BACKUP_ERR_GET_IP_FAILED=获取不到主节点IP
BACKUP_ERR_CONN_REMOTE_FAILED=连接远端服务器失败。
BACKUP_ERR_PATH_INVALID=非法的备份路径。
BACKUP_ERR_PATH_NOT_EXIT=备份路径不存在。
BACKUP_ERR_NO_SPACE=磁盘空间不足。
BACKUP_ERR_NO_ENV_PARA_ORACLE=Oracle环境变量没有设置。
BACKUP_ERR_LOGIN_FAILED=登录部署服务失败。
BACKUP_ERR_PARA=参数错误。
BACKUP_ERR_DB_USER_NO_AUTH=数据库用户无目标路径权限。
BACKUP_ERR_NO_THIRD_COMPONENT=缺少第三方组件。
BACKUP_ERR_TRANS_FILE_FAILED=上传文件失败 。                     
BACKUP_ERR_NET_SYS_RUNNING=网管正在运行。
BACKUP_ERR_CONN_FAILED=连接数据库失败。
BACKUP_ERR_BACKUP_SERVER_STOP=数据库备份服务器没有启动。
BACKUP_ERR_BACKUP_IN_PROCESS=已经有备份进程正在执行，请稍候再试。
BACKUP_ERR_PARSE_XML_FAILED=解析网管数据库配置文件错误。
BACKUP_ERR_BACKUP_FAILED=备份数据库失败。
BACKUP_ERR_DUMP_BCP_BACKUP_DB=使用Dump或bcp备份数据库失败。
BACKUP_ERR_DATABASE_XML_PERMISSION_FAILED=读取数据库描述文件失败。
BACKUP_ERR_DB_STATUS_TITLE=数据库状态检查前置脚本执行失败

ADVICE_ERR_NODE_STOP=请参考操作手册，启动从节点服务。
ADVICE_ERR_PATH_READONLY=请增加数据库用户对该目录的写权限。
ADVICE_ERR_COPY_FAILED=可能原因：\n1.备份路径所在的文件系统空间不足。\n2.需要备份的目录或文件不存在或者权限不足。
ADVICE_ERR_NOT_MASTER_NODE=请确认双机复制关系，在主用服务器上登录。
ADVICE_ERR_GET_IP_FAILED=请检查双机状态是否正常。
ADVICE_ERR_CONN_REMOTE_FAILED=可能原因：\n1.与远端服务器的网络连接异常。\n2.输入的远端服务器用户名或密码不正确。
ADVICE_ERR_PATH_INVALID=请参考操作手册，确认备份路径的合法性。
ADVICE_ERR_PATH_NOT_EXIT=请将数据备份到存在的目录下。
ADVICE_ERR_NO_SPACE=请及时清理磁盘空间中的垃圾数据。
ADVICE_ERR_NO_ENV_PARA_ORACLE=请联系研发支撑人员处理。
ADVICE_ERR_LOGIN_FAILED=请检查网管系统维护工具服务器端是否已经启动。
ADVICE_ERR_PARA=请联系研发支撑人员处理。
ADVICE_ERR_DB_USER_NO_AUTH=请检查目标路径是否已经赋予数据库用户写权限。
ADVICE_ERR_NO_THIRD_COMPONENT=请联系研发支撑人员处理。
ADVICE_ERR_TRANS_FILE_FAILED=可能原因如下：\n1、网络连接状态不正常。\n2、选择的FTP/SFTP服务器磁盘剩余空间不足。
ADVICE_ERR_NET_SYS_RUNNING=请关闭网管服务。
ADVICE_ERR_CONN_FAILED=检查数据库失败，可能原因：\n1.数据库未运行。\n2.数据库运行状态不正常。
ADVICE_ERR_BACKUP_ERR_PARSE_XML_FAILED=请检查网管数据库配置文件是否正常。
ADVICE_ERR_ADVICE_SERVER_STOP=请检查数据库备份服务器是否已经正常启动。
ADVICE_ERR_BACKUP_FAILED=请联系研发支撑人员处理。
ADVICE_ERR_BACKUP_IN_PROCESS=服务器正在进行数据库备份中，\n进行其他操作可能会导致数据不一致给系统带来潜在的危险。
ADVICE_ERR_DUMP_BCP_BACKUP_DB=使用Dump或bcp备份数据库失败。
ADVICE_ERR_DATABASE_XML_PERMISSION__FAILED=读取数据库描述文件失败。
 BACKUP_ERR_DB_STATUS_DETAIL=数据库状态检查前置脚本执行失败

Summary.usedDbInfo={0}数据库的使用记录为：\n
Summary.Process=进程 = 
Summary.User= 用户 = 