Backup.Title =网络管理系统备份程序
BackupWizardPage.Introduction =欢迎使用网络管理系统备份向导
BackupWizardPage.Introduce =本备份程序将引导您完成对网络管理系统数据库及组件文件的备份活动。\n请选择数据库的备份方式，并单击<下一步>继续。
BackupWizardPage.DatabaseBackup = 数据备份 －二进制模式（推荐）
BackupWizardPage.TableBackup = 数据备份 －文本模式
BackupWizardPage.OracleEnvNotSet=不能在服务器上设置Oracle环境。
BackupWizardPage.SelectPolicy= 选择备份策略
BackupWizardPage.FailedToGetDBLogonInfoFromDatamodel=从数据模型中获取数据库登录信息失败。
