DELETE_SYSTEM_FILE_FAIL=删除子系统文件失败。
DeleteComponentWorkflow.Title=正在删除组件...
InstallServerWorkflow.InstallTitle=正在安装，请稍候...
IncrementInstallWorkflow.PrimaryTitle=正在主机中进行安装...
IncrementInstallWorkflow.SecondaryTitle=正在备机中进行安装...
DELETE_SUBINSTANCE_CONNECT_DATABASE_FAIL=删除实例失败，请检查是否建立了数据库连接。
RunCheckUnDeployScriptNull=删除实例检查脚本名称或路径为空。
RunCheckUnDeployScriptFail=执行删除实例检查脚本失败。
DELETE_SUBINSTANCE_DELETE_DATABASE_FAIL=删除实例数据库失败。