ADD_DATAMODEL_FAILED=添加子系统到数据模型失败。
ADD_SITE_INFO_DATAMODEL_FAILED=添加站点信息失败。
ADD_SYSTEM_INFO_DATAMODEL_FAILED=添加系统到数据模型失败，系统版本：{0}。
ADD_SUBSYSTEM_INFO_DATAMODEL_FAILED=添加子系统{0}到数据模型失败。
ADD_NODE_INFO_DATAMODEL_FAILED=添加节点信息到数据模型失败，节点IP：{0}。
UNZIP_FILE_FAILED=解压文件{0}失败。
INIT_MACRO_ATTRIBUTE_VALUE_NULL=属性值为空
EXEC_POST_INIT_FAILED=执行后置初始化失败
TRANSFER_PROCESS_FILE_FAILED=传输进程文件失败
UPDATE_DATABASE_INFO_FAILED=更新数据模型中数据库信息失败
CREATE_NMSUSER_FAILED=创建ossuser用户失败，请检查是否存在无法删除的ossuser用户
TRANSFER_PACKAGE_DATA_FAILED=向子节点传包失败，请检查子节点连接正常，包文件正常？
TRY_SQL_CONNECTION_FAILED=数据库SQL连接失败。
