InstallInterface.Title=增量安装
InstallInterface.addnodeTitle=增加节点
InstallInterface.reinstallTitle=增量安装

MENU_SYS=系统(S)
MENU_OP=部署(D)
MENU_OP_ADDSLAVES=添加从服务器(A)...
MENU_ADD_COMPONENTS=添加组件(A)...
FileChooser.Browse=浏览文件夹
FileChooser.Confirm=确定
FileChooser.Cancel=取消

[DBServerInfo]
DBServerInfoPage.Title=管理数据库服务信息
DBServerInfoPage.InitialFailed=初始化数据库配置页面信息失败。
DBServerInfoPage.DBInfoRepeated=列表中有重复的数据库服务，请删除。
DBServerInfoPage.dbIDLabel=标识：
DBServerInfoPage.dbServerNameLabel=数据库服务名称：
DBServerInfoPage.dbServerPortLabel=数据库端口：
DBServerInfoPage.dbTypeLabel=数据库类型：
DBServerInfoPage.hostFixIPLabel=固定主机地址：
DBServerInfoPage.hostFloatIPLabel=浮动主机地址：
DBServerInfoPage.racAddress1Label = Oracle RAC 地址1：
DBServerInfoPage.racAddress2Label = Oracle RAC 地址2：
DBServerInfoPage.racAddress3Label = Oracle RAC 地址3：
DBServerInfoPage.racAddress4Label = Oracle RAC 地址4：
[/DBServerInfo]


[SoftwareLib]
SoftwareLibSelectPage.Choose=浏览(B)...
SoftwareLibSelectPage.PathTitle=请输入增量安装包所在路径：
SoftwareLibSelectPage.RefreshPath=正在更新软件库，请稍候...
SoftwareLibSelectPage.Title=选择软件库目录
SoftwareLibSelectPage.BackupFailed=备份OSSENGR目录失败。
SoftwareLibSelectPage.InitialFailed=初始化软件库失败。
SoftwareLibSelectPage.SyncFailed=同步静态数据模型失败。
SoftwareLibSelectPage.ChangcfgFailed=更新软件库目录配置失败。
SoftwareLibSelectPage.CheckPathEmpty=软件库路径不能为空。
SoftwareLibSelectPage.CheckPathFailed=检查软件库路径失败。
SoftwareLibSelectPage.ScriptExecFailed=拷贝数据库文件脚本@SCRIPTNAME执行失败。
SoftwareLibSelectPage.ProcessFinish=刷新软件库路径成功。
[/SoftwareLib]

[StartSubNodeServer]
StartSubNodeServerPage.Title=启动从/备服务器
StartSubNodeServerPage.CheckNodes=增加节点失败
StartSubNodeServerPage.StartFailed=启动从/备服务器失败。
StartSubNodeServerPage.StartSuccess=启动从/备服务器成功。
StartSubNodeServerPage.LoginFailed=登录从/备服务器失败。
StartSubNodeServerPage.FailDetail=以下节点启动失败：\n{0}\n\n可能的原因如下：\n1. 12212端口被占用。\n2. 从/备节点无法连接。\n3. 产品插件无法启动。
[/StartSubNodeServer]


[ComponentTree]
ComponentTree.Title=选择安装组件。
ComponentTree.NO_PKG_FILE_LIST=以下组件的部署包文件不存在，\n请确认是否继续安装？
ComponentTree.NO_PKG_FILE_TITLE=部署包文件不存在
ComponentTree.watiProgress=正在处理，请稍候...
[/ComponentTree]



[ServiceGroup]
ConfigServiceHostPage.Title=配置服务组
help=帮助

only_master=仅可以主服务器部署
only_slave=仅可以从服务器部署
any_server=可以任意服务器部署
all_must=所有服务器必须部署

single_single_type=单节点单实例类型
mutil_type=多实例类型
system_single_type=系统单实例类型
none_type=无实例类型

servicegroup_info=[服务组信息]
hostInfoName=节点名称：

the_select=光标所选的是：
must_select_one_servergroup=请至少选择一项服务组
must_select_one_host=请至少选择一个主机
must_select_one_host_node=请至少选择一个主机下面的节点

the_below_not_mutil_host=如下单实例不能同时部署在多台服务器上
the_below_only_mutil_slave_host=如下节点只支持部署在从服务器上
the_below_only_master=如下节点只支持部署在主服务器上
the_below_must_all_host=如下节点必须部署在所有服务器上。请选择所有服务器节点
[/ServiceGroup]


[Subsystem]
ConfigDeploymentsSubsystem.Title=配置多实例子系统的实例个数。
ConfigDeploymentsSubsystem.Node=节点
ConfigDeploymentsSubsystem.Subsystem=服务组
ConfigDeploymentsSubsystem.SubsystemType=部署包
ConfigDeploymentsSubsystem.InstanceCount=实例个数
ConfigDeploymentsSubsystem.SubsystemDescription=部署包描述

ConfigDeploymentsSubsystem.SubsystemInfo=组件信息
ConfigDeploymentsSubsystem.Summary_NodeName=服务器名称：
ConfigDeploymentsSubsystem.Summary_Subsystem=组件：
ConfigDeploymentsSubsystem.Summary_SubsystemType=组件类型：
ConfigDeploymentsSubsystem.Summary_InstanceCount=实例个数：
ConfigDeploymentsSubsystem.Summary_SubsystemDescription=描述：
ConfigDeploymentsSubsystem.MultipleInstances=单服务器多实例
[/Subsystem]


[Summary]
Summary.Title=安装信息确认
Summary.Prompt=提示
Summary.Retry=重试
Summary.CheckDisk=正在检测服务器磁盘空间，请稍候...
Summary.EmptyData=获取节点子系统信息为空。
Summary.InvokeFail=获取概述信息失败。
Summary.NewDataCheck=未检查到新增的组件，请选择：\n单击 <确定> 按钮，请手动返回到软件库页面重新选择。\n单击 <取消> 按钮，将会退出增量安装。
[/Summary]

[Progress]
IncrementInstallProgressPage.Title=增量安装进度
IncrementInstallProgressPage.Installing=正在安装，请稍候...
IncrementInstallProgressPage.InstallFailed=增量安装执行失败。
[/Progress]

[ExitPage]
IncrementInstallExitPage.addnodeFinishTitle=增加节点完成
IncrementInstallExitPage.reinstallFinishTitle=增量安装完成
IncrementInstallExitPage.FinishTitle=增量安装完成
IncrementInstallExitPage.FailedTitle=增量安装失败
IncrementInstallExitPage.FinishNote=已经安装完成。\n单击<完成>退出。
IncrementInstallExitPage.FinishNoteCMD=已经安装完成。
IncrementInstallExitPage.FailedNote=安装失败。
IncrementInstallExitPage.needRestartOSS=如果网管已经启动，请重启网管。
[/ExitPage]
DB_CONNECT_FAILED=以下数据库连接失败，请检查数据库服务是否运行。
HA_Synchronize_Check=双机处于关联状态，请先分离主备站点。
following_node_not_trust=检查主节点与以下节点的互信失败
Summary.check.error= 汇总信息检查有如下错误。


[msuitestart]
CHECK_NODE_START=开始检查节点信息。
CHECK_NODE_FAIL=检查节点信息失败，退出增加节点。
CHECK_NODE_END=检查节点信息成功。
CHECK_DATABASE_START=开始检查数据信息。
CHECK_DATABASE_FAIL=检查数据库信息失败，退出增加节点。
CHECK_DATABASE_END=检查数据信息成功。
TRANSFER_ENGR_FRAME_START=开始同步数据到从节点，可能需要花费一些时间，请稍候...
TRANSFER_ENGR_FRAME_FAIL=同步数据失败，退出增加节点。
TRANSFER_ENGR_FRAME_FAIL_UPGRADE=同步数据失败，退出升级安装。
TRANSFER_ENGR_FRAME_END=数据同步结束。
INCINSTALL_PATH_INVALID=增量安装路径错误，静默增量安装失败。
LAUNCH_UPGRADE_INSTALL=启动升级安装。
UPGRADE_INSTALL_WORKFLOW=开始升级安装流程。
UPGRADE_INSTALL_FINISHED=升级安装完成。
CHECK_DATABASE_FAIL_UPGRADE=检查数据库信息失败，退出升级安装。
CHECK_NODEINFO_DIRVALID=检查节点信息失败，请检查所有节点的网管路径是否存在或互信无效。升级安装将退出
CHECK_NODEINFO_DIRVALID_SINGLE=检查节点信息失败，请检查所有节点的网管路径是否存在。升级安装将退出
[/msuitestart]

SiteType_single_not_support_addnode=增加节点只针对分布式或者本地双机。
dual_sitetype_have_two_node=本地双机已经安装两个节点了。
IncrementInstallCheck.Retry=重试
IncrementInstallCheck.title= 环境检查
Installed_NMS_dir_Not_exist=以下节点的网管目录不存在。
FAILED_INVOKE_RPC=与服务器{0}会话异常，请确认该服务器后台运行或网络状态是否正常。
InstallDirNotEmpty=安装路径不为空。请选择其它路径。
UPGRADE_INSTALL_LOGIN_FAILED=登录失败！请检查回环IP是否有效或端口{0}被占用或证书无效。
NO_NEW_NODES=无新增节点，不需要进行扩容操作。
ONLY_ADD_DB_CREATE_INTERFACE=扩容操作时，拷贝数据库interface文件失败.
ONLY_ADD_DB_SUCCESS=扩容数据库节点成功.