[Public_Operate]
OPERATE_RESULT_SUCCESS=成功
OPERATE_RESULT_FAILED=失败
MODULE_ICMR=ICMR
MODULE_INSTALLDISK=安装盘
MODULE_MSUITE=系统维护工具
MODULE_UPGRADE=升级工具
MODULE_PATCH=补丁安装盘
OPERATE_ICMR=系统预配置
[/Public_Operate]


[Install_Operate]
OPERATE_INSTALL=安装@{LicenseProductName} @{LicenseProductVersion}网管
OPERATE_UNINSTALL=卸载@{LicenseProductName} @{LicenseProductVersion}网管
OPERATE_ADDNODE=增加@{LicenseProductName} @{LicenseProductVersion}网管节点
OPERATE_INCREMENTINSTALL=增量安装@{LicenseProductName} @{LicenseProductVersion}网管
OPERATE_INSTALLCLIENT=安装@{LicenseProductName} @{LicenseProductVersion}网管客户端
OPERATE_UNINSTALLCLIENT=卸载@{LicenseProductName} @{LicenseProductVersion}网管客户端
[/Install_Operate]


[Deploy_Operate]
MSuite_Query=查询网管部署信息
MSuite_SyncOSSInfo=同步网管部署信息到网络管理系统维护工具
MSuite_DelNode=删除从服务器{0}
MSuite_InitialDB=初始化网管数据库
MSuite_ChangeDTPwd=修改维护工具管理员登录密码
MSuite_Logout=注销登出维护工具服务端
MSuite_DelComponent=删除组件{0}
MSuite_AddComponent=增加组件{0}
MSuite_AddInstance=添加实例{0}
MSuite_DelInstance=删除实例{0}
MSuite_MoveInstance=从{0}迁移实例{1}到{2}
MSuite_LicenseDeploy=按License部署
MSuite_ModifyInstanceMemo=修改实例备注信息
MSuite_ChangeDBSAPwd=修改数据库管理员用户密码
MSuite_ChangeDBUserPwd=修改数据库用户密码
MSuite_ChangeTimeZone=当前时区修改为{0}，当前时间修改为{1}
MSuite_ConfigNTP=配置NTP服务器为：{0}
MSuite_JoinHA=同步主备站点{0}和{1}
MSuite_SplitHA=分离主备站点{0}和{1}
MSuite_ForcePrimary=强制{0}为主机
MSuite_ConfigNetWork=修改节点{0}的IP地址和主机名
MSuite_ModifyFloatIp=修改浮动IP地址
MSuite_ConfigRouter=配置节点{0}的路由信息:{1}
MSuite_ConfigRouter_Detail=配置节点{0}的路由信息:{1}
MSuite_SyncNetWork=同步网管系统的网络配置信息
MSuite_Backup=以{0}模式备份系统数据到服务器：{1}的{2}目录
MSuite_Restore=以{0}模式从服务器：{1}的{2}路径恢复系统数据
Commssioning_AddInstance=调测工具添加实例
Commssioning_ChangePValue=调测工具修改{0}密码
Commssioning_ChangeHostname=修改的主机名{0}为{1}
MSuite_Backup_Common=备份数据库
MSuite_Restore_Common=恢复数据库
MSuite_Verify_Rule=校验用户{0}密码规则
Commssioning_Precheck=调测工具前置检查
[/Deploy_Operate]

[Patch_Operate]
PatchExitPage.Operation.Detail.install=安装 {0} {1} 补丁
PatchExitPage.Operation.Detail.unInstall=卸载 {0} {1} 补丁
PatchExitPage.Operation.result.succeed=成功
PatchExitPage.Operation.result.failed=失败
PatchExitPage.Operation.type.install=补丁安装盘安装
PatchExitPage.Operation.type.unInstall=补丁安装盘卸载
[/Patch_Operate]

[Deploy_Operate]
MSuite_DeployByDomain=按域部署
MSuite_unDeployByDomain=按域去部署
[/Deploy_Operate]
