ProgressPage.JoinHA.Title=同步主备站点...
ProgressPage.JoinHA.RelateDatamodel=关联数据模型...
ProgressPage.JoinHA.ConfigLocalVCS=配置本端VCS...
ProgressPage.JoinHA.ConfigRemoteVCS=配置远端VCS...
ProgressPage.JoinHA.CreateLocalRep=创建本端复制关系...
ProgressPage.JoinHA.CreateRemoteRep=创建远端复制关系...
ProgressPage.JoinHA.ExecutePostscript=执行后置脚本...
ProgressPage.JoinHA.SyncDynamicFiles=同步动态文件...

ProgressPage.SplitHA.Title=拆离主备站点...
ProgressPage.SplitHA.DeleteLocalVCS=删除本端VCS配置...
ProgressPage.SplitHA.DeleteRemoteVCS=删除远端VCS配置...
ProgressPage.SplitHA.DeleteLocalRep=删除本端复制关系...
ProgressPage.SplitHA.DeleteRemoteRep=删除远端复制关系...
ProgressPage.SplitHA.UnrelateDatamodel=去关联数据模型...
PROMPT_MSG_NODE_NOT_MATCHED=<html>主备站点需要关联的节点数量不一致：<br>本端站点：<br>{0}<br>对端站点：<br>{1}</html>
PROMPT_MSG_SUBSYSTEM_NOT_MATCHED=<html>以下部署包不匹配：<br>本端站点：<br>{0}<br>对端站点：<br>{1}</html>
PROMPT_MSG_INSTANCE_NOT_MATCHED=<html>以下子实例不匹配：<br>本端站点：<br>{0}<br>对端站点：<br>{1}</html>
PROMPT_MSG_SUBSYSTEM_IN_NODE_NOT_MATCHED=<html>需要关联节点的部署包不一致：<br>本端节点：<br>{0}<br>对端节点：<br>{1}</html>

ProgressPage.ForcePrimary.Title=强制本端为主...
ProgressPage.ForcePrimary.CheckRep=检测复制关系...
ProgressPage.ForcePrimary.Offline=关闭备节点...
ProgressPage.ForcePrimary.Resync=重新同步...
ProgressPage.ForcePrimary.DeleteRemoteRep=添加集群...
ProgressPage.ForcePrimary.OnLine=启动网管...
ProgressPage.finish=完成

ProgressPage.DualPrimary.Title=双主...
ProgressPage.DualPrimary.CheckRep=检测复制关系...
ProgressPage.DualPrimary.DelRep=删除复制关系...
ProgressPage.DualPrimary.SinglePoint=创建单点复制...
ProgressPage.DualPrimary.DeleteRemoteRep=删除本地集群属性...
ProgressPage.DualPrimary.OnLine=启动网管...

ProgressPage.DelRep.Title=删除复制...
ProgressPage.DelRep.DelRep=删除远程复制关系...
ProgressPage.DelRep.CheckRep=检测删除远程复制结果...
ProgressPage.DelRep.DelRemoteRep=删除本地复制关系...
ProgressPage.DelRep.CheckRemoteRep=检测删除本地复制结果...
OWNER_NODE_IS_DIFFERENT=所在服务器不对应
OWNER_SUBSYSTEM_IS_DIFFERENT=所在部署包不对应
INSTANCE_NOT_MATCHED=不相同
ProgressPage.JoinHA.checkDatabase=检查数据库状态...
ProgressPage.JoinHA.checkVolume=检查复制卷...
ProgressPage.JoinHA.startVCS=启动远端VCS...
