SubsystemName=组件名称：
BackupVersion=备份版本号：
CurrentVersion=当前版本号：
InstanceToBeAdded=需要添加以下实例：
InstanceToBeDeleted=需要删除以下实例：
SubsystemToBeAdded=缺少组件：
SubsystemToBeDeleted=多余组件：
SubsystemCompressFileFailed=获取备份{1}组件文件失败，不能继续备份。

RestoreWorkFlow.Title=正在进行恢复，请稍候...
PrepareRestoreWorkFlow.Title=恢复预处理正在进行中，请稍候...
Task.RestoreDatabasesAdditional=恢复数据库表
Task.RestoreDatabases=数据库恢复：

[ErrorPrompt]
STARTWORKFLOW_SUCCESS=工作流启动成功。
LOGIN_NOTMASTER=登录服务器不是主服务器。
NODE_OFFLINE=存在服务器不可连接。
NODE_READONLY=存在服务器不可写。
SUBSYSTEM_NOTVALID=网管版本不一致。
DBMGRINIT_FAILED=数据库初始化工作流启动失败。
DBMGRCFG_FAILED=配置数据库工作流启动失败。
COMMAND_WRONG=前台传入命令错误。
MASTER_NODE_IP_INVALID=主服务器ip为空或者非法。
CHECK_BACKUP_INFO_FAILED=无法找到备份文件，请输入正确的路径。
DSPARAM_SERVER_INFO_WRONG=登录服务器失败，可能原因：\n 1. IP地址不正确。\n 2. 用户名或密码错误。\n 3. 远程服务未启动。
DSPARAM_DIR_WRONG=路径非法。
DSPARAM_DIR_NOTEXITS=无法找到备份文件，请输入正确的路径。
DSPARAM_PAESE_FAILED=解析ds参数失败。
DSPARAM_DIR_NOPESSION=1.该用户没有远程服务器该路径的权限。\n2.远程服务器该路径的空间不足。
LOCAL_SYSTEM_OSSENGR_SPACE_NOT_ENOUGH=该操作在分区“{0}”需要的运行空间不足。\n至少需空间：{1}MB，当前可用空间为：{2}MB。
DISK_NOT_ENOUGH=所需磁盘空间不足。分区“{0}”，所需空间为：{1}MB，\n可用空间为：{2}MB。
LOCAL_SYSTEM_SPACE_NOT_ENOUGH=所需磁盘空间不足。分区“{0}”，所需空间为：{1}MB，可用空间为：{2}MB。
REMOTE_SYSTEM_SPACE_NOT_ENOUGH=远程数据库服务器所需磁盘空间不足。分区“{0}”，所需空间为：{1}MB，可用空间为：{2}MB。
LOCAL_TMPDIR_SYSTEM_SPACE_NOT_ENOUGH=本机用于存放备份临时文件的磁盘空间不足。分区“{0}”，所需空间为：{1}MB，可用空间为：{2}MB。
RESULT_ALREADY_SCHEDULED=已经创建定时备份任务
RESULT_TASK_NAME_NULL=定时备份任务名称是空的
RESULT_START_TIME_ERROR=定时备份开始时间不正确。它必须是24小时制的，具体格式例如“1320”为下午1点20分。
RESULT_DELETE_TASK_SUCCESS=删除定时备份任务成功。
RESULT_DELETE_TASK_FAILED=删除定时备份任务失败。
RESULT_SCHEDULE_BACKUP_MESSAGE=已经创建定时备份，开始时间是 {0} ，时间间隔是{1}小时。
RESULT_NO_SCHEDULE_BACKUP_FOUND=没有定时备份任务。
RESULT_NEW_SUBSYSTEMS_TO_BE_ADDED=添加新的子系统
ORACLE_ENVIRONMENT_CHECK_FAILED=不能在服务器上设置Oracle环境。
LOGIN_FAIL=登录失败。
UNKNOWN_CLI_PARAMETER=未知的命令行参数。
ORACLE_SPACE_CHECK_FAILED=检查Oracle空间失败。
NO_PERMISSION_TO_USER=用户{0}没有路径{1}的操作权限。
INVALID_TEMP_PATH=临时备份目录空间不足，无法完成远程备份操作。
INVALID_DRIVE_BACKUP=无效的临时目录。
CHECK_BACKUP_INFO_MISMATCH_DATABASETYPE=文本模式恢复无法使用二进制模式备份。
CHECK_BACKUP_INFO_MISMATCH_BCPTYPE=二进制模式恢复无法使用文本模式备份。
NMS_SERVER_RUNNING=网管服务端正在运行
BACKUP_SUCCESSS=备份成功
BACKUP_FAIL=备份失败
RESTORE_SUCCESS=恢复成功。
RESTORE_FAIL=恢复失败。
RESTOREPRE_SUCCESS=恢复前置处理操作成功。
RESTOREPRE_FAIL=恢复前置处理操作失败。
FREEZE_FAIL=双机冻结失败，请查看日志信息。
JOBCREATE_FAIL=创建任务失败。
RESTORE_INSTANCEMISMATCH=实例不匹配。
RESTORE_SUBSYSTEMMISMATCH=子系统不匹配。
RESULT_UNKNOWN=未知错误。
DB_TMP_DISKSPACE_NOTENOUGH="{0}"磁盘空间不足，所需空间大于{1}MB。
[/ErrorPrompt]