INIT_DB_SUCCESS=初始化数据库完成。
INIT_DB_FAILED=初始化数据库失败。
PARA_CFG_SUCCESS=配置数据库参数完成。
PARA_CFG_FAILED=配置数据库参数失败。
ProgressPage.InitDatabaseTitle=正在进行数据库初始化，请稍候...
ProgressPage.DeleteDataBase=删除数据库...数据库名称：{0}
initdbcheck.DiskSpaceNotEnoughError=服务器磁盘{0}空间不足，所需空间为{1}MB，可用空间为{2}MB。
CREATE_DATABASE_FAILED=创建数据库 {0} 失败。
WORKFLOW_ALREADY_RUNNING=初始化数据库工作流已经在执行。
