

CheckTool=工程助手
AUTO_REQUIRE=自动修复
AFTERCHECK_PROMPT=检查结束。检查 @CheckSum 项，发现 @ErrorSum 个问题。

AFTERREQUIRE_PROMPT=自动修复后，仍然存在以下检查失败的项目。请根据失败检查项目的描述信息，手工修复
jlCheckinfo.StartCheck=单击 <开始>，执行检查项
jLbTitle=<html><p>工程助手是对服务器软硬件环境、数据库状态进行检查</p><p>请在下拉菜单中选择需要检查的场景。当环境存在问题时，可以查看详细的问题描述以及解决办法</p></html>
jLbTitleCMD=工程助手：
introduceCMD=检查影响安装升级相关的操作系统，数据库等因素。如果检查结果存在失败项，建议参考操作指南，确认或修改。
SelectCheckTypeCMD=选择检查类型：
inputInvaildCMD=输入错误，请重新输入。
jbRepair=修复
jbErrorDetail=显示结果
jbStartCheck=开始
Settings = 设置项
HideDetailResult=隐藏结果<<
ShowDetailResult=显示结果>>
RUN_FINISH=执行成功
ShowDetail=详细错误信息：
OK_Button=确认
Cancel_Button=取消
DB_Title=数据库信息
DB_Title_CMD=请输入数据库连接信息
DBEnterMsg=请使用数据库管理员用户登录
DBUser=用户名：
PassWD=密码：
DBIP=数据库服务器IP：
DBServer=数据库服务器名：
DB_Port=数据库端口：
Logion_failed=登录数据库失败。
Con_failed=数据库连接失败。选择"取消"，跳过数据库检查。
Con_failed_CMD=数据库连接失败。输入"Y"，重新输入数据库信息尝试连接，其它任意键跳过数据库检查。
Con_success=数据库连接成功。
InvalidIP=输入的IP无效。


Check_type=检测类型
Select_install=安装检查
Select_upgrade=升级前检查
Select_reconfigvcs=配置vcs前检查
Select_collection=收集环境信息


CheckOS_SystemDirSize.CheckInfo=检查操作系统目录剩余空间
CheckOS_SystemDirSize.CheckResult.windows=操作系统分区 "@SystemDir" 剩余空间小于 @RequireSize。建议先清理无用文件，保证操作系统分区 @SystemDir 空间大于2G
CheckOS_SystemDirSize.CheckResult.solaris=操作系统目录 "@SystemDir" 剩余空间小于 @RequireSize。使用命令"df -h"可以查看 @SystemDir 的使用情况
CheckOS_SystemDirSize.CheckResult.linux=操作系统目录 "@SystemDir" 剩余空间小于 @RequireSize。使用命令"df -h"可以查看 @SystemDir 的使用情况
CheckOS_SystemDirPermission.CheckInfo=检查操作系统目录权限
CheckOS_SystemDirPermission.CheckResult.solaris=操作系统目录 @SystemDir 权限小于@PathPermission。使用命令"ls -ld @SystemDir"查看目录权限，如果目录权限小于@PathPermission，建议使用命令"chmod @PathPermission @SystemDir"修改
CheckOS_EtcHosts.CheckInfo=对系统文件/etc/hosts进行合法性校验
CheckOS_EtcHosts.CheckResult.IteranceIP=系统文件/etc/hosts存在重复的IP信息，请使用文本修改工具vi修改，并重启操作系统生效
CheckOS_EtcHosts.CheckResult.invaildIP=系统文件/etc/hosts存在格式非法的IP信息 @invaildIP，请使用文本修改工具vi修改，并重启操作系统生效
CheckOS_EtcHosts.CheckResult.SystemIP=系统文件/etc/hosts中必须，并且只能存在一个系统IP。执行命令"cat /etc/hosts | grep loghost"查看，是否不存在或者存在多个系统IP。标志为"loghost"的IP作为系统IP。
CheckOS_EtcHosts.CheckResult.invaildHostname=通过系统命令"hostname"获取的系统主机名，和系统文件/etc/hosts配置的系统主机名不匹配，请使用文本修改工具vi修改/etc/hosts，并重启操作系统生效
CheckOS_FreeMemory.CheckInfo=检查操作系统内存使用状态
CheckOS_FreeMemory.CheckResult=检查到当前操作系统内存总数 @TotalMem MB，可用数 @FreeMem MB。剩余可用内存数低于总数的30%，建议关闭不必要的程序，或者重启操作系统以释放更多的内存资源。
CheckOS_FreeSwap.CheckInfo=检查操作系统swap使用状态
CheckOS_FreeSwap.CheckResult=检查到当前操作系统swap总数 @TotalMem ，可用数 @FreeMem。剩余可用swap数低于总数的30%，建议关闭不必要的程序，或者重启操作系统以释放更多的内存资源。使用命令"swap -s"可以查看当前swap使用情况
CheckOS_IPHosts.CheckInfo=检查操作系统IP配置情况
CheckOS_IPHosts.CheckResult=当前操作系统使用的IP(使用系统命令"ifconfig -a"可以获取到)和/etc/hosts文件中配置的IP不匹配，请修改
CheckOS_LoopIP.CheckInfo=检查操作系统回环IP配置
CheckOS_LoopIP.CheckResult.etchosts=操作系统网络配置文件/etc/hosts中没有配置回环IP信息，请在/etc/hosts中添加回环IP信息"127.0.0.1       localhost"，添加后重启操作系统生效
CheckOS_LoopIP.CheckResult.ifconfig=使用命令"ifconfig -a"无法获取回环IP信息，请重启操作系统，使回环IP生效
CheckOS_UserAdd.CheckInfo=检测操作系统是否可以添加用户
CheckOS_UserAdd.CheckResult=当前环境无法正常添加ossuser用户。请确认系统文件/etc/passwd、/etc/shadow是否损坏，或者使用系统命令pwconv修复
CheckOS_MaxShareMemory.CheckInfo=检查操作系统最大共享内存
CheckOS_MaxShareMemory.CheckResult.maxsharememory=请检查系统文件/etc/system中共享内存参数shminfo_shmmax设置是否正确，具体操作请参考网络管理系统安装或者升级指导书
CheckOS_MaxShareMemory.CheckResult.rlim_fd=需要在"/etc/system"中配置文件描述符的数量(rlim_fd_max和rlim_fd_cur)。具体操作方式，请参考网络管理系统安装或者升级指导书
CheckOS_SingleLogin.CheckInfo=检查操作系统是否是单个用户登录状态
CheckOS_SingleLogin.CheckResult=当前操作系统存在超过1名用户登录：@loginUser。请在安装或升级操作前确保只有一名用户登录，减少多用户登录情况下冲突操作造成的问题
CheckOS_SybaseOwnerGroup.CheckInfo=检查 "@pathName" 目录的属主是否和全局配置文件 "sysconfigure_install.xml" 配置的一致
CheckOS_SybaseOwnerGroup.CheckResult="@pathName" 目录的所属组和全局配置文件的不一致，请使用命令 "chown -RH @dbuser:@dbgroup @pathName"修改 "@pathName" 目录的属组，如果 "@pathName" 是一个链接，请再执行命令"chown -h @dbuser:@dbgroup @pathName"修改链接的属组。
CheckOS_AllNodeOssuser.CheckInfo=检查操作系统网管用户是否正常
CheckOS_AllNodeOssuser.CheckResult=操作系统 @ipAddress 的网管用户 @ossUser 不存在，请根据安装指南检查服务器系统预配置是否正确。
CheckOS_AllNodeOssuser.Exception=由于网络问题导致远程检查操作系统 @ipAddress 网管用户 @ossUser 失败，请重试。
CheckOS_AllNodeOssuser.ErrorMgr=从全局配置文件 /etc/OSSENGR/sysconfigure_install.xml 获取网管用户名称失败，请检查
CheckNMS_SupportUTF8.CheckInfo=检查操作系统是否支持UTF-8字符集
CheckNMS_SupportUTF8.CheckResult=当前环境没有安装UTF-8字符集，请参考升级指导书中，安装操作系统字符集的相关章节
CheckNMS_NetPort.CheckInfo=检查网络管理系统维护工具框架使用的端口[ @PORT ]是否被使用
CheckNMS_NetPort.CheckResult.solaris=网络管理系统维护工具框架端口被占用。使用系统命令"/usr/bin/netstat -an -P tcp | grep 端口"，可以查看端口状态
CheckNMS_NetPort.CheckResult.linux=端口被进程ID为 @PORCINFO的进程所占用。建议通过重启或者关闭进程的方式释放端口。端口释放过程通常需要2-3分钟，使用系统命令"/bin/netstat -ant | grep 端口"，可以查看端口状态。
CheckNMS_NetPort.CheckResult.windows=端口被进程 @PORCINFO占用。建议通过重启或者关闭进程的方式释放端口。端口释放过程通常需要2-3分钟，使用系统命令"netstat -ano | findstr 端口"，可以查看端口状态
CheckNMS_ClearScript.CheckInfo=检查网管挂起文件
CheckNMS_ClearScript.CheckResult=上一次网管卸载已经在计算机上执行了创建挂起文件的操作。运行安装或升级程序之前必须重新启动计算机
CheckNMS_DeploySvrProc.CheckInfo=检查网络管理系统维护工具后台
CheckNMS_DeploySvrProc.CheckResult=网络管理系统维护工具运行中。请参考网络管理系统"管理员指南"相关章节，停止网络管理系统维护工具后台服务
CheckNMS_LangCfgCharset.CheckInfo=操作系统语言配置文件检查
CheckNMS_LangCfgCharset.CheckResult.linux=当前操作系统的语言配置文件/etc/sysconfig/language中的语言配置项"RC_LANG"配置，非网络管理系统要求的语言，请修改为" @LANG"，并重启操作系统生效
CheckNMS_LangCfgCharset.CheckResult.solaris=当前操作系统的语言配置文件/etc/TIMEZONE中的语言配置项"LANG"配置，非网络管理系统需要。请修改为"LANG=@LANG"，并重启操作系统生效
CheckNMS_LangCharset.CheckInfo=检查操作系统语言
CheckNMS_LangCharset.CheckResult=操作系统的语言不是网络管理系统要求语言( @Lang )。使用系统命令"echo $LANG"可以查看当前操作系统的语言。使用系统命令"export LANG= @Lang"可以修改操作系统语言环境变量
CheckNMS_NmsUser.CheckInfo=检查 @OSSUSER是否被占用
CheckNMS_NmsUser.CheckResult=存在进程是使用 @OSSUSER用户启动，请关闭相关进程。使用命令"ps -ef |grep @OSSUSER"可以查看使用ossuser用户启动的相关进程信息
CheckDB_DatabaseStatus.CheckInfo=用户数据库健康状态检查
CheckDB_DatabaseStatus.CheckResult=@DBNAME 处于异常状态。请使用sql命令"use 数据库名称"的输出结果确认数据库状态。
CheckDB_DatabaseInUsing.CheckInfo=检查用户数据库是否被占用
CheckDB_DatabaseInUsing.CheckResult=用户数据库@DBNAME在使用中，使用sql命令sp_who查看数据库占用情况，并确认是否网管运行中，或者有第三方软件连接数据库
CheckDB_InputDBLogonInfo.CheckInfo=连接数据库
CheckDB_InputDBLogonInfo.CheckResult=连接失败或者数据库检查被取消
CheckDB_DatabaseSize.CheckInfo=检查数据库剩余空间
CheckDB_DatabaseSize.CheckResult=数据库 @DBNAME 的剩余空间小于10%，请使用sql命令"sp_helpdb 数据库名称"查看详情
CheckDB_DatabaseSingleMode.CheckInfo=检查数据库是否是单个用户登录状态
CheckDB_DatabaseSingleMode.CheckResult=当前数据库存在多个用户登录，使用sql命令sp_who查看数据库用户情况。安装或升级前强烈要求保持单一用户登录数据库。
CheckDB_SqlCommand.CheckInfo=校验数据库命令（isql，bcp，osql，sqlplus）
CheckDB_SqlCommand.CheckResult.isql=执行isql命令失败。建议执行"isql -U用户名 -P数据库密码 -S数据库服务名称"，查看具体的失败原因
CheckDB_SqlCommand.CheckResult.osql=执行osql命令失败。建议执行"osql -U用户名 -P数据库密码 -S数据库服务名称"，查看具体的失败原因
CheckDB_SqlCommand.CheckResult.bcp=执行bcp命令失败。建议执行"bcp master..sysdatabases out testbcp.out -c -U用户名 -P数据库密码 -S数据库服务名称"，查看具体的失败原因
CheckDB_SybaseInterface.CheckInfo=检查Sybase数据库网络配置文件@SYBASEPATH/interfaces
CheckDB_SybaseInterface.CheckInfoCMD=检查Sybase数据库网络配置文件@SYBASEPATH/interfaces
CheckDB_SybaseInterface.CheckResult.invaildIP=配置文件中存在非法IP，或者无IP配置信息。在确认存在IP问题后，请按照以下步骤修改IP信息：首先关闭数据库，修改非法的IP信息，重新启动数据库
CheckDB_SybaseInterface.CheckResult.getIPFailed=从@SYBASEPATH/interfaces中获取IP信息失败
CheckDB_SybaseInterface.CheckResult.NotMatchIP=@SYBASEPATH/interfaces中获取IP信息和/etc/hosts中配置的IP信息不匹配，请确认是否存在配置错误
CheckDB_SybaseBackupSvr.CheckInfo=检查Sybase数据库的备份服务是否启动
CheckDB_SybaseBackupSvr.CheckResult=备份服务没有启动。请参考指导书中关于启动数据库的章节，启动Sybase数据库备份服务
CheckDB_DBRunningCfg.CheckInfo=检查数据库运行配置
CheckDB_DBRunningCfg.CheckResult=请和当前网管要求的数据库配置比较，确认以下数据库运行配置是否存在错误，错误的数据库配置会造成数据库操作异常：@errDBSvrCfg


ColectOS_EnvInfo.CheckInfo=收集当前操作系统环境信息
ColectOS_EnvInfo.CheckResult=收集内容包括操作系统、网管、双机信息
ColectOS_EnvInfo.SUMMARY=信息收集完成。所有收集信息保存于目录 @COLLECTPATH。如果目录占用空间较大，建议做文件压缩处理。
CollectOS_EnvInfo_SolHA.getRLinkStatus.NORLink=双机复制状态异常或者不存在复制关系
CollectOS_EnvInfo_SolHA.getRLinkStatus.NORLink.detail=使用命令"vxprint -P"无法获取双机复制关系状态异常或者获取失败
CollectOS_EnvInfo_SolHA.getRLinkStatus.InvaildState=双机复制链接 @RLName的 @TYPE属性处于异常状态 @STATE
CollectOS_EnvInfo_SolHA.getRLinkStatus.InvaildState.detail=使用命令"vxprint -P |grep ^rl"查看双机的复制状态，@TYPE的状态为 @RIGHTSTATE表示正常运行状态
CollectOS_EnvInfo_SolHA.getRLinkStatus.CORRECTLY=双机复制状态正常
CollectOS_EnvInfo_SolHA.getRLinkStatus.CORRECTLY.detail=使用命令"vxprint -P"，可以查看双机复制状态
CollectOS_EnvInfo_SolHA.checkVCSStatus.NOVCS=资源组信息不存在
CollectOS_EnvInfo_SolHA.checkVCSStatus.NOVCS.detail=使用命令"hastatus -sum"无法获取双机复制关系状态异常或者获取失败
CollectOS_EnvInfo_SolHA.checkVCSStatus.InvaildState=VCS集群的资源组处于故障状态
CollectOS_EnvInfo_SolHA.checkVCSStatus.InvaildState.detail=资源组" @GROUPS"处于故障状态，使用"hastatus -sum"，可以查看详细的VCS集群状态。可以使用命令"hagrp -clear {资源组名称} -sys {操作系统主机名}"消除故障状态
CollectOS_EnvInfo_SolHA.checkVCSStatus.CORRECTLY=VCS集群的资源组状态正常
CollectOS_EnvInfo_SolHA.checkVCSStatus.CORRECTLY.detail=使用命令"hastatus -sum"，可以查看详细的VCS集群的资源组状态
CollectOS_EnvInfo_SolHA.checkHeartbeat.NOHeartbeat=双机心跳异常
CollectOS_EnvInfo_SolHA.checkHeartbeat.NOHeartbeat.detail=使用命令"hastatus -sum |grep '^L'"，可以查看详细的双机心跳信息。
Patch_PreCheck.CheckInfo=执行组件@component前置检查脚本@script。
Patch_PreCheck.CheckResult=执行检查结果不通过。
Patch_PreCheck.CheckResultNotFound=找不到脚本。
Check.Timeout=检查超时
Check.Item.Title=执行 {0}
Check.Item.Error.File.Not.Exist=脚本文件不存在。
Check.Item.Error.Return.Code=返回错误码 {0}。
OK= ( 正常 )
Failed= ( 异常 )  \n  [ 详细信息 ] {0}
RestorePreEnvCheck.title=恢复前检查
RestorePreEnvCheck.Retry=重试
Check.NullResult=检查失败，请检查网络连接是否正常。
