ClientSummary.Title=安装信息确认
ClientSummary.Prompt=提示
ClientSummary.CheckMemAndDisk=正在检测磁盘空间，请稍候...
ClientSummary.Retry=重试
ClientSummary.DiskSpaceNotEnoughCMD=磁盘空间不足。
ClientSummary.Cancel=退出安装
ClientSummary.Previous=返回上一步


ClientInstallUtil.SetupModeNotSupply=组件文件为空，程序将退出。
ClientInstallUtil.Error=错误
ClientInstallUtil.Unselected = 请选择组件。
ClientInstallUtil.NotAuthority=当前用户的权限受限，程序将退出。
ClientInstallUtil.AllPackagesInstalled=所有组件都已经安装了。
ClientInstallUtil.Hint=提示
ClientInstallUtil.IsVersionConflict=版本冲突，不能继续安装。
ClientInstallUtil.ConflictDetail=所选择的组件或补丁与当前版本冲突，不能继续安装。
ClientInstallUtil.InvalidCopyFilesClass=初始化jar过滤器失败。
ClientInstallUtil.DependenceError=组件依赖关系错误，如：出现循环依赖的情况。详细情况请查看日志。
ClientInstallUtil.NotFindXMLFilesContent=没有组件可以被安装。
ClientInstallUtil.ClientMode=只安装客户端
ClientInstallUtil.PathIsNull=安装路径不可以为空。
ClientInstallUtil.CheckInstallPathChar=安装路径不能有特殊字符，只支持字母、数字、下划线。
ClientInstallUtil.IsNotMatchProductRule=网管安装路径不符合路径规范，请参考安装指导书。


ClientSummaryUtil.DiskSpaceNotEnough=此分区磁盘空间不足：“{0}”
ClientSummaryUtil.ActualDiskSpace=可用的磁盘空间：
ClientSummaryUtil.NeededDiskSpace=需要的磁盘空间：
ClientSummaryUtil.BaseInfomatin=[基本信息]
ClientSummaryUtil.InstallPath=安装路径：
ClientSummaryUtil.OSType=操作系统类型：
ClientSummaryUtil.OSVersion=操作系统版本：
ClientSummaryUtil.ProductVersion=产品版本：
ClientSummaryUtil.Drive=磁盘：
ClientSummaryUtil.IsCreateShotcutOnDesk=是否在桌面创建快捷方式？

