ClientInstallProgress.CopyingFilesPleaseWait=正在安装客户端，请稍候...
ClientInstallProgress.CopyShowTime=分钟
ClientInstallProgress.InstallDiskXml=正在执行安装脚本...
ClientInstallProgress.InstallComplete=安装完成。



ClientInstallTask.CopyError=复制文件失败，程序将退出。
ClientInstallTask.UninstallInformation=正在保存安装信息...
ClientInstallTask.RecoverError=恢复文件 {0} 失败，是否继续？
ClientInstallTask.IsDiskFull=磁盘空间满。\n请手工清理磁盘后重试，或单击<取消>，退出此次安装。
ClientInstallTask.UnzipFiles=正在解压 {0}...
ClientInstallTask.CopyingFile=正在复制文件...
ClientInstallTask.CopyJRE=正在拷贝JRE...
ClientInstallTask.CopyUninstallFolderContent=正在生成卸载文件...
ClientInstallTask.CreateShotcuts=创建快捷方式...

