ClientCopyRight.ContentsVerify=本校验程序将帮您完成安装包的校验。
ClientCopyRight.Contents=本安装程序将指导您完成{0}的安装，请仔细阅读下述条款：
ClientCopyRight.NotAuthority=当前用户的权限受限，程序将退出。
ClientCopyRight.Agree=我接受上述条款
ClientCopyRight.Disagree=我不接受上述条款
ClientCopyRight.Cancel=确定取消安装吗？
ClientCopyRight.Yes=是
ClientCopyRight.No=否
ClientCopyRight.ReadClientCopyRight=请仔细阅读下述条款：
ClientCopyRight.ReadCopyRight=请仔细阅读下述条款：
ClientCopyRight.Title=版权声明

