ClientExportDeploySchema.ExportDeploySchemaFile=导出预定义部署文件：
ClientExportDeploySchema.Browse=浏览(B)
ClientExportDeploySchema.InvalidPath=请输入一个正确的文件名。
ClientExportDeploySchema.Next=下一步
ClientExportDeploySchema.DiskError=选择的分区错误。
ClientExportDeploySchema.DirectoryMustBeCharAndNum=1.必须选择该服务器的磁盘驱动器；\n2.要求目录名必须是绝对路径，且是英文字母，中文字符和数字以及\'_\'和\'-\'的组合；\n3.长度不能超过60个字符，'\\'或'/'或':'前不能有空格。
ClientExportDeploySchema.Error=错误
ClientExportDeploySchema.FileExist = 已经存在\n要替换它吗？
