ClientInstallExitPage.ErrorNote={0} 安装失败，具体信息请查看日志 {1}。
ClientInstallExitPage.Note={0} 客户端已经安装到 {1}。单击<完成>完成安装。\n为了保证安装文件被损坏时可以被恢复，建议手工备份安装目录。\n
ClientInstallExitPage.ErrorTitle=安装失败
ClientInstallExitPage.Title=安装完毕
ClientInstallExitPage.Finish=完成
ClientInstallExitPage.NoteCMD={0} 客户端已经安装到 {1}。\n为了保证安装文件被损坏时可以被恢复，建议手工备份安装目录。

