CMDWizardFrame.install = 安装
CMDWizardFrame.uninstall = 卸载
CMDWizardFrame.next = 下一步 >>
CMDWizardFrame.previous = << 上一步
CMDWizardFrame.cancel = 取消
CMDWizardFrame.hint = 提示
CMDWizardFrame.InstallAffirmCancel = 确定取消安装吗？
CMDWizardFrame.UninstallAffirmCancel = 确定取消卸载吗？
CMDWizardFrame.UpdateAffirmCancel = 确定取消升级吗？
