




[Common]
Commissioning.Menu.Tool=工具(T)
Commissioning.Menu.Title=调测工具(C)...
CommissioningTool=调测工具
APP_BUTTON=应用(A)
CheckDB_NMSStatus=检查数据库/网管运行状态...
DBNotRunning=检查数据库失败，可能原因：\n1.数据库未运行。\n2.数据库运行状态不正常。
NMSisRunning=服务器上的网管正在运行，请先停止网管。
HAjoined=双机处于关联状态，请先分离主备站点。
NeedRebootFirst=系统配置已经更改，请重启网管服务器操作系统使配置生效。
NEXT_STEP_PROMPT=数据有变更，是否提交？
INPUT_NOT_FULL=输入数据不完整，是否继续输入？
Commissioning.Confirm=调测工具适用于生产预安装后，结合实际组网参数对系统进行配置，\n可用于检测当前的配置，可以修改主机名、IP、调整组网方案、配置\n时钟、修改密码、配置OSS、配置路由、启用安全加固等操作。\n\n前置条件：\n1、确保网管已关闭。\n2、确保数据库已启动。{0}\n\n调测流程：\n1、按现网规划主备主机名、IP地址、密码、时钟等数据。\n2、关闭网管，保持数据库启动。\n3、运行调测工具。\n4、检查已有的配置。\n5、按调测向导进行调测。\n\n注意事项：\n如果进行IP组网调整，手工配置的IP信息会被清空，请做好备份，\n调整完成后，请重新手工配置。\n
Commissioning.Confirm.hainfo=\n3、确保双机处于分离状态。
Commissioning.start=开始
Commissioning.cancel=取消
DataNotChanged=提交的数据没有变更。
Colon=：
MSERROR_NMSONLINE_ChECK=网管正在运行，请手动停止网管，并重试。
MSERROR_NMSONLINE_ChECKMSG=网管正在以下主机上运行：
CommssioningPrecheckFailed=调测工具前置检查失败。
[/Common]


[WelcomPage]
QUERY_INFO=正在获取配置信息...
Commissioning.collectfailed=获取信息失败
Commissioning.Page.WelcomeSummary=调测前系统信息
sec_hardware=硬件信息
sec_hardware_cpu=处理器：
sec_hardware_ram=内存：
sec_hardware_disk=硬盘：

sec_software=软件信息
sec_software_OSVersion=操作系统：
sec_software_NMSversion=网管版本：
sec_software_installtype=安装类型：
sec_software_databasetype=数据库类型：
sec_software_databaseversion=数据库版本：
sec_software_databasesize=数据库安装类型：
sec_software_VCSversion=VCS版本：

sec_securityset=安全加固
sec_securityset_version=版本：
sec_securityset_isinstalled=是否安装：
sec_securityset_installed=已安装
sec_securityset_uninstalled=未安装
sec_securityset_set=运行状态：
sec_securityset_notrunning=未运行
sec_securityset_running=运行

sec_datetime=日期时间
sec_datetime_date=日期：
sec_datetime_time=时间：
sec_datetime_timezone=时区：

sec_ntp=NTP
sec_ntp_status=NTP状态：
sec_ntp_config=NTP配置：
sec_ntp_serverip=服务器IP：
notrunning=未运行
running=运行
ntpClient=客户端
ntpMedialServer=中间层服务器
ntpSeniorServer=顶层服务器
noconfig=未配置
unknow=未知

sec_virussoft=趋势防病毒软件
sec_virussoft_isinstalled=是否安装：
sec_virussoft_unintalled=未安装
sec_virussoft_officever=软件版本号：
sec_virussoft_virusver=病毒库版本号：

sec_router=路由
sec_router_destination=目的地
sec_router_netmask=子网掩码
sec_router_gateway=网关

sec_network=网络配置
sec_network_interface=网口
sec_network_ip=IP地址
sec_network_netmask=子网掩码
sec_network_iptype=IP类型

sec_hostname=主机名

sec_instance=多实例信息
sec_instance_subsystem=部署包
sec_instance_instancenum=实例个数

EXPORT_BUTTON=导出(E)
EXPORT_SUCCEED=成功导出文件到"{0}"。
EXPORT_FAILED=导出文件失败。
[/WelcomPage]


[DateTimeZone]
DateTimeZone.Title=配置时间时区
NowTimeZone=当前时区时间
NewTimeZone=新时区时间
DateTimeZone.Time=时间：
DateTimeZone.Zone=时区：
TOOLTIPTXT_CHANGETIMEZONE=修改时间时区
DateTimeZone.Info=请参考调测指南**章**节
TOOLTIPTXT_OPERATESUCCESS=修改时间成功，请重启维护工具服务。
TOOLTIPTXT_OPERATETIMEZONESUCCESS=修改时间时区成功，请重启网管服务器操作系统使配置生效。
TOOLTIPTXT_OPERATETIMEZONEFAILED=修改时间时区失败，请检测网络是否正常。
[/DateTimeZone]


[NTP]
NTP.Title=配置NTP
NTP.client=将服务器配置为NTP客户端
NTP.medialserver=将服务器配置为NTP中间级时间服务器
NTP.seniorserver=将服务器配置为NTP高层时间服务器
NTP.clientip=NTP服务器IP地址：
NTP.medialserverip=上级NTP服务器IP地址：
TITLE_PROGRESS_DLG=配置NTP
INPUT_IP_ERROR=输入的IP地址“{0}”不合法。
INPUT_IP_NEED_MODIFY=输入的IP地址“{0}”不符合NTP配置本地时钟规则，请按照NTP配置规则添加，例如：127.127.1.0。
TOOLTIPTXT_CFGNTPSUCCESS=配置NTP成功。
TOOLTIPTXT_CFGNTPSUCCESS_WITHIPNOCONNECTION=配置NTP成功，但是存在不可达IP。
TOOLTIPTXT_CFGNTPSUCCESS_IP=NTP服务器IP为：
TOOLTIPTXT_CFGNTPSUCCESS_NOCONNECTIONIP=不可达IP为：
TOOLTIPTXT_CFGNTPMASTERCANNOTDEL=NTP主用服务器不允许删除。
TOOLTIPTXT_CFGNTPATLEASTONEIP=至少需要配置一个NTP服务器。
TOOLTIPTXT_CFGNTPNOITEMSEL=请选择需要删除的NTP服务器。
TOOLTIPTXT_CFGNTPMAXLIMIT=NTP服务器至多可以配置10个。
TOOLTIPTXT_CFGNTPFAILED=配置NTP失败。
TOOLTIPTXT_CFGNTPIPVALID=配置NTP的IP无效。
TOOLTIPTXT_SAMENTP=输入的NTP服务信息重复。
UI_NTP_SERVER_MASTER_IP=主用服务器
UI_NTP_SERVER_STANDBY_IP=备用服务器
COL_NAME_SERVER=服务器
[/NTP]


[Hostname]
Commissioning.Page.Hostname=配置主机名
Hostname=主机名：
StartModifyHostname=修改主机名中，请稍候...
ModifyHostnameInstruction=请参考调测指南“如何修改单机系统（Windows）的主机名”章节。
MODIFY_HOSTNAME_SUCCEED=修改主机名成功，请重启网管服务器操作系统使配置生效。
MODIFY_HOSTNAME_FAILED=修改主机名失败。
INPUT_HOSTNAME_NOT_VALID=输入的主机名不合法。
INPUT_HOSTNAME_ERROR_DETAIL_1=新的主机名必须符合主机名的命名规则：\n1.网管服务器主机名在网络中必须是唯一的。\n2.主机名是长度不超过24个字符的字符串，所用字符必须是字母（A~Z或者a~z）、数字（0~9）、减号（-）。\n3.第一个字符必须是字母。最后一个字符不能是减号。\n
INPUT_HOSTNAME_ERROR_DETAIL_2=4.主机名不支持“--”字符串。\n5.主机名区分大、小写字母。\n6.主机名中不能有空白或空格符。\n7.不能使用单字符主机名。\n8.在高可用性系统（Veritas）中，不支持以下关键字作为主机名：\n
INPUT_HOSTNAME_SAME_WITH_OLDNAME=输入的主机名“{0}”已存在，请重新输入。

[/Hostname]


[PValue]
Commissioning.Page.ChangePValue=配置密码
SelectAll=全选
PVALUE_SELECTED=已勾选配置密码用户，是否修改？
PValueReference=请参考调测指南“如何修改单机系统（Windows）的数据库、维护工具密码”章节。
User=
ChangePValueWarnMsg=即将开始修改密码，是否继续？
ChangeFinsh=修改密码{0}，请查看详细信息获取修改结果。
ChangeSucceed=成功
ChangePartSucceed=部分成功
ChangeFailed=失败
OLD_PWD=旧密码
NEW_PWD=新密码
RENEW_PWD=确认新密码
OS_ROOT=操作系统root用户
OS_NMS=操作系统网管用户
OS_DB=操作系统数据库用户
DB_SA=数据库管理员用户
DB_NMS=数据库用户
MSUITE_ADMIN=维护工具管理员用户
ModifingPValues=正在修改密码...
NewPValueError=输入的密码必须满足下列条件：\n1.新密码不能为空。\n2.两次输入新密码必须相同。\n3.新密码不能与旧密码相同。
PValue.-1=未修改。
PValue.0=修改成功。
PValue.1=参数错误。
PValue.10=登录对端节点失败。
PValue.71=新密码为空。
PValue.72=两次输入的新密码不匹配。
PValue.73=新密码与旧密码相同。
PValue.74=新密码不符合规则，参考密码输入框提示规则。
PValue.75=确认新密码为空。
PValue.76=旧密码不符合规则，参考密码输入框提示规则。
PValue.80=修改成功。
PValue.81=校验旧密码失败。
PValue.82=校验旧密码失败。可能原因：1.旧密码输入错误。2.如果已经启用安全加固，请参考安装调测指南“如何修改操作系统用户密码”。
PValue.83=已经启用安全加固，请参考用户手册修改操作系统用户密码。
PValue.110=用户已经被锁定，还需{0}分钟解除锁定。
PValue.111=
PValue.119=修改失败，已经启用安全加固，请参考安装调测指南“如何修改操作系统用户密码”。
PValue.120=修改失败。
PValue.121=修改失败。可能原因：1.数据库旧密码错误。2.数据库状态异常。3.数据库启用了安全加固。
PValue.1509006=修改密码脚本不存在。
[/PValue]


[Router]
Commissioning.Page.ConfigRoute=配置路由
CONFIG_ROUTE_PROCESS_DLG=配置路由中，请稍候...
TOOLTIPTXT_CONFIGROUTESUCCESS=配置路由成功。
TOOLTIPTXT_CONFIGNETFAILED=配置服务器失败。
TOOLTIPTXT_CONFIGROUTEFAILED=配置路由失败。
INPUT_ROUTER_INFO_INVALID=输入的路由信息格式不正确。
INPUT_ROUTER_INFO_THE_SAME=输入的路由信息重复。
MODIFY_PARAMETER_ERROE=输入的网络参数与系统网络参数一致，请确认。
BTN_ADD=增加(D)
BTN_DEL=删除(E)
ConfigRouteFinish=配置路由完成，由于网络未接通，以下永久路由将在网络接通\n并且重启操作系统后生效。
CONFIRM_CHANGE_ROUTER_INFO=请确保新增/删除/修改路由的正确性,否则可能导致网络中断，请确认是否继续操作? 
CONFIRM_RM_ROUTER=是否确认要删除所选择的路由?

[/Router]


[Summary]
Commissioning.Page.Summary=调测完成
Commissioning.Info=以下是调测完成之后的配置信息：
Commissioning.Reboot=调测完成，请重启操作系统使配置生效。
Commissioning.useUEasyCheck=调测完成，请使用UEasy工具进行日常巡检。
[/Summary]
