


SubsystemTree.Title1 = 您已经选择按照{0}场景进行安装，默认选中{1}场景相关组件，您可以根据需要进行调整，安装后也可以通过网管系统维护工具进行调整。
SubsystemTree.Title2 = 您已经选择按照 License 文件安装，默认选中 License 文件中配置相关组件，您可以根据需要添加其他组件，后续也可以通过网管系统维护工具进行调整。
SubsystemTree.Title3 = 您已经选择自定义方式进行安装，您可以根据需要添加其他组件，后续也可以通过网管系统维护工具进行调整。
SubsystemTree.Title4 = 您已经选择全量方式进行安装，后续也可以通过网管系统维护工具进行调整。
SubsystemTree.ModifyButton =  选择组件
SubsystemTree.Done = 完成组件的选择
SubsystemTree.Title = 选择组件
DeploymentSchemeSubsystem.PakageFilesError=以下组件没有配置安装包文件。\n请修改后再运行安装。
DeploymentSchemeSubsystem.PackageDependencyError = 以下组件存在安装包依赖错误
DeploymentSchemeSubsystem.PackageErrorFilePath= 在目录 {0} 下找不到组件配置的安装包文件。\n组件与安装包对应关系如下：
DeploymentSchemeSubsystem.PackageDependenceFilePath= 在目录 {0} 下的安装包存在依赖错误。\n组件与安装包对应关系如下：


 
SubsystemTree.pkgnotexisted=有如下部署包不存在软件库{0}中，请按提示检查，并重新安装网管。
SubsystemTree.dependencynotexisted=有如下部署包的依赖配置错误，请按提示检查，并重新安装网管。
SubsystemTree.loopdependencyError= 有如下部署包存在循环依赖的错误配置，请按提示检查，并重新安装网管。
SubsystemTree.databasexmlError= 有如下组件的数据库描述文件配置错误，请按提示检查，并重新安装网管。
SubsystemTree.CrossdependencyError= 有如下组件的client和server部署包交叉依赖，请按提示检查，并重新安装网管。
SubsystemTree.staticdataError= 安装配置文件存在配置错误，请修改并重新安装网管。
errorXmlList=如下包描述文件xml解析失败
SubsystemTree.InitStaticDataError=初始化安装数据失败，请检查安装所需的配置文件是否存在。
subsystem.not.config.componentree=如下子系统未在组件树进行配置。

DeploymentSchemeSubsystem.AllNodesConfig=所有的节点将被默认配置。
ComponentTree.NO_PKG_FILE_LIST=以下组件的子系统描述文件不存在，\n请确认是否继续安装？
ComponentTree.NO_PKG_FILE_TITLE=子系统描述文件不存在
ComponentTree.NO_PKG_FILE_LIST_ERROR=以下组件的子系统描述文件不存在。
