
ConfigDeploymentsSubsystem.Title=配置多实例子系统的实例个数。
ConfigDeploymentsSubsystem.Node=节点
ConfigDeploymentsSubsystem.Subsystem=服务组
ConfigDeploymentsSubsystem.SubsystemType=部署包
ConfigDeploymentsSubsystem.InstanceCount=实例个数
ConfigDeploymentsSubsystem.SubsystemDescription=部署包描述
ConfigDeploymentsSubsystem.SinglePerNode=单服务器单实例
ConfigDeploymentsSubsystem.SinglePerSystem=系统单实例
ConfigDeploymentsSubsystem.NoInstance=单服务器无实例
ConfigDeploymentsSubsystem.MultipleInstances=单服务器多实例
ConfigDeploymentsSubsystem.SubsystemInfo=组件信息
ConfigDeploymentsSubsystem.Summary_NodeName=服务器名称：
ConfigDeploymentsSubsystem.Summary_Subsystem=组件：
ConfigDeploymentsSubsystem.Summary_SubsystemType=组件类型：
ConfigDeploymentsSubsystem.Summary_InstanceCount=实例个数：
ConfigDeploymentsSubsystem.Summary_SubsystemDescription=描述：
ConfigDeploymentsSubsystem_index=序号
modify_instance_count=修改实例数目
finish_config=完成配置
input_error=输入错误
list_separtor=请选择组件列表，使用逗号分隔
pls_input=请输入 
instance_count=实例个数
DeploymentSchemeSubsystem.options=选项
DeploymentSchemeSubsystem.InvalidInput=请输入正确选项






