bcp_check_error=复用数据库时，执行bcp命令检测失败。
ConfigDBServer.Browse=浏览(B)...
ConfigDBServer.Browse.Data=浏览(R)...
ConfigDBServer.CheckDBSoftwareLibPath=请输入数据库安装包的路径（例如：/opt/install/，thirdparty目录的上层目录即可）：
ConfigDBServer.CheckDBVersion=已经存在的数据库软件版本是@dbrelease，但是网管要求的数据库版本是@require，\n 请确认数据库版本，或者手工卸载已安装的数据库软件并继续网管安装。
ConfigDBServer.CheckFilePath=数据文件路径不能有特殊字符，只支持字母，数字，下划线，或者路径错误。
ConfigDBServer.checkInstallFile=目录 {0} 中，\n没有发现：{1} 数据库安装文件。 \n请确认路径或数据库安装文件包是否存在。
ConfigDBServer.CheckLinuxPackage=缺少安装Oracle的SUSE Linux软件包。\n
ConfigDBServer.CheckOraclePathc=oracle 11.0.7.0补丁安装包不存在，请先拷贝oracle 11.0.7.0补丁包。
ConfigDBServer.CheckSpareSpace=磁盘空间不足
ConfigDBServer.checkSQLSvrSortType=数据库的排序规则必须是"@sortType"，请使用Transact-SQL命令"sp_helpsort"检查当前数据库的排序规律。
ConfigDBServer.CheckSQLSvrVersion=已经存在的数据库软件版本是@dbrelease，但是网管要求的数据库版本是@require，请确认数据库版本。
ConfigDBServer.checkSybaseCharSet=校验Sybase数据库字符集失败\n 请修改数据库字符集为 @CharsetInfo。
ConfigDBServer.CheckSybaseVersion=已经存在的数据库软件版本是@dbrelease，但是网管要求的数据库版本是@require，请确认数据库版本，或者是否重新安装数据库。\n (Y)确认版本 (N)重新安装数据库软件。
ConfigDBServer.checkwindowsdir=获取操作系统目录环境%SystemRoot%失败。
ConfigDBServer.ConfirmReinstallSQLSvr=请确定是否复用已安装的数据库软件。\n选择(Y)，复用已安装数据库，可能会覆盖已有数据库数据，并且不能恢复，请首先备份数据库数据。\n选择(N)，需要用户手工卸载已安装的数据库软件并继续网管安装。
ConfigDBServer.ConfirmReinstallSybase=复用原有数据库软件或者安装新的数据库软件都可能会覆盖已有数据库数据并且不能恢复，请首先备份数据库数据。\n(Y)复用数据库软件(N)重新安装数据库软件。
ConfigDBServer.ConnectCheck=连接数据库失败，可能是由于如下原因导致的：\n1. 数据库服务器不在线。\n2. 数据库服务名错误。\n3. IP或端口错误。\n4. 数据库管理员用户名称错误。\n5. 数据库管理员用户密码错误。
ConfigDBServer.ConnectCheckNm=连接数据库失败，可能是由于如下原因导致的：\n1. 数据库服务器不在线。\n2. 数据库服务名错误。\n3. IP或端口错误。\n4. 数据库管理员用户名称错误。\n5. 数据库管理员用户密码错误。
ConfigDBServer.ConnectIPCheck=数据库IP地址非法。
ConfigDBServer.ConnectInfoCheckEmpty= 所有数据库配置信息不能为空。
ConfigDBServer.DatabasePort=数据库端口：
ConfigDBServer.DatabaseServerIP=数据库地址：
ConfigDBServer.DatabaseServerName=数据库服务名称：
ConfigDBServer.dataPathIncorrect=数据文件路径不能为空。
ConfigDBServer.DBDatePath=数据文件路径：
ConfigDBServer.DBInformation=数据库服务器信息
ConfigDBServer.DBLogDatePath=数据日志路径
ConfigDBServer.DBUserName=数据库用户名称
ConfigDBServer.DBUserPassword=网管数据库用户密码：
ConfigDBServer.DBUserPasswordConfirm=确认网管数据库用户密码：
ConfigDBServer.DBUserPasswordconfirmIncorrect=网管数据库用户密码输入不一致。
ConfigDBServer.DBUserPasswordIncorrect=数据库用户密码输入错误只能使用数字或者字符0-9,a-z,A-Z。
ConfigDBServer.GUIInitialize=初始化数据库配置页面信息失败。
ConfigDBServer.installDirLabel=安装包路径
ConfigDBServer.InstallPath=数据库安装路径
ConfigDBServer.InstallPathIncorrect=安装路径不能为空。
ConfigDBServer.INVALID_INSTAL_PATH_DATA=输入的数据文件路径不正确，可能原因：路径为空或长度超过60个字；路径包含非法字符；路径不是绝对路径。
ConfigDBServer.INVALID_INSTAL_PATH_DB=输入的数据库安装路径不正确，可能原因：路径为空或长度超过60个字；路径包含非法字符；路径不是绝对路径。
ConfigDBServer.INVALID_INSTAL_PATH_LOG=输入的日志文件路径不正确，可能原因：路径为空或长度超过60个字；路径包含非法字符；路径不是绝对路径。
ConfigDBServer.ISQLConnectCheck_Oracle=使用sqlplus命令连接Oracle服务失败，\n请确认Oracle的环境变量是否正确。
ConfigDBServer.ISQLConnectCheck_SQL=使用isql命令连接SQL Server服务失败，\n请确认SQL Server的环境变量是否正确。
ConfigDBServer.ISQLConnectCheck_Sybase=使用isql命令连接Sybase服务失败，\n请确认Sybase的环境变量正确。
ConfigDBServer.logPathIncorrect=日志文件路径不能为空。
ConfigDBServer.NMSOraclePasswdLength1=字母和数字
ConfigDBServer.NMSOracleUserPasswdChar=密码只能包含字母和数字。
ConfigDBServer.NMSPasswdLength=数据库用户密码长度不小于6位，并且只能包含：
ConfigDBServer.NMSPasswdLength1=字母和数字
ConfigDBServer.NMSPasswdLength2=（如果没有安装数据库服务器，将自动安装数据库服务器。
ConfigDBServer.NMSPasswdLength3=界面向导中已经默认生成缺省数据库管理员用户密码与
ConfigDBServer.NMSPasswdLength4=数据库用户密码，可以根据需要进行更改。）
ConfigDBServer.NMSUserAdministrator=安装SQL Server2008不能使用非管理员权限的用户安装，\n请注销系统后，使用具有管理员权限的用户登录系统，重新执行安装。
ConfigDBServer.NMSUserPasswdChar=密码只能包含字母和数字
ConfigDBServer.NMSUserPasswdChar2008=<html>网管数据库用户密码必须同时满足下列条件：<br>&nbsp;1：密码长度必需8个字符以上，且不超过30个字符。<br>&nbsp;2：密码字符只能是(A-Z、a-z、0-9、_)。<br>&nbsp;3：密码至少满足下列四个条件中的三个：<br> &nbsp; &nbsp; &nbsp;必须包含大写字母（A－Z）;<br> &nbsp; &nbsp; &nbsp;必须包含小写字母（a－z）;<br> &nbsp; &nbsp; &nbsp;必须包含数字（0－9）;<br> &nbsp; &nbsp; &nbsp;必须包含下划线。<br></html>
ConfigDBServer.NMSUserPasswdLength=网管数据库用户密码长度需要不小于6位
ConfigDBServer.NMSUserPasswdNULL=网管数据库用户密码不能为空。
ConfigDBServer.OracleConnectCheck=数据库管理员用户连接Oracle服务失败，请检查数据库服务是否启动，或者重新安装数据库？\n (Y)检查数据库 (N)重新安装数据库软件。
ConfigDBServer.OracleConnectCheckNm=连接Oracle服务失败，检查数据库是否启动或网管数据库用户密码是否正确。
ConfigDBServer.OracleNotExist=未安装oracle数据库，请先安装数据库。
ConfigDBServer.OraclePassword=<html>网管数据库用户密码必须同时满足下面条件：<br>&nbsp;1：长度不小于6位。<br>&nbsp;2：并且只能包含：字母、数字或下划线<br>&nbsp;</html>
ConfigDBServer.PassWordLengthError=密码长度不能小于6位。
ConfigDBServer.PassWordLengthError2008=密码长度不能小于8位。
ConfigDBServer.PathCreateFail=创建路径@Path失败，请确认当前路径是否正确。
ConfigDBServer.ResourcePathHavaSpace=SQL SERVER安装源路径不能包含有空格，请确认SQL SERVER的安装源路径。
ConfigDBServer.SANameIncorrect=数据库管理员用户密码名称输入错误，只能使用字符：a-z,A-Z
ConfigDBServer.SAOraclePasswdLength=数据库管理员用户密码长度不小于6位，并且只能包含：
ConfigDBServer.SAOraclePasswdLength1=字母、数字和下划线
ConfigDBServer.SAOraclePasswdLengthError=数据库管理员用户密码长度不能小于6位。
ConfigDBServer.SAOraclePasswdRule=<html>数据库管理员用户密码必须同时满足下面条件：<br>&nbsp;1：长度不小于6位。<br>&nbsp;2：并且只能包含：字母、数字或下划线<br>&nbsp;</html>
ConfigDBServer.SAPasswdLength=数据库管理员用户密码长度不能小于6位，并且只能包含：
ConfigDBServer.SAPasswdLength1=字母和数字
ConfigDBServer.SAPasswdLength2=（如果已经安装数据库服务器，将校验输入信息合法性
ConfigDBServer.SAPasswdLength2008=数据库管理员用户密码长度不小于8位，并且必须包含：
ConfigDBServer.SAPasswdLength20081=大写字母、小写字母、数字。不允许输入的符号（[] {}() , ; ? * ! @ . ）。
ConfigDBServer.SAPasswdLength20082=（如果已经安装数据库服务器，将校验输入信息合法性
ConfigDBServer.SAPasswdLength20083=（数据库管理员用户密码），并默认生成缺省数据库用户
ConfigDBServer.SAPasswdLength20084=密码，可以根据需要进行更改。
ConfigDBServer.SAPasswdLength3=（数据库管理员用户密码），并默认生成缺省数据库用户
ConfigDBServer.SAPasswdLength4=密码，可以根据需要进行更改。）
ConfigDBServer.SAPasswdLengthError=数据库管理员用户密码长度不能小于6位。
ConfigDBServer.SAPasswdNULL=数据库管理员用户的密码不能为空。
ConfigDBServer.SAPasswdRule=<html>数据库管理员用户密码必须满足下面条件：<br>&nbsp;1：长度不小于6位，且最大长度不能超过30位<br>&nbsp;2：并且只能包含：字母、数字或下划线<br></html>
ConfigDBServer.SAPasswdRule2008=<html>数据库用户密码必须同时满足下列条件：<br>&nbsp;1：密码长度必需8个字符以上，且不超过30个字符。<br>&nbsp;2：密码至少满足下列四个条件中的三个：<br> &nbsp; &nbsp; &nbsp;必须包含大写字母（A－Z）;<br> &nbsp; &nbsp; &nbsp;必须包含小写字母（a－z）;<br> &nbsp; &nbsp; &nbsp;必须包含数字（0－9）;<br> &nbsp; &nbsp; &nbsp;必须包含下划线。<br> &nbsp; &nbsp; &nbsp;不允许输入的符号（[] {}() , ; ? * ! @ . ）<br></html>
ConfigDBServer.SAPasswordconfirmIncorrect=管理员用户密码输入不一致。
ConfigDBServer.SAPasswordIncorrect=数据库管理员用户密码输入错误，只能使用数字或者字符0-9,a-z,A-Z
ConfigDBServer.SAUserName=数据库管理员用户名称
ConfigDBServer.SAUserPassword=数据库管理员用户密码：
ConfigDBServer.SAUserPasswordConfirm=确认数据库管理员用户密码
ConfigDBServer.SQLServer2000Password=<html>网管数据库用户密码需满足下面条件：<br>&nbsp;1：长度不小于6位，且最大长度不能超过30位<br>&nbsp;2：只能包含：字母、数字或下划线<br>&nbsp;</html>
ConfigDBServer.Summary=[配置数据库信息]
ConfigDBServer.Summary_InstallPath=安装路径：
ConfigDBServer.Summary_SAUserName=数据库管理员用户名称：
ConfigDBServer.SybaseConnectCheck=数据库管理员用户连接Sybase服务失败，原因：\n    管理员用户密码错误。\n请确认是否重新安装数据库？\n    (Y)重新检查数据库\n   (N)重新安装数据库软件。
ConfigDBServer.SybaseConnectCheckNm=网管数据库用户密码错误，数据库网管用户连接Sybase服务失败。
ConfigDBServer.SybaseNotExist=未安装sybase数据库，请先安装数据库。
ConfigDBServer.SybasePassword=<html>网管数据库用户密码需满足下面条件：<br>&nbsp;1：长度不小于6位，且最大长度不能超过30位<br>&nbsp;2：只能包含：字母、数字或下划线<br></html>
ConfigDBServer.the.dir=到如下目录：
ConfigDBServer.Title=请配置数据库参数。
ConfigDBServer.TitleCMD=请配置数据库参数
dir_Not_empty=Oracle安装目录 {0} 为非空目录，请选择另外一个目录。
EN_OS_NOT_Support_ZH_SQLServer=当前操作系统为英文的，不支持安装中文的SQL Server数据库。
osql_check_error=复用数据库时，执行osql命令检测失败。
Windows_Sybase_client_exist=本机安装了Sybase客户端，影响SQL Server的使用。请手动卸载Sybase后再安装网络管理系统。
ConfigDBServer.renamePassword=网管数据库用户密码与输入密码不一致，是否重置数据库密码为输入密码？ \n 是：重置网管数据库密码为输入密码。 \n 否：重新输入数据库密码。
ConfigDBServer.CheckOSSUserNAMEPWD=网管数据库用户名@DBUser不能为该用户密码。
ConfigDBServer.OSSUserPasswordconfirmIncorrect=网管数据库用户密码输入不一致。
ConfigDBServer.SAPWDConfirmIncorrect=数据库管理员用户密码输入不一致。
ConfigDBServer.SAPWDRuleSQL2008=<html>网管数据库用户密码必须同时满足下列条件：<br>&nbsp;1：密码长度必需8个字符以上，且不超过30个字符。<br>&nbsp;2：密码字符只能是(A-Z、a-z、0-9、_)。<br>&nbsp;3：密码至少满足下列四个条件中的三个：<br> &nbsp; &nbsp; &nbsp;包含大写字母（A－Z）;<br> &nbsp; &nbsp; &nbsp;包含小写字母（a－z）;<br> &nbsp; &nbsp; &nbsp;包含数字（0－9）;<br> &nbsp; &nbsp; &nbsp;包含下划线。<br></html>
ConfigDBServer.OSSUserPWDRuleSQL2008=<html>网管数据库用户密码必须同时满足下列条件：<br>&nbsp;1：密码长度必需8个字符以上，且不超过30个字符。<br>&nbsp;2：密码字符只能是(A-Z、a-z、0-9、_)。<br>&nbsp;3：密码至少满足下列四个条件中的三个：<br> &nbsp; &nbsp; &nbsp;包含大写字母（A－Z）;<br> &nbsp; &nbsp; &nbsp;包含小写字母（a－z）;<br> &nbsp; &nbsp; &nbsp;包含数字（0－9）;<br> &nbsp; &nbsp; &nbsp;包含下划线。<br></html>
ConfigDBServer.SAPWDRuleSQL2000=<html>数据库管理员用户密码需满足下面条件：<br>&nbsp;1：长度不小于6位，且最大长度不能超过30位<br>&nbsp;2：只能包含：字母、数字或下划线<br>&nbsp;</html>
ConfigDBServer.OSSUserPWDRuleSQL2000=<html>网管数据库用户密码需满足下面条件：<br>&nbsp;1：长度不小于6位，且最大长度不能超过30位<br>&nbsp;2：只能包含：字母、数字或下划线<br>&nbsp;</html>
ConfigDBServer.SAPWDRuleOracle=<html>数据库管理员用户密码必须同时满足下面条件：<br>&nbsp;1：长度不小于6位。<br>&nbsp;2：并且只能包含：字母、数字或下划线<br>&nbsp;</html>
ConfigDBServer.OSSUserPWDRuleOracle=<html>网管数据库用户密码必须同时满足下面条件：<br>&nbsp;1：长度不小于6位。<br>&nbsp;2：并且只能包含：字母、数字或下划线<br>&nbsp;</html>
ConfigDBServer.SAPWDRuleSybase=<html>数据库管理员用户密码需满足下面条件：<br>&nbsp;1：长度不小于6位，且最大长度不能超过30位<br>&nbsp;2：只能包含：字母、数字或下划线<br></html>
ConfigDBServer.OSSUserPWDRuleSybase=<html>网管数据库用户密码需满足下面条件：<br>&nbsp;1：长度不小于6位，且最大长度不能超过30位<br>&nbsp;2：只能包含：字母、数字或下划线<br></html>


ConfigDBServer.PasswdRuleSQL2008=<html><br>&nbsp;1：密码长度必需8个字符以上，且不超过30个字符。<br>&nbsp;2：密码至少满足下列四个条件中的三个：<br> &nbsp; &nbsp; &nbsp;必须包含大写字母（A－Z）;<br> &nbsp; &nbsp; &nbsp;必须包含小写字母（a－z）;<br> &nbsp; &nbsp; &nbsp;必须包含数字（0－9）;<br> &nbsp; &nbsp; &nbsp;必须包含下划线。<br> &nbsp; &nbsp; &nbsp;不允许输入的符号（[] {}() , ; ? * ! @ . ）<br></html>
ConfigDBServer.PasswdRuleOracle=<html><br>&nbsp;1：长度不小于6位。<br>&nbsp;2：并且只能包含：字母、数字或下划线<br>&nbsp;</html>
ConfigDBServer.PasswdRuleSybase=<html><br>&nbsp;1：长度不小于6位，且最大长度不能超过30位<br>&nbsp;2：只能包含：字母、数字或下划线<br></html>
ConfigDBServer.PasswdRuleSQL2000=<html><br>&nbsp;1：长度不小于6位，且最大长度不能超过30位<br>&nbsp;2：只能包含：字母、数字或下划线<br>&nbsp;</html>
Not_local_ip=非本机IP，请使用本机IP进行连接。

ServerConfig.DatabasePort=数据库端口：
ServerConfig.DatabaseServerIP=数据库服务器地址：
ServerConfig.DatabaseServerName=数据库服务器名：

ConfigDBServer.DatabaseProcess=第三方数据库工具在连接网管数据库的"{0}"，是否继续安装？ \n 是：继续安装，在创建数据库数据时会删掉连接该库的会话。 \n 否：返回重试，请手工关闭连接后再试。
dbUserNameLabel=数据库管理员用户名称：

