help = 帮助
pls_config = 请配置
only_master = 仅可以主服务器部署
only_slave = 仅可以从服务器部署
any_server = 可以任意服务器部署
all_must = 所有服务器必须部署
single_single_type = 单节点单实例类型
mutil_type = 多实例类型
system_single_type = 系统单实例类型
none_type=无实例类型
the_select = 光标所选的是：
must_select_one_servergroup = 请至少选择一项服务组。
must_select_one_host = 请至少选择一个节点。
must_select_one_host_node=请至少选择一个主机下面的节点。
the_below_not_mutil_host = 如下单实例不能同时部署在多台服务器上。
the_below_only_mutil_slave_host=如下节点只支持部署在从服务器上。
the_below_only_master=如下节点只支持部署在主服务器上
the_below_must_all_host=如下节点必须部署在所有服务器上。请选择所有服务器节点
servicegroup_name=服务组名
servie_name=服务名
instance_type=实例类型
deploy_server_type=部署服务器类型
description=描述
okbtn=确定
exist_mismatch_instancetype_deploynodetype=下面的服务组中存在实例类型或部署服务器类型不一致。
ConfigServiceHostPage.Title=配置服务组
config_service_group_index= 序号
config_service_group_hostname=服务器名称
config_selected_service_group=已选择的服务组
config_service_group_input_error=输入错误
pls_select_operation_type=请选择需要的操作类型
finish_config=完成配置
the_below_must_install_mustselect=以下必装的子系统至少要选中一个节点进行部署。
servicegroup_info=[服务组信息]
hostInfoName=节点名称：
the_below_dependy_mustselect=以下是被依赖的服务组必须至少要在一个节点中部署。

SrvGrpNotExist=服务组{0}不存在，退出.