CopyRight.title=版权声明
CopyRight.ReadCopyRight=请仔细阅读下述条款：
CopyRight.agree=我接受上述条款
CopyRight.disagree=我不接受上述条款
CopyRight.Yes=是
CopyRight.No=否
CopyRight.Cancel=确定取消安装吗？
CopyRight.UpgradeCancel=确定取消升级吗？

CopyRight.Contents = 本安装程序将指导您完成{0}的安装，请仔细阅读下述条款：
CopyRight.ContentsVerify=本校验程序将帮您完成安装包的校验。
CopyRight.ContentsCMD = 本安装程序将帮您完成 {0} 的安装。
CopyRight.NotAuthority = 当前用户的权限受限，程序将退出。

CopyRight.Contents_Upgrade =本升级将指导您完成{0}网管系统的升级，请仔细阅读下述条款：
CopyRight.ContentsVerify_Upgrade=本校验程序将帮您完成升级包的校验。
CopyRight.Hint_Upgrade=等待
CopyRight.processing_Upgrade=处理中，请稍候...
CopyRight.FailedTOgetSiteInfo= 从数据模型中获取节点信息失败。

Introduction.IsRunning=还有另一个安装程序正在运行。请在安装前退出此程序。
Introduction.ContentsCMD=这个安装向导将引导您通过 {0} 安装。
Introduction.NotAuthority=用户的权利受限，该程序将退出。
Introduction.DBConfigFileInvalid=数据库配置文件不正确，安装将退出。
