CreateDatabase.Title = 数据库设置
CreateDatabase.RestoreDefaultValue = 恢复缺省值
CreateDatabase.SamePath = 路径和第一行相同
CreateDatabase.DBName = 数据库名称
CreateDatabase.DBSize = 大小(MB)
CreateDatabase.MaxDBSize = 最大(MB)
CreateDatabase.Data = 数据文件路径
CreateDatabase.Log = 日志文件路径
CreateDatabase.LogSize = 大小(MB)
CreateDatabase.MaxLogSize = 最大(MB)
CreateDatabase.RawDevice = 裸设备
CreateDatabase.Yes = 是
CreateDatabase.No = 否
CreateDatabase.Hint = 提示
CreateDatabase.DBPathCanNotEmpty = 文件路径不能为空。
CreateDatabase.DirectoryError = 目录错误：“{0}”。
CreateDatabase.InvalidDiskDriver = 无效磁盘驱动器：“{0}”。
CreateDatabase.InvalidInput = ：输入无效 
CreateDatabase.DirectoryMustBeCharAndNum = 1.必须选择该服务器的磁盘驱动器；\n2.要求目录名必须是绝对路径，且是英文字母，中文字符和数字以及\'_\'和\'-\'的组合；\n3.长度不能超过60个字符，'\\'或'/'或':'前不能有空格。
CreateDatabase.DBDirNotExistCreateIt = 数据目录 {0} 不存在，创建吗？
CreateDatabase.LogDirNotExistCreateIt = 日志目录 {0} 不存在，创建吗？
CreateDatabase.Error = 错误
CreateDatabase.CanNotCreateDirectory = 不能创建该目录。
CreateDatabase.NotDir = “{0}”不是目录，请选择一个目录。
CreateDatabase.DataFileNotExist =  {0} 数据文件 {1} 不存在。
CreateDatabase.LogFileNotExist =  {0} 日志文件 {1} 不存在。
CreateDatabase.DeviceIsInFileSystem = 该设备已mount到文件系统中，请先unmount。
CreateDatabase.DBSizeIsTooSmall = ：数据的最大值不能小于 {0} MB。
CreateDatabase.CannotSmallerThanOne = ：数值不能小于1。
CreateDatabase.LogSizeIsTooSmall = ：日志的最大值不能小于 {0} MB。
CreateDatabase.InputNumber = ：数据区或日志区输入为空或非法。
CreateDatabase.DataDirectory = 数据文件路径
CreateDatabase.LogDirectory = 日志文件路径
CreateDatabase.DBGrowthError = ：{0} 的最大值 {1} 不能小于该数据库的文件增长值 {2}。
CreateDatabase.NotNakeDirectory = 不是裸设备
CreateDatabase.Select = 选择
CreateDatabase.VVRNotInstalledYet = 卷管理软件未安装或不可用。
CreateDatabase.VolumePathNotExist = 磁盘组 {0} 不存在。
CreateDatabase.IsSupportDual = 双机模式
CreateDatabase.VolumehasExisted = 卷 {0} 已存在，覆盖吗？
CreateDatabase.FailToCreateVolume = 创建卷 {0} 失败。
CreateDatabase.FailToDeleteVolume = 删除卷 {0} 失败。
CreateDatabase.YesAll = 全是
CreateDatabase.NoAll = 全否
CreateDatabase.VolumePathInvalid = 卷路径 {0} 非法。\n目录必须在/dev/vx/rdsk下，且目录中不能含有空格。
CreateDatabase.isData = 数据
CreateDatabase.isLog = 日志

CreateDatabase.DBSizeLessLeastSize =：数据值不能小于最小值 {0}MB。
CreateDatabase.LogSizeLessLeastSize =：日志值不能小于最小值 {0}MB。

CreateDatabase.ChooseDirTip = 选择文件路径
CreateDatabase.RestoreTip = 将所有选项设为默认值
CreateDatabase.SamePathTip = 将其它文件路径设置成与第一行文件路径相同
CreateDatabase.VolumePathEmpty = 卷路径不能为空。
CreateDatabase.DataFile = 数据文件
CreateDatabase.LogFile = 日志文件
CreateDatabase.DataCanntBeWrite = 创建数据目录 {0} 失败或该目录不可写。
CreateDatabase.LogCanntBeWrite = 创建日志目录 {0} 失败或该目录不可写。
CreateDatabase.NoDevicenoToDistribute = 数据库中已经没有可分配的设备号，程序将退出。
CreateDatabase.InvalidPath = 目录不合法：
CreateDatabase.TablespaceName = 表空间名称
CreateDatabase.Type = 类型
CreateDatabase.Single = 单机
CreateDatabase.RawDeviceDual = 裸设备双机
CreateDatabase.FileVolumeDual = 文件卷双机
CreateDatabase.Symboliclinks =  一个或多个目录为链接，将转换为真实目录。
CreateDatabase.VolumeNameTooLong = 卷名不能超过31个字符。
CreateDatabase.DuplicatePaths = 指定的卷路径不能重复。
CreateDatabase.DB2.PageSizeInvalid = {0}的页大小错误。页大小可以是4K、8K、16K或32K
CreateDatabase.DB2.DBMinimumSize =：数据的大小不能小于2MB。
CreateDatabase.VolumeNameInvalid = 卷名不存在或卷路径无效。
CreateDatabase.DataMountDir = 数据挂接路径
CreateDatabase.LogMountDir = 日志挂接路径
