CreateShortcut.InstallNote = \n安装程序将在如下目录创建快捷方式。\n请在文本输入框中输入目录名称。
CreateShortcut.InstallAgainNote = \n安装程序将在如下目录创建快捷方式。
CreateShortcut.DestinationFolder = 快捷方式文件夹
CreateShortcut.Title = 选择快捷方式文件夹
CreateShortcut.FolderNull = 文件夹名称不能为空。
CreateShortcut.LengthMoreThanMax = 文件夹名称不能超过60个字符。
CreateShortcut.InvalidCharacters = 文件夹名称必须是英文字母，中文字符，空格和数字以及\'_\'和\'-\'的组合。