StorageWelcomePage.Title=欢迎使用网络管理系统
StorageWelcomePage.Welcome=欢迎使用网络管理系统
StorageWelcomePage.WelcomeExt=网络管理系统
StorageWelcomePage.Request=请选择一种操作：
StorageWelcomePage.Backup=备份数据
StorageWelcomePage.Restore=恢复数据
StorageWelcomePage.CfgPolicy=配置备份策略
StorageWelcomePage.ReturnPrePage=上一步
StorageWelcomePage.Exit=结束
StorageWelcomePage.DeploymentTool=部署工具
StorageWelcomePage.DBMgrTool=数据库管理系统

ProgressPage.StorageTitle=正在备份，请稍候...
ProgressPage.CREATINGTASK=正在创建安装模块、执行升级脚本等任务流，请稍候...
ProgressPage.FinishTask=完成
ProgressPage.PreUpgradeTitle=正在创建备份、卸载老网管任务流，请稍候...
ProgressPage.UpgradeTitle=正在创建安装模块、执行升级脚本等任务流，请稍候...
ProgressPage.RollbackTitle=正在创建卸载当前网管任务流，请稍候...
ProgressPage.creatingTask=正在创建任务，请稍候...
ProgressPage.RollbackTitle_post=正在创建恢复老网管任务流，请稍候...
ProgressPage.BusyDialog=正在进行自动回滚...
