UPgrade.ConfigParas.CurrentVersion=数据设备路径
UPgrade.ConfigParas.SourceListLabel= 日志设备路径
UPgrade.ConfigParas.SourceList.OK=确认
UPgrade.ConfigParas.SourceList.Cancel=取消
UPgrade.ConfigParas.SourceListTitle=选择数据设备路径
UPgrade.sourceVersionDes=请设置新建数据库的数据设备路径和日志设备路径。
UPgrade.sourceVersionDes1=请选择数据设备和日志路径新建数据库
DatabaseFileBrowser.EmptyPath=数据设备路径和日志设备路径不可以为空。
DatabaseFileBrowser.EmptyDataPath=数据设备路径为空。
DatabaseFileBrowser.EmptyLogPath=日志设备路径为空。
DatabaseFileBrowser.SapaceNotEnoughPath=分区"{partitionname}"的剩余空间不足，需要空间：{requiSpace}MB，剩余空间：{freeSpace}MB。
DatabaseFileBrowser.PathInvalid=无效的路径：{path}。
