DBServerConfig.Hint = 提示
DBServerConfig.MDPIP = MDP IP：
DBServerConfig.DatabaseServerIP = 数据库服务器IP：
DBServerConfig.DBServerIPIsNotUseful = IP地址无效
DBServerConfig.DatabaseServerName = 数据库服务名称：
DBServerConfig.IpAddressCanNotbeEmpty = IP地址为空或填写错误。
DBServerConfig.DBServerNameCanNotbeEmpty = 数据库服务名称不能为空。
DBServerConfig.SUserNameCanNotbeEmpty = 管理员用户名称不能为空。
DBServerConfig.DatabaseType = 数据库类型：
DBServerConfig.DatabasePort = 数据库端口：
DBServerConfig.DatabaseSUserName = 数据库管理员用户名称：
DBServerConfig.DatabaseSUserPasswd = 数据库管理员用户密码：
DBServerConfig.NMDBUserName = 数据库网管用户名称：
DBServerConfig.NMDBUserPassword = 数据库网管用户密码：
DBServerConfig.NMDBUserPasswordConfirm = 数据库网管用户密码确认：
DBServerConfig.DBConnectError = 数据库连接错误。
DBServerConfig.SetDBPort_Error = 数据库端口错误。
DBServerConfig.CanNotConnectDB = 使用您输入的参数不能连到数据库，请确保数据库在线，并检查参数的正确性。
DBServerConfig.Title = 数据库服务配置
DBServerConfig.DatabaseIsUsing = 数据库正在被网管使用，请先关闭网管。
DBServerConfig.DBPort_null = 数据库端口不能为空。
DBServerConfig.InvalidCharcterinPort = 数据库端口必须是小于等于65535的正数。
DBServerConfig.DBServerIPNotRemote = 数据库服务不支持将服务器从远端的机器上卸载。
DBServerConfig.DBIsAlive = 数据库正在使用，是否继续？\n选择<是>，安装程序将自动终止相关进程。\n选择<否>，请手工终止相关进程。\n如果是远端进程，请手工关闭。
DBServerConfig.DBProcesskillFail = 有相关进程关闭失败，请用户手工关闭。
DBServerConfig.IsNotInstalledDB = 选择要卸载的数据库类型错误。
DBServerConfig.ConfigurationDestroyed = 数据库服务器配置文件被破坏，将使用缺省值。
ServerConfig.CheckingParameter = 正在检查参数合法性，请稍候...
DBServerConfig.PortIsInvalid = 连接数据库失败，可能是如下原因导致：\n数据库端口错误；\n数据库不在线。
DBServerConfig.SUserAndPwdIsInvalid = 管理员用户名或管理员密码密码不正确。
DBServerConfig.ServerNameIsInvalid = 数据库服务名称不正确。
DBServerConfig.ISQLCommandIsInvalid = 没有找到数据库isql命令。
DBServerConfig.NMDBUserPasswordIsInvalid = 网管用户密码错误。
DBServerConfig.DBIsOnline = 数据库正在使用，请手工终止相关进程，或者手工重启数据库服务。
DBServerConfig.DBServerOrUserHasSpace =  服务器名与管理员用户名不能以空格开头。
