DeploymentSchemeSubsystem.ModifyButton = 配置实例
DeploymentSchemeSubsystem.Title = 配置部署参数
DeploymentSchemeSubsystem.CheckBox= 显示所有部署包
DeploymentSchemeSubsystem.Subsystem = 组件
DeploymentSchemeSubsystem.SubsystemType= 部署包
DeploymentSchemeSubsystem.InstanceCount= 实例个数
DeploymentSchemeSubsystem.SubsystemDescription=部署包描述
DeploymentSchemeSubsystem.emptyNode= 除从保护节点外每个节点必须选择需要安装的组件。
DeploymentSchemeSubsystem.Cancel =取消
DeploymentSchemeSubsystem.Ok=确认
DeploymentSchemeSubsystem.Done=完成配置
DeploymentSchemeSubsystem.DependencyError = 所依赖的组件没有被选择。
DeploymentSchemeSubsystem.NodeName= 服务器名称：
DeploymentSchemeSubsystem.DetailMessage= 请给下面的节点选择组件：
DeploymentSchemeSubsystem.SlaveValidation = 不可以修改从保护服务器。
DeploymentSchemeSubsystem.IncorrectName = 节点数量不正确。
DeploymentSchemeSubsystem.InputFromBelow = 请输入正确的节点数量。
DeploymentSchemeSubsystem.SinglePerNode=单服务器单实例
DeploymentSchemeSubsystem.SinglePerSystem=系统单实例
DeploymentSchemeSubsystem.NoInstance=单服务器无实例
DeploymentSchemeSubsystem.MultipleInstances=单服务器多实例
DeploymentSchemeSubsystem.AddSubsystem = 添加组件
DeploymentSchemeSubsystem.AllNodesConfig = 配置所有节点上的组件：
DeploymentSchemeSubsystem.Node = 节点名称：
DeploymentSchemeSubsystem.DetailDependencyError = {1}依赖于组件{0}，如果选择组件{1}，必须选择组件{0}。
DeploymentSchemeSubsystem.SelectAll= 选择所有
DeploymentSchemeSubsystem.Select =选择
DeploymentSchemeSubsystem.UnSelect =去选择
DeploymentSchemeSubsystem.ChangeInstanceCount =修改实例个数
DeploymentSchemeSubsystem.Display =显示
DeploymentSchemeSubsystem.Reset =重新设置
DeploymentSchemeSubsystem.Operations=请选择您所需要的操作
DeploymentSchemeSubsystem.InputInstanceCount=请输入实例个数[{0}]
DeploymentSchemeSubsystem.IncompatiblePackageFound= {0}与{1}不兼容。
DeploymentSchemeSubsystem.IncompatiblityError=存在不兼容的选项。
DeploymentSchemeSubsystem.AllMustSelect=必须选择所有的组件。
DeploymentSchemeSubsystem.InvalidInput=无效的输入，请重新输入。
DeploymentSchemeSubsystem.Selection=选项
DeploymentSchemeSubsystem.SubsystemId=序号
DeploymentSchemeSubsystem.SubsystemList=请选择组件列表，使用逗号分隔
DeploymentSchemeSubsystem.PakageFilesError=以下组件没有配置安装包文件。\n请修改后再运行安装。
DeploymentSchemeSubsystem.PackageDependencyError = 以下组件存在安装包依赖错误

DeploymentSchemeSubsystem.SubsystemInfo=组件信息
DeploymentSchemeSubsystem.Summary_NodeName= 服务器名称：
DeploymentSchemeSubsystem.Summary_Subsystem = 组件：
DeploymentSchemeSubsystem.Summary_SubsystemType= 组件类型：
DeploymentSchemeSubsystem.Summary_InstanceCount= 实例个数：
DeploymentSchemeSubsystem.Summary_SubsystemDescription=描述：
DeploymentSchemeSubsystem.NodeNumberInput = 请输入节点序号：
DeploymentSchemeSubsystem.SelectServer = 请选择需要配置的服务器
DeploymentSchemeSubsystem.Prompt = 提示
DeploymentSchemeSubsystem.CheckNodesInformation =正在校验组件信息，请稍候...
DeploymentSchemeSubsystem.cannotModifyInstanceCoun=组件{0}的实例数目不可以修改。 
DeploymentSchemeSubsystem.PackageErrorFilePath= 在目录 {0} 下找不到组件配置的安装包文件。\n组件与安装包对应关系如下：
DeploymentSchemeSubsystem.PackageDependenceFilePath= 在目录 {0} 下的安装包存在依赖错误。\n组件与安装包对应关系如下：
DeploymentSchemeSubsystem.isDependedError=因为被其他部署包依赖，以下部署包至少需要安装一个实例：{0}

DeploymentSchemeSubsystem.options=选项
DeploymentSchemeSubsystem.ShowMessage=\n说明：“M”表示必装组件，“Y”表示待安装或已安装，“N”表示不安装\n


