DirectoryChooser.TitleText=选择文件夹
DirectoryChooser.FileTitleText=选择文件
DirectoryChooser.DesktopTip=桌面
DirectoryChooser.DirName=目录名：
DirectoryChooser.ApproveText=选择
DirectoryChooser.ApproveTip=打开选择的文件夹
DirectoryChooser.CancelTip=中止文件夹选择器对话框
DirectoryChooser.Cancel=取消
DirectoryChooser.Text=选择：
DirectoryChooser.LookIn=查看：