
ExitPage.Title=安装完毕
ExitPage.ErrorTitle=安装失败
ExitPage.Finish=完成
ExitPage.Note={0}成功安装到{1}。单击 <完成> 完成安装。\n
ExitPage.AffirmRestart=现在就重启操作系统吗？
ExitPage.Hint=提示
ExitPage.RestartTip =在您完成此向导后需要重新启动操作系统。
ExitPage.NoteCMD={0} 成功安装到 {1}。
ExitPage.CONFIRM=确认
UpgradeExitPage.Title=升级完成
RollbackExitPage.Title=回滚完成
ExitPage.Note.Rollback={0}回滚成功，网管的安装目录是{1}。单击 <完成> 退出。
PatchExitPage.Title =补丁安装完成
PatchUnistallExitPage.Title =补丁卸载结束
PatchExitPage.FailedNote =补丁安装失败。\n单击 <完成> 退出。
PatchExitPage.SuccessNote =补丁安装成功。\n单击 <完成> 退出。
PatchExitPage.NoteCMD =补丁安装已经完成。\n 
PatchUninstallExitPageCMD.Note =补丁卸载结束。
PatchRollBackExitPage.FailedNote =补丁卸载失败。\n单击 <完成> 退出。
PatchRollBackExitPage.SuccessNote =补丁卸载成功。\n单击 <完成> 退出。
ExitPage.NotePatch ={0}已经成功安装到 {1}。单击 <完成> 退出。
ExitPage.Note.upgrade={0}升级成功，网管的安装目录是{1}。单击 <完成> 退出。
ExitPage.Note.upgradecmd={0}升级成功，网管的安装目录是{1}。\n
ExitPage.ErrorScript=安装过程中，如下组件存在脚本执行异常，具体信息请查看日志：
ExitPage.ErrorNote =安装失败。单击<退出>结束安装。\n
ExitPage.Note.Rollbackcmd={0}回滚成功，网管的安装目录是{1}。
ExitPage.Restart=系统需要重新启动，请手工重启操作系统。
ExitPage.Note.FailedUpgrade=升级{0}失败，系统已经回滚到升级前版本。
ExitPage.Note.AUTOROLLBACK_FAILED=自动回滚失败。
ExitPage.Note.UpgradePartial=升级过程中某些操作执行失败，{0}升级失败。
PatchExitPageCMD.SuccessNote=补丁安装成功。
PatchExitPageCMD.FailedNote=补丁安装失败。
PatchFailExitPage.Title=补丁安装失败。
PatchfailExitPage.Note=补丁{0}安装失败。
RollbackFailedExitPage.Title=回滚失败
ExitPage.Note.Rollbackfailed=回滚{0}到{1}失败。
UpgradeFailedExitPage.Title=升级失败
PatchUnistallFailedExitPage.Title =补丁卸载失败
PatchRollBackFailedExitPage.Note =补丁卸载失败，\n单击 <完成> 退出。
ExitPage.Note.upgradeScriptFailed=某些脚本执行失败，请检查{0}
PatchUninstallExitPageCMD.NoteSuccess=补丁卸载成功。
PatchUninstallExitPageCMD.NoteFailed=补丁卸载失败。
PatchUninstallFailedExitPageCMD.Note=补丁卸载失败。
UpgradeExitPage.FailedOperations=检查所有操作失败的详细信息。