ExecuteScriptAction.SCRIPTNOTFOUND=脚本未找到，是否继续？
ExecuteScriptAction.HIGH=执行脚本失败，系统将回滚。
ExecuteScriptAction.FAILMEDIUM=执行脚本失败，是否继续？
ExecuteScriptAction.env.HIGH=执行脚本失败，系统将退出。
ExecuteScriptAction.Rollback.HIGH=执行脚本失败，回滚失败。
ExecuteScriptAction.MessageNote=开始执行
ExecuteScriptAction.RunningScriptsMessageHeader=运行时间已超过{minutesOfRun}分钟的执行脚本详细信息
ExecuteScriptAction.EmptyList=<空的>