
ExportDeploySchema.lExportDeploySchemaFile=导出预定义部署文件：
ExportDeploySchema.bBrowse=浏览(B)...
ExportDeploySchema.TitleExportDeploySchema=导出预定义部署文件
ExportDeploySchema.AlertSaveFileFailed=保存预定义部署文件失败。
ExportDeploySchema.next=下一步
ExportDeploySchema.InvalidPath=请输入一个正确的文件名。
file.exist = 已经存在\n要替换它吗？
label.text=导出文件路径：
