UPgrade.ConfigParas.CurrentVersion= 当前版本
UPgrade.ConfigParas.SourceListLabel= 选择源版本
UPgrade.ConfigParas.SourceList.OK=确定
UPgrade.ConfigParas.SourceList.Cancel=取消
UPgrade.ConfigParas.SourceList.Browes=浏览(B)...
UPgrade.sourceVersionDes= 用于回滚的备份路径不正确，请选择正确的备份路径。
UPgrade.ConfigParas.SourceListTitle=选择备份路径
UPgrade.ConfigParas.BackupPath=备份路径为空，请选择备份路径。
UPgrade.ConfigParas.Notexist=选择的路径不存在：{0}