com.oss.engineering.core.install.page.InputLicense=请选择有效的iManger U2000 License用于升级。
com.oss.engineering.core.install.page.Summary=此页面显示iManager U2000网管升级的汇总信息。
com.oss.engineering.core.rollback.page.RollBackIntroduction=请单击<下一步>开始回滚。
com.oss.engineering.core.u2000.gui.ProgressPage=此页面显示回滚iManager U2000网管的进度信息。
com.oss.engineering.business.u2000.gui.U2000ExitPage=iManager U2000 回滚完成。
com.oss.engineering.core.upgrade.page.SelectUpgradePacket = 选择包含升级包的目录。
com.oss.engineering.core.upgrade.page.UpgradeIntroduction=请单击<回滚>开始回滚或单击<继续>继续升级。
com.oss.engineering.core.upgrade.page.UpgradeSelectBackupPath = 选择每个服务器的备份路径和新版本安装路径。
