
com.oss.engineering.core.install.page.Introduction=这是安装的帮助页面，将指导您一步一步的完成网络管理系统的安装。
com.oss.engineering.core.install.page.CopyRight=此页列出网络管理系统的版权信息，请认真阅读。
com.oss.engineering.core.install.page.SelectLanguage=请选择安装后，网络管理系统版本的语言。
com.oss.engineering.business.install.page.CopyFiles=安装网络管理系统客户端过程信息。
com.oss.engineering.core.install.page.ExitPage=已完成网络管理系统的安装。
com.oss.engineering.business.install.gui.LicensePage=请选择网络管理系统的安装方式，分为3种：1、license文件安装：根据license文件自动生成安装策略进行网管安装；2、预定义部署文件安装：根据事先定义好的安装配置策略进行网管安装；3、手工安装：适合于有经验人员使用，能完全自定义安装策略。
com.oss.engineering.core.install.gui.NodeInfoTable=请配置网管服务器信息。\n如果该服务器有多个IP，则不显示默认IP，需要手工输入正确的IP。\n安装单机系统，只需要修改服务器参数，不需要进行增加服务器和删除服务器的操作。\n安装分布式系统，可以进行修改服务器参数，增加服务器和删除服务器的操作。
com.oss.engineering.business.install.gui.DeploymentSchemeSubsystem=请选择在网管务器上需要安装的组件，以及实例。
com.oss.engineering.business.install.gui.ConfigDBServer=请配置数据库服务器信息，用于安装数据库服务器。如果检查服务器已经安装了数据库，会根据用户输入的密码信息，对数据库用户进行连接检查，并提示用户是否复用已安装的数据库或者重新安装。\n复用已安装数据库或者重新安装数据库会破坏已有的数据库数据，请先备份数据库数据。
com.oss.engineering.core.install.page.Summary=显示网管安装的汇总信息。
com.oss.engineering.core.install.gui.TestDeploy=各组件配置信息。
com.oss.engineering.core.install.gui.ProgressPage=显示网管安装进度信息，主要有以下六个步骤：1、初始化数据模型；2、执行前置脚本；3、安装网管客户端；4、安装网管数据库软件；5、安装网管组件和部署实例；6、执行后置脚本。
com.oss.engineering.core.install.gui.ExportDeploySchema=提供预定义部署文件。
com.oss.engineering.core.install.gui.InstallExitPage=安装结束。
com.oss.engineering.core.install.page.UninstallSummary=此页显示网管卸载的概要信息。
com.oss.engineering.business.install.alarm.AlarmDisplaySetting=请配置告警灯的显示方式。
com.oss.engineering.core.install.page.UninstallExit=卸载完成。
com.oss.engineering.core.install.page.UninstallProgress=此页显示网管卸载过程信息。
com.oss.engineering.business.install.gui.SelectInstallType=请选择网管的安装类型。
com.oss.engineering.core.install.page.SelectInstallFolder=请选择网管的安装目录。
com.oss.engineering.business.install.page.SelectSlotMode=请选择合适的时隙模式。网络管理系统传送网络管理支持两种VC12在VC4时隙编号模式：一种是顺序模式（符合ITU-T G.707建议），另外一种是间插模式。顺序模式是ITU-T 在G.707 中建议的编号策略，顺序模式VC12 编号的计算公式为：VC-12 编号＝ "TUG-3" + ("TUG-2" - 1) × 3 + ( "TU-12" - 1) × 21，间插模式是优化VC3 路径的编号策略，间插模式VC12 编号的计算公式为：VC-12 编号＝("TUG-3" - 1) × 21 + ( "TUG-2" - 1) × 3 + "TU-12"。
com.oss.engineering.business.install.page.SelectStyle=请选择网络管理系统的安装版本风格。两种风格区别在于告警级别"提示"的表示：默认风格设置为"Warning"；北美风格设置为"Not Alarm"。
com.oss.engineering.business.databasemgr.client.pages.DatabaseMgrWizardPage=这是数据库管理工具的帮助页面， 将指导您一步一步的完成网络管理系统数据库管理。
com.oss.engineering.business.databasemgr.client.pages.DatabaseMgrProgressPage=数据库管理操作进度信息。
com.oss.engineering.business.databasemgr.client.pages.DatabaseMgrParaConfigPage=请配置数据库服务器参数。
com.oss.engineering.business.databasemgr.client.pages.DatabaseMgrExitPage=数据库管理操作完成。
com.oss.engineering.core.patch.page.PatchIntroduction =这是补丁安装的帮助页面，可以完成数据库和程序的补丁。
com.oss.engineering.core.patch.page.SelectPatchPackage =请选择补丁包文件。
com.oss.engineering.core.patch.page.SelectPatchSubSystem =请选择需要打补丁的服务器上的组件。
com.oss.engineering.core.patch.page.CheckPatchEnviornment =检查环境。
com.oss.engineering.core.patch.page.PatchSelectBackupPath =请选择备份文件和(或)程序的路径。
com.oss.engineering.core.patch.page.PatchInstallSummary =此页显示每个服务器网管补丁安装的汇总信息。
com.oss.engineering.core.install.page.UninstallNMSClientSummary=这些包显示客户端卸载的概要信息。
com.oss.engineering.core.install.page.UninstallNMSClientProgress=此页显示网络管理系统卸载过程信息。
com.oss.engineering.core.install.page.UninstallClientProgress=此页显示网络管理系统卸载过程信息。
com.oss.engineering.business.install.gui.InstallExitPage=已完成网络管理系统的安装。
com.oss.engineering.business.uninstallPage.UninstallSummary=此页显示网络管理系统卸载的概要信息。
com.oss.engineering.business.uninstallPage.UninstallProgress=此页显示网络管理系统卸载过程信息。
com.oss.engineering.business.uninstallPage.UninstallNMSClientSummary=这些包显示客户端卸载的概要信息。
com.oss.engineering.business.uninstallPage.UninstallNMSClientProgress=此页显示网络管理系统卸载过程信息。
com.oss.engineering.business.uninstallPage.UninstallClientProgress=此页显示网络管理系统卸载过程信息。
com.oss.engineering.business.uninstallPage.UninstallExit=卸载完成。


com.oss.engineering.core.upgrade.page.SelectUpgradePacket=选择升级包目录中包含的升级项目信息。
com.oss.engineering.core.install.gui.NMSExitPage=安装结束
com.oss.engineering.core.install.page.InputLicense=请选择有效的网管系统license文件后升级。
com.oss.engineering.core.rollback.page.RollBackIntroduction=请选择回滚到以前版本的备份路径。
com.oss.engineering.business.uninstallPage.InstallExitPage=安装结束。


