
usingDB=使用数据库
state=状态
removeButton=删除(R)
modifyButton=修改(M)...
installFolder=安装路径
hosttype=主机类型
hostid=主机标识
hostInfoPageTitle=管理节点信息
ftpUserPwd=FTP用户密码
ftpUserName=FTP用户名
ftpType=FTP类型
fixHostName=固定主机地址
des=描述信息
addButton=增加(A)...
SingleMode=非分布式安装
InstallDirectoryValidationFailed=确认安装目录失败。
HostInfo_DiretoryConfine=路径不能超过60个字符，请重新输入。
FtpValidationFailed=FTP验证失败。
FrameWorkDirectoryValidationFailed=验证安装框架目录失败。
FTPLoginFailed=FTP登录失败。
DistributeMode=分布式安装

yes=是
watchmanSystem=异地双机节点
usingDBLabel=使用数据库：
standbyHost=备机
standbyHASystem=双机备节点
sshUserPwdLabel=SSH用户密码：
sshUserNameLabel=SSH用户名：
slaveHost=从机
single=单机
rootPasswdlabel=管理员密码：
okButton=确定
nodeIDLabel=节点标识：
no=否
modifyHostInfoDlg=修改节点信息
masterHost=主机
installDirLabel=安装路径：
hosttypeLabel=主机类型：
hostFloatIPLabel=浮动主机地址：
hostFixIPLabel=固定主机地址：
desLabel=描述信息：
cancelButton=取消
addHostInfoDlg=增加节点信息
activeHASystem=双机主节点
FTP_portNotListening=FTP/SFTP服务器没有运行
FTP_ErrorCannotConnection=连接FTP/SFTP服务器失败

dbtype=数据库类型
dbserverport=数据库端口
dbservername=数据库服务名称
dbid=标识
dbaddress=数据库服务器IP
dbServerInfoPageTitle=管理数据库服务信息


racAddress4Label=Oracle RAC 地址4：
racAddress3Label=Oracle RAC 地址3：
racAddress2Label=Oracle RAC 地址2：
racAddress1Label=Oracle RAC 地址1：
modifyDBInfoDlgTitle=修改数据库服务信息
dbUserPwdLabel=数据库管理员用户密码：
dbUserNameLabel=数据库管理员用户名称：
dbTypeLabel=数据库类型：
dbServerPortLabel=数据库端口：
dbServerNameLabel=数据库服务名称：
dbServerAddressLabel=数据库服务器IP：
dbIDLabel=标识：
createDBInfoDlgTitle=增加数据库服务信息
OSType=操作系统类型：

remoteFrameworkError=无法连接以下节点的安装进程。
ossIsIntalled=不存在需要安装的节点。 \n {0}个节点之前已经安装成功：\n {1}
invalidRemotePath=框架远端路径不合法。
frameworkFileNotExist=框架文件没有找到。
SSHUser_invalid=SSH用户名或密码错误。
SSHUserName_null=SSH用户名为空。
SSHUserPWD_null=SSH密码为空。
NoSSH_Service=该主机没有运行SSH服务。
Host_Ip_Invalid=IP地址非法。
HostInfo_repeated=列表中有重复的主机，请删除。
HostInfo_hostfixipnouser=无法与指定的节点建立连接。
HostInfo_exist=节点信息已经存在。
HostInfo_WrongAdminPwd=管理员密码错误。
HostInfo_StandBySlave_No_Master=如果添加了从机备机，则必须添加主机备机。
HostInfo_StandByShared_Master_Slave=只能部署一个备机。
HostInfo_SFTPUserPasswdWrong=SFTP用户名或者密码错误。
HostInfo_PortNotListen=无法连接FTP端口。
HostInfo_No_Master=必须添加一台主机。
HostInfo_No_DB=如下主机使用数据库不存在，请重新选择。
HostInfo_Multi_StandBy_Master=列表中包含多台主机备机。
HostInfo_Multi_Master=列表中包含多台主机。
HostInfo_FTPUserPasswdWrong=FTP用户名或者密码错误。
HostIP_NamingIP_Same=在安装从机/备机时，命名服务地址不能和本机地址相同。
HostFloatIP_null=浮动主机地址为空。
HostFixName_null=固定主机名为空。
HostFixIP_null=固定主机地址为空。
HoatInfo_ChineseChars=主机标识包含中文字符。
FTPUserName_null=FTP用户名为空。
ErrorNullInstallPath=安装目录为空。
DirectoryMustBeCharAndNum=目录名必须是绝对路径，且是英文字母，中文字符和数字以及\'_\'和\'-\'的组合，且长度不能超过60个字符，\n'\\'或'/'或':'前不能有空格。
AdminPwd_null=管理员密码不合法。

NoSpace=下列节点没有足够的空间。\n请先清理磁盘。
InstallDirNotEmpty=安装路径不为空。请选择其它路径。
IncrementInstallDirNotEmpty=安装路径不为空。
ErrorInstallPath=安装路径不合法，请重新输入。
CheckSpaceFailed=检查安装空间失败。


STANDBY_SLAVE=从机备机
STANDBY_MASTER=主机备机
STANDBY_COMMON=通用备机
SQLPLUS_NOT_RUNNING=SQLPLUS命令不在path路径中。
SERVER_IP_INVALID=数据库IP地址非法。
ORACLE_RAC_IP_WRONG=Oracle RAC地址格式不正确。
ORACLE_RAC_IP_CONFLICT=Oracle RAC地址不能重复。
ORACLE_RAC_HOST_NOT_ENOUTH=Oracle RAC模式最少需要2个RAC地址。
ORACLE_IP_PORT_WRONG=无法连接数据库服务器。\n数据库主机地址、端口号或服务名错误。
DB_SUSERNAME_PASSWORD_WRONG=数据库管理员用户名或密码错误。
DB_SERVERNAME_INVALID=连接数据库失败，可能是由于如下原因导致的：\n数据库服务器不在线；\n数据库服务名错误；\nIP或端口错误；\n密码错误。
DBUserPwd_null=数据库密码为空。
DBUserName_null=数据库实例名称不能为空。
DBServerPort_null=数据库服务端口为空。
DBServerName_null=数据库服务名称为空。
DBInfo_repeated=列表中有重复的数据库服务，请删除。
DBInfo_exist=数据库服务信息已经存在。
DBConnected_fail=数据库服务连接失败。
DB2_PORT_NUMBER_WRONG=连接数据库失败，可能是如下原因导致：\n数据库端口错误；\n数据库不在线。

InstallPath_Null=安装路径为空。
DirNotExistCreateIt=路径 {0} 不存在。是否创建？

uploadWaitMessage=正在上传文件到远端机器，请稍候...
uploadHint=正在上传
selectOperation=操作类型：
selectHost=选择ID：
invalidConfigExport=主机的SSH信息检查失败。\n请检查 ConfigExport.xml后重试。
hostname_not_same=固定IP地址和浮动IP地址不在同一台机器上
are_reuse_Engr_daem=检测到以下节点的进程正在运行，是否需要更新？
addMoreDBInfos=是否需要进行操作？
ScriptNotFound=检查脚本不存在
RsyncNotInstall=rsync工具未安装
RemoteRsyncNotRunning=新增节点中的rsync服务未运行
RemoteRsyncCfgNotFound=新增节点中的rsync配置文件不存在或错误。
NotLocalIP=IP地址必须是本地IP。
NodeConnection_Failed=RPC连接失败。
NewNodeIPNotFound=IP {0}不存在或错误。
InvalidHostID=无效的 StandAloneHOSTID。
InvalidConfigHostID={0}中配置了非法的主机ID。
InvalidConfig=不可用的 {0}。
InstallDir=安装目录
Host_IP_notLocaleIP=非主机节点IP地址不能是本机IP地址。
Host_IP_LocaleIP=主机节点IP地址必须是本机IP地址。
HostTitle=节点信息
HostInfoPage.InstallDirNotWritable=创建安装目录失败或该目录不可写。
HostInfoPage.FrameWorkDirNotWritable=创建安装框架目录失败。\n 或者安装框架目录无写权限。
HostInfoPage.CheckingParameters=正在对输入参数进行检测，请稍候...
HostInfoPage.CheckingDlgTitle=参数检测中
HostIDnotmatched=DefaultValues.properties中配置的主机ID在{0}中不存在。
Float_Ip_Invalid=浮动IP地址无效。
FTPUser=FTP 用户名
ExpectNotInstall=expect工具未安装。
ExecScriptFailed=执行检查脚本失败。
EmptyHostDetails=节点信息不存在。
EmptyDBDetails=数据库信息不存在。
DBTitle=数据库服务器信息
CheckTrustWithNewNodeFail=检查主节点与{0}的互信失败。
CanNotConnectNewNode=不能连接到新增节点。

LOGIN_FAILED_ONLY_LOGIN_ONE_MASTER=节点{0}已经被其它主节点登录，请检查。
SyncConfigureFileFailed=同步文件失败。