InitDBExitPage.InitialExitPage.Title=数据库初始化操作成功。
InitDBExitPage.InitialExitPage.TitleFail=初始化数据库操作失败。
InitDBExitPage.CfgDatabaseParaPage.Title=您已成功完成数据库参数配置操作。
InitDBExitPage.Note=请单击<完成>结束初始化数据库向导。
InitDBExitPage.StartNMSNote=请手工启动网管服务，确保网管数据的完整性。
InitDBExitPage.ERRORNote=请单击<退出>结束初始化数据库向导。