InitDBWizardPage.DatabaseInitial=初始化数据库
InitDBWizardPage.ParaCfg=配置数据库参数
InitDBWizardPage.Title=网络管理系统数据库初始化向导
InitDBWizardPage.Introduction=网络管理系统数据库初始化
InitDBTool.Title=网络管理系统数据库初始化向导
InitDBWizardPage.WARNING_MESSAGE=初始化工具将要初始化网管数据，是否继续？
InitDBWizardPage.WARNING_TITLE=警告
InitDBWizardPage.Introduce=该工具将引导您初始化网络管理系统的所有数据库。\n\n进行初始化之前，请了解如下事项：\n1.数据库初始化将清空所有数据库数据，恢复到安装后的原始状态，请谨慎操作。\n2.数据库初始化操作后将无法回滚，建议您在初始化之前使用备份工具对数据进行备份。\n3.执行数据库初始化之前，请确保网络管理系统已经停止。
initdbcheck.ErrorTitle=错误
initdbcheck.DatabaseConnectionFailed=连接数据库失败，请检查数据库服务是否运行。
initdbcheck.DBInfoFileInvalid=sysconfigure.xml文件或者数据库描述文件异常。
initdbcheck.NodeSysmoniRunning=节点{0}网管正在运行，请先停止网管
initdbcheck.DiskSpaceNotEnoughError=服务器磁盘{0}空间不够，需要{1}MB，但是只有{2}MB
initdbcheck.ProcessRunningOnDatabase=无法初始化数据库，数据库正被如下进程使用：
initdbcheck.RefreshDBConnectionFailed=数据库连接失败，请检查数据库服务是否运行。
initdbcheck.LocalIPInvalid=检查sysconfigure.xml中的ip失败。 
initdbcheck.NMSALIVEMSG=网管正在以下主机上运行：
initdbcheck.NMSALIVE=网管正在运行，请手动停止网管，并重试。
InitDBWizardPage.FailedToGetDBLogonInfoFromDatamodel=从数据模型中获取数据库登录信息失败。
RestoreSelFilePage.initDBFailed=初始化数据库失败。
