InitPackage.Title = 正在初始化组件...
InitPackage.Hint = 提示
InitPackage.ScriptFailed = 执行 {0} \n失败，继续吗？
InitPackage.DatabaseFailed = 创建数据库 {0} 失败，继续吗？
InitPackage.Finished = 完成
InitPackage.PreInstallScript = 安装前置脚本
InitPackage.PreDBScript = 数据库前置脚本
InitPackage.CreateDatabase = 创建数据库
InitPackage.PostDBScript = 数据库后置脚本
InitPackage.PostInstallScript = 安装后置脚本
InitPackage.DBExist = 数据库已经存在，需要重新创建吗？
InitPackage.DropError = ：数据库在删除时出错，可能是先前数据库出现了非正常操作，\n如果继续安装该数据库，可能安装不会成功。是否继续？
InitPackage.DBInstallContinue = ：是否继续安装这个数据库？
InitPackage.Yes = 是
InitPackage.No = 否
InitPackage.YesAll = 全是
InitPackage.NoAll = 全否
InitPackage.SeriousError = 执行 {0} \n时发生了致命错误，安装向导将退出安装。
InitPackage.ScriptError = 脚本 {0} 执行中出错。
InitPackage.UnknowError = 执行 {0} 时发生了未知错误。
InitPackage.ScriptExecutionFailed = 脚本执行失败。继续吗？
InitPackage.ScriptNotFound = 脚本 {0} 没有找到。
InitPackage.ScriptIOException = 执行 {0} 脚本的时候发生IO异常。
InitPackage.Envhintinfo = 环境变量需要覆盖吗？
InitPackage.Reserve = 保留
InitPackage.CreateVolumes = 创建卷
InitPackage.SucceedToCreateVolume = 创建卷{0}成功。
InitPackage.Overlay = 覆盖
InitPackage.PathOverLang = 系统环境变量PATH过长，请手工调整长度。\n单击<重试>重新检测长度或单击<取消>退出安装。
InitPackage.Over = 初始化组件结束
InitPackage.Completed = 完成
InitPackage.PathIsNullOrEmpty = 系统PATH不存在或者非法。\n选择“是”设置PATH，否则安装将被取消。
InitPackage.DropDBError = 数据库删除错误。
InitPackage.ReJarError = 创建升级包错误。
InitPackage.InitPackageShowTime = 分钟
InitPackage.AddRegeditFail = 添加注册表 {0} 失败。
InitPackage.DBCreationFailed = 创建数据库失败。继续吗？
InitPackage.ScriptExecutionFailedDetail = 脚本 "{0}" 执行失败。
