InputLicensePanel.Select = 选择文件
InputLicensePanel.Browse = 浏览(B)...
InputLicensePanel.Title=选择License文件
InputLicensePanel.licenseNote = \n升级程序将读取以下License文件。\n要读取其他License文件，请单击<浏览>，选择其他文件。
InputLicensePanel.SelectLicenseFileLabel = License文件：
InputLicensePanel.tempLicenseTitle = License信息
InputLicensePanel.OK = 确定
InputLicensePanel.tempLicense =  这是一个临时License，将在 {0} 天后过期。\n如果过期，请向华为技术有限公司购买正式的License。
InputLicensePanel.licensefile_notexist = 您输入的License文件不存在，请重新输入。
InputLicensePanel.error = 错误
InputLicensePanel.InvalidLicense = 非法License。
InputLicensePanel.Hint = 提示
InputLicensePanel.LicenseFileExist = 在安装目录下，License文件已经存在，覆盖吗？\n如果覆盖，请先备份原有License文件。
InputLicensePanel.DirectoryError = 目录错误：
InputLicensePanel.DirectoryMustBeCharAndNum = 要求目录名必须是绝对路径，且是英文字母，中文字符和数字以及\'_\'和\'-\'的组合，且长度不能超过60个字符\n'\\'或'/'或':'前不能有空格。
InputLicensePanel.CanntBeWrite = 创建License目录失败或该License目录不可写。
InputLicensePanel.LicenseFileNull = License文件不能为空。
InputLicensePanel.LicenseExpired = 此临时License文件{0}天前已经过期，请向华为技术有限公司公司购买正式License。
InputLicensePanel.CopyFailed = 复制License文件失败。
LicensePage.License.Alert.SelectFile=请选择一个License文件。
LicensePage.License.Alert.Invalid=请选择一个有效的License文件。
LicensePage.License.Alert.Use=解析License失败。
LicensePage.ImportScheme.Alert.SelectFile=请选择一个部署文件。
LicensePage.ImportScheme.Alert.Invalid=请选择一个有效的部署文件。
LicensePage.LicenseFileNotValid=License文件不存在。
LicensePage.DiretoryNull = 安装路径不可以为空。
LicensePage.PathTooLengthy = 文件路径长度不可以超过60个字符。
LicensePage.InstallMethod=安装方式
LicensePage.InstallMethodManual=手工定义部署系统。
LicensePage.InstallMethodLicense=按License安装。
LicensePage.InstallMethodSchema=按部署文件安装。
LicensePage.License.Alert.InputFile=请选择License文件的路径。
LicensePage.ImportScheme.Alert.InputFile=请选择部署文件的路径。
InputLicensePanel.licenseNoteCMD=请输入License文件。
