
InstallCheck.title= 安装前检查

success = 成功
failed = 失败

InstallCheck.Retry=重试


check.total.number = 7


ck_0 = 检查omcsysm用户组
ck_1 = 检查dbuser用户
ck_2 = 检查omcuser用户
ck_3 = 检查ftpuser用户
ck_4 = 检查操作系统的版本号
ck_5 = 检查操作系统分区空间大小
ck_6 = 检查数据库字符集


ret|10001 = {0} 用户组创建失败
ret|10002 = {0} 用户组尚未创建
ret|10003 = {0} 分区没有足够的空间
ret|10004 = {0} 分区不存在
ret|10005 = 当前操作系统版本号为：{0}\n   与版本号5.10/Generic_118833-36或5.8/Generic_108528-29不匹配
ret|-10001 = {0} 用户组没有创建
ret|-10002 = {0} 用户组尚未创建
ret|-10003 = {0} 数据库系统文件错误或者丢失


preinstallcheckFilePath = ./logs/preinstallcheck.log
execScript = ./install/omcscript/preinstallcheck.sh
check_failed_confirm=安装前检查失败，选择 Y 将重新检查，选择 N 将退出安装
