ProgressPage.InstallProcessTitle = 显示安装进度
ProgressPage.UninstallTitle=正在卸载，请稍候...
ProgressPage.UpgradeTitle=正在升级，请稍候...
ProgressPage.PreUpgradeTitle=正在创建前置升级任务，请稍候...
ProgressPage.RollbackTitle=正在创建前置回滚任务，请稍候...
ProgressPage.PreRollbackTitle=正在准备回滚，请稍候...
ProgressPage.DATAMODEL_INIT=正在初始化数据，请稍候...
ProgressPage.InstallFailed=安装失败，请查看相关日志：\n{0}logs
ProgressPage.UninstallFailed=卸载失败，请查看相关日志：\n{0}
ProgressPage.UpgradeFailed=升级失败，请查看相关日志
ProgressPage.RollbackFailed=回滚失败，请查看相关日志
ProgressPage.installPatchTitle= 开始补丁安装，请稍候...
ProgressPage.uninstallPatchTitle=开始补丁卸载，请稍候...
ProgressPage.PatchTitle=正在安装补丁，请稍候...
ProgressPage.PrePatchRollbackTitle=正在卸载补丁，请稍候...
ProgressPage.creatingTask=正在创建任务，请稍候...
ProgressPage.UpgradeTitle_pre=正在执行前置升级，请稍候...
ProgressPage.RollbackTitle_pre=正在执行前置回滚，请稍候...
ProgressPage.BusyDialog= 正在进行自动回滚...
ProgressPage.AutoRollbackFinish= 自动回滚完成。
ProgressPage.Title=显示安装进度，主要有以下两大步骤：1、安装准备；2、安装软件。
ProgressPage.Title.Upgrade=升级进度信息
ProgressPage.Title.Rollback=回滚进度信息
ProgressPage.InstallTitle =正在安装，请稍候...

progressPage.exit.partSuccess=部分成功
progressPage.exit.allSuccess=全部成功
progressPage.exit.allFailed=全部失败

progressPage.exit.des={0}升级在{1}目录{2}
progressPage.exit.failed={0}个节点本次安装失败：
progressPage.exit.failedip={0} : 在{1}%失败 - {2}
progressPage.exit.success={0}个节点本次安装成功：
progressPage.exit.alreadySuccess={0}个节点之前已经安装成功:
progressPage.exit.ipinvalid=节点ip不合法。




