
ExitPage.Title=安装完毕
ExitPage.Finish=完成

ExitPage.more.one.fail.Note={0}安装部分成功。 \n{1} 个节点本次安装失败： \n{2}\n\n{3}个节点本次安装成功： {4}.\n{5}个节点本次安装失败：{6}.\n
Exitpage.more.retry.success.Note={0}安装部分成功。 \n{1} 个节点本次安装失败：\n{2}\n\n{3}个节点本次安装成功： {4}.\n{5}个节点本次安装失败：{6}.\n{7}个节点之前已经安装成功：{8}.\n
ExitPage.more.all.success.Note={0}安装成功。\n所有主机{1}已经成功安装在{2}。

ExitPage.more.all.fail.Note={0}安装失败。\n{1}。

ExitPage.one.fail.Note={0}安装失败。\n{1}。
.
ExitPage.one.success.Note={0}安装成功。\n{1}主机已经成功安装在{2}。

ExitPage.fail.percent=失败于


ExitPage.AffirmRestart=现在就重启操作系统吗？
ExitPage.CONFIRM=确认
ExitPage.Hint=提示
PatchExitPage.Note=补丁{0}已经安装完成。\n安装日志存储在：\n {1} \n单击 <完成>退出。
ExitPage.ErrorNote={0}安装失败，具体信息请查看日志 {1}。
ExitClientPage.Note={0}客户端已经已经安装到 {1} 目录。\n单击 <完成> 完成安装。
ExitPage.RestartTip =在您完成此向导后需要重新启动操作系统。
ExitPage.NoteCMD={0}已经安装到 {1} 目录。
ExitPage.ErrorScript=安装过程中，如下子系统存在脚本执行异常，具体信息请查看日志：
ExitPage.ErrorTitle=安装失败
ExitPage.somefail.percent=在{0}%失败 - 

