IsBackupPage.title = 是否备份网管应用程序和数据库
IsBackupPage.content = 请根据需要选择是否备份网管应用程序和数据库。 \n当选择“是”，程序会自动进行备份；\n若选择“否”，程序则直接进入打补丁阶段。\n建议您选择“是”，如果在打补丁过程中出现错误，那么程序将自动回滚到安装补丁前状态；\n如果您选择“否”，请您最好先手工备份网管应用程序和数据库，\n如果在打补丁过程中出现错误，程序将提示您手工恢复网管。
IsBackupPage.yes = 是
IsBackupPage.no = 否
IsBackupPage.cmd = 备份网管应用程序和数据库
IsBackupPage.titleforclient = 是否备份网管客户端
IsBackupPage.contentforclient = 请根据需要选择是否备份网管客户端。 \n当选择<是>，程序会自动进行备份； \n若选择<否>，程序则直接进入打补丁阶段。\n建议您选择“是”，如果在打补丁过程中出现错误，那么程序将自动回滚到安装补丁前状态；\n如果您选择“否”，请您最好先手工备份网管客户端，\n如果在打补丁过程中出现错误，程序将提示您手工恢复网管。