DIALOGTITLE=警告
PROCESSEXIST=<html>不能重复启动进程 "@process" <br>请关闭已经开启的服务进程："@process"</html>
PROCESSUSE=<html>服务进程 "@process" 已经启动，<br>请先停止后再操作。</html>
PORTSEXIST=<html> 通讯端口(@ports)被占用。 <br> 使用命令@portcmd查看端口占用情况，或者请在2-3分钟后重试</html>
PORTSEXIST_WIN=<html>通讯端口(@ports)被占用。<br>可以选择“是”查看端口占用情况,或者选择“否”重试，<br>端口检查时间由于系统差异可能消耗较长时间。</html>
PORTSEXIST_SILENT=通讯端口(@ports)被占用。
SEARCH_PORT=正在搜索占用12212，12213，13314，12215端口的进程：
PLEASE_WAIT=开始搜索，请等待...
WAIT_FEW_MIN=正在释放端口，请稍候再试。
TOTAL_MEMORY_NOTENOUGH=该服务器的内存小于2G，只能支持单域安装或客户端的安装。
CHINESELANG=<html>不支持当前操作系统的语言设置，如果继续有可能失败。<br>目前支持的语言包括：@langList</html>
CHINESECHARSET=<html>当前操作系统的语言配置文件中的LANG值不符合网管安装要求。<br> 请把"@CifFile"配置文件中的"@oldLang"修改为"@Lang"。<br>修改完成后并重启操作系统配置文件生效。</html>
CHECKNMSCLIENT=网管已经安装在"@installPath"，请在卸载后再次进行安装。
REPEXIST=复制关系存在，请先删除。
CLEARSCRIPT=上一次网管卸载已经在计算机上执行了创建挂起文件的操作，运行安装程序之前必须重新启动计算机。
PATHLENGTH=PATH环境变量的长度过长，请删除PATH环境变量一些无用的字段后再重新执行。
INSTALLDISKPATHINVALID=安装盘目录下不能存在中文，下划线，空格。
JRECHECK=当前操作系统下不能发现网管JRE，请确认JRE目录 @HWJREROOT 是否存在。
NMSCHECK=<html>用户@userName正在被使用，请退出使用<br>(请使用"ps -ef | grep @userName" 命令查看哪些进程正被@userName用户使用)。</html>
NMSFILECHECK=用户文件遭到损坏，无法添加删除ossuser用户。
LOOPIPCHECK=系统没有配置回环IP，请在"/etc/hosts"中配置回环IP，并重启操作系统生效。
UPGAREPATHLENGT=PATH环境变量的长度过长。请删除PATH环境变量一些无用的字段后再重新执行。
INSTALLDISKCHECK=@INSTALLROOT文件不存在，请确定版本正确之后重新安装。
SYSCONFIGIPCHECK=@INSTALLROOT文件不存在，请确定该文件正常生成后重新安装。
ZHLANG=中文
ENLANG=英文
CONTINUE=继续
CANCEL=取消
YES=是
NO=否
NETMANAGERPROCESS=网管后台服务正在运行，是否需要停止？
INVALIDATIONOPTION=您输入的选项无效，请重新输入。
STOPPROCESS=停止网管后台服务失败。
WATIMESSAGE=正在停止网管进程，请稍候...
DBUSEDCHECK=SQL Server企业管理器正在使用，请先关闭。
LESSMEMORY=内存小于1G，请先释放内存。
LESSTMP="/tmp"目录空间小于512M，请先释放空间。
PACKAGECLIENTCHECK=<html>客户端独立安装包(包名称含client)与基础包(包名称含base)<br>或核心包(包名称含core)不能同时存在，请重新解压。<html>
PACKAGECHECK=基础包(包名称含base)与核心包(包名称含core)必须同时存在，请重新解压。
DISKHANGUP=@DATADIR目录未挂接成功，请先执行OSSICMR(命令如下：cd /opt/OSSICMR/bin; ./install.sh -r)。
DBXML=@DATABASE目录下的数据库配置文件不正确，请检查。
REPETITIONHOSTIP=/etc/hosts文件中存在重复IP。请删除后，重启操作系统使之生效。
REPETITIONHOSTNAME=/etc/hosts文件中存在重复主机名。请删除后，重启操作系统使之生效。
TIMEZONENOLANG=/etc/TIMEZONE文件中缺少LANG环境变量(LANG=zh_CN.GB18030)。请添加后，重启操作系统使之生效。
NMSPROCESSEXIST=网管后台进程正在运行，请先停止。
HOSTNAMECHECK=<html>服务器主机名不符合规则，请修改主机名。<br>1. 主机名长度不超过24个字符；<br> 2．用字符可以是字母（ A~ Z ）数字（0 ~ 9）减号（-）； <br>3. 第一个宇符必须是字母；<br> 4. 最后一个字符不能是减号；<br>5. 不支持主机名中有"--"字符串。</html>
SHAREMENINFO=<html>没有配置系统共享内存，请先执行系统预配置。(命令如下：cd /opt/OSSICMR/bin; ./install.sh -r)<html>
SYSCONFCHECK=没有配置 @INSTALLROOT 文件，请配置。
DATABASEPACKAGECHECK=@INSTALLROOT目录为空或者不存在，请配置数据库的相关文件。
CHECKOSSPROCESS=@OSSPATH正在被一些进程使用，请先停止后再操作。
CHECKOSSRUNNING=网管进程正在运行，请先停止再操作。
OSSENVVAR=OSSENGRROOT或者OSSJRE环境变量不存在，请检查。
CERTDATECHECK=证书无效。
DIALOG_ERROR_TITLE=错误
CHECK_PORTANDSSL=启动失败，请检查端口是否被占用或者证书无效。
CHECK_DISK_SPACE=@TEMPDIR目录或当前目录没有足够的可用空间。@TEMPDIR目录需要2G，当前目录需要500M。
PACKAGEPATHCHECK=独立客户端安装包路径不能包含 !, $和空格。
SYSCONFHAIPCHECK=/engr/deploy/conf/sysconfigure_ha.xml文件中IP为本地IP，请检查。
CHECK_SYSCONFIGURE_XML_FAIL=启动失败，sysconfigure.xml文件不存在或者不可读，请修复。