
LicensePage.rbSelectLicense=按License安装（适用于已有license文件的用户）
LicensePage.lSelectLicense = 导入License文件：
LicensePage.bSelectLicense = 选择预定义部署文件...
LicensePage.rbImportScheme = 按典型组网安装（推荐）
LicensePage.schemaLabel = 部署文件：
LicensePage.okButton = 确定
LicensePage.cancelButton = 取消
LicensePage.schemaTip = 请选择有效的部署文件
LicensePage.lImportScheme = 选择场景：

LicensePage.Title= 请选择安装方式。
LicensePage.DefineManually=自定义安装（适用于有经验的用户）
LicensePage.GenerateSchema=预定义部署文件
LicensePage.License.Alert.SelectFile=请选择License文件
LicensePage.License.Alert.Invalid=请选择有效的License文件

LicensePage.ImportScheme.Alert.SelectFile=请选择场景
LicensePage.ImportScheme.Alert.Invalid=请选择一个有效的场景。

LicensePage.InstallMethod=安装方式
LicensePage.InstallMethodManual=手工定义配置系统
LicensePage.InstallMethodLicense=License安装
LicensePage.InstallMethodSchema=典型组网安装
LicensePage.License.Alert.InputFile=请输入一个License文件路径
LicensePage.ImportScheme.Alert.InputFile=请输入一个配置文件路径
LicensePage.AccessName = 接入域

LicensePage.InstallType =安装方式
LicensePage.SelectInstallation=请选择安装方式。
LicensePage.byLicense=按License安装 (适用于已有License文件用户)
LicensePage.FullInst=全量安装
LicensePage.select = 浏览(B)...
File.path.cannot.empty=文件路径不能为空。
