MENU_OP_MONITOR_REP=监控复制状态(M)...
LABEL_MONITOR_RLINK=Rlink的复制进度
SLIDEBAR_MONITOR_RLINK=Rlink的复制进度条
BUTTON_QUERY=查询
BUTTON_CANCEL=取消
MENU_OP=部署(D)
VXRLINK_ERROR=主备数据复制处于中断状态，可能原因如下: \na、复制网络中断（Replication status: paused due to network disconnection）\nb、双机处于复制双主状态（网络未恢复前，对主端显示是网络中端，备端查询无Replication status:项）\nc、双机数据复制缓冲卷溢出（Replication status: logging to DCM (needs dcm resynchronization)）
COPY_PROTOCAL=复制协议:
COPY_PROGRESS=复制速度(非当前网络带宽):
DISK_NAME=磁盘名称
DISK_GROUP=磁盘组
USAGE_RATE=使用率(%)
QUERYING_DATA=正在查询数据...
