
NMS.AllSteps=版权声明;选择网管语言;选择安装类型;选择组件;配置服务器;配置服务组;配置部署参数;配置安装参数;导出文件
NMS.AllPages=CopyRight;SelectLanguage;SelectInstallType,SelectInstallTypeU;SubsystemTree;NodeInfoTable;ConfigServiceHostPage;DeploymentSchemeSubsystem;SelectStyle,SelectSlotMode,ConfigDBServerWindows,ConfigDBServer;ExportDeploySchema