WelcomePage=信息预览
DateTimeZonePage=配置时间时区
ChangeNTPPage=配置NTP
ModifyHostnamePage=配置主机名
ControllerPage=配置控制卡
VirusSoftCheckPage=防病毒软件
ChangePValuePage=配置密码
AlarmConfigPage=配置硬件告警
NMSLicensePage=网管License
VCSLicensePage=配置Veritas License
ReplaceNMSLicensePage=配置SSL证书
AddInstancePage=添加实例
ConfigNetworkPage=配置网络
ConfigRoutePage=配置路由
SecuritySetPage=安全加固
SummaryPage=完成
DeployNbiInstancePage=北向接口