
ProgressPage.subSteps=初始化;安装
NMS.AllSteps.SelectScheme=选择安装方式
CopyRight=版权声明
SelectLanguage=选择网管系统语言
SelectInstallTypeU=选择服务器类型
SelectInstallType=选择服务器类型
LicensePage=选择安装方式
SelectLicense=选择License文件
ComponentTree=选择组件
NodeInfoTable=配置服务器
HostInfoPage=配置服务器
ConfigServiceHostPage=配置参数
ConfigDeploymentsSubsystem=配置参数
ConfigDBServerWindows=配置数据库
ConfigDBServer=配置数据库
DBServerInfoPage=配置数据库
ExportDeploySchema=导出文件
Summary=安装信息汇总
InstallProgressPage=正在安装
InstallExitPage=完成
InstallCheck=安装前检查
