SoftwareLibSelectPage=选择软件库目录
DBServerInfoPage=配置数据库
HostInfoPage=配置服务器
StartSubNodeServerPage=启动从服务器端
ComponentTree=选择安装组件
ConfigServiceHostPage=配置参数
ConfigDeploymentsSubsystem=配置实例
IncrementInstallSummaryPage=安装概述
IncrementInstallProgressPage=安装进度
IncrementInstallExitPage=完成
IncrementPreCheck=环境检查
