
ClientCopyRight=简介
SelectClientLanguage=设置网管语言
SelectClientInstallFolder=选择安装路径
SetClientShortcutFld=设置快捷方式
ClientSummary=安装确认
ClientExportDeploySchema=导出文件
ClientInstallProgress=正在安装
ClientInstallExitPage=完成