NodeInfoTable.description = 已检测到当前系统为单机配置，请配置服务器信息。
NodeInfoTable.description1 = 已检测到当前系统为分布式配置，请配置主从服务器信息。
NodeInfoTable.description2 = 已检测到当前系统为双机集中式配置，请配置双机服务器信息。
NodeInfoTable.description3 = 已检测到当前系统为双机分布式配置，请配置主从服务器信息。
NodeInfoTable.description2windows = 已检测到当前系统为双机集中式配置，请配置双机服务器信息。
NodeInfoTable.description3windows = 已检测到当前系统为双机分布式配置，请配置主从服务器信息。
NodeInfoTable.Select = 选择文件
NodeInfoTable.AddButton = 增加
NodeInfoTable.modifyButton= 修改
NodeInfoTable.deleteButton = 删除
NodeInfoTable.Done=完成
NodeInfoTable.confirmation = 确认
NodeInfoTable.Synchronize_Title = 框架同步
NodeInfoTable.Synchronize_Start = 开始框架同步...

NodeInfoTable.CheckInstallPath = 输入的路径不合法，请重新输入。
NodeInfoTable.CheckInstallPathChar = 安装路径不能有特殊字符，只支持字母、数字、下划线。

NodeInfoTable.Title= 部署服务器

NodeInfoTable.Node_Name = 名称
NodeInfoTable.Public_IP_Address = IP地址
NodeInfoTable.Private_IP_Address= 私网IP：
NodeInfoTable.Node_Type = 类型
NodeInfoTable.Root_Password= 网管系统维护工具密码
NodeInfoTable.Installation_Path = 安装路径
NodeInfoTable.InvalidPublicIp = IP地址非法
NodeInfoTable.privateIpIsEmpty= 私网IP为空
NodeInfoTable.publicIpIsEmpty= IP地址为空
NodeInfoTable.InvalidPrivateIp = 私网IP非法
NodeInfoTable.No_MASTER_NODE = 一个服务器必须是主服务器
NodeInfoTable.DUPLICATE_MASTER_NODE = 只能有一个主服务器
NodeInfoTable.DUPLICATE_SLAVE_NODE = 最多只能有一个从保护服务器
NodeInfoTable.SUB_NODE_MUST_FOR_SLAVE = 添加从保护服务器时必须存在从服务器。
NodeInfoTable.NO_BACKUP= 不备份应用程序和数据库

NodeInfoTable.nodeIDLabel = 服务器名称
NodeInfoTable.nodeTypeLabel = 服务器类型
NodeInfoTable.publicIPLabel = IP地址

NodeInfoTable.privateIPLabel= 私网IP
NodeInfoTable.AddTitle = 增加服务器
NodeInfoTable.rootPasswdlabel=网管系统维护工具密码
NodeInfoTable.installDirLabel= 安装路径
NodeInfoTable.okButton= 确认
NodeInfoTable.cancelButton=取消
NodeInfoTable.MASTER_NODE = 主服务器
NodeInfoTable.SUB_NODE = 从服务器
NodeInfoTable.SLAVE_NODE = 从保护服务器
NodeInfoTable.InvalidNodeName=非法的服务器名称
NodeInfoTable.INVALID_PUBLIC_IP = IP地址无效。
NodeInfoTable.INVALID_PRIVATE_IP = IP地址无效。
NodeInfoTable.PATH_FIELD_EMPTY = 路径不可以为空。
NodeInfoTable.NODE_FIELD_EMPTY = 服务器名称不可以为空。
NodeInfoTable.INVALID_PUBLIC_IP_PING = 无法连接IP地址。
NodeInfoTable.INVALID_PRIVATE_IP_PING = 无法连接私网IP。
NodeInfoTable.DUPLICATE_PUBLIC_IP =  IP地址不可以重复。
NodeInfoTable.DUPLICATE_PRIVATE_IP = 私网IP不可以重复。
NodeInfoTable.DUPLICATE_NODE_ID = 服务器名称不可以重复。
NodeInfoTable.promt=提示
NodeInfoTable.SELECTBACKUPPATH=备份路径为空，请选择备份路径。

NodeInfoTable.PUBLIC_PRIVATE_IP_NOTSAME = IP地址和私网IP不可以重复。
NodeInfoTable.INVALID_INSTAL_PATH = 服务器的安装路径无效：
NodeInfoTable.LOGIN_NODE_FAILED = 登录服务器失败，可能由以下原因引起。\n1.端口被占用。\n2.密码错误。\n3.部署后台没有启动。
NodeInfoTable.DiretoryConfine = 路径不能超过60个字符，请重新输入。
NodeInfoTable.Currentpatherror = 当前安装路径超过了60个字符，请更改安装路径软件将退出。
NodeInfoTable.PathIsNull = 安装路径不可以为空。
NodeInfoTable.invalidPath = 1.目录名必须是绝对路径，且是英文字母，数字以及'_'的组合。\n 2.目录名长度不能超过60个字符，且目录必须可写。\n 3.请检查驱动器的有效性。

NodeInfoTable.CONFIRMATION_MESSAGE= 确认删除所选服务器？
NodeInfoTable.CONFIRM = 确认
NodeInfoTable.error = 错误
NodeInfoTable.loopBackAddress = 不可以使用环路IP地址
NodeInfoTable.Synchronize_TotalMessage=正在同步框架，请稍候...
NodeInfoTable.SYNCHRONIZE_FRAMEWROK_FAILED=同步框架失败。
NodeInfoTable.Synchronize_IP=正在同步服务器：
NodeInfoTable.CHANGE_SYBASE_INTERFACES_FAILED=更改Sybase文件interfaces失败。

NodeInfoTable.FileChooser_Title_Input=请输入新建目录的名称
NodeInfoTable.FileChooser_Msg_Select=名称：
NodeInfoTable.FileChooser_Error_Select=目录名称无效，目录名称只能是字母或数字(a-z A-Z 0-9)。
NodeInfoTable.LOGOUT_NODE_FAILED=注销失败。
NodeInfoTable.IncorrectPassword=密码不正确。
NodeInfoTable.NullPassword =密码为空。
NodeInfoTable.LoginFailed =登录服务器失败，可能由以下原因引起。\n1.端口被占用。\n2.密码错误。
NodeInfoTable.GetHostNameFailed =服务器 {0} 的部署工具后台服务正在启动，请稍候再试...
NodeInfoTable.defaultPath =/opt/oss
NodeInfoTable.UnixdefaultPath =/opt/oss
NodeInfoTable.WindowsdefaultPath =c:\\oss
NodeInfoTable.masterNodeName = hostname
NodeInfoTable.atLeastOneSubNode = 至少要有一个子服务器
NodeInfoTable.SomeOtherFileInTheInstallDir=服务器 {0} 的安装路径 {1} 为非空目录，请清空该目录。
AddNodeDialog.RemoteIP=远程IP
NodeInfoTable.NEW_INSTALL=新安装路径
NodeInfoTable.OLDINSTALL=旧安装路径
NodeInfoTable.NODE_TYPE_INVALIDATE=请在主服务器选择安装路径
NodeInfoTable.IP_IS_NOT_LOCAL=输入IP错误，请输入本地IP。
NodeInfoTable.DirNotExistCreateIt = 服务器 {0} 目录 {1} 不存在，创建吗？
NodeInfoTable.Node_Details=服务器信息
NodeInfoTable.Summary_Node_Name= 服务器名称：
NodeInfoTable.Summary_Public_IP_Address= IP地址：
NodeInfoTable.Summary_Node_Type= 服务器类型：
NodeInfoTable.Summary_Installation_Path=安装路径：
NodeInfoTable.Help.Distribute.Message=请配置网管服务器信息。\n如果该服务器有多个IP，则不显示默认IP，需要手工输入正确的IP。\n安装集中式系统，只需要修改服务器参数，不需要进行增加子服务器和删除子服务器的操作。\n安装分布式系统，可以进行修改服务器参数，增加子服务器和删除子服务器的操作。
NodeInfoTable.Help.Single.Message=请配置网管服务器信息。\n如果该服务器有多个IP，则不显示默认IP，需要手工输入正确的IP。
NodeInfoTable.Help.1toN.Message=请配置网管服务器信息。\n如果该服务器有多个IP，则不显示默认IP，需要手工输入正确的IP。
NodeInfoTable.Prompt = 提示
NodeInfoTable.InitBeforeSubsystem =正在初始化组件信息，请稍候...
NodeInfoTable.changeServerNameSelect=请选择服务器：
NodeInfoTable.privatePanelError=节点 {0} 的公网配置与私网配置冲突，请重新配置IP或修改私网配置文件。
NodeInfoTable.CheckPrivatePanelFailed=节点"{0}"网卡平面检查失败。
NodeInfoTable.CheckDSConnection=DS通讯连接失败，请检查IP。
NodeInfoTable.PASSWORD_IS_DIFFERENT=管理员用户密码与主服务器管理员用户密码不一致。
NodeInfoTable.ipAddressError={0}与文件{1}定义不一致，请确认文件{1}配置。
NodeInfoTable.privateConfigureError=请检查各节点私网配置文件"engineering/conf/privateNetCfg.xml"是否一致。
NodeInfoTable.SureInstallSingelInVerritas=请问是否确定在已经安装了Veritas软件的服务器上安装单机系统？ \n单击<是>，继续单机系统安装。\n单击<否>，请重新选择安装类型。
NodeInfoTable.SureInstallSingelInVerritas.CMD=请问是否确定在已经安装了Veritas软件的服务器上安装单机系统？ \n选择<是>，继续单机系统安装。\n选择<否>，请重新选择安装类型。
NodeInfoTable.NeedInstallVeritas=安装Veritas热备份系统必须先安装Veritas软件，请完成Veritas软件安装后，重新启动网管安装。
NodeInfoTable.ServerIP=服务器地址：
NodeInfoTable.InstallExit = 静默安装将退出。
NodeInfoTable.browse=浏览(B)...
NodeInfoTable.NodeInfoTitle=请配置服务器。
NodeInfoTable.NodeRecommendInfo=建议不要选择操作系统的系统分区进行安装。
NodeInfoTable.InstallationPath=安装路径：
FilePath.isNotMatchProductRule=网管安装路径不符合路径规范，请参考安装指导书。
ossIsIntalled=不存在需要安装的节点，不需要再次进行安装。 \n {0}个节点之前已经安装成功：\n {1}