OptionPane.info=提示
OptionPane.warn=警告
OptionPane.error=错误
OptionPane.yes=是
OptionPane.no=否
OptionPane.cancel=取消
OptionPane.ok=确定
OptionPane.AllYes=全是
OptionPane.AllNo=全否
OptionPane.ShowDetail=显示详细信息
OptionPane.Exit=退出
OptionPane.Continue=继续
OptionPane.prompt=提示
OptionPane.Detail=详细信息
OptionPane.Confirmation=确认
OptionPane.Retry=重试
OptionPane.Ignore=忽略
