UPgrade.ConfigParas.CurrentVersion= 当前版本
UPgrade.ConfigParas.SourceListLabel= 选择源版本
UPgrade.ConfigParas.SourceList.OK=确认
UPgrade.ConfigParas.SourceList.Cancel=取消
UPgrade.ConfigParas.SourceList.Browes=浏览(B)...
UPgrade.sourceVersionDes=数据库sa用户的密码不正确。\n请输入正确的密码后单击<确定>继续。\n单击<取消>退出。
UPgrade.ConfigParas.SourceListTitle=提示
UPgrade.ConfigParas.Password=密码