ProgressPage.TotalTitle=正在执行{0}，请稍候...
ProgressPage.processstart=正在启动{0}...请稍候。
ProgressPage.failederror=启动{0}失败。

ProgressPage.Deploy=按域部署
ProgressPage.Undeploy=按域去部署
ProgressPage.install=安装
ProgressPage.incinstall=增加节点
ProgressPage.reinstall=重新安装
ProgressPage.upgradeinstall=升级安装

ProgressPage.Deployment=部署
ProgressPage.Undeployment=去部署
ProgressPage.Installation=安装
ProgressPage.IncrementalInstallation=增加节点
ProgressPage.Reinstallation=增量安装
ProgressPage.Upgradeinstallation=升级安装

ProgressPage.InstallProcessTitle = 安装。
ProgressPage.PatchInstallProcessTitle = 显示补丁安装进度
ProgressPage.PatchUnInstallProcessTitle = 显示补丁卸载进度
ProgressPage.communicateerror = 无法与节点机器进行通讯
ProgressPage.InstallTitle=正在安装，请稍候...
ProgressPage.UninstallTitle=正在卸载，请稍候...
ProgressPage.UpgradeTitle=正在升级，请稍候...
ProgressPage.PreUpgradeTitle=正在创建前置升级任务，请稍候...
ProgressPage.RollbackTitle=正在创建前置回滚任务，请稍候...
ProgressPage.PreRollbackTitle=正在准备回滚，请稍候...
ProgressPage.DATAMODEL_INIT=正在初始化数据，请稍候...
ProgressPage.InstallFailed=安装失败，请查看相关日志：\n{0}logs
ProgressPage.UninstallFailed=卸载失败，请查看相关日志：\n{0}
ProgressPage.UpgradeFailed=升级失败，请查看相关日志
ProgressPage.RollbackFailed=回滚失败，请查看相关日志
ProgressPage.PatchInstallFailed=补丁安装失败，请查看相关日志。
ProgressPage.PatchRollBackFailed=补丁回滚失败，请查看相关日志。
ProgressPage.installPatchTitle= 开始补丁安装，请稍候...
ProgressPage.uninstallPatchTitle=开始补丁卸载，请稍候...
ProgressPage.PatchTitle=正在安装补丁，请稍候...
ProgressPage.PrePatchRollbackTitle=正在卸载补丁，请稍候...
ProgressPage.creatingTask=正在创建任务，请稍候...
ProgressPage.UpgradeTitle_pre=正在执行前置升级，请稍候...
ProgressPage.RollbackTitle_pre=正在执行前置回滚，请稍候...
ProgressPage.BusyDialog= 正在进行自动回滚...
ProgressPage.AutoRollbackFinish= 自动回滚完成。
ProgressPage.Title=显示安装进度，主要有以下两大步骤：1、安装准备；2、安装软件。
ProgressPage.Title.Upgrade=升级进度信息

ProgressPage.Title.Rollback=回滚进度信息
ProgressPage.Underline======================================
ProgressPage.Percentage=%

SelectPackage.HINT=错误
ProgressPage.Wait=等待
ProgressPage.Completed={0}完成
MSG_HOST_DISCONNECTED=以下节点连接失败：{0}， 请检查网络连接。