
Restore.Title =网络管理系统恢复程序
RestoreWizardPage.Introduction =欢迎使用网络管理系统恢复向导
RestoreWizardPage.Introduce =本恢复程序将引导您完成对网络管理系统数据库及组件文件的恢复活动。\n请选择数据库的恢复方式，并单击<下一步>继续。
RestoreWizardPage.DatabaseBackup = 数据恢复 －二进制模式（推荐）
RestoreWizardPage.TableBackup = 数据恢复 －文本模式
RestoreWizardPage.OracleEnvNotSet=服务器上没有设置Oracle环境变量。
RestoreWizardPage.FailedToGetDBLogonInfoFromDatamodel=从数据模型中获取数据库登录信息失败。
