
RestorePreProgressPage.Title=恢复预处理正在进行中，请稍候...
RestorePreProgressPage.NewSubsystemsInBackup=组件不一致。建议通过增量安装或重新安装确保组件一致后再进行恢复；\n否则强制恢复会导致以下不一致的组件信息丢失，是否继续？
RestorePreProgressPage.InstanceMismatch=以下组件的实例不一致，请使用部署工具添加/删除。
RestorePreProgressPage.InstanceDynamicMacroMismatch=以下实例的动态宏不一致，强制恢复可能导致网管某些进程启动失败，是否继续？
RestorePreProgressPage.SubsystemNotValid=组件无效。
RestorePreProgressPage.RestorePreCheckError=恢复前置检查请求服务异常。
RestorePreProgressPage.RestoreFailed=恢复失败。