RestoreExitPage.Title=恢复操作成功。请手工启动网管服务。
RestoreExitPage.Note=请单击<完成>结束恢复向导。
RestoreExitPage.ERRORNote=请单击<退出>结束恢复向导。
RestoreExitPage.ErrorTitle=恢复操作失败
RestoreExitPage.RestoreSuccess=恢复操作成功。
RestoreExitPage.RestoreFailed=恢复操作失败。