
RestoreProgressPage.Title = 恢复正在进行中，请稍候...
BackupProgressPage.Introduce = 请选择您要采用的备份介质，然后单击<下一步>继续。
BackupProgressPage.LocalBackup = 备份到本地服务器
BackupProgressPage.RemoteBackup = 备份到远程服务器
BackupProgressPage.LocalBackupPath = 本地服务器备份路径：
BackupProgressPage.RemoteBackupPath = 远程服务器备份路径：
BackupProgressPage.IP=服务器IP：
BackupProgressPage.TransferMode =传送方式：
BackupProgressPage.UserName=用户名：
BackupProgressPage.Password=密码：
BackupProgressPage.Browse=浏览...

RestorePreProgressPage.NewSubsystemsInBackup=组件不匹配
IsBackupPage.yes=是
IsBackupPage.no=否
IsBackupPage.cmd=备份OSS应用程序和数据库

