RestoreSelFilePage.Introduction=请选择备份文件
RestoreSelFilePage.IntroductionForBCP=请选择文本的备份文件。
RestoreSelFilePage.IntroductionForDump=请选择二进制的备份文件。
RestoreSelFilePage.Introduce=请选择执行恢复的备份文件位置。\n选择完毕后请单击<下一步>继续。
RestoreSelFilePage.LocalRestore=从本地服务器恢复
RestoreSelFilePage.RemoteRestore=从远程服务器恢复
RestoreSelFilePage.IP=服务器IP：
RestoreSelFilePage.TransferMode=传输方式：
RestoreSelFilePage.UserName=用户名：
RestoreSelFilePage.Password=密码：
RestoreSelFilePage.Browse=浏览(B)...
RestoreSelFilePage.PromptInputError=恢复信息输入不完整，请重新输入。
RestoreSelFilePage.IsLocalIp=不允许使用本地服务器作为FTP/SFTP服务器。
RestoreSelFilePage.RemoteRestorePath=远程服务器恢复路径：
RestoreSelFilePage.LocalRestorePath=本地服务器恢复文件：
RestoreSelFilePage.DatabaseConnectionFailed=检查数据库失败，可能原因：\n1.数据库未运行。\n2.数据库运行状态不正常。
RestoreSelFilePage.LoginFailed=登录服务器失败，请检查用户名/密码。
RestoreSelFilePage.ConnectionFailed=连接远程服务器失败。
RestoreSelFilePage.DetailError=可能原因：\n 1. IP地址不正确。\n 2. 用户名或密码错误。\n 3. 远程服务未启动。
RestoreSelFilePage.InvalidIp=IP地址无效。
RestoreSelFilePage.ToContinue=该操作将会重启网络管理系统。\n是否继续？
RestoreSelFilePage.AllFolders=所有文件
RestoreSelFilePage.BackupServerNotRuuning=数据库备份服务没有运行，不能恢复数据库。
RestoreSelFilePage.INVALID_INSTAL_PATH=选择的备份路径不正确。\n1.必须选择该服务器的磁盘驱动器。\n2.要求目录名必须是绝对路径，且是英文字母，数字以及'_'，'-'的组合，长度不能超过60个字符，且路径中不能包含空格。
RestoreSelFilePage.error=错误
RestoreSelFilePage.InputError=恢复信息输入不完整，请重新输入。
RestoreSelFilePage.InCompleteIP=远程服务器IP为空。\n
RestoreSelFilePage.InCompleteUserName=用户名为空。\n
RestoreSelFilePage.InCompletePath=恢复路径为空。\n
RestoreSelFilePage.InCompletePassword=密码为空。\n
RestoreSelFilePage.PasswordMismatch=密码长度不能超过60个字符，并且只能包含以下字符：\n
RestoreSelFilePage.NMSALIVE=网管正在运行，请手动停止网管，并重试。
RestoreSelFilePage.NMSALIVEMSG=网管正在以下主机上运行：
RestoreSelFilePage.IpInvalid=IP地址不正确。\n
RestoreSelFilePage.Solution=由于上次操作异常工程后台无法正常运行，请重启工程后台。
RestoreSelFilePage.BrowseWindowLookIn=查看
RestoreSelFilePage.BrowseWindowFileName=文件名称
RestoreSelFilePage.BrowseWindowOpen=打开
RestoreSelFilePage.BrowseWindowCancel=取消
RestoreSelFilePage.PreRestoreCheckError=预恢复检查失败，请查看日志。
RestoreSelFilePage.PreRestoreCheckError_Details=可能原因：\n1.备份文件不存在。\n2.备份文件非法。\n3.临时目录权限不足。
RestoreSelFilePage.SelectFTPWarning=当前采用FTP协议，传输的内容没有加密，\n存在安全隐患，强烈建议采用安全的SFTP\n传输协议。请确认是否继续？
RestoreSelFilePage.SelectFTPOk=确认
RestoreSelFilePage.SelectFTPCancel=取消
RestoreSelFilePage.SSHConnectionFailed =使用SSH连接远程数据库失败。
RestoreSelFilePage.DBInfoFileInvalid=sysconfigure.xml文件或者数据库描述文件异常。