UpgradeSelectBackupPath.title= 选择备份路径
UpgradeSelectBackupPath.desciptionAppAndDatabase= 请选择回滚操作所需要的备份路径。
UpgradeSelectBackupPath.Browse=浏览(B)...
UpgradeSelectBackupPath.error= 错误
UpgradeSelectBackupPath.DirectoryMustBeCharAndNum= 路径必须是由数字、字母或者下划线组成的绝对路径，路径长度不能大于60个字符，路径分隔符与盘符前不允许出现空格。
UpgradeSelectBackupPath.hint= 信息
UpgradeSelectBackupPath.DirNotExistCreateIt= 目录{0}不存在。
UpgradeSelectBackupPath.NullTitle= 备份路径不可以为空。
UpgradeSelectBackupPath.InvalidDiskDriver= 无效的路径：
UpgradeSelectBackupPath.DirectoryError = 错误的目录："{0}"。
Upgrader.ConfigNotFound= 备份路径中未找到upgrader.properties文件。
Upgrader.ConfigTargetDBNotFound= 备份路径中未找到targetDB.txt文件。
Upgrader.ConfigMacrostxtNotFound= 备份路径中未找到“{0}”文件。
Upgrader.ConfigNmsRootDirNotExist= 网管路径{0}不存在。
Upgrader.ConfigUpgradeModeNotFound=在upgrader.properties文件中缺少升级模式信息。
RollBackInroduction.DBServerConfigFileNotFound=缺少数据库服务器配置信息文件。
RollBackInroduction.DBServerConfigFileError=加载数据库服务器配置信息失败。
Upgrader.ConfigUpgradeDualModeNotFound=在upgrader.properties文件中未找到升级的双机/单机模式信息。
Upgrader.ConfigUpgradeDualModeFileVolumeNotFound=在upgrader.properties文件中未找到升级的卷信息。
Upgrader.ConfigUpgradeDualModeFirstDeviceNotFound= 在upgrader.properties文件中未找到升级的第一台设备信息。
Upgrader.ConfigUpgradeDualModeSecondDeviceNotFound = 在upgrader.properties文件中未找到升级的第二台设备信息。
Upgrader.ConfigUpgradeNMSTypeNotFound = 在upgrader.properties文件中未找到升级的网管类型信息。
Upgrader.ConfigUpgradepluginManagerNotFound = 在upgrader.properties文件中未找到升级的插件管理信息。
BackupDBProgress.AppIsOnline=检测到依然有网管进程运行，请手动停止网管进程。
Upgrader.ConfigEnvNotFound=在upgrader.properties文件中未找到环境变量信息。
Upgrader.ConfigLastInstallDirNotFound=环境变量 {0} 不存在。
DBServerConfig.PortIsInvalid_Win = 连接数据库服务器失败，可能原因如下：\n数据库服务器端口错误；\n数据库服务器未启动；\nMSDE未启动。
DBServerConfig.PortIsInvalid = 连接数据库服务器失败，可能原因如下：\n数据库服务器端口错误；\n数据库服务器未启动。
DBServerConfig.ServerNameIsInvalid_Win = 连接数据库失败，可能由于以下原因导致：\n数据库服务名称错误；\n数据库未启动。
DBServerConfig.ServerNameIsInvalid = 数据库服务器名错误。
DBServerConfig.InstanceAndPwdIsInvalid = 数据库用户名或用户密码错误。
DBServerConfig.SUserAndPwdIsInvalid = 数据库管理员用户名或者管理员用户密码错误。
DBServerConfig.InstancePwdNull = 数据库密码不允许为空。
DBServerConfig.ISQLCommandIsInvalid = 无法找到isql命令。
SetupUpgradeEnvironment.CannotEndWithSeperator =网管环境变量不正确或者以/和\\结尾。
Upgrader.ConfigUpgradeShortCutPathNotFound = 在upgrader.properties文件中未找到快捷方式信息。
Upgrader.ConfigUpgradeNMsEnvarNotFound = 在upgrader.properties文件中未找到NMSENVVAR信息。
BackupProgress.ProIsAlive = 后台程序正在运行，是否继续？\n单击<是>自动停止后台程序。\n单击<否>手动停止后台程序。
Upgrader.ConfigUpgrade_SELEPRO_NotFound =在upgrader.properties文件中未找到projectName信息。
Upgrader.ConfigUpgrade_PROJECTNAME_NotFound = 在upgrader.properties文件中未找到projectName信息。
Introduction.Title =简介
Introduction.Contents =本安装程序将帮您完成网络管理系统软件的回滚。
Introduction.ContentsVerify=本校验程序将帮您完成安装包的校验，\n单击 <下一步> 进行下一步操作，\n单击 <取消> 取消校验。
Introduction.IsRunning = 系统检测到另一个安装程序正在运行，请先退出该程序后再继续安装。
Introduction.ContentsCMD =本安装程序将帮您完成网络管理系统软件的回滚。
Introduction.NotAuthority = 当前用户的权限受限，程序将退出。
Introduction.DBConfigFileInvalid = 数据库配置文件错误，安装程序将退出。
Introduction.ContentsUpgrade =本安装向导将引导完成网络管理系统升级。\n单击 <下一步> 进行下一步操作。\n单击 <取消> 取消升级。
Introduction.ContentsUpgradeCMD = 本安装向导将引导完成网络管理系统升级。\n单击 <下一步>n 进行下一步操作。\n单击 <取消>c 取消升级。
Introduction.InitBeforeUpgradeInstall = 正在收集源版本信息...
Introduction.hint = 信息
Introduction.UpgradeTime = 升级日期
Introduction.SourceVersion = 源版本
Introduction.Operation = 操作
Introduction.TargetVersion = 目标版本
Introduction.ComponentName= 组件名称
Introduction.RollBack = 回滚
Introduction.Details = 详细
Introduction.Next = 下一步
Introduction.Exit = 退出
Introduction.SerialNumber = 序列号
Introduction.NodeInfo = 服务器信息
Introduction.Continue = 继续
Introduction.mainPageConfirmation = 请按任意键选择操作
Introduction.invalidInput = 输入无效
Introduction.UPGRADECOMPONENTDETAILS=升级组件详情
Introduction.serialNo=选择
UpgradeSelectBackupPath.showversioncheck=是否将网管回滚到{version}版本？
CheckUpgradeEnviornment.ENTER_PASSWORD=数据库sa用户的密码不正确\n请输入正确的密码。
CheckUpgradeEnviornment.PASSWRONG=提示
CheckUpgradeEnviornment.GETTINDBINFOFAILED.connection=获取数据库连接失败。
UpgradeSelectBackupPath.NORollbackInfo=回滚信息不存在，不可以执行回滚操作。
UpgradeSelectBackupPath.Confirm=确认
CheckUpgradeEnviornment.ERRORINGETTINGINFO=获取数据库信息失败。
SelectPackage.HINT=等待
SelectPackage.processing=处理中，请稍候...

UPgrade.ConfigParas.CurrentVersion= 当前版本
UPgrade.ConfigParas.SourceListLabel= 选择源版本
UPgrade.ConfigParas.SourceList.OK=确定
UPgrade.ConfigParas.SourceList.Cancel=取消
UPgrade.ConfigParas.SourceList.Browes=浏览...
UPgrade.sourceVersionDes=回滚的备份路径不存在，请选择备份路径。
UPgrade.ConfigParas.SourceListTitle=输入备份路径

Summary.ApplicationInUse=网管目录{name}正在被使用，操作不可以继续。
UpgradeSelectBackupPath.NORollbackInfo_tile=错误：
RollbackIntroduction.Error=错误
Summary.DatabaseNotRunning=数据库服务器未运行。
NodeInfoTable.LOGIN_NODE_FAILED=连接备机失败。
CheckUpgradeEnviornment.APPLICATIONNOTEXIST=备份文件不存在，回滚不能继续。
rollback.ApplicationNoTexist= 应用程序目录{name}不存在
rollback.rollbackDatabaseNotexist=数据库备份文件不存在，不可以继续回滚。
RollbackInformation.inconsistentIP=回滚信息不正确。回滚无法继续执行。
CheckUpgradeEnviornment.GETTINDBINFOFAILED.ISQLFAILED=使用isql命令连接数据库失败。
CheckUpgradeEnviornment.GETTINDBINFOFAILED.SQLPLUSFAILED=使用isqlplus命令连接数据库失败。
CheckUpgradeEnviornment.FailedToGetIP=获取系统IP地址失败，系统将退出。
CheckUpgradeEnviornment.IPISNOTLOCALIP=数据模型中的IP地址不是本地IP地址，系统将退出。
RollbackInformation.WaitMessage=正在处理回滚信息，请稍候...
UpgradeDBTaskService.AUTOROLLBACK_FAILED=自动回滚失败