SelectClientInstallFolder.Browse=浏览(B)...
SelectClientInstallFolder.InstallNote=\n安装程序将在以下文件夹中安装 {0}，\n要安装到此文件夹请单击<下一步>，\n要安装到其他文件夹，请单击<浏览>，然后选择其他文件夹。
SelectClientInstallFolder.DestinationFolder=安装路径：
SelectClientInstallFolder.InstallAgainNote=\n安装程序将在以下文件夹中安装 {0}。
SelectClientInstallFolder.DiretoryNull=安装路径不能为空。
SelectClientInstallFolder.CheckInstallPathChar=安装路径不能有特殊字符，只支持字母、数字、下划线。
SelectClientInstallFolder.Hint=提示
SelectClientInstallFolder.InitBeforeInstall =正在初始化安装信息，请稍候...
SelectClientInstallFolder.CheckSpaceSize=安装盘所在分区“{0}”空间不足。
SelectClientInstallFolder.Error=错误
SelectClientInstallFolder.InitStaticDataError=初始化安装数据失败，请检查安装所需的配置文件是否存在。
SelectClientInstallFolder.DependenceError=组件依赖关系错误，如：出现循环依赖的情况。详细情况请查看日志。
SelectClientInstallFolder.Title=选择安装路径
SelectClientInstallFolder.DirectoryError=目录错误：“{0}”。
SelectClientInstallFolder.DirectoryMustBeCharAndNum_windows=1.文件夹名不能包括如下特殊字符：*,?,/,!,",<,>,|,%,^,&,;,#,(,),:和+；\n2.安装路径长度不能超过60个字符；\n3.安装目录必须为空；\n4.不能选择驱动器根目录或系统根目录；\n5.在“\”或“:”前不能添加空格或“\”或“/”；\n6.安装目录名不能以“.”开头和结尾；\n7.安装路径必须是绝对路径。
SelectClientInstallFolder.DirectoryMustBeCharAndNum=1.文件夹名不能包括如下特殊字符：*,?,\,!,",<,>,|,%,^,&,;,#,(,)和+；\n2.安装路径长度不能超过60个字符；\n3.安装路径不能为空，并且不能包含空格；\n4.不能选择驱动器根目录或系统根目录；\n5.在“/”前不能添加空格或“\”或“/”；\n6.安装目录名不能以“.”开头和结尾；\n7.安装路径必须是绝对路径。
SelectClientInstallFolder.NoSupportPathBlank=要求目录名必须是绝对路径，且是英文字母，中文字符和数字以及‘_’和‘-’的组合，长度不能超过60个字符，且目录路径中不能有空格。
SelectClientInstallFolder.SomeOtherFileInTheInstallDir=目录 {0} 为非空目录，请选择另外一个目录。
SelectClientInstallFolder.IllegalFilesInFolder=目录 {0} 下含有非法文件，请将其删除后再安装，或选择别的目录进行安装。
SelectClientInstallFolder.IllegalFilesList=非法文件列表：
SelectClientInstallFolder.AnotherVersionExist=系统中存在另一个版本，\n已安装的版本：{0} \n当前安装的版本：{1} \n如果您安装当前版本，已安装的版本可能无法使用，\n是否继续安装？
SelectClientInstallFolder.VersionNotAvailable=<不可用>
SelectClientInstallFolder.CanntBeWrite=创建安装目录失败或该目录不可写。
SelectClientInstallFolder.Symboliclinks=目录是链接，将转换为真实目录。
SelectClientInstallFolder.SystemIsNotCompatible=检测到已安装的系统和本次要安装的系统版本不兼容，是否继续安装？\n继续安装请修改安装路径，否则安装程序将退出。
SelectClientInstallFolder.SystemIsNotCompatibleExit=检测到已安装的系统和本次要安装的系统版本不兼容，安装程序将退出。
SelectClientInstallFolder.DirNotExistCreateIt=目录 {0} 不存在，创建吗？
SelectClientInstallFolder.CreateDirFail=不能创建该目录。
SelectClientInstallFolder.InvalidDiskDriver=无效磁盘驱动器：“{0}”。
SelectClientInstallFolder.InvalidPath=目录不合法。

