SelectInstallFolder.Select = 选择
SelectInstallFolder.Browse = 浏览(B)...
SelectInstallFolder.InstallNote = \n安装程序将在以下文件夹中安装 {0}，\n要安装到此文件夹请单击<下一步>，\n要安装到其他文件夹，请单击<浏览>，然后选择其他文件夹。
SelectInstallFolder.InstallAgainNote = \n安装程序将在以下文件夹中安装 {0}。
SelectInstallFolder.DestinationFolder = 目的地文件夹：
SelectInstallFolder.Title = 选择安装路径
SelectInstallFolder.TitleChoice = 提示
SelectInstallFolder.DirNotExistCreateIt = 目录 {0} 不存在，创建吗？
SelectInstallFolder.Error = 错误
SelectInstallFolder.DirectoryError = 目录错误：“{0}”。
SelectInstallFolder.DiretoryConfine = 路径不能超过60个字符，请重新输入。
SelectInstallFolder.DirectoryMustBeCharAndNum = 1.必须选择该服务器的磁盘驱动器；\n2.要求目录名必须是绝对路径，且是英文字母，中文字符和数字以及\'_\'和\'-\'的组合；\n3.长度不能超过60个字符，'\\'或'/'或':'前不能有空格。
SelectInstallFolder.CreateDirFail = 不能创建该目录。
SelectInstallFolder.InstallFolder = 安装路径为：
SelectInstallFolder.SomeOtherFileInTheInstallDir = 目录 {0} 为非空目录，请选择另外一个目录。
SelectInstallFolder.IllegalFilesInFolder = 目录 {0} 下含有非法文件，请将其删除后再安装，或选择别的目录进行安装。
SelectInstallFolder.IllegalFilesList = 非法文件列表：
SelectInstallFolder.DependenceError = 组件依赖关系错误，如：出现循环依赖的情况。详细情况请查看日志。
SelectInstallFolder.hint = 提示
SelectInstallFolder.InitBeforeInstall =正在初始化安装信息，请稍候...
SelectInstallFolder.ApproveTip = 打开选择的文件夹
SelectInstallFolder.DesktopTip = 桌面
SelectInstallFolder.DirName = 目录名：
SelectInstallFolder.CanntBeWrite = 创建安装目录失败或该目录不可写。
SelectInstallFolder.InvalidDiskDriver = 无效磁盘驱动器：“{0}”。
SelectInstallFolder.DiretoryNull = 安装路径不能为空。
SelectInstallFolder.PackageXmlWrong = 组件描述文件{0}错误，安装程序将退出。
SelectInstallFolder.SystemIsNotCompatible = 检测到已安装的系统和本次要安装的系统版本不兼容，是否继续安装？\n继续安装请修改安装路径，否则安装程序将退出。
SelectInstallFolder.SystemIsNotCompatibleExit = 检测到已安装的系统和本次要安装的系统版本不兼容，安装程序将退出。
SelectInstallFolder.InvalidPath = 目录不合法。
SelectInstallFolder.NoSupportPathBlank = 要求目录名必须是绝对路径，且是英文字母，中文字符和数字以及\'_\'和\'-\'的组合，长度不能超过60个字符，且目录路径中不能有空格。
SelectInstallFolder.AnotherVersionExist = 系统中存在另一个版本，\n已安装的版本： {0} \n当前安装的版本： {1} \n如果您安装当前版本，已安装的版本可能无法使用，\n是否继续安装？
SelectInstallFolder.IsExit = 成功退出。
SelectInstallFolder.Symboliclinks = 目录是链接，将转换为真实目录。
SelectInstallFolder.PackageOrGroupNameNull = 组件或组件组必须配置名称。安装程序将退出。
SelectInstallFolder.MandatoryTagNotFound = 组件描述文件有一个或多个必配项没有配置：{0}。\n安装程序将退出。
SelectInstallFolder.CHANGE_SYBASE_INTERFACES_FAILED=更改sybase文件interfaces失败。
