SelectLicense.selectlicense=License文件：
SelectLicense.info=License 信息
SelectLicense.Inputdes_CMD=请配置网管系统运行时所需的License文件（如果没有License文件请输入"n"继续执行下一步）。
SelectLicense.Inputdes=请配置网管系统运行时所需的License文件（如果没有License文件，取消勾选，再单击<下一步>）。
SelectLicense.Inputdes.license=请配置网管系统运行时所需的License文件。
SelectLicense.Checkdes=安装时自动设置网管License文件
LicensePage.select=浏览(B)...
LicensePage.License.Alert.SelectFile=请选择License文件。
LicensePage.License.Alert.None=所设置的License文件不存在，请设置正确的License文件。
LicensePage.License.Alert.Invalid=请选择有效的License文件。
LicensePage.InstallDiskFile.None=InstallDisk.xml文件不存在，请配置该文件，并重新启动安装。
LicensePage.InstallDiskFile.Error=InstallDisk.xml文件里配置的license信息不正确。
LicensePage.Alert.Size=License文件大于10M，请选择正确的文件。
InputLicensePanel.SelectLicenseFileLabel=请输入license文件路径
