SelectPackageUtil.DatabaseName = 数据库名称：
SelectPackageUtil.ProcessName = 相关进程：
SelectPackageUtil.UserName = 用户名：
SelectPackageUtil.RemotePrograme = （远端进程。）
SelectPackageUtil.DBSetName = 数据库集合名称：
SelectPackageUtil.DBNames = 数据库名称：
SelectPackageUtil.DefaultPolicyIntroduction = 数据库备份工具将在
SelectPackageUtil.DefaultTimeType1 = 每天{0}时开始对数据库自动备份。
SelectPackageUtil.DefaultTimeType2 = 每周{0}的{1}时开始对数据库自动备份。
SelectPackageUtil.DefaultTimeType3 = 每月{0}日{1}时开始对数据库自动备份。
SelectPackageUtil.Sun = 星期日
SelectPackageUtil.Mon = 星期一
SelectPackageUtil.Tues = 星期二
SelectPackageUtil.Wed = 星期三
SelectPackageUtil.Thurs = 星期四
SelectPackageUtil.Fri = 星期五
SelectPackageUtil.Sat = 星期六