SelectPath.title = 选择网管路径
SelectPath.CMDtitle = 网管路径
SelectPath.NullTitle = 输入的路径不能为空。
SelectPath.error = 错误
SelectPath.DirectoryError = 目录错误。
SelectPath.InvalidDiskDriver = 无效磁盘驱动器。
SelectPath.DirectoryMustBeCharAndNum = 1.必须选择该服务器的磁盘驱动器；\n2.要求目录名必须是绝对路径，且是英文字母，中文字符和数字以及\'_\'和\'-\'的组合；\n3.长度不能超过60个字符，'\\'或'/'或':'前不能有空格。
SelectPath.hint = 提示
SelectPath.DirNotExist = 目录不存在。
SelectPath.ProcessTitle = 正在运行的程序 ：
