SelectInstallType.InstallationType=安装类型
SelectInstallType.singleinstallation=安装单机系统
SelectInstallType.singleserversystem=单机系统
SelectInstallType.SunClusterHa=SunCluster热备份系统
SelectInstallType.VeritasHa=Veritas热备份系统
SelectInstallType.WindowsClusterHa=高可用性系统（Windows Cluster热备份）
SelectInstallTypeU.desTextArea=请选择服务器类型。
SelectInstallTypeU.dualServerRadioBtn=本地双机（适用于共享存储的本地双机）
SelectInstallTypeU.InstallationType=安装类型
SelectInstallTypeU.multiServerRadioBtn=分布式（适用于分布式或分布式异地双机）
SelectInstallTypeU.NeedInstallVeritas=安装Veritas热备份系统必须先安装Veritas软件，请完成Veritas软件安装后，重新启动网管安装。
SelectInstallTypeU.serverPanelTitle=服务器类型
SelectInstallTypeU.SingleInstallation=安装单机系统
SelectInstallTypeU.singleServerRadioBtn=单机（适用于单机或异地双机）
SelectInstallTypeU.sunclusterhotinstallation=安装SunCluster热备份系统
SelectInstallTypeU.SureInstallSingelInVerritas.CMD=请问是否确定在已经安装了Veritas软件的服务器上安装单机系统？ \n选择<是>，继续单机系统安装。\n选择<否>，请重新选择安装类型。
SelectInstallTypeU.SureInstallSingelInVerritas=请问是否确定在已经安装了Veritas软件的服务器上安装单机系统？ \n单击<是>，继续单机系统安装。\n单击<否>，请重新选择安装类型。
SelectInstallTypeU.Title =选择安装类型
SelectInstallTypeU.veritashotinstallation=安装Veritas热备份系统
SelectInstallTypeU.windowsclusterhotinstallation=安装WindowsCluster热备份系统
