SelectInstallType.addNodeRadioBtn=增加节点
SelectInstallType.desTextArea=请选择服务器类型。
SelectInstallType.dualServerRadioBtn=本地双机（适用于共享存储的本地双机）
SelectInstallType.InstallationType=安装类型
SelectInstallType.multiServerRadioBtn=分布式（适用于分布式或分布式异地双机）
SelectInstallType.newDeployRadioBtn=全新安装
SelectInstallType.reDeployRadioBtn=重新安装节点
SelectInstallType.serverPanelTitle=服务器类型
SelectInstallType.singleinstallation=安装单机系统
SelectInstallType.singleServerRadioBtn=单机（适用于单机或异地双机）
SelectInstallType.SunClusterHa=SunCluster热备份系统
SelectInstallType.Title =选择安装类型
SelectInstallTypeU.Title=选择安装类型
