SetClientShortcutFld.InstallNote=\n安装程序将在如下目录创建快捷方式。 \n请在文本输入框中输入目录名称。
SetClientShortcutFld.DestinationFolder=快捷方式文件夹：
SetClientShortcutFld.DiretoryNull=快捷方式文件夹不能为空。
SetClientShortcutFld.Title=设置快捷方式文件夹
SetClientShortcutFld.CreateShort=在桌面上创建快捷方式
SetClientShortcutFld.CreateShortInFolder=在桌面上的快捷方式目录中创建快捷方式
SetClientShortcutFld.CreateShortNormal=直接在桌面上创建快捷方式
SetClientShortcutFld.DirectoryError=快捷方式文件夹非法，请输入合法的文件夹名称。\n1.文件夹名称不能包含\ / : * ? " , < >和|；\n2.文件夹长度不能超过60个字符；\n3.文件夹不能为空。
SetClientShortcutFld.Error=错误