ShowDlg.title = 提示
ShowDlg.exitBtn = 退出
ShowDlg.retryBtn = 重试
ShowDlg.confirmBtn = 确定
ShowDlg.pwd = 密码：
ShowDlg.path = 网管路径：
ShowDlg.select = 选择
ShowDlg.error = 错误
ShowDlg.DirectoryError = 目录错误：
ShowDlg.DirectoryMustBeCharAndNum = 1.必须选择该服务器的磁盘驱动器；\n2.要求目录名必须是绝对路径，且是英文字母，中文字符和数字以及\'_\'和\'-\'的组合；\n3.长度不能超过60个字符，'\\'或'/'或':'前不能有空格。