SaveDbinfoError=保存数据库信息到sysconfigure.xml文件失败。
SaveDbserverError=保存数据库服务信息到sysconfigure.xml文件失败。
SaveDeployschemeError=保存部署信息到deployscheme.xml文件失败。
SaveHostinfoError=保存节点信息到sysconfigure.xml文件失败。
SaveInstallscopeError=保存安装类型到installscope.ini文件失败。
SaveInstallsummaryError=保存实例信息到InstallSummary.xml文件失败。
SaveMacroError=保存宏信息到macros.ini文件失败。
SaveScanZipError=保存待安装7z文件列表到installscope.ini文件失败。
ServicegroupStaticdataerror=校验服务组配置失败。
SrvGrpNotExist=服务组{0}不存在，将退出操作。
delInstallScopeiniError=删除installscope.ini文件失败。
writeRemoteNodeIDIni=保存nodeID.ini文件失败。
copySysconfigurexmlToServer=保存sysconfigure.xml到网管目录失败。
copySysconfigurexmlToEngr=恢复sysconfigure.xml到维护工具目录失败。
copyFilesLocaleOrRemote=复制数据文件到远程失败。
failNodes=上次{0}失败节点：
install=安装
upgradeinstall=升级安装