
StorageWelcomePage.Title=欢迎使用网络管理系统
StorageWelcomePage.Welcome=欢迎使用网络管理系统
StorageWelcomePage.WelcomeExt=网络管理部署系统
StorageWelcomePage.Request=请选择以下操作方式：
StorageWelcomePage.Backup=备份网络管理系统数据
StorageWelcomePage.Restore=恢复网络管理系统数据
StorageWelcomePage.CfgPolicy=配置网络管理系统备份策略
StorageWelcomePage.ReturnPrePage=返回上一页
StorageWelcomePage.DeploymentTool=部署工具
StorageWelcomePage.Exit = 结束

BackupPolicyWelcomePage.Title=欢迎使用网络管理系统
BackupPolicyWelcomePage.TimeBackup=配置网络管理系统定时备份任务
BackupPolicyWelcomePage.FileClear=配置网络管理系统备份文件清理任务
BackupPolicyWelcomePage.ReturnPrePage=返回上一页
BackupPolicyWelcomePage.Welcome=欢迎使用网络管理部署系统
BackupPolicyWelcomePage.WelcomeExt=网络管理部署系统
BackupPolicyWelcomePage.Request=请选择以下操作方式：
BackupPolicyWelcomePage.Exit = 结束
StorageWelcomePage.DBMgrTool=数据库管理工具
ProgressPage.StorageTitle=正在进行存储管理，请稍候...
WizardFrame.PatchAffirmCancel = 确定取消补丁吗？
