SummaryProgress.ProIsAlive=升级相关的应用程序正在运行，是否继续？\n单击<是>将自动停止网管应用程序。\n单击<否>不自动停止网管应用程序。
Summary.Title = 安装信息确认
Summary.BaseInfomatin = [基本信息]
Summary.InstallPath = 安装路径：
Summary.DiskSpaceNotEnough = 此分区磁盘空间不足：“{0}”。
Summary.DiskSpaceNotEnoughWarning = 磁盘{0}上的空间不足。
Summary.DiskSpaceNotEnoughCMD = 磁盘空间不足。
Summary.ActualDiskSpace = 可用的磁盘空间：
Summary.NeededDiskSpace = 需要的磁盘空间：
Summary.MaxAfterExpansion = 自增长后所需的最大空间： 
Summary.OSVersion = 操作系统版本：
Summary.DatabaseType = 数据库类型：
Summary.DatabaseVersion = 数据库版本：
Summary.ProductVersion = 产品版本：
Summary.PackageInfomation = [组件信息]
Summary.SetupMode = 安装方式
Summary.SelectedPackages = 安装的组件如下：

Summary.Exception = 创建数据库异常。
Summary.Confirm = 确认参数是否正确，如果正确，请选择<下一步>继续，否则选择<上一步>返回修改。\n选择<下一步>后不能再进行回退。

Summary.MemoryNotEnough = 系统内存不足。
Summary.ActualMemorySize = 物理内存大小：
Summary.NeededMemorySize = 需要内存大小：
Summary.MemorySizeNOTSET = 没有定义
Summary.OSType = 操作系统类型：
Summary.Cancel = 退出安装
Summary.Previous = 返回上一步
Summary.UsedState = 磁盘空间：
Summary.isCreateShotcutOnDesk = 是否在桌面创建快捷方式？
Summary.drive = 磁盘：
Summary.Subsystem = 组件：
Summary.SubsystemDescription=描述：
Summary.SourceVersion = 源版本：
Summary.TargetVersion = 目标版本：
Summary.susbystemInformation=升级的组件名称：
Summary.newSusbystemInformation=新增的组件名称：
Summary.IndividualDetails=所需空间大小分别为
Summary.DBSERVER_SIZE=DBServer需要的空间为：
Summary.NMS_APP_SIZE=应用程序需要的总空间：
Summary.NMS_DB_SIZE=应用数据库需要的总空间：
Summary.PMS_DB_SIZE=性能管理应用数据库需要的空间：
Summary.Neededspace=安装应用程序所需磁盘空间大小：
Summary.NODEINFO=\n[服务器信息]\n
Summary.nodeName=服务器名称：
Summary.sapceNotenough=磁盘“{partitionname}”上的空间不足，所需空间为：{requiSpace}，剩余空间为：{freeSpace}。
Summary.Backupspacerequired = 备份应用程序所需的分区空间 "{partitionname}"
Summary.freeSpaceon= 分区上的剩余空间 "{key}"
Summary.colonrequired=：
Summary.PatchTitle = 确认补丁安装
Summary.backupPath= 备份路径
Summary.systemexit=不能继续升级。
Introduction.SELECTOPERATION=选择选项
Introduction.Continue=重试
Introduction.cancle=取消
Introduction.exitSuccess=系统退出成功
Introduction.previous=上一步
BackupDBProgress.DB_INUSE=数据库被使用
SummaryProgress.ProIsAlivecmd=升级相关的应用程序正在运行，是否继续？\n输入y<是>将自动相关的应用程序。\n输入n<否>手工停止相关的应用程序。
Summary.newDBspaceRwq=数据库所需磁盘空间 “{partitionname}”：
Summary.ApplicationInUse=应用程序目录{name}正在被使用。操作不能继续。
Summary.ActualDiskSpaceForBackup = 备份可用磁盘空间： 
Summary.NeededDiskSpaceForBackup = 备份需要的磁盘空间： 
Summary.subsystempathNotexit= 以下组件路径在系统中不存在。
SelectPackage.HINT=等待
SelectPackage.processing=正在处理汇总信息
upgrade.Summary=请确认升级详细信息
UPgrade.ConfigParas.CurrentVersion=数据设备路径
UPgrade.ConfigParas.SourceListLabel= 日志设备路径
UPgrade.ConfigParas.SourceList.OK=确认
UPgrade.ConfigParas.SourceList.Cancel=取消
UPgrade.ConfigParas.SourceListTitle=选择数据设备路径
UPgrade.sourceVersionDes=请设置新建数据库的数据设备路径和日志设备路径。
DatabaseFileBrowser.EmptyPath=数据设备路径和日志设备路径不可以为空。
DatabaseFileBrowser.EmptyDataPath=数据设备路径为空。
DatabaseFileBrowser.EmptyLogPath=日志设备路径为空。
DatabaseFileBrowser.SapaceNotEnoughPath=分区“{partitionname}”的剩余空间不足，需要空间：{requiSpace}，剩余空间：{freeSpace}。\n
DatabaseFileBrowser.PathInvalid=无效的路径：{path}。
UPgrade.DataPathSelect=请选择新建数据库的数据设备路径。
UPgrade.LogPathSelect=请选择新建数据库的日志设备路径。
Summary.DeviceNotExist= 下面的数据库设备路径不存在。
UpgradeSelectBackupPath.Confirm=确认：
Summary.DatabaseNotRunning=数据库服务器未运行。
Summary.Prompt = 提示
Summary.CheckMemAndDisk =正在检测服务器内存及磁盘空间，请稍候...
Summary.DevicesapceNotenough=磁盘“{partitionname}”上的空间不足，所需空间为：{requiSpace}，剩余空间为：{freeSpace}。
DatabaseFileBrowser.DifferentPath=源网管数据库路径不一致。
Summary.Retry = 重试

SummaryUtil.FailedDir=创建“{path}”目录失败。
SummaryUtil.PermissionCheckFail=无“{path}”目录权限。
Summary.SpaceRequiredForUpgrade=分区“{partitionname}”升级空间需求：
UpgradeSelectBackupPath.NodeConnection Failed= RPC 连接失败。

CopyFiles.InvalidCopyFilesClass = 初始化jar过滤器失败。
CopyFiles.DependenceError = 组件依赖关系错误，如：出现循环依赖的情况。详细情况请查看日志。
CopyFiles.NotFindXMLFilesContent = 没有组件可以被安装。

Summary.SetupModeNotSupply=组件文件为空，程序将退出。
Summary.Hint=错误
Summary.Unselected = 请选择组件。
SummaryUtil.UnparseXML = 解析数据库配置文件失败。