ClientInstallType=客户端
ServerInstallType=服务器
ProgressPage.InstallTitle=正在安装，请稍候...
ProgressPage.UninstallTitle=正在卸载，请稍候...
ProgressPage.InitDataModel=正在初始化数据...
ProgressPage.PreUpgradeTitle=正在进行备份、卸载老网管，请稍候...
ProgressPage.UpgradeTitle=正在执行安装模块、升级脚本，请稍候...
ProgressPage.RollbackTitle=回滚到网管源版本，请稍候...
ProgressPage.PatchTitle=正在安装补丁，请稍候...
ProgressPage.PrePatchTitle=正在安装补丁，请稍候...
ProgressPage.PrePatchRollbackTitle=正在卸载，请稍候...
ProgressPage.PatchFailed=安装补丁失败，请查看详细日志
Function.InstallClient=正在执行安装{0}{1}{2}
Function.AddSubsystemDataModel=正在添加子系统信息到数据模型...
Function.deployAddSubsystemInstance=正在部署子系统实例...
Business.Install=正在执行安装...
Task.TransferMastertoSlave=安装{0}{1}{2}，正在传输包文件...
Task.Unzip=正在{0}上解压{1}文件...
Task.AddSubsystemDataModel=正在添加子系统信息到数据模型...
Task.ReplaceFileMacro=安装{0}{1}{2}，执行宏替换
Task.Preinstallscript=安装{0}{1}{2}，执行前置安装脚本
Task.Predbscript=安装{0}{1}{2}，执行前置数据库脚本
Task.Postdbscript=安装{0}{1}{2}，执行后置数据库脚本
Task.Postinstallscript=安装{0}{1}{2}，执行后置安装脚本
Task.Createshutcut=安装{0}的{1}{2}，创建快捷方式
Task.RegeditItem=安装{0}{1}{2}，注册系统项
Task.RegeditService=安装{0}{1}{2}，注册系统服务
Task.RegedtiEnvironment=安装{0}{1}{2}，注册环境变量
Task.CreateProchandle=安装{0}{1}{2}，创建进程句柄
Task.CreateDB=安装{0}{1}{2}，创建数据库
Task.MoveInstancfileFromSubNodeToBackup=安装{0}{1}{2}，转移子服务器实例文件到保护服务器
Task.ChangeConfigure=安装{0}{1}{2}，修改保护服务器配置
Task.DoLocalInstallProtectPostWork=安装{0}{1}{2}，执行保护后置操作
Function.InstallDatabaseSoftware=在{0}执行安装数据库操作

Task.SybaseInstall=正在安装SYBASE数据库...
Task.SybaseBuild=正在配置SYBASE数据库...
Function.dBConnection=正在建立数据库连接...
Function.initMacroData=正{0}在初始化宏...
Function.initSerializeData=正在初始化串行数据...
Task.Addinstancetodatamodel=安装{0}{1}{2}，添加实例到数据模型
Task.Startinstanceprocess=安装{0}{1}{2}，启动实例进程
Function.preCheck=正在进行安装前的检查...
Function.installDiskXml=正在{0}执行安装后脚本...
Function.alarmDisplay=正在{0}设置告警灯配置...
Function.PreInitTask=正在{0}执行前置初始化任务...
Function.PostInitTask=正在{0}执行后置初始化任务...
Function.addSubsystemInstance=正在创建{1}实例操作...
Function.sybaseAgent=正在安装sybase客户端...


Function.PreInitDatabase=正在执行前置初始化数据库任务，请稍候...
Function.CreateDatabase=正在创建数据库，请稍候...
Task.DeleteAllDatabaseAction=删除所有数据库
Task.CreateDatabase=创建数据库
Function.ExecDatabaseScript=执行数据库脚本
Function.PostInitDatabase=正在执行后置初始化数据库任务，请稍候...
Task.execInstallScript=执行安装脚本
Function.CheckApplicationInUse=正在检查目录是否被占用

ProgressPage.UpgradeTitle_creatTask=正在创建安装模块、执行升级脚本等任务流，请稍候...
ProgressPage.RollbackTitle_creattask=正在创建恢复老网管任务流，请稍候...
ProgressPage.RollbackTitle_pre=正在进行卸载当前网管，请稍候...
Task.DeleteInstance=删除实例...
Task.PreEngrAddInstanceScript=执行添加实例前置脚本
Task.PostEngrAddInstanceScript=执行添加实例后置脚本
Function.FreezeHAServiceGroup=冻结资源组
Function.UnfreezeAndFlushHAServiceGroup=解冻资源组
Task.UnDeployScript=执行删除部署数据脚本
Task.UnDeployInstanceScript=执行删除实例数据脚本
Task.MoveDeployedFlagForInstallSummary=迁移{0}部署信息
Task.DeleteInstanceDynamicMacro=删除实例动态宏
Task.PreEngrDeleteInstanceScript=执行删除实例前置脚本
Task.PostEngrDeleteInstanceScript=执行删除实例后置脚本

Task.ParallBackupFile=正在{0}执行组件{1} 升级备份脚本{2}，请稍候...
Function.ParallelUpgadeInstall=正在{0}执行组件{1} 升级安装脚本{2}，请稍候...
Function.AfterUpgradeInstall=正在{0}执行组件{1} 升级安装后置脚本{2}，请稍候...
Task.SubsytemDBUpgrade= 正在{0}执行组件{1} 升级数据库{2}，请稍候...
Task.PostUpgradeScriptTask=正在{0}执行组件{1} 升级后置脚本{2}，请稍候... 
Task.DropDBUpgrade=正在 {0} 执行 {1} 数据库删除操作...
Task.RenameNewDBUpgrade =正在 {0} 执行 {1} 数据库改名操作...
Task.UpgradeScript=正在 {0} 执行 {1} 升级脚本...




Task.InitSiteInfoToDatamodel=初始化站点信息到数据模型
Task.InitStaticMacroData=初始化静态宏
Function.InstallServer=安装服务器，正在执行安装{0}{1}{2}
Function.PreInstallServer=在{0}上执行服务器前置安装脚本
Task.SetInstalledSubsystem=在{0}上重置已安装组件信息
Function.postInstallClient=在{0}上执行安装客户端的后置脚本
Task.PostInstallClientScript=执行客户端的后置脚本
Task.TransferSubsystemFile=传输 {1}组件部署包
Task.PreInstallClientCheck=检查{0}上的客户端安装
Task.PreInstallServerScript=在{0}上执行安装服务器的前置脚本
Task.PostInstallServerScript=在{0}上执行安装服务器的后置脚本
Task.AddDatabaseAdapter=配置数据库适配
Function.InstanceData=在{0}上初始化{1}的实例信息
Task.InitDeployScript=在{0}{1}上初始化部署{2}
Task.PreDeployInstanceScript=部署实例在{0}
Task.GlobalPreDeploy=部署实例在{0}
Task.AddNodeAdapter=配置节点
Function.PreDeployInstance=在{0}上执行部署实例前置脚本操作
Function.PostDeployInstance=在{0}上执行部署实例后置脚本操作
Task.DeployScript=在{0}{1}上初始化部署{2}
Function.CopyUninstallContent=拷贝安装盘文件
Function.CopyUninstallContentToLocal=清理未安装数据
Function.ExitInstall=退出{0}安装
Function.ExitInstallScript=安装脚本执行完成
Function.PackageSerializeAction=串行化部署包
Function.PostInstallServer=在{0}上执行安装服务器的后置脚本

Task.CreateSysconfigureForNMS=创建{0}系统配置文件
Task.InitInstanceData=初始化{0}实例数据
Task.MarkInstalledFlagForInstallSummary=保存{0}安装信息
Task.InstallDBConnection=创建{0}数据库连接池
Task.PostDeployInstanceScript=执行{0}部署实例的脚本
Task.SaveDynamicMacroTask=保存{0}动态宏
Task.MarkDeployedFlagForInstallSummary=保存{0}部署信息
Function.unistallserver=卸载{0}服务器
Task.UninstallDataBaseTask=卸载{0}数据库数据
Task.UninstallShortcutsTask=卸载{0}快捷方式
Task.UninstallServiceTask=删除{0}服务
Task.UninstallEnvTask=清理{0}环境设置
Task.UninstallRegisteryTask=卸载{0}注册信息
Task.UninstallOSSUserTask=删除{0}OSS用户
Task.UninstallFilesTask=删除{0}安装路径目录
Function.Preuninstallserver=准备卸载{0}安装盘服务器
Task.GlobalPreUninstallServerTask=准备卸载{0}安装盘服务器
Function.Postuninstallserver=卸载{0}安装盘服务器
Task.UninstallClearEngrEnvTask=清除{0}安装盘配置文件
Task.GlobalPostUninstallServerTask=执行{0}前置卸载脚本
Task.SyncGlobalFileForNodes=更新全局配置文件
Function.ExitDeleteInstance=删除实例结束
Task.CopyUninstallContent=拷贝卸载相关文件
Task.CopyUninstallContentToLocal=拷贝卸载相关文件
Task.PackageSerializeAction=串行化部署包
Task.ModifyPermissionForOSS=修改文件权限
Task.AddAllInsDBToSysconfigureFileTask=记录组件{1}的数据库信息到{0}
Task.InstallVCREDI=安装VCREDI...
Function.InstallVCREDI=安装VCREDI...

Task.MsdeInstall=SQL Server安装检查
Task.SqlServerInstall=安装SQL Server

Task.GlobalPreUndeployTask=执行全局去部署预置脚本 {0}...
Task.UndeployTask=执行 {1} 去部署脚本 {0}...
Task.GlobalPostUndeployTask=执行全局去部署后置脚本 {0}...



[StorageWorkflow]
Task.compressfile=压缩组件{0}的配置文件
Task.transferfile=传输组件{0}的配置文件
Task.deletetempfile=删除组件{0}的临时文件
Task.backupsubsystemdatabase=备份组件{0}所属数据库
Task.backupdatamodel=备份数据模型
Task.compressdata=生成压缩包
Task.getsum=对备份压缩包进行签名
Task.transferdata=传输备份文件
Task.deleteTmpFile=删除备份临时文件
Task.enablearchivelogs=启用数据库归档日志
Task.disablearichivelogs=禁用数据库归档日志
Task.checksum=检查压缩包签名
Task.uncompressdata=解压备份文件
Task.comparedm=正在比较数据模型，此操作将会花费一点时间，请稍候...
Task.transferinstallsubsystem=传输组件{0}安装包文件
Task.decompressinstallfiles=解压组件{0}安装包文件
Task.DatabaseInUse=检查正在使用的数据库
Task.syncdatabase=同步数据库
Task.restoresubsysdb=恢复组件{0}数据库数据
Task.decompressfile=解压组件{0}配置文件
Task.restoredm=恢复数据模型
Task.deleterestoretmp=删除恢复临时文件
Task.createdbuser=创建数据库用户
Task.initdb=初始化组件{0}的数据库
Task.configdb=配置数据库参数
Task.intalldisk=执行安装后数据库脚本
Task.checkDatabaseInUse=正在检查数据库是否在使用...
Task.deleteOldBackupFile=删除旧的备份文件
Task.ExecuteScript=执行存储工具脚本/插件
Task.KillDatabaseProcesses=停止连接所有数据库的连接
Task.DeleteInstanceFiles=删除多余的实例文件
Task.BackupDatabaseCreateXMLs=正在创建数据库XML文件...
Task.BackupDatabaseCollectTableInfo=正在收集表信息...
Task.BackupDatableCreateTableXMLs=正在创建表信息XML文件...
Task.PrepareRestoreDatabase=正在准备恢复数据库...
Task.BackupDatabases=数据库备份 ：
Task.RestoreDatabases=数据库恢复 ：
Task.BackupDatabasesMain=备份数据库总进度
Task.RestoreDatabasesMain=恢复数据库总进度
Task.startprocess=更新服务器进程：{1}
Task.stopprocessbysubsys=更新服务器进程：{1}
Task.instanceAction=更新实例信息
Task.CheckDatabaseSizeAction=检查数据库可用空间
Task.BackupDatabasesAdditional=备份数据库表
Task.RestoreDatabasesAdditional=恢复数据库表
Task.CompareBackupInfos=正在比较备份数据，此操作将会花费一点时间，请稍候...
Task.ExecAddInstanceScript=执行添加实例脚本
Task.ExecPostRestoreDatabaseScript=恢复数据库后执行脚本
Task.ExecPostRestoreFilesScript=恢复子系统文件后执行脚本
Task.ExecPreRestoreDatabaseScript=恢复数据库前执行脚本
Task.ExecPreRestoreFilesScript=恢复子系统文件前执行脚本
Task.KillDBConnection=停止所有数据库的连接
Task.RestoreCheckTablesAction=正在检查空间大小...
Function.CheckDatabaseInUse=检查正在使用的数据库
Function.CompareBackupInfos=正在比较备份数据，此操作将会花费一点时间，请稍候...
Function.DisableArchiveLog=禁用数据库归档日志
Function.EnableArchiveLog=启用数据库归档日志
Function.PostRestore=正在执行后置恢复操作...
Function.PreRestore=正在执行前置恢复操作...
Function.RestoreSubsystemDatabase=恢复数据库
Function.TransferFromRemote=传输备份文件
Function.TransferSubsystemFiles=传送备份子系统配置文件
Function.UncompressData=解压备份文件
[/StorageWorkflow]

[MoveInstance]
Function.InitialMoveInstance=迁移实例初始化中
Function.ExitMoveInstance=迁移实例退出中
Function.MoveInstance=正在迁移实例
Task.FreezeHAServiceGroup=冻结资源组
Task.UnfreezeAndFlushHAServiceGroup=解冻资源组
Task.executeMoveInsPostScript=正在执行迁移后置脚本...
Task.executeMoveInsPreScript=正在执行迁移前置脚本...
Task.modifyInstallSummary=修改全局配置文件
[/MoveInstance]


Task.backupApp=正在备份应用程序...
Task.backupDB=正在备份数据库...
Task.uninstallApp=正在卸载应用程序...
Task.updateDataModel=正在更新数据模型{0}{1}{2}...
Task.upgradeDB=正在更新数据库{0}{1}{2}...
Task.upgradeTables=正在升级表{0}{1}{2}...
Task.upgradeConfigFiles=正在升级配置文件{0}{1}{2}...
Task.backupAppJar=正在备份子系统数据 ...
Task.backupConfigFiles=正在{0}{1}为组件{2}备份配置文件...
Task.backupPatchFiles=正在备份{0}{1}{2}...
Task.copyingJRE=正在复制JRE ...
Task.rollbackDatabase=正在恢复数据库...
Task.uninstallApplicationRollback=正在卸载子系统{0}{1}{2}...
Task.rollbackDataModel=正在恢复数据模型...
Task.rollbackApplication=正在恢复应用程序...
Task.executeScript=正在执行脚本...
Task.rollbackApplicationItems=正在恢复子系统{0}{1}{2}...
Task.copylicense=正在恢复License文件...
Task.updateDynamicDataModel=正在更新数据库实例...
Task.uninstallShortcuts=正在卸载快捷图标，请稍候...
Task.uninstallEnvironment=正在卸载环境变量，请稍候...
Task.createConfig=正在创建配置文件，请稍候...

Function.transferInstanceFile=正在传输实例文件...
Function.transferProcessFile=正在传输进程文件...
Task.stopProcessOnSrcNode=正在停源节点此实例进程...

Task.modifyDataModel=正在修改数据模型...
Task.startProcessOnDestNode=正在启动目标节点此实例进程...
Task.deletesubsystem=正在删除子系统...
Task.postUnInstallScript=正在执行卸载子系统前置脚本...
Task.preUnInstallScript=正在执行卸载子系统后置脚本...
Task.autorollbackApplication=正在升级，请稍候...
Task.doAutoRollbackItemenv=正在升级，请稍候...
Task.AutoRollbackDatabase=正在升级，请稍候...
Task.ConnectDB=正在连接数据库...
Task.DeployCreateProchandle=正在创建实例句柄...
Task.DeployconnectDB=正在连接数据库...
Task.StorePatchInfo=存储补丁备份信息和版本信息
Task.replaceFileMacro_patch=正在为子系统 {0} 配置文件执行宏替换...
Task.PackageExecuteScripts=正在为子系统 {0} 执行补丁安装脚本...
Task.PatchRollbackdatamodel=恢复数据模型
Task.PrunUninstallScript=正在为子系统 {0} 执行补丁安装脚本...
Task.rollbackPatchFiles=回滚补丁安装对 {0}{1}{2}，正在备份文件...
Task.UninstallScripts=执行配置在Installdisk.xml中的卸载脚本
Task.UninstallPostScripts=执行配置在Installdisk.xml中的卸载后置脚本
Task.StorePatchInfoTofile=保存补丁备份信息到patchBackupInfo.xml文件
Task.DeployStartinstanceprocess=正在注册实例进程...
Task.updateDataModelsync=同步数据模型
Task.postInstallClientScript=执行安装client后置脚本
Task.InitDataModelDBInfo=正在刷新数据库模型中数据库信息...
Function.PreBackupDB=正在执行备份前置脚本，请稍候...
Function.PostBackupDB=正在执行备份后置脚本，请稍候...
Function.PreBackupConfigFile=正在执行备份配置文件前置脚本，请稍候...
Function.PostBackupConfigFile=正在执行备份配置文件后置脚本，请稍候...
Function.PreBackupApplication=正在执行备份应用程序前置脚本，请稍候...
Function.PostBackupApplication=正在执行备份应用程序后置脚本，请稍候...
Function.PreUninstallApplication=正在执行卸载应用程序前置脚本，请稍候...
Function.PostUninstallApplication=正在执行卸载应用程序后置脚本，请稍候...
Function.PreInstallClient=正在执行安装客户端前置脚本，请稍候...
Function.PostInstallClient=正在执行安装客户端后置脚本，请稍候...
Function.PreUpgradeScript=正在执行升级前置脚本，请稍候...
Function.PostUpgradeScript=正在执行升级后置脚本，请稍候...
Function.PreInstallNew=正在执行新增安装前置脚本，请稍候...
Function.PostInstallNew=正在执行新增安装后置脚本，请稍候...
Function.PreRollbackUninstallNMS=正在执行卸载应用程序前置脚本，请稍候...
Function.PostRollbackUninstallNMS=正在执行卸载应用程序后置脚本，请稍候...
Function.PreRollbackApplication=正在执行回滚应用程序前置脚本，请稍候...
Function.PostRollbackApplication=正在执行回滚应用程序后置脚本，请稍候...
Function.PreRestoreDB=正在执行恢复数据库前置脚本，请稍候...
Function.PostRestoreDB=正在执行恢复数据库后置脚本，请稍候...
Function.PreRestoreApplciation=正在执行恢复应用程序前置脚本，请稍候...
Function.PostRestoreApplciation=正在执行恢复应用程序后置脚本，请稍候...
Function.UpgradeFinish=正在执行升级结束脚本，请稍候...
Function.UpgradeAfterActionTask=删除数据冗余信息
Function.autoExportCMD=正在执行导入命令字...
Task.InitPluginMgrTableWhenInstall=正在执行插件脚本...
Task.AddDeploymentInfoTask=正在添加部署信息文件中的实例数据库信息...
Task.ExecHedExLoadTask=正在执行HeDex配置操作...
Task.CreateProcessForUpgradeTask=正在生成进程描述文件...
pre=前置升级脚本
post=后置升级脚本
Task.ReconfigDBAutoIncreaseForUpgrade=配置网管数据库自增长属性
Task.CopyEngineeringTask=生成网络管理系统维护工具客户端
Function.PostAutoRollbackApplication=执行后置回滚脚本，请稍候...
Function.executeCauScripts=正在执行CAU重整脚本...
Function.isCauFinished=CAU重整没有结束，请稍候...
Function.ModifySybaseDeivce=修改网管数据库属性
Function.InitInstallData=初始化安装数据...
Function.UninstallNMSEnv=正在卸载快捷方式、环境变量和注册表信息，请稍候...
Function.RollbackUninstallNMS=正在卸载当前网管，请稍候...
Function.RollbackApplicaion=正在恢复网管，请稍候...
Function.RestoreNMSEnv=正在恢复快捷方式、环境变量和注册表信息，请稍候...
Function.RollbackDBTask=正在恢复数据库，请稍候...
Function.DoAutoRollbackOnUpgradeFail=正在准备升级...
Function.RollbackFinish=正在执行回滚脚本，请稍候...
Function.PreSubSystemUpgrade=执行子系统升级前置脚本
Function.PostSubSystemUpgrade=执行子系统升级后置脚本
Task.UninstallScriptsTask=正在执行子系统卸载脚本...
Task.CreateDatabaseInterface=创建数据库interface文件
Task.PreInitInstall=执行工程安装前置脚本
Task.ConfigNICIP=初始化配置文件NIC
Function.ModifyPermissionForOSS=修改网管目录权限
Function.AddNode_Master=正在主节点执行添加节点操作...
Task.RestoreDatamodelTask=正在重置数据...
Task.GlobalPreAddNodeScript=在{0}上执行添加节点前置脚本
Task.SyncNodeNMSFiles=从{0}传输网管文件到新节点
Task.PostSyncNodeNMSFiles=在{0}上执行传输网管文件后执动作
Task.GlobalPostAddNodeScript=在{0}上执行添加节点后置脚本
Task.ExitInstallScript=在{0}上执行全局退出脚本
Task.DeleteSubsystem=正在删除组件...
Task.PostDBScript=执行{0}{1}{2}，执行后置数据库脚本
Function.AddInstance=正在添加实例...
Function.AddNode_SubNode=正在解压网管文件...
Function.GlobalPostAddNode=正在执行添加节点后置脚本...
Function.GlobalPreAddNode=正在执行添加节点前置脚本...
Function.InitAddInstanceData=正在初始化实例{1}...
Function.ExitAddNode=正在添加节点...
Function.ExitAddInstance=正在添加实例{1}...
Function.PreDeleteInstance=正在执行删除实例前置操作...
Function.DeleteInstance=正在执行删除实例...
Function.PostDeleteInstance=正在执行删除实例后置操作...
Function.PatchBackup=正在备份补丁文件...
Function.PrePackageExecuteScripts=正在执行删除实例后置操作...
Function.PostPackageExecuteScripts=正在执行组件包后置脚本操作...
Function.PostPatchInstall=正在执行补丁后置操作...
Function.PrePatchRollBack=正在执行补丁回滚前置操作...
Function.PatchRollBack=正在补丁回滚...
Function.PreDeleteComponent=正在执行删除组件后置操作...
Function.PostDeleteComponent=正在执行删除组件前置操作...
Function.TransferPatchFiles=正在传输补丁文件...
Function.PrePatchInstall=正在执行补丁前置操作...
Task.PrePatchBackupDB=正在{0}上执行备份补丁数据库前置操作...
Task.PatchbackupDatabase=正在{0}上执行备份补丁数据库...
Task.PostPatchBackupDB=正在{0}上执行备份补丁数据库后置操作...
Task.PreBackupApplication=正在{0}上执行备份补丁前置操作...
Task.PatchBackupApplication=正在{0}上备份网管文件...
Task.PostBackupApplication=正在{0}上执行备份网管文件后置操作...
Task.PrePatchRollBackDB=正在{0}上执行备份补丁数据库回滚前置操作...
Task.PatchRollBackDB=正在{0}上回滚数据库...
Task.PostPatchRollBackDB=正在{0}上执行回滚数据库后置操作...
Task.PrePatchRollBackApplication=正在{0}上执行回滚数据库后置操作...
Task.PatchRollBackApplication=正在{0}上备份回滚网管文件...
Task.PostPatchRollBackApplication=正在{0}上执行备份回滚网管文件后置操作...
Function.PostPatchRollBack=正在{0}上执行补丁回滚的后置操作...
Function.addInstance=正在添加{1}实例...
Task.CreateDBUser=正在创建数据库普通用户...
Task.UpdateSysconfigureForNMS=正在{0}上更新系统配置文件...

Function.InitDeleteNodeData=正在初始化删除节点数据...
Task.GlobalPreDelNode=正在执行删除节点前置操作...
Task.DelNode_SubNode=正在删除从服务器...
Task.DelNode_Master=正在删除节点配置信息...
Task.DelEngrSubNode=正在删除数据模型中节点信息...
Task.GlobalPostDelNode=正在执行删除节点后置操作...

PACKAGE_FILE=软件包
COMPONENT=组件
ProgressPage.InitDatamodel=初始化数据模型，请稍候...
ProgressPage.CreateJob=创建工作，请稍候...
INSTALL=安装
UNCOMPRESS=解压缩
Function.deployAddComponentInstance=部署组件的实例，请稍候...
Task.QueryAllInformation=查询部署信息
Task.AddComponentDataModel=安装{0}{1}{2}，添加组件到数据模型
Task.OracleInstall=安装Oracle数据库...
Task.AddServiceToImapConfigFile=添加实例进程服务到IMAP数据库
Function.addComponentInstance=创建 {0} 的组件实例
Task.deletecomponent=正在删除组件...
Task.PreDeployInstanceSendMsg=正在发送信息...
Task.PostDeployInstanceSendMsg=正在发送信息...
Task.PostDeleteDataScript=删除临时表的信息
Task.ChmodUserTask=给新文件添加权限
Task.PreDeployScript=在{0}{1}上预初始化部署{2}
Function.Adjustdeploypackage=正在执行部署调整
Task.Adjustdeploypackage=在{0}{1}上调整部署{2}
Task.CreateImapServiceExForNMS=创建imapservice_svc_ex.xml文件...

Function.PreunDeployByDomain=正在服务器{0}上执行按域去部署前置操作，请稍候... 
Function.GlobalPreUndeploy=正在服务器{0}上执行按域去部署全局前置脚本，请稍候... 
Function.UndeployByDomain=正在服务器{0}上执行按域去部署，请稍候...
Function.GlobalPostUndeploy=正在服务器{0}上执行按域去部署全局后置脚本，请稍候...
Function.postUndeployByDomain=正在服务器{0}上执行按域去部署后置操作，请稍候...

Function.preDeployByDomain=正在服务器{0}上执行按域部署前置操作，请稍候...
Function.GlobalPreDeploy=正在服务器{0}上执行按域部署全局前置脚本，请稍候...
Function.PreDeployScript=正在服务器{0}上执行按域部署前置脚本，请稍候...
Function.InitDeploypackage=正在服务器{0}上执行按域部署，请稍候...
Function.GlobalPostDeploy=正在服务器{0}上执行按域部署全局后置脚本，请稍候...
Function.PostDeployByDomain=正在服务器{0}上执行按域部署全局后置操作，请稍候...
Task.CopyEngrFilesAction=拷贝工程文件到网管目录中
Function.PublicOperation=清理过程数据文件
Task.PublicOperation=清理过程数据文件...
Function.Unzip=正在解压...