Summary.Hint = 信息
Summary.Title = 确认卸载
Summary.BaseInfomatin = [基本信息]
Summary.InstallPath = 安装路径： 
Summary.DiskSpaceNotEnough = "{0}"磁盘空间不足。
Summary.DiskSpaceNotEnoughCMD = 磁盘空间不足。
Summary.ActualDiskSpace = 可用磁盘空间： 
Summary.NeededDiskSpace = 需要磁盘空间： 
Summary.OSVersion = 操作系统版本： 
Summary.DatabaseType = 数据库类型： 
Summary.DatabaseVersion = 数据库版本： 
Summary.ProductVersion = 产品版本： 
Summary.Exception =  创建数据库时产生异常。
Summary.PackageInfomation = [组件信息]
Summary.SetupMode = 安装模式
Summary.SelectedPackages = 安装组件： 

Summary.Confirm = 确认安装参数。单击 <下一步> 开始安装。\n单击 <上一步> 修改安装参数。

Summary.MemoryNotEnough = 内存不足。
Summary.ActualMemorySize = 物理内存： 
Summary.NeededMemorySize = 需要内存： 
Summary.MemorySizeNOTSET = 未定义
Summary.OSType = 操作系统类型： 
Summary.Cancel = 退出安装
Summary.Previous = 上一步
Summary.UsedState = 使用状态： 
Summary.isCreateShotcutOnDesk = 是否在桌面创建快捷方式？
Summary.SubsystemInfomation =[卸载组件]：
Summary.NoSubsystems =没有组件可被卸载。
Summary.NoSubsystemsPrompt =没有组件可被卸载。卸载过程将退出。
UninstallSummary.EnvironmentError=安装环境异常，请检查
Summary.AreYouSureToContinue = 开始卸载，确定是否继续？
Summary.DBConnectFail=无法连接数据库，请确认数据库是否已经正确启动。
Summary.NotLocalIP=非本地IP，请检查 server/etc/conf/sysconfigure.xml 文件。