UninstallClient.Title = 卸载客户端
UninstallClient.AreYouSureToContinue = 将开始卸载客户端，确定继续吗？
UninstallClient.Finish = 完成
UninstallClient.Hint = 提示
UninstallClienter.UninstallClient = 卸载客户端已完成。
UninstallClienter.Note = {0} 成功卸载。 \n单击<完成>完成卸载。
UninstallClienter.RestartTip = 在您完成此向导后需要重新启动操作系统。
UninstallClient.AffirmRestart = 现在就重启操作系统吗？
UninstallClient.ClearDirConfirm = 为了不影响您的下一次安装，请手工删除安装目录。
UninstallClient.Warn = 警告
UninstallClient.ClearDirConfirmDetail = 以下文件和目录需要手工删除：
UninstallClient.DelEnv = 删除环境变量
UninstallClient.DeleteShortcuts = 删除快捷方式
UninstallClient.DeleteRigisters = 删除注册表
UninstallClient.DeleteFiles = 删除文件
UninstallClient.Completed = 完成

