UninstallService.RemotePrograme = (远程进程)
UninstallService.DatabaseName = 数据库名： 
UninstallService.ProcessName = 进程名： 
UninstallService.UserName = 用户名： 
UninstallService.DBIsOnline = 数据库正被使用，请手动关闭所有进程，\n 或手动重启数据库服务。
UninstallService.DBConnectionError= 数据库连接错误。请检查数据库服务是否正在运行。
UninstallService.LoginFailed= 登录以下服务器失败。请检测网络连接。
NODEINFO_DATAMODEL_FAIL=数据模型中没有该服务器的信息。
CHECK_LOG=请根据日志获取详细信息。
UninstallService.NMSAlives=网管进程正在运行，请先执行关闭网管的操作。
UninstallService.NMSAlivesDetail=网管正在运行的服务器IP如下：
UninstallService.DropDBFailed=删除网管数据库失败。
