Task.PreUninstallScripts=执行卸载前置脚本
Task.PostUninstallScripts=执行卸载的后置脚本
Task.UninstallDB=卸载数据库
Task.UninstallEnv=删除环境变量
Task.UninstallShortcuts=删除快捷方式
Task.UninstallRegistery=删除注册信息
Task.UninstallFiles=卸载应用
Task.UninstallPreScripts=执行卸载前置脚本
Task.UninstallScripts=执行卸载脚本
Task.UninstallPostScripts=执行卸载后置脚本
Task.UninstallService=删除服务

