ExitPage.Title=卸载完成
ExitPage.Finish=结束
ExitPage.Note={0}已成功卸载。\n单击 <完成> 完成卸载。

ExitPage.AffirmRestart=确认重启操作系统吗？
ExitPage.Hint=提示
ExitPage.RestartTip=请重新启动操作系统。
ExitPage.NoteCMD={0}已成功卸载。
ExitPage.CONFIRM=确认
ExitPage.ErrorNote={0}卸载失败，具体信息请查看日志 {1}。
ExitPage.ErrorTitle=卸载失败
ExitPage.NoteTip=\n\n提示：
ExitPage.NoteMsg=\n{0} 部分文件未删除，系统重启后会自动删除。