UninstallProgress.InstallTitle=正在安装，请稍候...
UninstallProgress.UninstallTitle=正在卸载，请稍候...
ProgressPage.Title = 正在卸载
ProgressPage.UninstallTitle=正在卸载
ProgressPage.InstallTitle=正在安装
ProgressPage.AreYouSureToContinue=将开始卸载，请确认是否继续？
UninstallProgress.failedmsg=卸载过程中执行任务失败。
