UPgrade.ConfigParas.CurrentVersion= 当前版本：
UPgrade.ConfigParas.SourceListLabel= 源版本：
UPgrade.ConfigParas.SourceList.OK=确定
UPgrade.ConfigParas.SourceList.Cancel=取消
UPgrade.ConfigParas.SourceListTitle=版本列表
UPgrade.sourceVersionDes= 源版本中不存在当前的{domain}版本，请选择源版本。