/* XPM */
static char * iManager-N2000_pm[] = {
"124 108 66 1",
" 	c #3C3C6A6A8C8C",
".	c #44446E6E9494",
"X	c #3C3C6E6E9494",
"o	c #3C3C6E6E8C8C",
"O	c #44446E6E8C8C",
"+	c #3C3C6A6A9494",
"@	c #44446A6A8C8C",
"#	c #3C3C66668C8C",
"$	c #3C3C66668484",
"%	c #34345A5A7C7C",
"&	c #2C2C56567474",
"*	c #343456567C7C",
"=	c #2C2C5A5A7C7C",
"-	c #34345E5E8484",
";	c #444472729494",
":	c #4C4C76769C9C",
">	c #4C4C76769494",
",	c #343462628484",
"<	c #2C2C52527474",
"1	c #24244E4E6C6C",
"2	c #3C3C62628484",
"3	c #4C4C6E6E8C8C",
"4	c #54547E7E9C9C",
"5	c #2C2C4E4E6C6C",
"6	c #2C2C56567C7C",
"7	c #34345E5E7C7C",
"8	c #64648282A4A4",
"9	c #5C5C82829C9C",
"0	c #2C2C5E5E8484",
"q	c #6C6C8E8EACAC",
"w	c #4C4C7A7A9C9C",
"e	c #54547A7A9494",
"r	c #74749292ACAC",
"t	c #54547A7A9C9C",
"y	c #6C6C9292ACAC",
"u	c #2C2C52526C6C",
"i	c #2C2C5E5E7C7C",
"p	c #6C6C8A8AA4A4",
"a	c #64648A8AA4A4",
"s	c #5C5C7E7E9C9C",
"d	c #444476769494",
"f	c #4C4C72729494",
"g	c #545476769494",
"h	c #5C5C8282A4A4",
"j	c #64648686A4A4",
"k	c #343462628C8C",
"l	c #64648A8AACAC",
"z	c #5C5C8686A4A4",
"x	c #444472728C8C",
"c	c #6C6C8E8EA4A4",
"v	c #343466668C8C",
"b	c #242452527474",
"n	c #4C4C72728C8C",
"m	c #64648E8EACAC",
"M	c #5C5C86869C9C",
"N	c #646486869C9C",
"B	c #74749696ACAC",
"V	c #64648E8EA4A4",
"C	c #545482829C9C",
"Z	c #5C5C7E7EA4A4",
"A	c #343466668484",
"S	c #242456567C7C",
"D	c #7C7C9A9AB4B4",
"F	c #1C1C4A4A6C6C",
"G	c #444466668C8C",
"H	c #74749696B4B4",
" .Xo.X . .Xo.oX.XOXXOX.oX.XXOX.o+.+X@o.oX.o.+o.oX.X.Xo.X@Xo.X.Xo.X@X@o+. .+O+. X@X@X+O+. .+X@X .+O+o.XOXo.XOXX.o.o.X.o.oX.X.",
"X. . .XXX. . . X@X@X+O+. X@X+X@XOXOXo.+. . XOX+. X@X@X@XXO+o@X@X+OXXOX.oXOXXOX.oX.X.oX.oXOXOX.oXOX.X+O+. X@X@X . X@X+O+. X@X",
"@oXOXX@X@oX.XX.o.XXOX.oXOXo.o.oX@X .+OXo.Xo.+OXo.o.oXOXX@X.X.XXo.o+O+X@X@X+O+X . X@o+. . .+X@X+O+X@XOXo.o.XXOX.XX.oXOXXOXOXX",
"X.+X@XX.o. X@X@X . X@X+. . X@X@XX.XOXX@X .+o.X@X@X+O+X@XXo@X . .+o.XOXoX.o.X.o.X.XOX.oX.Xo.o.o.X.oXO+O+X@X@X+o@X@X+O+. X@X@X",
"@X.o.X@o+.XOX.oX.o.X.o.o.XX.XXX. X@X .X.Xo.X@XX.XXOX.oXO+.oX.o.Xo.+O+O+. X@o . X@o+O+X@X . .+X@o+. .XX.o.Xo.o.Xo.o.X.oX.XXOX",
"Xo@X+OX.oX@X .+O X@o+. X@X@X@X@X.XOX.o@X@X+o.o@X@X+O+. XOX@X@X+O+o.XoX.o.XX.XX.XX.X.o.o.X.Xo.oX.oXOX@X@X+O+X@X@X+O+o@X@X@X+O",
" .XXOX+O+OXX.oX.X.XX.oX.Xo.oXOXX@o+. XX.XOXO+o.Xo.o.Xo.X@XX.Xo.o.X . . X@X@X@X@X@X@o+O+X@o+O+. . .+oXOXXOXOXXOXXOX.o.XXOXXOX",
"XO+O+OXXX. . . X@X@X@X@X@X+. X@Xo.oX.o@X X@X.X .+o+O+. X.o@X@X+O+OXX.X.Xo.oXXOXo.oX.XX.oXOXXOXX.Xo.X@X@X+O+O+X@X+O+X@X@X@X+O",
"@Xo.XX@X@oXOXX.o.oX.XXOXXOXOX.X. .+O+.o.X.XX@o.o.o.Xo.XO+o.XXOX.XX@X@o+O+X@X@X .+X@X@X .+.+O+X@o .+OXXXOX.oX.o.o.XOX.oX.Xo.X",
"X. X@XX.o.+X@X@X+O+o@X+O+X . o@XXOXo.o+o@X@XX.+o+. .+o@X.X . . X@XXOXXOXOXXOX.XOXOXOXOXo.oX.XOX.X.oX@X@X .+O+X@X .+o@X@X@X@X",
"@X.XOX@o+.XOXOXo.XOX.X.XOXOXX.XX@X+. .X.Xo.X@XOX.oXOX.XX@o.X.XXOX. . . .+X@X+O X@X+X@X .+X@o . X@o+OXOXX.oX.XOXX.oX.XX.oX.oX",
"Xo@X+.o.Xo@X+. .+o+O+o@X .+o@X@X.o.oXo@X@X .Xo+O+. X@X@XXO+o@X@X+OXXOXXOXOXOXX.XXOXOX.XOXOX.XX.XX.XX+. . . X@X@X@X@X@X . .+O",
" .Xo.o+. .o.XOXo.o.oX.oX.Xo.XOXX@X .+.XX.XOX@XOXXOX.Xo.X@XX.Xo.XOX+O+X@X . X@X@X@X@X X@X . X@X@X@X@o.oXOXX.o.XXOXX.oXOX.Xo.X",
"XO+. .oX.o+O X@X+O+.+O+O+O+O+X@Xo.Xo.o@X .+XXO+. X@X@X+OXX@X@X+O+OX.o.o.XX.XX.Xo.XX.X.o.XX.XXOXo.oX.+O+X@X@X . X@X .+. X@X@X",
"@Xo.XX+O+o.XX.XOX.Xo.oX.XX.XXOXO+. . XOX.XOX@Xo.o.Xo.XOX OooXOX.XX@X+O+X@X@X@X . X@X@o+X@X@X@X .+X@XoX.oX.oX.o.XOX.o.oXOX.oX",
"X.+o@XOX.X@X@X . X@X+O+o@X@X@X+OXo.X.X+O+o+.o.+X@X@X OX..X.XO+o@XOXOXXOXXOXo.o.X.o.oX.XOXXOXX.XOXOXO+O+O+O+O+X@X+O+X@X@X .+O",
" .o.o.+X@oXOXX.XXOXOX.X.Xo.oXXOX+O+X@o.o.XOX+OXOXXOX.XX  #$@XOX X.o+. .X@X .+X@X .+X@X@X O+X@o@X . XOXX.XXOXXOXo.o.o.XX.Xo.X",
".o+O+o.oX. X@X@X@X+O+o@X@X+O+O+o.XOXo.+o+O+OXX@X@X+OXO#%&*=-#;:>oX.oX.o+OX.o.oXOXo.oXo.X.X.o.XX.XX.X+O+o@X+O+. .+o+. X@X@X@X",
"+X.XX. .+OX.Xo.oXXOXX.Xo.o.X.XX. . X@XOX.oX. .XX.o.o@,<1<=-%-2344O+@X@X.oX@X . .+. .+. X@X . X@X@X@o.o.X.o.Xo.XXOX.oXOXOXXOX",
".o@X@XX.oX@X@X+O+O+o@X@X+O+o@X@Xo.X.XX+O+. X.o@X+OX.,5567====6=#89o.XXO+.+o.XX.oXOXo.o.XXOXX.XX.oXOX+O+o@X+O+o@X . .+O+X@X+O",
" X.oXX@o+.Xo.XOX.XX.XOXo.X.XOXo.+. X@o.Xo.X. XOXOX. &560-=%=%=-6$qw@X@XoXOXX@X@X@X+. X@X@X@X@X@o+.+o.XX.oXOX.XX.o.XXOXXOXOXX",
".o+. .XXOX@X+O+o@X@X .+O+o@X+O+OXo.Xo. O+o@X.X+O+OX,5<=%===%===-=eqX.o.+O+O+XOXX.o.o.XX.oX.oX.oXOXOX@X@X+O+o@X@X+O+O+O+X@X@X",
" XOXOX O+.oXOXX.Xo.X.oX.X.Xo.XOX .+O+X.XX.XX@o.oX.X%16%0=%===%=%=@r>X.o.oXXOXX@X@X .+X@o+. X@o+O+O+XXOXo.o.X.oX.o.oXOXXOXXOX",
"X. X@X.XXO+.+o@X@X . . o@X@X@X+.Xo.XOX@X@X@Xo.+X@XO75<=%===%====6$qt .o+. .+O+.oX.X.o.o.XOX.X.X.XXOX@X+O+X@X . X+O+.+X@X@X+O",
"@XX.XX@X@XOXo.X.oX.oX.X.XOX.XXOX@X . XOXOXo.+OXOX.;71&0%=%===%=%=#y4 .X.o.Xo.oXX@X@o+O+X@X . X@o+O+OXXOX.OXo.X.o.o.oXOXOXXOX",
"Xo@X@Xo.oX+O+o@X+O+. X@X+o+o@X+OXOXXOX X+O+XOX X OX#u&%====%===-=Or:o.o@X+OXXOXOXXo.XXOXXOXo.Xo.oXOX .+o+X . o+O+X . X@X+O+o",
"..o.X.X.XO.X.X.XOXOXOXOXOX..XOX.X.XOX.X.OX.o.X..X..o%5=70%0=-=%i%9pX..X.XOX.o..XXO.X.o.XOX.X.o.X.X.X.XO.XO.X..X.XO.X.X.XOX..",
"Xo.Xo@X+O+Xo.o.XX.XX.XX.X.oXOX.o+O+. XOXX.o.+OXo.oX. &<i%=%=%=-6Oq>X.X.oX.+O+X .@XX. .+O+. .+. . . .XOXX.Xo.oX.o.Xo.o.XOX.o+",
".+O+.XOXX.o. X@X@X@X@X@X@o+O+. XOXXOX. X@o+XOXo.X..oX 7&=%====%OatX@o.o.X.o.o..oXX@o.XoX.oXOXo.XXOX O+X@X .+X@o+. .+X@o+. X.",
"XOXoX@X@X .+.XX.oX.oXOXXOX.Xo.o.+. X@XX.X.XO+..O # ... #,---,@>s:OXOX;X  OX.+o..XOXX .+O+. X@X . X.X.XOXOXOXOX.Xo.o.oX.o.X. ",
"O+.+OXXOX.o.oX@o+. X@X+O+X@X@X+.Xo.o.X@X@X@X; ,&&6,#Oww. . O;>d;+.X.X#%*=-#fw;X@XX@X.o.oXo.X.o.X. X@X . X@X . X@X@X .+O+X@oX",
"XoXOX@X+O+X .+OXOXOX.o.XOXo.XOXo@X+. XOXoXo. %5<6%%%-#ghd+..OXO+o@X %5<6%%--.s4XO.oX@X+O+. X@X .o.XXOXX.XX.XX.XOXX.X.oX.oX. ",
"O+O+X.o.o.o.Xo.X+O+X@X . X@X . .XOXOX.o+.o..%1<==-==6=-ga>oXX .X.o@=5<=%=0=%=$jhoX.OXXOX.oXOXX. X@X@X@X@X@X@X@o+X@X@o+. . .X",
"X.XOX .+o+. .+o@XX.oX.o.X.X.oX.o+. X@X.Xo..ku1*-=%=%0%==sl.@X.o+OX-1<6%=%=%0=6@qt X.o.+o+O+. .o.XXOXXOXo.oXOXX.o.oXOX.oX.Xo@",
"X@X .XXOX.oXOX.o.X@X@X+. X@o+. XOXX.XX@o.X &56===%==%=-6$p4XO+o.X25<6-=%0%=%%=6>q: X.o.o.XXOX .+o@X+O+X@X+O+X@X@X+O+X@X@X .X",
".oX.o@X+O+. X@X+O XOXOXo.Xo.XOX.+o@X@XXOX@%1<=%0*=%===%0=9aOX.o. &16=%======0%=-9j;+OX+O+O+X.XOX.X.o.o.X.o.XOXX.XOX.oX.XOXO+",
"o+. .Xo.oXOX.Xo.XX.X X@X+O+. X@Xo.XOXX@X.,1<6%====0==%=%=ea.X .X%5<=%=6-=6-=%==6#as .o.Xo.X@o . X@o+O+X@o+O+X@X@o+O+X@X . X.",
"XOXX. .+O+X@X@X@X@X@X.XOX.oX.oXO+O X@X.o#<560%=%==%=%==-=4p.oXO,51=%==%==%====%==3qw .+O+XOX.XX.XX.XXOXXOXXOXOXX.X.o.o.XX.X ",
"O+X@oX.oX.o.oX.Xo.oX.X . X . .+.XXX.Xo. *16=*0==*0====0%=jz.@X <56%=%===%=60%=%%==sa; OXXOX X@X@X@X@o+. .+O+O+X@X@o+O+X@X@o.",
".XOX. X@X@X+O+o@X+. X@XX.XOXXOXo@X@X@X.-15%==%===%=%=%%6xq> X@%1<%====%===%==0==-6,j9X@XO+.X.Xo.oX.o.Xo.oX.oX.o.oX.Xo.oXo.X ",
"X .+o.XOXXo.o.X.o.o.XOXO+O+X@X .o.XXo.#55==-===-=====762asXo.-1<==%==%===%===%=%=-6 qt+OXOX@o+O+X@X+O+O+X@X+O+O+X@X@X+O+. X.",
".oXOX@X+O+. X@o+. X@o+O+o.o.XOX.+o@X. &1<%===%==%=%=%=i9l. .$516=%==%==%===%06===--=ga; .XXo.XOXOXOXXXOXOXOX.oXOXXOXOXX.o.o+",
"X .+.oXOX.oX.XX.oX.XX.XX.o+. X@Xo.o.X-1<%==%60=%====06>q> .+&16%===%=-$7==%===%=%=%=7jz.XO .X@X+O+X@X@X+O+X@X+.+O+O+X@X@X .X",
"X.oXO+. X@X@X@X@X@X@X@X@X@Xo.XXO+o.o255==-6=%====%=%=$p4 .X75<%=%=%=7e3&-===%=06===-6#q4+.X. XOXXOXXOXOXX.o.o.oX.XXOX.oX.XX@",
". X@XXOX.oX.oX.XXOXo.Xo.Xo.X@X@X.o.#<16%==%=0==%==%=78z.X.215====%==fc21%=%====%0%=%=6fp>X@oX.X@X+O+O+X@X@X .+X@o+O+O+X@X@o.",
".XOX. X@X@X . X@X+O+X@X .+o+.o.o+.O%1<%=%===%=%==7==ta;@X u5&=%====2p4v&<==%=%======-==9a.X. X@XOX.oX.o.oX.Xo.o.XOXX.o.oX.o+",
"X .+oXOXX.o.X.o.XOX.o.o.XOX.oX+o.o-1<%0==6-======-6Opt XO=5<=-==%=-9a..,<=%====%=-==%==2ah@o.o.XX@X+O+O+X@X@X@X+O+X@o+O+. X.",
".oXOX@X@o+. X@X+O+X@X+O+o+. .o.X.#<1%=%=%==%=%=%-=,ah.X.,ub=%==-==gq;o.o%5=0%======%6%-6.qw .X . XOX.oX.oXOXX.XOXXOX.XXOX.o+",
"X .+.XXX.XOX.oXOXXOXo.XOX.oXO+o. &56=%===-=====%==sa; O <56%==%=&@qwo..X &<%0%==%=%=0==-6sa;+OXOX.X@X+O+O+X@X@o+O+O+X@o+O+o.",
".XOXo@X@X@X+O+. . . . X . . X..X%1<=-=%0===%==-i6np: .o*1<===%==2jh ..o..$<&%=%===0*=%=%=-jho+.X . XOXX.X.oXXOX.XX.o.o.Xo.o+",
"X@X .o.XXX.o.oX.oX.XXOX.oX.X.oX$55=%=====%===%=6$msXX.-1<=%==%i%4a.XOX@Xo.,5=%0=%=%=====-= qto.o.oX.X@X@o . . X@X@o+O+X@X+.X",
"Xo.X.+o@X@X+O+O+. X@X+O+. X@X. &16%=%=%=%==%0%=-9j.o.$<5=%==706ny:o.XXXO+.O=u=-====-=%==--6gq;XO.X@X .oX.XX.o.XXOX.Xo.OXOXX@",
"X@X@oo.o.Xo.Xo.oXOXo.o.oXOXOX.-1<%==========%==>c: ;X71&=-==%6$q4 .X@X@X.oX#<&%==%===0=%===%MjXXXOXo.oX@X@o+o+O X X@X+o+X@oX",
".X.X.X.XOX.o.X.X.X..X.X.X.X.X@&5&=%=-=-=%=%=06@c4 ;..71*7==-=-Nz.@XOXOXOX..;,56i%==%==%=%=-=frf..XOX.X.X.X.o..X.X.OXO.X.OXO.",
"+o.o.+O+X@X+O+X@X@oXX@X@X@Xo. &56%=%===%===%=7j8XXOXO#<<0-=%=>qfoX.XX.X. XOXo%<%==%==%=%===6@B>Xo.+. X@Xo.X.XX.o.oX.Xo.oX.XX",
"X. X@oXOX.o.XOXOXX. .oX.oXO+.o%16===%====%=-=sl;O..+.o2&==%=.cw .o@X@X .XO+.; &<7==%====%=%=@Bw+.oX.X.o.+o@X@X .+. X@X+. X@X",
"@XX.XX.+O+X@X .+X@XOX+O+X@X.o.#u&=%===%=%=76OVt X.oXO.X+2$$nsw.X.XOXo.XO+XXOX.,<6%==%=%=====fyf .X@o+O+o.XOXo.XOXo.o.o.o.o.X",
".o@X@X@XXOXo.Xo.o.o+.o.o.Xo+.@X%1%==%===i-=2aho. .+O+XOX.o+;.o. .o+. . XOX@X+O;7u=-=====%=%=9jX.o.o.XXOX@X+O+X@X+. X+. X@X .",
"+o.oX.Xo.+O+X@X@X X.o+O+X@X.oX. %<=%===%%=isa. X.o.Xo.XOX.XX@XOX .Xo.Xo.+OXo.X. 6b%=%%=%0%6fq:OXOX+O+O+.oXOX.o.o.o.o.oX.Xo.X",
".X+O+o@X .X.o.XX.XO+.oX.oXO+O+o. -%==%===-el>+. .+o@X+O+.o.. .X.X. . .+OXX@X .+x %&======%;aw@X. .oX.oXO+.+o+. X@X+. X@X@X@X",
" XOX.oX.XOX . X@X@XoX@X@X@XX.X. .o 2,,,2@t4;@XOX.o.X.o.Xo.+o.X@X@oX.Xo.X+OX.Xo.X.@$,7-7- gs>OXOX.o+O+O+.Xo.o.oX.Xo.oX.o.XXOX",
".o+O+. . X@Xo.XOXX.+OXX.XXO+o@XX.X.o@X@.;;;XXO+o+. X@X .+o.X+OXXX. X@X .oX@X@XO+XOX   @;>;;XO+. X.XXo.Xo@X+O+. . . . . X@X+O",
"+.o.Xo.oX.X.X+O+X@o.XX@oX@XOXXo. X@X.XOX.  @XOX.o.o.oX.o.X@o.X@X@o.XOX.o+.Xo.+oXOX.O.X...O+ .Xo.X . .o+.o.o.Xo.oX.XXOXXOXOXX",
"Xo+. .+O+o@X@X.o.o. .XO..o.X.o.XOX.o.o.XOX.oXo.o.Xo.XOXoXoo.oXo.XO+oXOX.oX@Xo.X.oXoXX@X XXOXo+. OXoXOXOX+O+X@X+. X@X+O+X@X@X",
"@X.oXOXXOX.oXOX+O+XXO+  X .XO..o.X@X.XOX..o....X...Xo......X...o+X;..X...OXOX..o....OXOX;OX...oX;...X.X.OXXOXOXOXOX.o.o.XXOX",
"XO+. X@X+O+. X@XXOX@X>h4XOX X+o+OXXo + X X. v +  vo.+#vv#+ +v +.o@v +  v .X.   X vv#+X. vX v X. vv#o + +XO+X@X . X@X+O+o@X+.",
"+OXo.X.o.XXo.X.o.+OXofer8o:4444wX .OtC4s4>X>wt449w. ;444:;d494o.X;:t44h4.oXO;:44Z44t;@o>ttzt. O:44w.;tCf .o.XX.XX.Xo.XX.o.o.",
"X.+. X@X . . X@X OX@-=bfz @gte9p;.o+fsgett :4egw8cjX@4h9qefgsqho@.eeg>9plfX;>tgghhs9>+;gg>splfv>Nsch@ejz .+o@X@X@X@X@X@X+.+o",
"@o.oX.oX.o.XXOXX.XX.,=6A. ,=%=,c:v.,==%#>+$%%,,%=>q>k77-fO%==nq; ,=,#%=$pz# -$.7=7ffX.$,@2=@aV#-7ifz6=nsXo.OXo.oXOXoX.oXOXo.",
"XX+O+O+O+X@X@X@X@XO.4s4j4. i==6jh; %=6=>z#v=#>.7b74to=66$O,=6,8>#i-;:,&bfV-7b3h06=9C#2S$m.=b$r:,667n-= ..+o+. X@X .+O+X@X@X ",
"@o.oX.XXOX.oX.Xo.XO#Ot3jD>,2@==3as=$2=7gh .fe4n,62swX--behv-=$Mf+Otst$==fa0-bgy267ft#=6$jO%=%s>k77->; @oXOX.o.X.X.XOXo.X.XX.",
"XO+. X@X+o@X@X@X .+ =bF$r:,$t%=%4@2>7==>h .x @@i6,sw@-ibtj,%=2z> ;@$O-=6fak,<@j$b-O;,%6,>,-,, ;$=62j;.X. X@X+O+o@X . . X@X@X",
" .Xo.oXOX.XX.oX.X.o;#,=.9;v@z,==%%e;=%%>hv,=6f;76,s:o-7bt9ki6$hdk%b@4i%6navO7AO#$.;.,==#p> +Xw:v%=2jX+.oX.oXOXo.X.X.Xo.XOXoX",
".X .+. X@X@X . X@X+.$%SOz>v@a === hv,==eak76$l47=29tX--bszv%=$j:===ey-==fq#;,394z9j9v%=7ayw>Os>v%=$l;.O+O+. .+O+o@X .+O+X@XO",
"+o.o.oX.Xo.o.X.o.XO;$i6$pjO rh$=%@s 26=fB>-%=gt%==9l>-%b>rf=6,aj,=6@8,==3B;%=-@@@$sq>==62Mje#>+#=62apwX.Xo.Xo.XX.oX.XOXXOX.X",
".X . X@X@X+. X@X+OX#,%%i3fG7O4 %=OX2,=%->w$==-$-=%#e@=7=,e =%-@4O=%i#,%=->fi==<b6S=8e#,76=2,$X 7%=% ew@X@X .+o@X@X@X . .+o@X",
" X.XX.o.Xo.oX.oXOX.  +  vvv k#X  o    o v . # .X   v  + #v#o  A#.o# o.   v+O2,,,$77w>XX  #v ..   o vk o.o.XOXOXXo.Xo.oXXOXo.",
".o@X@X+O+. .+O+. X..;.X.;.;.;.X..X.;X.X.;.Xo.OXO;..X.o..;.;..X.Xo...X..X..v-4a4:w,2;o..O..;.+.X;.X.;;.+O+X .+X@X@X .+. . .+o",
"+.Xo.o.oXOXo.XoX.oXX@oX.+O+. X.o+OX.;X;O+o.;.;;X.o+;:dX @XX X;:f. X .Xo;>> =$sNs,#;w.o+Xo+XOXo. X@X+OXOXXO.oXOX.oX.o.o.XX.o.",
"Xo@X+o+O+X@X O+O+. .o. .o.XOXO+.o. ;hNjlt .tzzh>+>4s9qa:XO.;t94jqwOX.;t4szygv-0$f9tjq4.o.XO+. XOXXOXO+X@X+o+O+o+X@X+o+o@X X ",
"o.X.OX.X.o.X.X.X.o.X.o.X.o.o..o.X. 2 @ 9r;A #3:;;;#$2#py>XXO$@ 29rto.O@ @,sB4.;. @@,gBhXO.XOX.X..o.X.XOX.o..X.XO.XO.X.OX..X.",
".XOXXOXOX.o.o.oXOX.o.XXOXX.XXX.XOXX =667aq.v$>; 22,==6-a4+$=-4 ==syX#=%t;=6tr;#=%>>0&fr:+.o.Xo.oX.Xo.X.XX.Xo.o.XXOXXOXX.oX.o",
"X@X+O+. X@X+O+X@X+O+X@X@X@X@X@o+O+O.,776$yav@4>  X;#7=6eh 76$j#,6,c:7=2z@,6-a476,9;-==j9oX@X . X@X . X@X@o+O+. X@X+O+X@X . .",
"Xo.o.oX.XXOX.o.XOXXOXo.XX.Xo.o.XX.X #>,66OHt$Z;+.o.o-=%>w2=6 c ,67Ze6=$qo,=%44%S2a:0%=eh.o.XOX.X.o.o.Xo.oX.oXOX.oXOX.o.X.XoX",
" .+O+X@X@o+. X@X+O+. . X@o+O+X@X@o. $hO6-64qOtd@XX.+,62;;,=&@qv7=7etS=2q+-==t4%b2pd-i6fzOX+O+X@X .+X . .+O+. X@X .+O+X@o+O+.",
"XOXXOXX.o.oX.oXOXXOXXX.XOX.X.oX.oX. kh>0%=-ggC>X.O; =,OXX,%S@c ,6=e4<=2qo,==gt=6,af0%=OjXo.XOXXOXo.o.XX.oXOX.XX.XOXXOXo.Xo.o",
"O+X@X@X@X .+O+.+O+X@X@X . X@o+. X@X #9> ,=7=@j;+oX.=7 +:4#=& qv-=%>g6=$c+-%=>w%b2a>0%6O9.X@o+. . .+. X@o+O+X@X@o@X . .+O+. X",
"XOXXOXXOX.oX.oX.XOXo.o.XX.XOXOXX.o. 2Zd. =7S$Mf ;:OxZz>ga =6@q -=7t;==2q.,67g>i6,p:-=%>tXOX.Xo.XXOXo.X.o.XOXXOXX.XOXXOXo.o.X",
"OX+O+X@X@X+O+X@o+. .+X@X@o+.+X@X@X. Aj.v.#76Gh;.f$,fge#@h %6$c.-=-4 76,pd-&,tO-&-jw-==t;@X@X . X@X . X@X+O+X@X@X@o+X@X+O+X@X",
"XOX.o.XoXOX.o.XOXo.o.oX.o.oXOXOXXOX;$ar4@XA6$j;A-i%%=7b3j ,6-q9=6@>+#67jj%= fX#6=Mp,6$fo.XOX.o.XOX.X.oXOXOXOXXOXX.XOXo.XOXXO",
". X@X+O+. X@X . X@X+O+O X@X@X@X+OX 27@gwX. 7,>;-6%=6==&#:. ,=O@%,o.X@,=@x%, .XO,=@.70OX. . X@X+O+X@X .+O+X@X+O+X@X@X . . X@X",
"X.Xo.oXOX.XX.o.X.X.oX.X.XX.XX.XOX.  #Ako.o. # o          X.  ,A  .X.XO k,#o.X.X. ,,#o.XOXXOXXOXo.oXOXOXXOX.o.XOX.oX.X.XXOX.o",
"O+O+. .+X@X@o+. X@o+. X@X@X@X@o+X@X.X;.. . X..+.;X.O.X..X@X.X...X@X@o.XO.X. X@o.X..X.. .+O+. .+O+. X@X+O+O+X@o+. X@X@o+O+. X",
"Xo.oX.o.oXOX.oX.XOXOX.Xo.oX.oX.o.oX@X@Xo.X.oXOXO+O+X . OXOXo@XX@XXOXo. .XOX.Xo.o@X.o@XX.oX.oXOXXOX.XXOX.oXOXXOXOX.oX.XOXo.XO",
"+O+X@X .+O+X@X@X .+X@o+O+X@o+. .+X@o+O+. X@X@X+O+X@X@X+. X@X@X@X . .+. X@X@X .+. X@X X@o+. X@X+O+X@X@X@X+O+. .+X@X+O+o+. X@X",
"X.XOX.oXOX.oX.o.oXOX.X.o.o.X.oXOXOX.Xo.o.XXOX.oX.oXOXOXX.XX.Xo.o.XXOXo.XOXXOXOXo.Xo.X.XOXOX.Xo.o.oX.Xo.o.XXOXo.o.o.XOXOX.X.o",
"@X . X+O+X@X@X .+O+X@X .+X@X . .+X@o+O+X@X@X O+. . .+X@X@X@o+O+X@X@X .+O+X@X@X .+O+X@X .+X@X . .+X@o+O+X@X@X . .+X@X+. X@X .",
"XOXXOXOX.oX.o.Xo.X.oXOXo.oX.o.Xo.XOX.XOXXOX.XX.oX.Xo.oXOXo.XOX.oX.o.X.oX.o.XX.Xo.X.oXOXo.oX.o.Xo.XOX.XOXXOX.X.Xo.oXOXX.XXOXX",
"+. . .+o+O+O+X@X@X . . .+. X@X . .+X@o+. . X@X@X@X . . .+. X@X . .+X@o+. . X@X@X@X . . .+. X@X . .+X@o+. . X@X . .+X@X@X@X@X",
".oX.Xo.XOXX.o.oX.o.XX.Xo.o.XX.XOXo.oX.XOXXOXo.oX.o.XX.Xo.o.XX.XOXo.oX.XOXXOXo.oX.o.XX.Xo.o.XX.XOXo.oX.XOXXOXo.oX.o.oXOXo.XXO",
"+X@X .+O+X@X .+. X@X@o+O+X@X@X@X+O+. . X .+. .+. X@X@o+O+X@X@X@X+O+. . X .+. .+. X@X@o+O+X@X@X@X+O+. . X .+. .+. X@X@X+. X@X",
".o.X.oXOXOX.Xo.o.XXOXX.o.oX.Xo.o.XXOXX.o.oX.Xo.o.XXOXX.o.oX.Xo.o.XXOXX.o.oX.Xo.o.XXOXX.o.oX.Xo.o.XXOXX.o.oX.Xo.o.XX.Xo.o.XOX",
"+X@o+. .+X@o+O+X@X@X . .+X@o+O+X@X@X . .+X@o+O+X@X@X . .+X@o+O+X@X@X . .+X@o+O+X@X@X . .+X@o+O+X@X@X . .+X@o+O+X@X@o+O+. X .",
".oX.XOXo.XOX.o.oX.o.XOXo.XOX.o.oX.o.XOXo.XOX.o.oX.o.XOXo.XOX.o.oX.o.XOXo.XOX.o.oX.o.XOXo.XOX.o.oX.o.XOXo.XOX.o.oX.o.XOXo.XOX",
"+X@X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X@X+. .+X",
".o.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.oXo.o",
"oXo.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X"};
