WelcomePage.Title=欢迎使用网络管理系统
WelcomePage.Welcome=欢迎使用网络管理部署系统
WelcomePage.WelcomeExt=网络管理系统
WelcomePage.Request=请选择以下操作方式：
WelcomePage.Install=安装
WelcomePage.Patch=补丁
WelcomePage.Upgrade=升级
WelcomePage.BackupRestore=备份和恢复
WelcomePage.Maintanence=维护
WelcomePage.Uninstall=卸载
WelcomePage.Exit=结束
WelcomePage.NoSubsystems=无组件可被修改。
WelcomePage.NeedCreateUpgradeDataModel=升级前需要创建数据模型，请单击<确认>开始创建数据模型。
WelcomePage.CreateUpgradeDataModelFinish=创建数据模型成功。
WelcomePage.CreateUpgradeDataModel=正在创建数据模型，大约需要5-15分钟，请稍候...
WelcomePage.DBMainTool=数据库维护工具
WelcomePage.UninstallDone=安装未完成，系统将退出。
WelcomePage.InstallDone=安装已完成，系统将退出。
WelcomePage.InvalidMode=安装模式错误，系统将退出。
WelcomePage.DataModelNotDelete=数据模型没有删除，请删除目录
WelcomePage.NeedCreateUpgradeDataModelcmd=升级前需要创建数据模型，升级将创建数据模型。
WelcomePage.CreateUpgradeDataModelFailed=创建数据模型失败。
WizardFrame.NoSchemaFile=请给出有效的离线配置文件。
WizardFrame.SchemaFileNotFound=离线配置文件不存在。
WizardFrame.SilentFileNotFound=静默文件不存在。
WizardFrame.SchemaFileError=离线配置文件无效。
WizardFrame.DatamodelNOTcorrectUpgrade=数据模型不正确，不可以继续升级。
WizardFrame.DatamodelNOTcorrectRollback=数据模型不正确，不可以继续回滚。
WizardFrame.DatamodelNOTcorrectRollback_Error=错误：
WizardFrame.DatamodelNOTcorrectPatch=数据模型不正确，补丁安装无法继续。
