WizardFrame.U2000FW=工程框架
WizardFrame.install=安装
WizardFrame.uninstall=卸载
WizardFrame.Verify=校验
WizardFrame.next=下一步
WizardFrame.nextCMD=下一步>
WizardFrame.previous=< 上一步
WizardFrame.previousCMD=上一步
WizardFrame.cancel=取消
WizardFrame.hint=提示
WizardFrame.confirmation=确认
WizardFrame.InstallAffirmCancel=确定取消安装吗？
WizardFrame.UninstallAffirmCancel=确定取消卸载吗？
WizardFrame.VerifyAffirmCancel=确定取消校验吗？
WizardFrame.UpdateAffirmCancel=确定取消操作吗？
WizardFrame.PatchAffirmCancel=确定取消补丁吗？
WizardFrame.UpgradeAffirmCancel=确定取消操作吗？
WizardFrame.StoreAffirmCancel=请确认是否取消？
WizardFrame.IsCanceling=正在取消...
WizardFrame.UpgradeIsCanceling=正在取消升级...
ossIsIntalled=不存在需要安装的节点，不需要再次进行安装。 \n {0}个节点之前已经安装成功：\n {1}
WizardFrame.InputError=已经到了第一页，不能再往前。
WizardFrame.CanNotCancelInstall=无法取消安装。
WizardFrame.confirm=确定
WizardFrame.Language_zh=中文
WizardFrame.Language_en=English
WizardFrame.SetupLangTitle=选择安装语言
WizardFrame.SetupLangHint=请选择安装时使用的语言：
WizardFrame.VerifyLangTitle=选择校验语言
WizardFrame.VerifyLangHint=请选择校验时使用的语言：
WizardFrame.Yes=是
WizardFrame.No=否
WizardFrame.Exit=退出
WizardFrame.Continue=继续
WizardFrame.Detail=详细信息
WizardFrame.Y=Y
WizardFrame.N=N
WizardFrame.Finish=完成
WizardFrame.CannotPrevious=此页面不能回到上一页面。
WizardFrame.IsContinue=是否继续？
WizardFrame.IsExit=成功退出。
WizardFrame.residualTime=剩余
WizardFrame.InstallProductShowLable=版本：
WizardFrame.Filetype=文件类型：
WizardFrame.WelcomeTitle=欢迎使用网络管理系统
WizardFrame.WelcomeInputItem=选择操作类型
WizardFrame.ContentsCMD=请选择如下操作
WizardFrame.Install=安装
WizardFrame.Patch=补丁安装网络管理系统
WizardFrame.Upgrade=升级
WizardFrame.Backup=备份与恢复
WizardFrame.Maintanence=维护
WizardFrame.Uninstall=卸载
WizardFrame.LoginTitle=登录
WizardFrame.LoginInputItem=请选择输入项
WizardFrame.LoginCommond=请输入登录命令
WizardFrame.Ip=IP 地址
WizardFrame.Port=端口
WizardFrame.Username=用户名
WizardFrame.Password=密码
WizardFrame.IpInvalid=ip格式错误，请重新输入。
WizardFrame.PortInvalid=端口格式错误，请重新输入。
WizardFrame.UsernameNull=用户名为空。
WizardFrame.PasswordNull=密码为空。
WizardFrame.InputItemInvalid=输入项错误，请重新输入。
WizardFrame.LoginSuccess=登录成功。
WizardFrame.UsernameError=输入的用户名错误，请重新输入。
WizardFrame.PasswordError=输入的密码错误，请重新输入。
WizardFrame.MSuitePwd=请输入网络管理系统维护工具登录密码
WizardFrame.AlreadyLoginError=已经有用户登录，不允许多个用户登录。
WizardFrame.Help=帮助
WizardFrame.InstallDone=已经安装过了
WizardFrame.UninstallDone=系统没有找到安装
WizardFrame.NotSupported=命令行模式下不支持此功能。
WizardFrame.DBMgrTool=数据库维护工具
WizardFrame.ConvertorAffirmCancel=确定退出License申请表生成工具吗？
WizardFrame.upgrade=升级


WizardFrame.pathchinstall=补丁安装
WizardFrame.pathchuninstall=补丁卸载
WizardFrame.SchemaFileNotFound=离线配置文件不存在。
WizardFrame.NoSchemaFile=请给出有效的离线配置文件。
WizardFrame.SchemaFileError=离线配置文件无效。
WizardFrame.rollback=回滚
WizardFrame.incrementinstall=增量安装组件

ProgressPage.installPatchTitle=开始补丁安装，请稍候...
ProgressPage.uninstallPatchTitle=开始补丁卸载，请稍候...
WizardFrame.BackupTitle=网络管理系统备份程序
WizardFrame.RestoreTitle=网络管理系统恢复程序
WizardFrame.PatchRollback=补丁卸载网络管理系统
WizardFrame.IscancelingUninstallation=正在取消卸载...
