#---No Comment---
# 这个文件用于为接入设备定义所有可更换部件的过滤参数，例如：boards, optical modules 和 ONT.

# 可更换部件对象类型, 例如：boards, optical modules 和 ONT
# 类型枚举，必须输入其中一个: ont, board, olt_opticalmodule, backboard
object_type=ont

# ONT型号(最大32字节)，精确匹配，可选输入，不输入为空
ne_type=

# ONT软件版本(最大32字节)，模糊匹配，可选输入，不输入为空
ne_software_version=

# ONT硬件版本(最大16字节)，模糊匹配，可选输入，不输入为空
ne_hardware_version=

# ONT生产厂商(整数)，精确匹配，可选输入，不输入为空
ne_vendor=

# Description字段中的扩展字段(最大256字节)，模糊匹配，可选输入，不输入为空
description_extend_1=

# Description字段中的扩展字段(最大256字节)，模糊匹配，可选输入，不输入为空
description_extend_2=

#================ 21条码信息(21条码整体是可选参数，但如果21条码有数据，各必须参数要求一起组合起来) ================
# 类别代码(2字节)，一般写21，精确匹配，必须输入
barcode_type_code=

# P/N代码(8字节)，精确匹配，必须输入
barcode_pn_code=

# EMS代码(2字节)，精确匹配，可选输入，不输入为空
barcode_ems_code=

# 日期(2字节)，精确匹配，可选输入，不输入为空
# 格式采用 年/月 形式；年（1字节）A-Z, A-2010；月(1字节)1-C，十六进制数表示月份
# 只是输入 年 参数，表示过滤 某年 生产的部件，输入 年/月 参数表示过滤 某年某月 成产的部件
# 输入 A年-B年 参数，表示过滤 A年到B年 生产的部件，输入 A年/A月-B年/B月 参数表示过滤 A年A月 到 B年B月 生产的部件
barcode_date=
