about.version=$U2000Component_Client_VersionName
about.desc=The environment and power monitoring realizes the centralized management and monitoring of the environment parameters and power parameters of the whole network.
env=Access environment and power monitor