#INSTALLROOT name for the secondary client that are configured in upgrade/config/clientdefine.xml, for these client the install path is #fixed 
secondaryClientRoot = dependent
#INSTALLROOT name for the secondary clients that does not have a direct relation with primary client
tcatroot = nondependent
