error_title=Error
error_notXls=Please Choose "xlsx" file
error_xlsFormat_sheet=Blank file
error_xlsFormat=Blank file
error_fileNotFund=File not found
error_readField=Failed reading file
error_fileTooLarge=File should be less than 50000 lines
error_writeField=Failed writing file
userName= Username:
ipAddress= IP Address :
pwd=Password :
LogIndialogTitle=Login failed,please enter the correct username and password
error_login=Login failed
error_userName_empty=User name can not be empty
error_ip_empty=IP address can not be empty
error_pwd_empty=Password can not be empty
error_port_empty = Port can not be empty
error_create_socket=Failed to connect the server, the username, password, ip or connect type is incorrect.
tl1DialogTitle=TL1 Import Tool
file_button=File ...
button_submit=Submit
button_close=Close
button_cancel=Cancel
error_file_choose=please choose "xlsx" file
reset_button=Reset
info_filenotFund=File not found
info_fileHasOpen=File is open, close and try again
error_fileHasOpen=File is open
info_connectTl1_field=Failed to create tl1 socket
error_connectTl1_field=Failed to create tl1 socket
tl_result_success=Success
tl_result_field=Faild
tl_custom_endesc=TL1 timeout
port = Port :
info_port_not_number=Port must be an integer
error_port_not_number=Port must be an integer
excelFile = File :
all_ok=Complete implementation
process_info_all =all/success/faild:
changeDialogTitle=Change Password
error_pwd=Change password failed: Invalid password.
warn_info=Warn
confirm_isExecute = The operation will apply the files to NEs and is irreversible. If the files contain risky operations, it may lead to service interruption. Are you sure you want to apply the files?
Untrusted_CA = Certificate verification failure.Possible causes: 1. The trust certificate is not trusted; 2. The trust certificate has expired.
namesequence = Physical Root