############################################################################
#调测工具资源文件
############################################################################
#4. 主机名
[customize]
ModifyHostnameInstruction=如果是Windows Server 2008系统，请见《U2000 单机系统软件安装调测指南 (Windows)》中的“如何修改单机系统（Windows 2008）的主机名”章节。\n如果是Windows 7系统，请见《U2000 单机系统软件安装调测指南 (Windows 7)》中的“如何修改单机系统（Windows 7）的主机名”章节。\n如果是Windows 10系统，请见《U2000 单机系统软件安装调测指南 (Windows 10)》中的“如何修改单机系统（Windows 10）的主机名”章节。
DateTimeZone.Info=如果是Windows Server 2008系统，请见《U2000 单机系统软件安装调测指南 (Windows)》中的“如何修改单机系统（Windows）的时间和时区”章节。\n如果是Windows 7系统，请见《U2000 单机系统软件安装调测指南 (Windows 7)》中的“如何修改单机系统（Windows 7）的时间和时区”章节。\n如果是Windows 10系统，请见《U2000 单机系统软件安装调测指南 (Windows 10)》中的“如何修改单机系统（Windows 10）的时间和时区”章节。
[/customize]
#5. 控制卡
[Controller]
SC.Title=控制卡设置说明
SC.Info.Win=如果是Windows Server 2008系统,请参见《U2000 单机系统软件安装调测指南 (Windows)》中的“配置IBM服务器集成管理模块（IMM）的IP地址”或者“配置华为服务器集成管理模块（iMana）的IP地址”章节。\n如果是Windows 7系统,请参见《U2000 单机系统软件安装调测指南 (Windows 7)》中的“配置IBM服务器集成管理模块（IMM）的IP地址”或者“配置华为服务器集成管理模块（iMana）的IP地址”章节。\n如果是Windows 10系统,请参见《U2000 单机系统软件安装调测指南 (Windows 10)》中的“配置IBM服务器集成管理模块（IMM）的IP地址”或者“配置华为服务器集成管理模块（iMana）的IP地址”章节。
SC.Info=如果是Solaris单机系统，请参见《U2000 单机系统软件安装调测指南 (Solaris)》中的“配置控制器IP”章节。\n如果是Solaris双机系统，请参见《U2000 高可用性系统 (Veritas) 软件安装调测指南 (Solaris)》中的“配置控制器IP”章节。\n如果是Linux单机系统，请参见《U2000 单机系统软件安装调测指南 (SUSE Linux，PC服务器)》中的“配置控制器IP”章节。\n如果是本地Linux双机系统，请参见《U2000 本地高可用性系统 (Veritas) 软件安装调测指南 (SUSE Linux，PC服务器)》中的“配置控制器IP”章节。\n如果是异地Linux双机系统，请参见《U2000 异地高可用性系统 (Veritas) 软件安装调测指南 (SUSE Linux，PC服务器)》中的“配置控制器IP”章节。
[/Controller]

#6. 防病毒软件
[VirusSoft]
VirusSoftCheck.Title=趋势防病毒软件状态显示
VirusSoftCheckPage.unintalled=未安装趋势防病毒软件
VirusSoftCheckPage.intalled=已安装趋势防病毒软件
VirusSoftCheckPage.officeScanVer=趋势防病毒软件版本：
VirusSoftCheckPage.virusVer=病毒库版本：
VirusSoftCheckPage.Info=详细操作，请参见《iManager U2000 防病毒软件部署用户指南 (OfficeScan11.0)》。\n
[/VirusSoft]

#7. 修改密码
[PValue]
PValueReference=配置密码工具提供数据库管理员用户、数据库用户、维护工具管理员用户的密码修改。如需修改系统密码请参考安装调测指南的“如何修改操作系统用户administrator的密码”章节。
VNC_ROOT=VNC管理员用户
VNC_NMS=VNC网管用户
VCS_ADMIN=VCS管理员用户
VNC_ROOT_PValue_RULE=
VNC_NMS_PValue_RULE=
VCS_ADMIN_PValue_RULE=<html>密码要求：<br>&nbsp;1. 密码必须是8-30个字符长。<br>&nbsp;2. 密码必须包含如下四种字符的组合：<br>&nbsp;&nbsp;&nbsp;&nbsp;至少一个大写字母；<br>&nbsp;&nbsp;&nbsp;&nbsp;至少一个小写字母；<br>&nbsp;&nbsp;&nbsp;&nbsp;至少一个数字；<br>&nbsp;&nbsp;&nbsp;&nbsp;特殊字符： ~@#^*-_+[{}]:./?<br>&nbsp;3. 密码不能和帐号或者帐号的倒写一样。<br>&nbsp;</html>
PValue.83=修改失败，已经启用安全加固，请参考安装调测指南“如何修改操作系统用户密码”
[/PValue]

#8. 告警配置
[Alarm]
Commissioning.Page.AlarmConfig=告警配置
AlarmConfigInstruction_lin=如果服务器或磁盘阵列发生故障或状态不正常，则系统上报告警到U2000。\n1：确认当前界面显示的控制器IP必须和实际配置的控制器IP一致。\n2：配置工作站系统控制器IP和磁盘阵列控制器IP请参见《U2000 单机系统软件安装调测指南 (SUSE Linux)》或《U2000 异地高可用性系统 (Veritas) 软件安装调测指南 (SUSE Linux，PC服务器)》中的“配置控制器IP”章节。\n3：如果是S3900磁盘阵列、S2600磁盘阵列和OceanStor 5500 V3磁盘阵列还需要手工配置硬件告警监控功能，请参见请参见《U2000 单机系统软件安装调测指南 (SUSE Linux)》或《U2000 异地高可用性系统 (Veritas) 软件安装调测指南 (SUSE Linux，PC服务器)》中的“配置硬件告警监控功能”章节。
AlarmConfigInstruction=如果服务器或磁盘阵列发生故障或状态不正常，则系统上报告警到U2000。\n1：确认当前界面显示的控制器IP必须和实际配置的控制器IP一致。\n2：配置工作站系统控制器IP和磁盘阵列控制器IP请参见《U2000 单机系统软件安装调测指南 (Solaris)》或《U2000 高可用性系统 (Veritas)安装调测指南 (Solaris)》中的“配置控制器IP”章节。\n3：如果是M4000/M5000服务器、S3900磁盘阵列、S2600磁盘阵列和OceanStor 5500 V3磁盘阵列还需要手工配置硬件告警监控功能，请参见请参见《U2000 单机系统软件安装调测指南 (Solaris)》或《U2000 高可用性系统 (Veritas)安装调测指南(Solaris)》中的“配置硬件告警监控功能”章节。
Server.ControlIP=控制卡IP
Disk.ArrayA.ControlIP=磁盘阵列A IP
Disk.ArrayB.ControlIP=磁盘阵列B IP
INPUT_IP_IS_NULL=输入IP为空。
INPUT_IP_ERROR=输入IP错误。
ALARM_CONFIG_SUCCESS=告警配置成功。
ALARM_CONFIG_FAILED=告警配置失败。
[/Alarm]

#9. 网管证书
[NMSLicense]
Commissioning.Page.NMSLicense=网管License
NMSLicense_Content_Win=        详细操作，请参见《U2000 单机系统软件安装调测指南 (Windows)》中的“加载U2000 License”章节。\n
NMSLicense_Content=        如果是Solaris单机系统，请参见《U2000 单机系统软件安装调测指南 (Solaris)》的“加载U2000 License”页面中命令行方式加载U2000 License。\n        如果是Solaris双机系统，请参见《U2000 高可用性系统 (Veritas) 软件安装调测指南 (Solaris)》的“加载U2000 License”页面中命令行方式加载U2000 License。\n        如果是Linux单机系统，请参见《U2000 单机系统软件安装调测指南 (SUSE Linux，PC服务器)》的“加载U2000 License”页面中命令行方式加载U2000 License。\n        如果是本地Linux双机系统，请参见《U2000 本地高可用性系统 (Veritas) 软件安装调测指南 (SUSE Linux，PC服务器)》的“加载U2000 License”页面中命令行方式加载U2000 License。\n        如果是异地Linux双机系统，请参见《U2000 异地高可用性系统 (Veritas) 软件安装调测指南 (SUSE Linux，PC服务器)》的“加载U2000 License”页面中命令行方式加载U2000 License。
[/NMSLicense]

#10. VCS许可证
[VCSLicense]
VCSLicense.Title=配置Veritas License
VCSLicense.Stand=VRTS STORAGE FOUNDATION:
VCSLicense.Option=VRTS REPLICATOR:
VCSLicense.HADR=VRTS CLUSTER SERVER:
VCSLicense.HighVersion=VRTS License:
VCSLicense.warm=一个完整的Veritas license包含:VRTS STORAGE FOUNDATION、VRTS REPLICATOR和VRTS CLUSTER SERVER \n请确认您已经获取到了完整的Veritas license \n如果您的license不完整，注册后会导致双机无法正常工作。
VCSLicense.warmTheSameKey=存在至少两个相同的密钥，请重新输入
VCSLicense.completeCheckfailed=更新失败，检查License完整性失败!
VCSLicense.versionCheckfailed=更新失败，检查License版本和Veritas不匹配!
VCSLicense.workCheckfailed=更新失败，检查License无效!
VCSLicense.permissionCheckfailed=刷新License文件权限失败!
VCSLicense.updateLicenseFailed=更新{0}失败。
VCSLicense.standlicense=当前的VCS已使用正式的license
VCSLicense.templicense=当前的VCS未使用正式的license
VCSLicense.Failed=更新Veritas License失败。
VCSLicense.backupLicensefailed=备份License失败。
VCSLicense.typeerror=获取Veritas License类型失败。
VCSLicense.Succeed=更新Veritas License成功，重启操作系统后生效。
MACHINECTRL_UPDATELICENSE_SUCCESS=更新VRTS License成功。
MACHINECTRL_UPDATELICENSE_FAILED=更新VRTS License失败。
VCSLicense.setlicense=设置正式license 
INPUT_NOT_FULL=请输入所有的license。
[/VCSLicense]

#11. 更新网管证书
[ReplaceNMSLicense]
Commissioning.Page.ReplaceNMSLicense=配置SSL证书
CertManage_Browse=浏览
CertManage_LIST_FILES=文件列表
List_CERT_FILES_FAILED=浏览证书文件列表失败
CertManage_Title=证书配置

CertManage_IdentityCertDesc=<html>身份证书是标识实体（用户、计算机或服务）身份的数字文档。<br/>私钥是与身份证书上主体公钥对应的非对称密钥。<br/>PKCS#12是一种个人信息交换语法标准，该标准格式中定义了如何存储实体的私钥、证书等个人信息。<br/><b><font color='aa0000'>注意：</font></b>更新身份证书后，请更新相对应的信任证书，否则会导致维护工具客户端无法登录。更新完成后请重启维护工具前后台。</html>
CertManage_IdentityCertClientGroup=SSL Client证书
CertManage_IdentityCertServerGroup=SSL Server证书
CertManage_IdentityCertFile=文件名：
CertManage_IdentityCertPwd=PFX密码：

CertManage_Tab_IdentityCert=身份证书
CertManage_ProvidePWD=请提供证书密码。

CertManage_Tab_TrustCert=信任证书
CertManage_TrustCert_Info=<html>信任证书是信任机构的身份证书，用于验证由该机构颁发的身份证书的有效性。</html>
CertManage_Tbl_IssueTo=颁发给
CertManage_Tbl_Issuer=颁发者
CertManage_Tbl_StartDate=有效开始时间
CertManage_Tbl_EndDate=有效结束时间
CertManage_Btn_Add=增加
CertManage_Btn_Del=删除
CertManage_Btn_Confirm=确定
CertManage_Btn_Cancel=取消

CertManage_ConfirmToUpdate=请确认是否要更新证书文件？
CertManage_ConfirmToDelete=请确认是否要删除该证书文件？
CertManage_ConfirmTitle=确认
CertManage_ProvideFilePath=请输入文件路径。

CertManage_SucceedUpdateTrustCert=已成功更新信任证书文件。
CertManage_FailUpdateTrustCert=更新信任证书文件出错。
CertManage_Fail=错误

CertManage_Code_1000=成功更新维护工具客户端身份证书。
CertManage_Code_1001=成功更新维护工具服务器端身份证书。
CertManage_Code_1002=成功更新维护工具信任证书。
CertManage_Code_1004=更新完证书后将进行cau重整，耗时15分钟左右，在此期间请勿重复更新证书。
CertManage_Code_1005=如果未更新维护工具客户端身份证书和信任证书，请同步更新。
CertManage_Code_1006=如果未更新维护工具服务端身份证书和信任证书，请同步更新。
CertManage_Code_1007=如果未更新维护工具信任证书，请同步更新。
CertManage_Code_1008=如果未更新身份证书，请同步更新。

CertManage_Code_2000=更新维护工具客户端身份证书失败。
CertManage_Code_2001=更新维护工具服务器端身份证书失败。
CertManage_Code_2002=更新维护工具信任证书失败。
CertManage_Code_2003=无法读取客户端证书内容，更新本地客户端证书失败。
CertManage_Code_2004=更新本地维护工具客户端身份证书失败。
CertManage_Code_2005=更新本地客户端身份证书失败，证书不存在。

CertManage_Code_2010=身份证书不存在。
CertManage_Code_2011=PFX 密码不正确或者所选文件被损坏。
CertManage_Code_2013=输入参数错误，请重新输入。
CertManage_Code_2014=解析证书文件失败。
CertManage_Code_2015=信任证书文件不存在。
CertManage_Code_2016=准备添加的证书内容已经包含在现有证书内容里，不能重复添加。
CertManage_Code_2017=在以下从结点更新证书失败。
CertManage_Code_2018=在以下从结点修改证书权限失败。
CertManage_Code_2019=检查主节点与下面从结点的互信失败。
CertManage_PathOnServer=请输入服务器上的证书绝对路径

CertManage_ProvideP12=身份证书文件扩展名为p12，请输入正确的证书文件名。
CertManage_ProvideCer=信任证书文件扩展名为cer，请输入正确的证书文件名。
The_following_Node_Not_Running=以下节点服务没有启动
CertManage_Exit_Confirm_Msg=证书更新不完整，确定退出更新证书吗？

START_CAU=CAU重整中，预计需要15分钟
EXECUTE_CAU_SUCCEED=CAU重整成功
EXECUTE_CAU_FAILED=CAU重整失败
CAU_RPC_INVOKE_FAILED=CAU Rpc 调用失败

#确认提示框的资源
BTN_CANCLE=取消
BTN_CONFIRM=确定
BTN_ADD=增加(D)
BTN_DEL=删除(E)
BTN_YES=是
BTN_NO=否
TITLE_MSGDIG_INFORMATION=提示
TITLE_MSGDIG_SEVERE=错误
TITLE_MSGDIG_WARNING=警告
[/ReplaceNMSLicense]

#13. 组网配置
[Network]
ONE_NIC=单网卡
TWO_NIC=双网卡
TWO_NIC_IPMP=双网卡(IPMP)
THREE_NIC=三网卡
FOUR_NIC=四网卡
SIX_NIC=六网卡
NetworkReference_Win=如果是Windows Server 2008系统，请见《U2000 单机系统软件安装调测指南 (Windows)》中的\n“如何修改单机系统（Windows 2008）的IP地址”章节。\n
NetworkReference=如果是Windows Server 2008系统，请见《U2000 单机系统软件安装调测指南 (Windows)》中的“如何修改单机系统（Windows 2008）的IP地址”章节。\n如果是Windows 7系统，请见《U2000 单机系统软件安装调测指南 (Windows 7)》中的“如何修改单机系统（Windows 7）的IP地址”章节。\n如果是Windows 10系统，请见《U2000 单机系统软件安装调测指南 (Windows 10)》中的“如何修改单机系统（Windows 10）的IP地址”章节。
GetNetSolutionErr=获取组网信息失败
NetworkSolution=组网方案
CheckChangeSolution=当前为"{0}",是否需要切换到"{1}"场景？
Commissioning.Page.ConfigNetwork=组网和IP设置
INPUT_NIC_SAME=配置的网卡"{0}"重复
INPUT_IP_SAME=配置的IP "{0}"重复
INPUT_NETMASK_ERROR=输入的子网掩码"{0}"错误
Solaris_Single=(Solaris单机)
Solaris_HA=(Solaris双机)
Linux_Single=(Linux单机)
Linux_Localdual=(Linux本地双机)
Linux_Remotedual=(Linux异地双机)
CURRENT_SULUTION_ISNOTFORMAL=当前环境找不到匹配的组网方案，切换为默认组网
COL_NAME_INTERFACE=网口类型
COL_NAME_NIC=网卡
COL_NAME_IPADDRESS=IP地址
COL_NAME_NETMASK=子网掩码
COL_NAME_IPTYPE=IP类型
MasterInterface={0} 主用
SlaveInterface={0} 备用
FloatInterface={0} 浮动
NO_CHANGE_IS_THERE=输入的网络参数与系统网络参数一致，请确认。
EXECUTE_SCRIPT_FAILED=脚本执行失败 :"{0}"
MODIFY_NETWORK_FAILED=配置网络失败。
Config_network_succeed=配置网络成功。
MODIFY_NETWORK_SUCCESSED=配置网络成功,该配置将在重启计算机后生效。
StartConfigNetwork=开始进行网络配置，大约需要10分钟。
INPUT_IP_USED=您输入的IP地址"{0}"无效，请确认IP地址是否已经被使用。
ConfigNetwrok_NEXT_STEP_PROMPT=请确认是否执行组网调整？
INPUT_NIC_ISEMPTY=输入的网卡地址为空。
ModifyRebootSystem=系统配置已经更改，请重启操作系统使配置生效，在配置生效前无法再修改网络配置。
CoinfgNetwork_NetworkCard_failure=检测到当前服务器网卡或者网卡配置异常，请修复好相应的网卡信息再进行调测。
[/Network]

#15. 安全加固
[SecuritySet]
Commissioning.Page.SecuritySet=安全加固
RunSecuritySet=启用安全加固
SecuritySetInstruction_Win=详细操作，请参见《U2000 Windows操作系统安全加固指南》。\n
SecuritySetInstruction=请勾选启动安全加固。
RunSecuritySet_Running=启用安全加固(已启用)
RunSecuritySet_Not_Running=启用安全加固(未启用)
RunSecuritySet_installed=启用安全加固(已安装)
RunSecuritySet_uninstalled=启用安全加固(未安装)
SecuritySet_installed=安全加固软件已安装
SecuritySet_uninstalled=安全加固软件未安装
SecuritySetWarning=如果取消安全加固，系统将存在风险，是否继续？
StartSecuritySet_Win=开始进行安全加固，大约需要20分钟。
StartSecuritySet=开始进行安全加固，大约需要10分钟。
SECURITY_SET_SUCCEED=安全加固成功，配置将在重启计算机后生效。
SECURITY_SET_SUCCEED_IN_MS=安全加固成功。
SECURITY_SET_FAILED=安全加固失败。
SECURITY_SET_PROMPT=安全加固已经启动，是否再次执行？
SecuritySet_NEXT_STEP_PROMPT=安全加固未启用，是否执行安全加固？
[/SecuritySet]

#16. 激活网卡
[ActiveNic]
CONFIG_NIC_PROCESS_DLG=配置激活网卡中，请稍候...
TOOLTIPTXT_CONFIGNICSUCCESS=配置激活网卡成功，该配置将在重启计算机后生效。
TOOLTIPTXT_CONFIGNICFAILED=配置激活网卡失败。
Commissioning.Page.ActiveNic=配置激活网卡
INPUT_HOSTNAME_USED=配置的主机名"{0}"已经被使用。
INPUT_HOSTNAME_ERROR=输入的主机名"{0}"错误
COL_NAME_HOSTNAME=主机名
sec_activenic=配置网卡信息
[/ActiveNic]

#17.部署域状态
[WelcomPage]
deployState=部署状态
Access=接入域：
IP=IP域：
Trans=传送域：
Undeployed=未部署
deployed=已部署
[/WelcomPage]

#18. VRTS版本
[VRTSVersion]
VRTSVersion.Failed=获取VRTS版本失败.
[/VRTSVersion]
