################################################################################
# 
#           定制工程维护工具前台界面资源 InstallDisk.properties (zh_CN)
#
#
################################################################################

# 定制维护工具显示安装类型
Locale_HA=本地双机
Remote_HA=异地双机
Distribute_HA=双机分布式
Distribute_Single=单机分布式
Single=单机
