#Based on the below properties, client main window will be adjusted to width and height values available to the system.
#set property 
#for 100%
#client.width.ratio=1;// for 100% default
#client.height.ratio= 1;//for 100% default
#for 80 % setting
#client.width.ratio=0.8;// for 80%
#client.height.ratio= 0.8;//for 80%
#Minimum allowed = 0.1//10%
#Maximum allowed = 1 //100% 

client.width.ratio=1
client.height.ratio=1