#platform version
platform_version=iMAPV200R008C01B023

#the executable file name of client upgrade 
update_jre_file = ./jre/bin/java -Djava.library.path=./update/lib
update_main_class = 
update_application_paras=
update_lib_files = ./update/lib/clientupdate.jar;./lib/iview.jar

#the filechooser default path
iview.filechooser.defaultpath=report

#ToolTip delay time
iview.tooltip.delaytime = 60

#System setting - displace setting visible
iview.systemsetting.displaceSettingVisible=true

#bootstrap loader used.You needn't config this property if you don't use the function of bootstrap
#patch path
boot_patch_dir=./lib/patch/*.jar
#other class path
boot_classpath=
#app main class
boot_mainclass=com.swimap.iview.framework.Main
#help class path
boot_helpclasspath=lib/iview.jar;lib/helpSupportLib/jhall.jar;lib/iviewlib.jar

#Launch Online Help in browser
webhost = http://127.0.0.1:31028/hedex/hedex.do?fe=2000&lib=iMAP&p=h&id=
homepage = http://127.0.0.1:31028/hedex/hedex.do?fe=2000&lib=iMAP&p=h&id=

jsse.enableCBCProtection=false