sysmonitorclient_name=iManager U2000 Unified Network Management System-System Monitor Client
about.version=$U2000Component_Client_VersionName
about.desc=iManager U2000 Unified Network Management System-System Monitor Client

AboutDialog_1999_2001=2009-2017
