about.version=$U2000Component_Client_VersionName
about.desc=Provides the cross-domain basic NMS functions, involving importing and exporting scripts, managing NE time, synchronizing NEs, and managing NMS objects.
unitedmgr=United Function Management 