#@  调用MPLS不同入口的开关，0:topo调用IP组件（topo右键菜单入口），1:devWin 单网元左树节点
mplsEntryType = 1
DisplayPortStatus = 0

#@  通过开关判断是否委内瑞拉局点，从而决定要不要支持atur特性 。UA5000IPMB 设备和 MA5600V3设备 ADSL右键菜单显示"终端Ping"(1表示显示 0表示不显示)
aturEntryType = 1
#@ 全网POTS MA5600设备“电话号码导出配置”默认不显示该菜单项(1表示显示 0表示不显示).在特定局点(摩洛哥)使用
ExportTelNoEnable = 0