#@ 通讯模块的时间常量
#| The Time Constant of communication module
[comm]
DefaultTimeout = value(90)
DefaultMiniumTime = value(0)
[\comm]
#@ 运行模式设置（正常/LCT）
#| Running mode setup (Normal/LCT)
[LCT_Setting]
#LCTVersion = value(TRUE)
maxNENumber = value(32)
[\LCT_Setting]
#@ 网元管理器个数控制
[NE_ExplorerInstance]
maxNEExplorerInstanceNumber = value(10)
[\NE_ExplorerInstance]
#@ 时间显示模式
#@ 0表示按网管服务器本地时间显示；1表示按网管客户端本地时间显示 2表示按网元本地时间显示；默认按按网管服务器本地时间显示
[TimeMode]
mode = value(0)
[\TimeMode]
#@ 主流/北美风格
[InterfaceStyle]
#@ 以下value属性的值用于定义程序的界面风格：主流(0)，北美(1)
style = value(0)
[\InterfaceStyle]
#@ 界面风格设置
#| Interface Style setup
[ui_style]
uistyle= value(Huawei)
[\ui_style]
[font_size]
huawei_unix= value(14)
huawei_windows= value(12)
[\font_size]
#@ 复用段压制功能的缺省开关：开(1) 关(0)
#| The default switch of MS suppression function: Open(1) Close(0).
[squelch_Switch_DefaultClose]
squelch_Switch_DefaultClose=value(0)
[\squelch_Switch_DefaultClose]
#@ 波分光纤搜索功能的缺省开关：开(1) 关(0)
#| The default switch of WDM fiber search function: Open(1) Close(0).
[search_WDM_fiber_DefaultClose]
squelch_Switch_DefaultClose=value(0)
[\search_WDM_fiber_DefaultClose]
#@ SDH路径排序时比较费时间，增加进度条。
#@ 只有路径条数大于下面这个数值时，才显示进度条，否则不显示。
#| For the sortting of SDH trail is so slowly, so add the progress bar.
#| Only the count of trail is bigger then the underside number it will be show ,otherwise it wont show.
[trailSort]
trailSortNum=value(500)
[\trailSort]
#@ IP网关的通讯端口号定义(缺省值为1400)
#@ 网关的通讯端口号定义(IP端口缺省值SDH设备为1400，SONET设备为3081；OSI端口缺省值SDH设备为8888，SONET为TT)
#| Define the communication port of IP gateway (Default value is 1400).
[GatewayPort]
IPgatewayPort = value(1400)
gatewayNESSLPort = value(5432)
OSIgatewayPort = value(8888) editable(false)
IPgatewayPort_NA = value(3081)
OSIgatewayPort_NA = value(HW) editable(true)
[\GatewayPort]
#@ 开(1) 关(0)
#| Enable(1) Disable(0)
[WhetherPrintAuthorityInfo]
checkAuthority=value(0)
[\WhetherPrintAuthorityInfo]
[DeviceSearchUsername_Setting]
username_t2000 = value(root)
username_lct = value(lct)
[\DeviceSearchUsername_Setting]
#@ dd表示日；MM表示月；yyyy或yy表示年；HH表示时（24小时制）；mm表示分，ss表示秒
#@ 字母个数严格限制，时间格式中至少应包含时和分，注意所有的表示符严格区分大小写！
#pattern = value(MM-dd-yyyy HH:mm:ss)
[DateFormat]
pattern = value(yyyy-MM-dd HH:mm:ss)
[\DateFormat]
#@ 网元管理器窗口打开是否最大化的配置项:1 表示最大化打开，默认为 1；其他值表示普通窗口化打开。
[NEEXPLORE]
DEFAULT_TO_MAX = value(1)
[\NEEXPLORE]
#@ MCA板的光谱分析参数:默认为 0  表示进入光谱分析的时候不查询，1 表示刚进入光谱分析的时候就去查询，20为默认的光谱补偿
[WDMMCAPARATER]
EnterToQuery = value(0)
CompensationPowerValue= value(20)
[\WDMMCAPARATER]
[disxcDo]
easy = value(1)
[\disxcDo]
[gctproxypara]
gctproxyip= value(127.0.0.1)
gctproxyport= value(9900)
[\gctproxypara]
#@ 设置是否显示链路时隙管理菜单 0表示无 1表示有 默认 0
#| Is need to have Link Timeslot Management menu，0:not  1:yes  default：0
[ENABLELINKTIMESLOTMGR]
EnableLinkTimeslotMgrMenu = value(0)
[\ENABLELINKTIMESLOTMGR]
#@ 使能只创建网关网元   1：使能  0：禁止  默认：0
# Enable the function of creating only the GNE. 1: Enabled. 0: Disabled. Default: 0.
# 该设置项只在LCT版本上有效
# The setting applies to only the Web LCT.
[LocalAccess]
GatewayOnly=value(0)
[\LocalAccess]
#@ 使能共路由检查  1：使能  0：禁止  默认：0
[ENABLE_SHAREROUTECHECK]
enableshareroutecheck=value(1)
[\ENABLE_SHAREROUTECHECK]
[SNC_RELATE]
sdhsncp_relate_enable=value(0)
tl1wdmsncp_relate_enable=value(0)
tl1ngwdmsncp_relate_enable=value(0)
wdmsncp_relate_enable=value(0)
ngwdmsncp_relate_enable=value(0)
[\SNC_RELATE]
