## Deployment tool error code information
# Command line interface resources
[CMDLINE]
CMDLINE_EXAMPLE_DEPLOYDOMAIN=Deploy domain:deploy -ip 127.0.0.1 -port 12212 -username admin deploydomain -domain Access
CMDLINE_EXAMPLE_UNDEPLOYDOMAIN=Undeploy domain:deploy -ip 127.0.0.1 -port 12212 -username admin undeploydomain -domain Access
CMDLINE_DEPLOY_DOMAIN=Domain name
CMDLINE_DOMAIN_DEPLOY=Deploy domain
CMDLINE_UNDEPLOY_DOMAIN=Domain name
CMDLINE_DOMAIN_UNDEPLOY=Undeploy domain
CMDLINE_QUOTE_DOMAINNAME=Domain name (available options: Access, Trans, and IP)
CMDLINE_EXAMPLE_DEPLOYDOMAIN_BT=Deploy domain:deploy deploydomain -domain Access
CMDLINE_EXAMPLE_UNDEPLOYDOMAIN_BT=Undeploy domain:deploy undeploydomain -domain Access
CMDLINE_QUOTE_CONFIGFILE=config file path
