
state=State
hostid=Node ID:
hosttype=Node Type:
fixHostName=Fixed IP Address:
des=Description
usingDB=Database in Use:
addButton=Add...
removeButton=Remove...
modifyButton=Modify...
finishedButton=Finish...
Host_Fixed_Ip=Fixed Host IP:
hostInfoPageTitle=Manage Host Information
ftpType=FTP type
FTPUser=FTP user
ftpUserName=FTP user name
ftpUserPwd=FTP user password
ftpUserNameLabelCMD=FTP User Name
ftpTypeOne=FTP
ftpTypeTwo=SFTP
InstallDir=Installation Directory
installFolder=Installation Path:
SingleMode=Non-distribution Mode
DistributeMode=Distribution Mode

HostTitle=Host Information
addHostInfoDlg=Add
modifyHostInfoDlg=Edit
hostidLabel=Host ID:
hosttypeLabel=Node Type:
isDBServerLabel=Whether it is the database server:
hostFixIPLabel=Fixed IP Address:
hostFloatIPLabel=Floating IP Address:
usingDBLabel=Database In Use:
sshUserNameLabel=SSH User Name:
sshUserPwdLabel=SSH User Password:
desLabel=Description:
okButton=OK
cancelButton=Cancel
yes=Yes
no=No
nodeIDLabel=Host ID:
rootPasswdlabel=Admin password:
installDirLabel=Installation path:
masterHost=Master Host
slaveHost=Slave Host
standbyHost=Standby Host
single=Single
activeHASystem=Active Node of HA System
standbyHASystem=Standby Node of HA System
watchmanSystem=Watchman System

ftptypeLabel= Type:
ftpUserNameLabel= User Name:
ftpUserPwdLabel= Password:


dbServerInfoPageTitle=Manage database Server Information
dbid=DB ID
dbservername=Server Name
dbserverport=Server Port
dbtype=Server Type
dbaddress=Server IP Address


DBTitle=Database Server Information
createDBInfoDlgTitle=Add
modifyDBInfoDlgTitle=Modify
dbIDLabel=ID:
dbServerNameLabel=Server Name:
dbServerPortLabel=Server Port:
dbServerAddressLabel=Server IP Address:
dbTypeLabel=Server Type:
dbUserNameLabel=Administrator Name:
dbUserPwdLabel=Administrator Password:
nmsDBUserNameLabel=OSS user name:
nmsDBUserPwdLabel=OSS user password:
nmsDBUserPwdConfirmLabel=Confirm OSS database user password:
racCheckBoxLabel = Oracle RAC mode
racAddress1Label = Oracle RAC address 1:
racAddress2Label = Oracle RAC address 2:
racAddress3Label = Oracle RAC address 3:
racAddress4Label = Oracle RAC address 4:
OSType = OS type: 
addMoreDBInfos = Are you sure you want to perform any operation?
selectOperation = Operation Type:
selectHost = Select ID:
EmptyHostDetails = No host information found.

HostID_null=The host ID is empty.
HostFixName_null=The fixed host name is empty.
HostFixIP_null=The fixed IP address is invalid.
HostFloatName_null=The floating host name is empty.
HostFloatIP_null=The floating IP address is invalid.
HostInfo_exist=The host information already exists.
SSHUserName_null=The SSH user name is empty.
SSHUser_invalid=The SSH user name or password is incorrect.
HostInfo_hostfixipnouser=Failed to connect to a specified host.
TooManyHostsToDeploy=There are too many hosts to be deployed.
HostInfo_repeated=Host conflict. Delete unwanted hosts.
HostInfo_Multi_Master=The list contains more than one master host.
HostInfo_CantPing=Failed to connect to the following hosts:\nDo you want to continue?
HostInfo_SSH_Invalid=The SSH user name or password is incorrect on the following host:\nAre you sure you want to continue?
HoatInfo_ChineseChars = The Host ID contains Chinese characters.
HostInfo_Multi_StandBy_Master = The list contains more than one standby master host.
HostInfo_StandBySlave_No_Master = A standby server for the master server must be added if a standby server has been added for the slave server.
HostInfo_StandByShared_Master_Slave = Only one standby server can be deployed.
HostInfo_No_Master = A master server is required.
HostInfo_No_DB = The database used by the following host does not exist. Select an in-use database.
HostInfo_FTPUserPasswdWrong = The FTP user or password is incorrect.
FTPUserName_null = The FTP user name is empty.

FTPLoginFailed = FTP login failed.
ftptypeLabelCMD=FTP
HostInfo_PortNotListen = Failed to connect to the FTP port.
HostInfo_SFTPUserPasswdWrong = The SFTP user or password is incorrect.
HostInfo_WrongAdminPwd = Incorrect administrator password.
ErrorNullInstallPath = The installation directory is empty.
AdminPwd_null = The administrator password is invalid.
HostIP_NamingIP_Same = When you install the slave server, the local server address and server address of the naming server cannot be same.
uploadFrameworkMessage = Are you sure you want to upload the framework?
frameworkFileNotExist = The framework release file is not found.
invalidRemotePath=The remote path for framework is invalid.
NoSSH_Service=No SSH service is running on the host.

FTP_ErrorCannotConnection = Failed to connect to the FTP/SFTP service.
FTP_portNotListening = The FTP/SFTP service is not running.
FtpValidationFailed=FTP authentication failed. 
InstallDirectoryValidationFailed = Failed to install the authentication directory.
FrameWorkDirectoryValidationFailed = Failed to authenticate the framework directory.
Host_Ip_Invalid = The host IP address is invalid.
Float_Ip_Invalid = The floating IP address is invalid.
Host_IP_LocaleIP=The IP address of the primary site must be the same as that of the local server.
Host_IP_notLocaleIP=The IP address of a non-primary site cannot be same as that of the local server.
DirectoryMustBeCharAndNum = The path must be an absolute path composed of characters, numbers, \'-\', or\'_\'. The path name contains a maximum of 60 characters. No space should exist before '\\', '/', or ':'.


ErrorInstallPath = The installation path is invalid. Enter another installation path.
InstallDirNotEmpty = The installation directory for the following node cannot be empty. Choose another installation path.
CheckSpaceFailed = Failed to check available space for installation.
NoSpace = The following nodes do not have sufficient space:\nClean up the disk.


DBConnected_fail=Failed to connect to the database server.
DBID_null=The database server ID is empty.
DBServerName_null=The database server name is empty.
DBServerPort_null=The database server port is empty.
DBUserName_null=The database administrator name is empty.
DBUserPwd_null=The database password is empty.
NMSDBUserName_null=The OSS database user name is empty.
NMSDBUserPwd_null=The OSS database user password is empty.
NMSDBUserPwdConfirm_null=The confirm password is empty.
DBInfo_exist=The ip address or server name already exists.
NMSDBUserPwd_differ=The OSS database user password and confirm password do not match.
DB2_DBUSERNAME_PWD_WRONG = The database instance name or password is incorrect.
DB2_SERVER_NAME_WRONG = Database imapdb does not exist on the specified server.
DB2_PORT_NUMBER_WRONG = Failed to connect to the database. Possible causes are as follows:\nThe database port is incorrect.\nThe database is offline.
DB2_FIX_HOST_NAME_WRONG = Failed to connect to the database server.
DB_SUSERNAME_PASSWORD_WRONG = The database administrator name or password is incorrect.
DB_SERVERNAME_INVALID=Failed to connect to the database. Possible causes are as follows:\n1. The database server is offline.\n2. The server name is incorrect.\n3. The IP address or port number is incorrect.\n4. The administrator name is incorrect.\n5. The administrator password is incorrect.
DB_ChineseChars = The database server ID contains some Chinese characters.
DBInfo_repeated=The list contains duplicate database server information. Delete unwanted information.
ORACLE_IP_PORT_WRONG = Failed to connect to the database server.\nThe database server address, port number, or server name is incorrect.
ORACLE_RAC_HOST_NOT_ENOUTH = At least two RAC addresses are required in Oracle RAC mode.
ORACLE_RAC_IP_WRONG = The Oracle RAC addresses are in incorrect format.
ORACLE_RAC_IP_CONFLICT = The RAC addresses cannot be the same.
DB_Databases_Empty = The required database does not exist.
SERVER_IP_INVALID = The database server IP address is invalid.
SQLPLUS_NOT_RUNNING = SQLPLUS is not contained in the path.
EmptyDBDetails= No database details available.

STANDBY_MASTER=Master Standby
STANDBY_SLAVE=Slave Standby
STANDBY_COMMON=Shared Standby


uninstallHostInfoPageTitle = Host Information
modifyUninstallHostInfoDlg = Modify Host Information
DirNotExistCreateIt = The directory {0} \ndoes not exist. Do you want to create it?

UnistallFileError = The uninstall script is not found in the specified path. Check the installation path.
InstallPath_Null = The installation path is empty.


remoteFrameworkError = Failed to connect to the framework.
remoteServerError=The remote machine does not support the File Browser option.\nEnter the installation path manually.
uploadHint = Uploading
uploadWaitMessage = Uploading files on remote machine(s)... Please wait.
uploadWaitCompress = Compressing the files for uploading... Please wait.
HostInfoPage.CheckingDlgTitle=Check parameters
HostInfoPage.CheckingParameters=Checking the input parameters... Please wait.
HostInfoPage.InstallDirNotWritable=Failed to create the installation directory \n or the directory cannot be written.
HostInfoPage.FrameWorkDirNotWritable=Failed to create the FrameWork directory \n or the directory cannot be written.
HostInfoPage.DifferentInstallDir=The installation directories on nodes must be the same.
HostIDnotmatched=The Host ID entered in the DefaultValues.properties file does not exist in {0}.
NotLocalIP = The IP address must be a local one.
invalidConfigExport=Failed to authenticate SSH details on the master server.\n Try again after checking the ConfigExport.xml file.
InvalidConfig=Invalid {0}.
InvalidHostID=Invalid standalone host ID.
ScriptFileNotFound = The configuration file {0} is not found. 
InvalidConfigHostID= An invalid host ID is set in {0}.
PackageFile.Empty = No component description file is found. Installation will exit.

Host_Fixed_IP=Fixed Host IP:
HostInfoPage.upload.error=Transmission packet throw unknown exception
hostname_not_same=Fixed host address and floating host address are not in the same machine
ConfigDBServer.ConnectInfoCheckEmpty= All the database configuration information should not be empty.
DBServerInfoPage.NMDBUserPassword=OSS Database User Password:
DBServerInfoPage.NMDBUserPasswordConfirm=Confirm OSS Database User Password:

DBServerInfoPage.NMDBUserPWDNULL=The OSS database user cannot be blank.
DBServerInfoPage.NMDBUserRePWDNULL=The confirmation password cannot be blank.
DBServerInfoPage.NMDBUserPWDNOTSAME=The password of the OSS database user does not match the confirmation password.
DBServerInfoPage.OSSUserPWDRuleSQL2008=OSS dbuser password requirements:  \n 1. The database user password must contain 8 to 30 characters.  \n 2. Password characters should contain only (A-Z,a-z,0-9,_).  \n 3. The database user password must contain three out of the following four elements:    \n Uppercase letters (A-Z)    \n Lowercase letters (a-z)    \n Digits (0-9)    \n Underscores (_)
DBSVR_NAME_ERROR=Server Name {0} is error.
ConfigDBServer.dbname.password.error=Failed to verify the password of the OSS database user {0}.
ConfigDBServer.Oracle.dbname.password.error=Failed to verify the OSS database user(s). \nClick Details to view the user(s).
finishedButton=Finish