
Backup.Title=Network Management System Backup Wizard
BackupWizardPage.Introduction=Welcome to Network Management System Backup Wizard
BackupWizardPage.Introduce=This backup wizard will guide you through the backup of the OSS database and component files. \nSelect a database backup mode and click <Next>.
BackupWizardPage.DatabaseBackup=Data Backup - Binary Mode (Recommended)
BackupWizardPage.TableBackup=Data Backup - Text Mode
BackupWizardPage.OracleEnvNotSet=The Oracle environment has not been configured on the server.
BackupWizardPage.FailedToGetDBLogonInfoFromDatamodel=Failed to obtain the database login information from the data model.
