BackupExitPage.Title=Backup succeeded.
BackupExitPage.Note=Click <Finish> to close the backup wizard.
BackupExitPage.ErrorTitle=Backup failed.
BackupExitPage.ERRORNote=Click <Exit> to close the backup wizard.
BackupExitPage.BackupSuccess=Backup succeeded.
BackupExitPage.BackupFailed=Backup failed.