Backup.ConfigParas.OK=OK
Backup.ConfigParas.Cancel=Cancel
Backup.ConfigParas.Browse=Browse...
Backup.tempPath=The temporary path for remote backup cannot be used. The possible causes are as follows:\n1.The available space for the temporary path is insufficient.\n2.The temporary path does not exist.\nEnter a temporary path.
Backup.BackupTitle=Select Temporary Path