
BackupDBProgress.DB_INUSE=The database is in use. Please try again.
UninstallApplicationTaskService.FailedTODELETE=Failed to delete the installation directory {name}.
AutoRollbackservice.FAILEDDELETE=Failed to delete the installation directory {name}. Manually delete it and continue automatic rollback.
Check.FolderAccessUpgrade=Failed to access installation folder "{installPath}". Check and click <Retry> to continue. \n Click <Cancel> to stop the upgrade.
Check.FolderAccessRollback=Failed to access installation folder "{installPath}". Check and click <Retry> to continue.\n Click <Cancel> to stop the rollback.
UpgradeTablesFailed=An error occurred when executing the scripts. Check logs for details.
UPGRADE_Table_FAIL=Table upgrade failed.
UPGRADE_Table_FAIL_rollback=Table upgrade failed. The automatic rollback is complete.
UPGRADE_Table_FAIL_rollback_cmd=Upgrade failed. The application will perform rollback. Please wait.
ExecuteScriptAction.SCRIPTNOTFOUND=No scripts found. Are you sure you want to continue?

BACKUP_SUCCEED=Backup succeeded.
BACKUP_ERR_NODE_STOP=The slave server is not started.
BACKUP_ERR_PATH_READONLY=The backup path is read-only.
BACKUP_ERR_COPY_FAILED=Failed to copy files.
BACKUP_ERR_NOT_MASTER_NODE=The server to which you log in is not the master server.
BACKUP_ERR_GET_IP_FAILED=Failed to obtain the IP address of the master server.
BACKUP_ERR_CONN_REMOTE_FAILED=Failed to connect to the remote server.
BACKUP_ERR_PATH_INVALID=Invalid backup path.
BACKUP_ERR_PATH_NOT_EXIT=The backup path is incorrect.
BACKUP_ERR_NO_SPACE=Insufficient disk space.
BACKUP_ERR_NO_ENV_PARA_ORACLE=The Oracle environment variable is not set.
BACKUP_ERR_LOGIN_FAILED=Failed to log in to the OSS maintenance tool server.
BACKUP_ERR_PARA=Parameter error.
BACKUP_ERR_DB_USER_NO_AUTH=The database user does not have permissions on the destination path.
BACKUP_ERR_NO_THIRD_COMPONENT=Third-party components are unavailable.
BACKUP_ERR_TRANS_FILE_FAILED=Failed to upload the file.
BACKUP_ERR_NET_SYS_RUNNING=The OSS is running.
BACKUP_ERR_CONN_FAILED=Failed to connect to the database.
BACKUP_ERR_BACKUP_SERVER_STOP=The database backup server is not started.
BACKUP_ERR_BACKUP_IN_PROCESS=There is one backup process is running, please try again later.
BACKUP_ERR_PARSE_XML_FAILED=Parse OSS database configuration files failed.
BACKUP_ERR_BACKUP_FAILED=Failed to back up the database.
BACKUP_ERR_DUMP_BCP_BACKUP_DB=Failed to backup database using Dump or bcp.
BACKUP_ERR_DATABASE_XML_PERMISSION_FAILED=Failed to read the database description file.
BACKUP_ERR_DB_STATUS_TITLE=Failed to excute pre-check database status script.

ADVICE_ERR_NODE_STOP=Refer to the relevant operation manuals to start services on the secondary site.
ADVICE_ERR_PATH_READONLY=Add the write permission on the directory for the database user.
ADVICE_ERR_COPY_FAILED=Reason can be:\n1.The file system has no enough free space.\n2.The files or directories do not exist or do not have permission to copy.
ADVICE_ERR_NOT_MASTER_NODE=Verify that the replication relationship is correct in the HA system and log in to the active server.
ADVICE_ERR_GET_IP_FAILED=Verify that the HA system works properly.
ADVICE_ERR_CONN_REMOTE_FAILED=Reason can be:\n1.The network is disconnected.\n2.The entered user name or password is not correct.
ADVICE_ERR_PATH_INVALID=Refer to relevant operation manuals to ensure that the backup path is valid.
ADVICE_ERR_PATH_NOT_EXIT=Back up data to a correct directory.
ADVICE_ERR_NO_SPACE=Clean up junk data from the disk in a timely manner.
ADVICE_ERR_NO_ENV_PARA_ORACLE=Contact Research and Development engineers for support.
ADVICE_ERR_LOGIN_FAILED=Verify that the MSuite server is running.
ADVICE_ERR_PARA=Contact Research and Development engineers for support.
ADVICE_ERR_DB_USER_NO_AUTH=Verify that the database user has the write permission on the target directory.
ADVICE_ERR_NO_THIRD_COMPONENT=Contact Research and Development engineers for support.
ADVICE_ERR_TRANS_FILE_FAILED=The possible causes are as follows:\n1.The network status is abnormal.\n2.The FTP/SFTP sever do not has enough free space.
ADVICE_ERR_NET_SYS_RUNNING=Disable OSS services.
ADVICE_ERR_CONN_FAILED=Failed to check the database. Possible cause:\n1.Database server is not running.\n2.Database is running abnormal.
ADVICE_ERR_ADVICE_SERVER_STOP=Check whether the database backup server is running.
ADVICE_ERR_BACKUP_ERR_PARSE_XML_FAILED=Check whether OSS database configuration files are configured properly.
ADVICE_ERR_BACKUP_FAILED=Contact Research and Development engineers for support.
ADVICE_ERR_BACKUP_IN_PROCESS=The database of the server is being backed up.\nPerforming another operation now may result in data inconsistency and thus causes potential system risks.
ADVICE_ERR_DUMP_BCP_BACKUP_DB=Failed to backup database using Dump or bcp.
ADVICE_ERR_DATABASE_XML_PERMISSION__FAILED=Failed to read the database description file.
BACKUP_ERR_DB_STATUS_DETAIL=Failed to excute pre-check database status script.

Summary.usedDbInfo=Used DB record for {0} are : \n
Summary.Process=Process = 
Summary.User= User = 
