BackupMediumPage.Introduction=Select a backup location.
BackupMediumPage.Attention=The database backup operation will directly back up data files that contain sensitive data, \nsuch as users' passwords and privacy. You are obliged to formulate a privacy policy according \nto the applicable law and take sufficient measures to fully protect the sensitive data.
BackupMediumPage.Introduce=Select a backup medium and click <Next>.
BackupMediumPage.LocalBackup=Local server
BackupMediumPage.RemoteBackup=Remote server
BackupMediumPage.IP=Server IP Address:
BackupMediumPage.TransferMode=Transfer Mode:
BackupMediumPage.UserName=User Name:
BackupMediumPage.Password=Password:
BackupMediumPage.Browse=Browse...
BackupMediumPage.PromptInputError=The backup information is incomplete. Enter complete backup information.
BackupMediumPage.DirNotExistCreateIt=Directory {0} does not exist. Do you want to create it?
BackupMediumPage.error=Error
BackupMediumPage.CREATE_PATH_FAIL=Failed to create the directory.
BackupMediumPage.CREATE_PATH_FAIL_REASON=Possible causes: Permissions not enough on the destination path. 
BackupMediumPage.invalidPath=1.The path must be a relative path that consists of characters, numbers, and hyphens (-) or underscores (_).\n2.The full path contains a maximum of 60 characters, and cannot contain blank space.
BackupMediumPage.PATH_HAVE_NO_PERMISSION=Permissions not enough on the destination path.
BackupMediumPage.DatabaseConnectionFailed=Failed to check the database. Possible cause:\n1.Database server is not running.\n2.Database is running abnormal.
BackupMediumPage.setGlobalSettingInfoFailed=Backup failed.
BackupMediumPage.ConnectionFailed=Failed to connect to the remote server.
BackupMediumPage.LoginFailed=Failed to log in to the server. Check the user name and password.
BackupMediumPage.prompt=Prompt
BackupMediumPage.readingDataModel=Initializing backup tasks... Please wait.
BackupMediumPage.FailedToGetDBLogonInfoFromDatamodel=Failed to obtain database login information from the data model.
BackupMediumPage.AllFolders=All Folders
BackupMediumPage.BackupServerNotRuuning=Backup services on the database are not running and cannot back up the database.
BackupMediumPage.DBInfoFileInvalid=sysconfigure.xml file or database configuration files not valid.
BackupMediumPage.SelectPolicy=Backup policy:
BackupMediumPage.BackupCountLabel=Maximum Number of Backup Files:
BackupMediumPage.PromptInvalidBackupCount=Incorrect number of backup files.
BackupMediumPage.PromptZeroBackupCount=Maximum number of backup files value should be between 1 and 9999.
BackupMediumPage.BackupFileDelete=If the backup operation succeed in the end, the following backup files \nwill be deleted. Do you want to continue?
BackupMediumPage.IsLocalIp=Can not use local server as FTP/SFTP server.
BackupMediumPage.pathNameInvalid =The path is invalid.

BackupMediumPage.BackupCountToolTip=(Note: When the number of backup files reaches the threshold, the earliest backup files will be automatically deleted.)
BackupMediumPage.INVALID_LOCAL_BACKUP_PATH=The selected path is incorrect.
BackupMediumPage.INVALID_REMOTE_BACKUP_PATH=The selected path is incorrect.\n1.The disk drive of the server must be selected.\n2.The path must be a relative path under FTP/SFTP user's home dir that consists of characters, numbers, and hyphens (-) or underscores (_),\nand contains a maximum of 60 characters, and cannot contain blank space.
BackupMediumPage.DetailError=The possible causes are as follows: \n 1. The IP address is incorrect. \n 2. The user name or password is incorrect. \n 3. The remote service is not started.
BackupMediumPage.LocalBackupPath=Backup Path:
BackupMediumPage.RemoteBackupPath=Backup Path:
BackupMediumPage.InputError=The backup information is incomplete.
BackupMediumPage.InCompleteIP=The remote server IP address is empty.\n
BackupMediumPage.InCompleteUserName=The user name is empty.\n
BackupMediumPage.InCompletePath=The path is empty.\n
BackupMediumPage.InCompletePassword=The password is empty.\n
BackupMediumPage.PasswordMismatch=The password must contain less than 60 characters \nand consists of only the following characters:\n
BackupMediumPage.IpInvalid=The IP address is incorrect.\n
BackupMediumPage.Solution=An operation anomaly results in a failure to run the engineering server. Restart the engineering server.
BackupMediumPage.NMSALIVE=The OSS is running. Ensure that the OSS is not performing configurations. \n Otherwise, some data will be lost after database backup. \n Are you sure you want to continue?
BackupMediumPage.NMSALIVEMSG=OSS services are running on the following hosts:
BackupMediumPage.BrowseWindowLookIn=View
BackupMediumPage.BrowseWindowFileName=File Name:
BackupMediumPage.BrowseWindowOpen=Open
BackupMediumPage.BrowseWindowCancel=Cancel
BackupMediumPage.NMSALIVEMSGCMD=Click (Y) to continue backup.\nClick (N) to quit backup.
BackupMediumPage.SelectFTPWarning=The FTP transmission mode is used currently. The transmission\ncontents are not encrypted and therefore security risks exist.\nThe SFTP transmission mode is strongly recommended.\nAre you sure you want to continue?
BackupMediumPage.SelectFTPOk=OK
BackupMediumPage.SelectFTPCancel=Cancel
BackupWizardPage.SSHConnectionFailed = Failed to connect to the remote database server using SSH.