[Public_Operate]
OPERATE_RESULT_SUCCESS=SUCCESS
OPERATE_RESULT_FAILED=FAIL
MODULE_ICMR=ICMR
MODULE_INSTALLDISK=InstallDisk
MODULE_MSUITE=
MODULE_UPGRADE=
MODULE_PATCH=
OPERATE_ICMR=
[/Public_Operate]


[Install_Operate]
OPERATE_INSTALL=Install @{LicenseProductName} @{LicenseProductVersion} OSS
OPERATE_UNINSTALL=Uninstall @{LicenseProductName} @{LicenseProductVersion} OSS
OPERATE_ADDNODE=Add @{LicenseProductName} @{LicenseProductVersion} OSS node
OPERATE_INCREMENTINSTALL=Incrementally install @{LicenseProductName} @{LicenseProductVersion} OSS
OPERATE_INSTALLCLIENT=Install @{LicenseProductName} @{LicenseProductVersion} OSS client
OPERATE_UNINSTALLCLIENT=Uninstall @{LicenseProductName} @{LicenseProductVersion} OSS client
[/Install_Operate]


[Deploy_Operate]
MSuite_Query=Query OSS deployment information
MSuite_SyncOSSInfo=Synchronize OSS deployment information to the OSS maintenance tool
MSuite_DelNode=Delete the slave node {0}
MSuite_InitialDB=Initialize the OSS database
MSuite_ChangeDTPwd=Change the MSuite Administrator password
MSuite_Logout=Log out from the maintenance server
MSuite_DelComponent=Delete component {0}
MSuite_AddComponent=Add component {0}
MSuite_AddInstance=Add instance {0}
MSuite_DelInstance=Delete instance {0}
MSuite_MoveInstance=Move instance {1} from {0} to {2}
MSuite_LicenseDeploy=Deploy by license
MSuite_ModifyInstanceMemo=Modify instance memo information
MSuite_ChangeDBSAPwd=Change the DataBase Administrator password
MSuite_ChangeDBUserPwd=Change the DataBase User password
MSuite_ChangeTimeZone=Change the time zone to {0} and the time to {1}
MSuite_ConfigNTP=Set the NTP server to {0}
MSuite_ConfigNTP_FAILED=Set the NTP server
MSuite_JoinHA=Synchronize the primary node {0} and the secondary node {1}
MSuite_SplitHA=Separate the primary node {0} and secondary node {1}
MSuite_ForcePrimary=Force {0} to be the active server
MSuite_ConfigNetWork=Configure IP address and host name of node {0}
MSuite_ModifyFloatIp=Modify float IP address
MSuite_ConfigRouter=Configure route information for node {0}
MSuite_ConfigRouter_Detail=Configure route information for node {0}.{1}
MSuite_SyncNetWork=Synchronize the network configuration of OSS
MSuite_Backup=Back up OSS data to path {3} on server {2} in {1}{0}
MSuite_Restore=Restore OSS data from {3} on server {2} in {1}{0}
Commssioning_AddInstance=Add instances by commissioning tool
Commssioning_ChangePValue=Change the {0} password
Commssioning_ChangeHostname=Configure host name from {0} to {1}
Commssioning_PreExport=Export pre-commissioning system information
Commssioning_AfterExport=Export completed commissioning system information
MSuite_Backup_Common=Back up OSS data 
MSuite_Restore_Common=Restore OSS data
MSuite_Delete_Backup_File=Delete Backup File(s)
MSuite_Delete_Backup_File_Local=Delete Backup File(s):{0}
MSuite_Delete_Backup_File_remote=Delete Backup File(s):{0} at server {1} by user {2}
MSuite_Verify_Rule=Verify password rule for {0}
Commssioning_Precheck=Commssioning precheck
[/Deploy_Operate]

[Patch_Operate]
PatchExitPage.Operation.Detail.install=Install {0} {1} patch
PatchExitPage.Operation.Detail.unInstall=Uninstall {0} {1} patch
PatchExitPage.Operation.result.succeed=Successful
PatchExitPage.Operation.result.failed=failed
PatchExitPage.Operation.type.install=Patch disk installation
PatchExitPage.Operation.type.unInstall=Patch disk uninstallation
[/Patch_Operate]

[Deploy_Operate]
MSuite_DeployByDomain=Deploy by domain
MSuite_unDeployByDomain=Undeploy by domain
[/Deploy_Operate]
