INIT_DB_SUCCESS=Succeeded in initializing the database.
INIT_DB_FAILED=Failed to initialize the database.
PARA_CFG_SUCCESS=Succeeded in setting database parameters.
PARA_CFG_FAILED=Failed to set database parameters.
ProgressPage.InitDatabaseTitle=Initializing the database... Please wait.
ProgressPage.DeleteDataBase=Deleting database data.... Database name:{0}
initdbcheck.DiskSpaceNotEnoughError=The disk space is insufficient on device {0}.Required space: {1} MB; Free space: {2} MB.
CREATE_DATABASE_FAILED=Create database {0} failed.
WORKFLOW_ALREADY_RUNNING=Initial Database workflow already running.