SubsystemName=Component Name: 
BackupVersion=Backup version: 
CurrentVersion=Current version: 
InstanceToBeAdded=The following instances need to be added:
InstanceToBeDeleted=The following instances need to be deleted:
SubsystemToBeAdded=Missing components:
SubsystemToBeDeleted=Extra components:
SubsystemCompressFileFailed=Failed to obtain backup of {0} component files. The backup operation cannot be continued.

RestoreWorkFlow.Title=Restoring... Please wait.
PrepareRestoreWorkFlow.Title=Preparing for restoration... Please wait.
Task.RestoreDatabasesAdditional=Restore the database table.
Task.RestoreDatabases=Database restoration:

[ErrorPrompt]
STARTWORKFLOW_SUCCESS=Succeeded in starting the workflow.
LOGIN_NOTMASTER=The login server is not the master server.
NODE_OFFLINE=The existing servers cannot be connected. 
NODE_READONLY=The existing servers are unwritable.
SUBSYSTEM_NOTVALID=OSS version mismatch.
DBMGRINIT_FAILED=Failed to start the initialization database workflow.
DBMGRCFG_FAILED=Failed to start the configuration database workflow.
COMMAND_WRONG=The command is invalid.
MASTER_NODE_IP_INVALID=The IP address of the master server is empty or invalid.
CHECK_BACKUP_INFO_FAILED=No backup file is found. Enter a correct path.
DSPARAM_SERVER_INFO_WRONG=Failed to log in to the server.Reason can be: \n 1.The IP address is incorrect. \n 2.The user name or password is incorrect. \n 3.The remote service is not started.
DSPARAM_DIR_WRONG=The path is invalid.
DSPARAM_DIR_NOTEXITS=No backup file is found. Enter a correct path.
DSPARAM_PAESE_FAILED=Failed to parse the ds parameter.
DSPARAM_DIR_NOPESSION=1.The user has no permission on this path for the remote server.\n2.There is not enough space on this path for the remote server.
LOCAL_SYSTEM_OSSENGR_SPACE_NOT_ENOUGH=The available disk space is insufficient at partition "{0}", required space at least:{1}MB, free space:{2}MB.
DISK_NOT_ENOUGH=The available space for {0} is insufficient.\nRequired space:{1}MB,\nAvailable space:{2}MB
LOCAL_SYSTEM_SPACE_NOT_ENOUGH=The available disk space is insufficient. Partition "{0}", required space:{1}MB, free space:{2}MB.
LOCAL_TMPDIR_SYSTEM_SPACE_NOT_ENOUGH=The available disk space of local machine is insufficient. Partition "{0}", required space:{1}MB, free space:{2}MB.
REMOTE_SYSTEM_SPACE_NOT_ENOUGH=The available disk space is insufficient on remote Database server. Partition "{0}", required space:{1}MB,free space:{2}MB.
RESULT_ALREADY_SCHEDULED=The scheduled backup task has been created.
RESULT_TASK_NAME_NULL=The task name is empty.
RESULT_START_TIME_ERROR=The start time is incorrect. It must be in 24-hour format. For example 1320 stands for 1:20 pm.
RESULT_DELETE_TASK_SUCCESS=Succeeded in deleting the schedule backup task.
RESULT_DELETE_TASK_FAILED=Failed to delete the schedule backup task.
RESULT_SCHEDULE_BACKUP_MESSAGE=The backup task is scheduled, with the start time as {0} and the interval as {1} hour.
RESULT_NO_SCHEDULE_BACKUP_FOUND=No scheduled backup task is created.
RESULT_NEW_SUBSYSTEMS_TO_BE_ADDED=Add new subsystems.
ORACLE_ENVIRONMENT_CHECK_FAILED=The Oracle environment cannot be set on the server.
LOGIN_FAIL=Login fail
UNKNOWN_CLI_PARAMETER=Unknown command line parameter
ORACLE_SPACE_CHECK_FAILED=Failed to check the Oracle space.
NO_PERMISSION_TO_USER=User {0} does not have permissions on path {1}.
INVALID_TEMP_PATH=The available space for the temporary directory is insufficient \n to complete the remote operation.
INVALID_DRIVE_BACKUP=The temporary directory is invalid.
CHECK_BACKUP_INFO_MISMATCH_DATABASETYPE=Failed to back up data in binary mode during restoration in text mode.
CHECK_BACKUP_INFO_MISMATCH_BCPTYPE=Failed to back up data in text mode during restoration in binary mode.
NMS_SERVER_RUNNING=The OSS server is running.
BACKUP_SUCCESSS=Backup succeeded.
BACKUP_FAIL=Backup failed.
RESTORE_SUCCESS=Restoration succeeded.
RESTORE_FAIL=Restoration failed.
RESTOREPRE_SUCCESS=Succeeded in restoring the pre-processing operation.
RESTOREPRE_FAIL=Failed to restore the pre-processing operation.
FREEZE_FAIL=Failed to freeze the HA system. View operation logs.
JOBCREATE_FAIL=Failed to create the task.
RESTORE_INSTANCEMISMATCH=Instance mismatch
RESTORE_SUBSYSTEMMISMATCH=Subsystem mismatch
RESULT_UNKNOWN=Unknown error.
DB_TMP_DISKSPACE_NOTENOUGH=The disk space on partition {0} is insufficient. Required space more than {1}MB.
[/ErrorPrompt]