DELETE_SYSTEM_FILE_FAIL=Failed to delete subsystem files.
DeleteComponentWorkflow.Title=Deleting components...
InstallServerWorkflow.InstallTitle=Installing components...
IncrementInstallWorkflow.PrimaryTitle=Installing components on primary server...
IncrementInstallWorkflow.SecondaryTitle=Installing components on secondary server...
DELETE_SUBINSTANCE_CONNECT_DATABASE_FAIL=Failed to delete instances. Check whether the database connection is set up.
RunCheckUnDeployScriptNull=The name or path of the check script for deleting instances is empty.
RunCheckUnDeployScriptFail=Failed to execute check scripts for deleting instances.
DELETE_SUBINSTANCE_DELETE_DATABASE_FAIL=Failed to delete the instance database.