
ADD_DATAMODEL_FAILED=Failed to add the subsystem to the data model.
ADD_SITE_INFO_DATAMODEL_FAILED=Failed to add site information.
ADD_SYSTEM_INFO_DATAMODEL_FAILED=Failed to add the system to the data model. The system version is {0}.
ADD_SUBSYSTEM_INFO_DATAMODEL_FAILED=Failed to add subsystem {0} to the data model.
ADD_NODE_INFO_DATAMODEL_FAILED=Failed to add node information to the data model. The node IP address is {0}.
UNZIP_FILE_FAILED=Failed to unzip file {0}.
INIT_MACRO_ATTRIBUTE_VALUE_NULL=The attribute value is empty.
EXEC_POST_INIT_FAILED=Failed to execute post-initialization.
TRANSFER_PROCESS_FILE_FAILED=Failed to transfer the process file.
UPDATE_DATABASE_INFO_FAILED=Failed to update database information from the data model.
CREATE_NMSUSER_FAILED=Failed to create the ossuser user. Check whether the ossuser user already exists.
TRANSFER_PACKAGE_DATA_FAILED=Failed to transfer package data to the slave node. \nCheck whether the server is connected properly and whether information contained \nin the package is correct.
TRY_SQL_CONNECTION_FAILED=Failed to connect to the database SQL.
