ProgressPage.JoinHA.Title=Synchronize HA System...
ProgressPage.JoinHA.RelateDatamodel=Associate with Data Model...
ProgressPage.JoinHA.ConfigLocalVCS=Configure Local VCS...
ProgressPage.JoinHA.ConfigRemoteVCS=Configure Remote VCS...
ProgressPage.JoinHA.CreateLocalRep=Create Local Replication...
ProgressPage.JoinHA.CreateRemoteRep=Create Remote Replication...
ProgressPage.JoinHA.ExecutePostscript=Execute post scripts...
ProgressPage.JoinHA.SyncDynamicFiles=Synchronize dynamic files...

ProgressPage.SplitHA.Title=Separate Primary Site from Secondary Site...
ProgressPage.SplitHA.DeleteLocalVCS=Delete Local VCS Configurations...
ProgressPage.SplitHA.DeleteRemoteVCS=Delete Remote VCS Configurations...
ProgressPage.SplitHA.DeleteLocalRep=Delete Local Replication...
ProgressPage.SplitHA.DeleteRemoteRep=Delete Remote Replication...
ProgressPage.SplitHA.UnrelateDatamodel=Disable Association with Data Model...

PROMPT_MSG_NODE_NOT_MATCHED=<html>The number of nodes to be associated with the primary site and that for the secondary site are different.<br>Local site:{0}<br>Remote site:{1}</html>
PROMPT_MSG_SUBSYSTEM_NOT_MATCHED=<html>The following deployment packages do not match. <br>Local site:{0}<br>Remote site:{1}</html>
PROMPT_MSG_INSTANCE_NOT_MATCHED=<html>The following instances do not match.<br>Local site:{0}<br>Remote site:{1}</html>
PROMPT_MSG_SUBSYSTEM_IN_NODE_NOT_MATCHED=<html>The deployment packages to be associated with nodes for the primary and secondary sites are different.<br>Local site:{0}<br>Remote site:{1}</html>


ProgressPage.ForcePrimary.Title=Force Local Site as Primary...
ProgressPage.ForcePrimary.CheckRep=Check Replication Relationship...
ProgressPage.ForcePrimary.Offline=Shut Down Secondary Site...
ProgressPage.ForcePrimary.Resync=Resynchronize...
ProgressPage.ForcePrimary.DeleteRemoteRep=Add Clusters...
ProgressPage.ForcePrimary.OnLine=Start OSS...
ProgressPage.finish=finish

ProgressPage.DualPrimary.Title=Dual-Host...
ProgressPage.DualPrimary.CheckRep=Check Replication Relationship...
ProgressPage.DualPrimary.DelRep=Delete Replication Relationship...
ProgressPage.DualPrimary.SinglePoint=Create Single-Point Replication...
ProgressPage.DualPrimary.DeleteRemoteRep=Delete Local Cluster Attributes...
ProgressPage.DualPrimary.OnLine=Start OSS...

ProgressPage.DelRep.Title=Delete Replication Relationship...
ProgressPage.DelRep.DelRep=Delete Remote Replication Relationship...
ProgressPage.DelRep.CheckRep=Check Result of Deleting Remote Replication Relationship...
ProgressPage.DelRep.DelRemoteRep=Delete Local Replication Relationship...
ProgressPage.DelRep.CheckRemoteRep=Check the Result of Deleting Local Replication Relationship...
OWNER_NODE_IS_DIFFERENT=Not locate on the matched server.
OWNER_SUBSYSTEM_IS_DIFFERENT=Not locate in the matched deploy package.
INSTANCE_NOT_MATCHED=Do not match.
ProgressPage.JoinHA.checkDatabase=Checking database...
ProgressPage.JoinHA.checkVolume=Checking volume...
ProgressPage.JoinHA.startVCS=Starting remote VCS...