InstallInterface.Title=Incremental Installation
InstallInterface.addnodeTitle=Addnode Installation
InstallInterface.reinstallTitle=Reinstallation

MENU_SYS=System
MENU_OP=Deploy
MENU_OP_ADDSLAVES=Add Slave Server...
MENU_ADD_COMPONENTS=Add Component...
FileChooser.Browse=Browse Folder
FileChooser.Confirm=OK
FileChooser.Cancel=Cancel

[DBServerInfo]
DBServerInfoPage.Title=Manage Database Server Information
DBServerInfoPage.InitialFailed=Failed to initialize the database configuration information.
DBServerInfoPage.DBInfoRepeated=The list contains duplicated database server information. Delete unwanted information.
DBServerInfoPage.dbIDLabel=ID:
DBServerInfoPage.dbServerNameLabel=Database Server Name:
DBServerInfoPage.dbServerPortLabel=Database Server Port:
DBServerInfoPage.dbTypeLabel=Database Server Type:
DBServerInfoPage.hostFixIPLabel=Fixed server address:
DBServerInfoPage.hostFloatIPLabel=Float server address:
DBServerInfoPage.racAddress1Label = Oracle RAC address 1:
DBServerInfoPage.racAddress2Label = Oracle RAC address 2:
DBServerInfoPage.racAddress3Label = Oracle RAC address 3:
DBServerInfoPage.racAddress4Label = Oracle RAC address 4:
[/DBServerInfo]


[SoftwareLib]
SoftwareLibSelectPage.Choose=Browse...
SoftwareLibSelectPage.PathTitle=Select the software library to be used for the incremental installation:
SoftwareLibSelectPage.RefreshPath=Refreshing the software library... Please wait.
SoftwareLibSelectPage.Title=Select Software Library Directory
SoftwareLibSelectPage.BackupFailed=Failed to back up the OSSENGR directory.
SoftwareLibSelectPage.InitialFailed=Failed to initialize the software library.
SoftwareLibSelectPage.SyncFailed=Failed to synchronize the static data model.
SoftwareLibSelectPage.ChangcfgFailed=Failed to change the software library configurations.
SoftwareLibSelectPage.CheckPathEmpty=The software library path cannot be empty.
SoftwareLibSelectPage.CheckPathFailed=Failed to check the software library path.
SoftwareLibSelectPage.ScriptExecFailed=Failed to copy the database script @SCRIPTNAME.
SoftwareLibSelectPage.ProcessFinish=Software library updated successfully.
[/SoftwareLib]

[StartSubNodeServer]
StartSubNodeServerPage.Title=Start Slave/Standby Servers
StartSubNodeServerPage.CheckNodes=add nodes failed
StartSubNodeServerPage.StartFailed=Failed to start the slave/standby servers.
StartSubNodeServerPage.StartSuccess=Slave/standby servers started successfully.
StartSubNodeServerPage.LoginFailed=Failed to log in to the slave/standby servers.
StartSubNodeServerPage.FailDetail=Failed to start from the following nodes:\n{0}\n\nPossible causes are as follows:\n1. Port 12212 is in use.\n2. Connection to the slave/standby server failed.\n3. Failed to start product plugin.
[/StartSubNodeServer]


[ComponentTree]
ComponentTree.Title=Select Installation Component.
ComponentTree.NO_PKG_FILE_LIST=Deployment packages for the following components are unavailable:\n Are you sure you want to continue?
ComponentTree.NO_PKG_FILE_TITLE=The package file does not exist
ComponentTree.watiProgress=Processing... please wait.
[/ComponentTree]


[ServiceGroup]
ConfigServiceHostPage.Title=Configure Service Group
help=Help

only_master=Deploy only the master server
only_slave=Deploy only the slave server
any_server=Deploy any server
all_must=Deploy all servers

single_single_type=Single-node single-instance type
mutil_type=Multi-instance type
system_single_type=Single-instance system type
none_type=No instances type

servicegroup_info=[Service Group Info]
hostInfoName=Node Name:

the_select=The selected node is:
must_select_one_servergroup=Select at least one service group.
must_select_one_host=Select at least one host.
must_select_one_host_node=Select at least one host node.

the_below_not_mutil_host=A single instance cannot be deployed on multiple servers.
the_below_only_mutil_slave_host=The following nodes can be deployed only on the slave server:
the_below_only_master=The following nodes can be deployed only on the master server:
the_below_must_all_host=The following nodes must be deployed on all servers. Select all server nodes.
[/ServiceGroup]


[Subsystem]
ConfigDeploymentsSubsystem.Title=Set the Number of Multi-Instance Subsystem Instances.
ConfigDeploymentsSubsystem.Node=Node
ConfigDeploymentsSubsystem.Subsystem=Service Group
ConfigDeploymentsSubsystem.SubsystemType=Deployment Package
ConfigDeploymentsSubsystem.InstanceCount=Count
ConfigDeploymentsSubsystem.SubsystemDescription=Description
ConfigDeploymentsSubsystem.MultipleInstances=Single-server multi-instance

ConfigDeploymentsSubsystem.SubsystemInfo=Component Information
ConfigDeploymentsSubsystem.Summary_NodeName=Server Name:
ConfigDeploymentsSubsystem.Summary_Subsystem=Component:
ConfigDeploymentsSubsystem.Summary_SubsystemType=Component Type:
ConfigDeploymentsSubsystem.Summary_InstanceCount=Instance Count:
ConfigDeploymentsSubsystem.Summary_SubsystemDescription=Description:
[/Subsystem]


[Summary]
Summary.Title=Confirm Installation Information
Summary.Prompt=Prompt
Summary.Retry=Retry
Summary.CheckDisk=Checking disk space... Please wait.
Summary.EmptyData=No subsystem information found.
Summary.InvokeFail=Failed to obtain brief information.
Summary.NewDataCheck=No new components found.\nClick <OK>. Then click <Previous> to return to the software library page and select components again.\nClick <Cancel> to exit the incremental installation.
[/Summary]

[Progress]
IncrementInstallProgressPage.Title=Incremental Installation Progress
IncrementInstallProgressPage.Installing=Installing... Please wait.
IncrementInstallProgressPage.InstallFailed=Failed to perform incremental installation.
[/Progress]

[ExitPage]
IncrementInstallExitPage.addnodeFinishTitle=Addnode installation completed.
IncrementInstallExitPage.reinstallFinishTitle=Reinstallation completed.
IncrementInstallExitPage.FinishTitle=Incremental installation completed.
IncrementInstallExitPage.FailedTitle=Incremental installation failed.
IncrementInstallExitPage.FinishNote=Incremental installation completed.\nPress <Finish> to exit.
IncrementInstallExitPage.FinishNoteCMD=Incremental installation completed.
IncrementInstallExitPage.FailedNote=Installation failed.
IncrementInstallExitPage.needRestartOSS=If the OSS has been started, restart it.
[/ExitPage]
DB_CONNECT_FAILED=Failed to connect to the following databases. Check whether the database server is running.
HA_Synchronize_Check=Primary is synchronizing with secondary. Please split HA first.
following_node_not_trust=Failed to communicate between the primary node and the following node(s)
Summary.check.error= The summary information check has the following error(s).


[msuitestart]
CHECK_NODE_START=Start to check all node information.
CHECK_NODE_FAIL=Failed to check node information. Exit from node addition.
CHECK_NODE_END=Node information checked successfully.
CHECK_DATABASE_START=Start to check all database information.
CHECK_DATABASE_FAIL=Failed to check database information. Exit from node addition.
CHECK_DATABASE_END=Database information checked successfully.
TRANSFER_ENGR_FRAME_START=Start to synchronize engineering frame to all nodes, maybe it will take several minutes...Please wait.
TRANSFER_ENGR_FRAME_FAIL=Failed to synchronize data. Exit from node addition.
TRANSFER_ENGR_FRAME_FAIL_UPGRADE=Failed to synchronize data. Exit from upgrade install.
TRANSFER_ENGR_FRAME_END=Data synchronization is complete.
INCINSTALL_PATH_INVALID=The path for incremental installation is incorrect. Silent incremental installation failed.
LAUNCH_UPGRADE_INSTALL=Launch upgrade install.
UPGRADE_INSTALL_WORKFLOW=Start upgrade install workflow.
UPGRADE_INSTALL_FINISHED=Upgrade install Finished.
CHECK_DATABASE_FAIL_UPGRADE=Failed to check database information. Exit from upgrade install.
CHECK_NODEINFO_DIRVALID=Check node info failed,please check all node oss path is exists or trust is invalid. UpgradeInstall will exit
CHECK_NODEINFO_DIRVALID_SINGLE=Check node info failed,please check all node oss path is exists. UpgradeInstall will exit
[/msuitestart]


SiteType_single_not_support_addnode=Add node just for distribute server or dual server.
dual_sitetype_have_two_node=Dual server have installed two nodes.
IncrementInstallCheck.Retry=Retry
IncrementInstallCheck.title= Environment Check
Installed_NMS_dir_Not_exist=The OSS directory does not exist on the following node(s).
FAILED_INVOKE_RPC=Failed to connect to the server {0}. Check the status of node manager.
InstallDirNotEmpty=The installation directory is not empty on the host. Select another path.
UPGRADE_INSTALL_LOGIN_FAILED=login failed! Please check if the loopback IP was invalid or port {0} was occupied or certification was invalid.
NO_NEW_NODES=It has not contains new node, can not execute add node operate.
ONLY_ADD_DB_CREATE_INTERFACE=Copy database interface failed with addding db.
ONLY_ADD_DB_SUCCESS=Add DB nodes success.
