ClientCopyRight.ContentsVerify=This verification wizard will guide you through the verification of installation packages.
ClientCopyRight.Contents=This installation wizard will guide you through the process of installing the {0}. Please read the following terms:
ClientCopyRight.NotAuthority=The user rights are restricted. The program will exit.
ClientCopyRight.Agree=I accept these terms
ClientCopyRight.Disagree=I do not accept these terms
ClientCopyRight.Cancel=Are you sure you want to cancel the installation?
ClientCopyRight.Yes=Yes
ClientCopyRight.No=No
ClientCopyRight.ReadClientCopyRight=Read the following agreement carefully:
ClientCopyRight.ReadCopyRight=Read the following agreement carefully:
ClientCopyRight.Title=Client Copyright Notice

