ClientInstallExitPage.ErrorNote={0} Installation failed. For details, see the log {1}.
ClientInstallExitPage.Note=The {0} client has been installed to {1}. Click <Finish> to exit.\n Manually backing up the installation directory is recommended. If the installation file is corrupted, the backup data can be used to restore the file.\n
ClientInstallExitPage.ErrorTitle=Installation failed.
ClientInstallExitPage.Title=Installation completed
ClientInstallExitPage.Finish=Finish
ClientInstallExitPage.NoteCMD=The {0} client has been installed to {1}. \n Manually backing up the installation directory is recommended. If the installation file is corrupted, the backup data can be used to restore the file.

