ClientSummary.Title=Confirm Installation
ClientSummary.Prompt=Information
ClientSummary.CheckMemAndDisk=Checking disk space... Please wait.
ClientSummary.Retry=Retry
ClientSummary.DiskSpaceNotEnoughCMD=The disk space is insufficient.
ClientSummary.Cancel=Exit installation
ClientSummary.Previous=Previous


ClientInstallUtil.SetupModeNotSupply=The component file is empty. The program will exit.
ClientInstallUtil.Error=Error
ClientInstallUtil.Unselected=Select a component.
ClientInstallUtil.NotAuthority=The user rights are restricted. The program will exit.
ClientInstallUtil.AllPackagesInstalled=All components are installed.
ClientInstallUtil.Hint=Information
ClientInstallUtil.IsVersionConflict=Version conflict. Cannot continue the installation.
ClientInstallUtil.ConflictDetail=The selected component or patch conflicts with the current version. Cannot continue the installation.
ClientInstallUtil.InvalidCopyFilesClass=Failed to initialize the JAR file filter.
ClientInstallUtil.DependenceError=The dependency between components is incorrect. For example, a dependency loop occurs.\nView the logs for details.
ClientInstallUtil.NotFindXMLFilesContent=No components can be installed.
ClientInstallUtil.ClientMode=Client Only
ClientInstallUtil.PathIsNull=The installation path cannot be empty.
ClientInstallUtil.CheckInstallPathChar=The installation path cannot contain special characters but letters, numbers, and underscores.
ClientInstallUtil.IsNotMatchProductRule=The installation path does not match the path rule. Set the path by referring to the installation guide.


ClientSummaryUtil.DiskSpaceNotEnough =The disk space on partition {0} is insufficient.
ClientSummaryUtil.ActualDiskSpace =Available Disk Space:
ClientSummaryUtil.NeededDiskSpace =Required Disk Space:
ClientSummaryUtil.BaseInfomatin =[Basic Information]
ClientSummaryUtil.InstallPath =Installation Path:
ClientSummaryUtil.OSType =OS Type:
ClientSummaryUtil.OSVersion =OS Version:
ClientSummaryUtil.ProductVersion=Product Version:
ClientSummaryUtil.drive =Drive:
ClientSummaryUtil.isCreateShotcutOnDesk = Do you want to create a shortcut on the desktop?
