ClientInstallProgress.CopyingFilesPleaseWait=Installing client... Please wait.
ClientInstallProgress.CopyShowTime=Minutes
ClientInstallProgress.InstallDiskXml=Executing installation scripts...
ClientInstallProgress.InstallComplete=Installation completed.



ClientInstallTask.CopyError=Failed to copy files. The program will exit.
ClientInstallTask.UninstallInformation=Saving installation information...
ClientInstallTask.RecoverError=Failed to restore the file {0}. Are you sure you want to continue?
ClientInstallTask.IsDiskFull=The disk is full. \nClear it and retry, or click <Cancel> to exit the installation.
ClientInstallTask.UnzipFiles=Decompressing {0}...
ClientInstallTask.CopyingFile=Copying file...
ClientInstallTask.CopyJRE=Copying JRE...
ClientInstallTask.CopyUninstallFolderContent=Creating uninstallation files...
ClientInstallTask.CreateShotcuts=Creating shortcuts...
