ClientExportDeploySchema.ExportDeploySchemaFile=Export Predefined Deployment File:
ClientExportDeploySchema.Browse=Browse (B)
ClientExportDeploySchema.InvalidPath=Enter a correct file name.
ClientExportDeploySchema.Next=Next
ClientExportDeploySchema.DiskError=The selected partition is incorrect.
ClientExportDeploySchema.DirectoryMustBeCharAndNum=1.The disk drive for the server must be selected.\n2.The path must be an absolute path that consists of characters, numbers, and hyphens (-) or underscores (_), \n3.and the path name contains a maximum of 60 characters. No space should exist before \\, / or colon (:).
ClientExportDeploySchema.Error=Error
ClientExportDeploySchema.FileExist = The file already exists. \nDo you want to replace it?

