CMDWizardFrame.install = Install
CMDWizardFrame.uninstall = Uninstall
CMDWizardFrame.next = Next >>
CMDWizardFrame.previous = << Previous
CMDWizardFrame.cancel = Cancel
CMDWizardFrame.hint = Information
CMDWizardFrame.InstallAffirmCancel = Are you sure you want to cancel the installation?
CMDWizardFrame.UninstallAffirmCancel = Are you sure you want to cancel the uninstallation?
CMDWizardFrame.UpdateAffirmCancel = Are you sure you want to cancel the upgrade?
