
[Common]
Commissioning.Menu.Tool=Tools
Commissioning.Menu.Title=Commissioning Tool...
CommissioningTool=Commissioning Tool
APP_BUTTON=Apply
CheckDB_NMSStatus=Checking DB / NMS running status...
DBNotRunning=Failed to check the database. Possible cause:\n1.Database server is not running.\n2.Database is running abnormal.
NMSisRunning=The OSS is running on the server. Please stop it first.
HAjoined=Primary is synchronizing with secondary. Please split HA first.
NeedRebootFirst=The system configuration has been changed, please reboot the system first to take effect.
NEXT_STEP_PROMPT=Data has been changed, submit it?
INPUT_NOT_FULL=Input data is not full, continue input?
Commissioning.Confirm=Commissioning tool applies to the production of pre-installed, combined\nwith the actual network parameters to configure the system. It can be\nused to detect the current configuration, you can modify the host name,\nadjust the networking solution, change time and timezone, change passwords,\nconfigure the OSS, configure routing, enable the security reinforcement.\n\nPreconditions:\n1. Make sure that network management is stoped.\n2. Make sure that the database is running.{0}\n\n Commissioning Steps:\n1. According to the current network planning active and standby host name,\n    IP address, password, time and timezone.\n2. Stop the NMS, keep the database online.\n3. Run tune Commissioning tool.\n4. Check the existing configuration.\n5. Commissioning as the Commissioning Wizard.\n\nPrecautions: \nIP networking adjustment clears all the manually configured IP information.\nBack up the information before performing the adjustment and configure\nthe information again after the adjustment is complete.\n
Commissioning.Confirm.hainfo=\n3. Make sure that the HA have not been joined.
Commissioning.start=Start
Commissioning.cancel=Cancel
DataNotChanged=The new data is the same as the old data.
Colon=:
MSERROR_NMSONLINE_ChECK=The OSS services are running. Stop them and try again.
MSERROR_NMSONLINE_ChECKMSG=The OSS services are running on the following hosts:
CommssioningPrecheckFailed=Commssioning precheck failed.
[/Common]


[WelcomPage]
QUERY_INFO=Collecting Config Information...
Commissioning.collectfailed=Collect failed
Commissioning.Page.WelcomeSummary=Pre-Commissioning System Information
sec_hardware=Hardware Information
sec_hardware_cpu=CPU:
sec_hardware_ram=RAM:
sec_hardware_disk=Disk:

sec_software=Software Information
sec_software_OSVersion=OS Version:
sec_software_NMSversion=OSS Version:
sec_software_installtype=Install Type:
sec_software_databasetype=Database Type:
sec_software_databaseversion=Database Version:
sec_software_databasesize=Database Size:
sec_software_VCSversion=VCS Version:

sec_securityset=Security Set
sec_securityset_version=Version:
sec_securityset_isinstalled=Is Installed:
sec_securityset_installed=installed
sec_securityset_uninstalled=Not Installed
sec_securityset_set=Security Set Status:
sec_securityset_notrunning=Not Running
sec_securityset_running=Running

sec_datetime=Date Time Zone and Time
sec_datetime_date=Date:
sec_datetime_time=Time:
sec_datetime_timezone=Time Zone:

sec_ntp=NTP
sec_ntp_status=NTP Status:
sec_ntp_config=NTP Configure:
sec_ntp_serverip=Server IP Address:
notrunning=Not Running
running=Running
ntpClient=Client
ntpMedialServer=Medial Server
ntpSeniorServer=Senior Server
noconfig=Not Conifgured
unknow=Unknown

sec_virussoft=Tendence Anti-Virus Software
sec_virussoft_isinstalled=Is Installed:
sec_virussoft_unintalled=Not Installed
sec_virussoft_officever=Version:
sec_virussoft_virusver=Viruslib Version:

sec_router=Route
sec_router_destination=Destination
sec_router_netmask=Netmask
sec_router_gateway=Gateway

sec_network=Network Configure
sec_network_interface=Interface
sec_network_ip=Ip Address
sec_network_netmask=Netmask
sec_network_iptype=Ip Type

sec_hostname=Host Name

sec_instance=Multiple Instance
sec_instance_subsystem=subsystem
sec_instance_instancenum=instance number
EXPORT_BUTTON=Export
EXPORT_SUCCEED=Export to "{0}" success.
EXPORT_FAILED=Export file failed.
[/WelcomPage]


[DateTimeZone]
DateTimeZone.Title=Set Date Time Zone
NowTimeZone=Current Time Zone
NewTimeZone=New Time Zone
DateTimeZone.Time=Date Time:
DateTimeZone.Zone=Time Zone:
TOOLTIPTXT_CHANGETIMEZONE=Set Date Time Zone
DateTimeZone.Info=Please refer ****
TOOLTIPTXT_OPERATESUCCESS=Succeeded in changing the time.
TOOLTIPTXT_OPERATETIMEZONESUCCESS=Succeeded in changing the time and time zone, it will take effect after the NMS server machine restarts.
TOOLTIPTXT_OPERATETIMEZONEFAILED=Failed to change the time and time zone. Please check whether the network is normal.
[/DateTimeZone]


[NTP]
NTP.Title=Set NTP
NTP.client=Set the server as NTP Client
NTP.medialserver=Set the server as NTP middle server
NTP.seniorserver=Set the server as NTP senior server
NTP.clientip=NTP server IP:
NTP.medialserverip=superior NTP server IP:
TITLE_PROGRESS_DLG=Set NTP
INPUT_IP_ERROR=Input IP {0} is invalid.
INPUT_IP_NEED_MODIFY=The input IP address {0} is not match the NTP configuration rules of local clock. \nPlease add according NTP configuration rules,for example 127.127.1.0.
TOOLTIPTXT_CFGNTPSUCCESS=Succeeded in configuring the NTP.
TOOLTIPTXT_CFGNTPSUCCESS_WITHIPNOCONNECTION=Succeeded in configuring the NTP,but some IP can not be reachable.
TOOLTIPTXT_CFGNTPSUCCESS_IP=NTP IP address:
TOOLTIPTXT_CFGNTPSUCCESS_NOCONNECTIONIP=Not reachable IP:
TOOLTIPTXT_CFGNTPMASTERCANNOTDEL=NTP master server can not be deleted.
TOOLTIPTXT_CFGNTPATLEASTONEIP=At least one NTP server should be configured.
TOOLTIPTXT_CFGNTPNOITEMSEL=Please select the NTP server you want to delete.
TOOLTIPTXT_CFGNTPMAXLIMIT=The maximum number of NTP server that you can configure is 10.
TOOLTIPTXT_CFGNTPFAILED=Set NTP failed.
TOOLTIPTXT_CFGNTPIPVALID=Invalid NTP IP.
TOOLTIPTXT_SAMENTP=There is reduplicate NTP IP.
UI_NTP_SERVER_MASTER_IP=Master Server
UI_NTP_SERVER_STANDBY_IP=Standby Server
COL_NAME_SERVER=Server
[/NTP]


[Hostname]
Commissioning.Page.Hostname=Set Host Name
Hostname=Host Name:
StartModifyHostname=Modifying the host name...Please wait
ModifyHostnameInstruction=Refer "Modify host name of single-server system(windows)" in commissioning guide.
MODIFY_HOSTNAME_SUCCEED=Succeeded in changing the host name, it will take effect after the NMS server machine restarts.
MODIFY_HOSTNAME_FAILED=Modify host name failed.
INPUT_HOSTNAME_NOT_VALID=Input host name is invalid.
INPUT_HOSTNAME_ERROR_DETAIL_1=The new host name must comply with the host name naming rule:\n1.The host name of the U2000 server must be unique on the network.\n2.The host name must be a string consisting of no more than 24 characters that can only be letters (A to Z, a to z), digits (0 to 9) and hyphen (-).\n
INPUT_HOSTNAME_ERROR_DETAIL_2=3.The first character must be a letter and the last character cannot be a hyphen.\n4.The host name cannot contain --.\n5.The host name must be case-sensitive.\n6.The host name cannot contain any space.\n7.The host name cannot contain only one character.\n8.The host name cannot be any of the following keywords in the high availability system:\n
INPUT_HOSTNAME_SAME_WITH_OLDNAME=The host name {0} already exists. Enter another one.

[/Hostname]


[PValue]
Commissioning.Page.ChangePValue=Set Password
SelectAll=Select All
PVALUE_SELECTED=Set user password is selected, confirm changes?
PValueReference=Refer "Change database & MSuite password of single-server system(windows)" in commissioning guide.
User=
ChangePValueWarnMsg=It will start to change password(s), are you sure you want to continue?
ChangeFinsh=Change password {0}, please check the detail information.
ChangeSucceed=success
ChangePartSucceed=partially success
ChangeFailed=failed
OLD_PWD=Old Password
NEW_PWD=New Password
RENEW_PWD=Confirm Password
OS_ROOT=OS root User
OS_NMS=OS OSS User
OS_DB=OS DB User
DB_SA=DataBase Administrator
DB_NMS=DataBase User
MSUITE_ADMIN=MSuite Administrator
ModifingPValues=Modifing password...
NewPValueError=Password requirements:\n1.New password can not be empty.\n2.Two new passwords must be same.\n3.New password can not be same as old password.
PValue.-1=Not Change.
PValue.0=Change success.
PValue.1=Parameters error.
PValue.10=Login remote node failed.
PValue.71=New password is empty.
PValue.72=The new passwords do not match.
PValue.73=New password is same as old password.
PValue.74=New password mismatch the rule. Check the tooltips in password input box for rule.
PValue.75=Confirm password is empty.
PValue.76=Old password mismatch the rule. Check the tooltips in password input box for rule.
PValue.80=Change success.
PValue.81=Check old password failed. 
PValue.82=Check old password failed. Possible causes: 1.Old password is incorrect. 2.If have enabled security enhance, refer to Installation and Commissioning Guide "How to modify the operating system user password".
PValue.83=Security set has been enabled. Check user manual to change os user password.
PValue.110=User has been locked and will be unlocked after {0} minutes.
PValue.111=
PValue.119=Operate failed, have enabled security enhance, refer to Installation and Commissioning Guide "How to modify the operating system user password".
PValue.120=Change failed.
PValue.121=Change failed. Possible causes:1.The old password is incorrect. 2.The database is abnormal. 3.The database have enabled security enhance.
PValue.1509006=Change password script file not exist.
[/PValue]


[Router]
Commissioning.Page.ConfigRoute=Configure Route
CONFIG_ROUTE_PROCESS_DLG=Configuring the Route
TOOLTIPTXT_CONFIGROUTESUCCESS =Succeeded in configuring the route.
TOOLTIPTXT_CONFIGNETFAILED =Failed to configure the server.
TOOLTIPTXT_CONFIGROUTEFAILED =Failed to configure the route.
INPUT_ROUTER_INFO_INVALID=Invalid route.
INPUT_ROUTER_INFO_THE_SAME=There is reduplicate routes.
MODIFY_PARAMETER_ERROE=Input network configuration is the same with system's configuration, please check.
BTN_ADD=Add
BTN_DEL=Delete
ConfigRouteFinish=Configure route finish, because the network is not connected, \nthe following persistent routes will be take effect after \nnetwork is connected and OS is rebooted.
CONFIRM_CHANGE_ROUTER_INFO=Ensure that the route is added, deleted, or modified correctly. Otherwise, network \ninterruption may occur. Are you sure you want to continue?
CONFIRM_RM_ROUTER=Are you sure you want to delete the selected?
[/Router]


[Summary]
Commissioning.Page.Summary=Commissioning Completed
Commissioning.Info=The config informations after commissioning are as below:
Commissioning.Reboot=Commissioning finished, it will take effect after the NMS server machine restarts.
Commissioning.useUEasyCheck=Commissioning finished successfully, please use UEasy tool to perform routine inspection.
[/Summary]

