
SubsystemTree.Title1 = You are installing components by {0}. By default, the components of the {1} are automatically selected. You can select components according to the requirements or by using the OSS Maintenance suite after the installation.
SubsystemTree.Title2 = You are installing components by license file. By default, the components specified in the license file are selected. You can add components according to the requirements or remove or add components by using the OSS Maintenance suite after the installation.
SubsystemTree.Title3 = You are installing components in custom mode. You can also add or remove components by using the OSS Maintenance suite after the installation is complete.
SubsystemTree.Title4 = You are installing components in full installation mode. You can remove or add components by using the OSS Maintenance suite after the installation.


SubsystemTree.ModifyButton = Select Component
SubsystemTree.Done = Completed
SubsystemTree.Title = Select Components
DeploymentSchemeSubsystem.PakageFilesError=The following components do not have installation package files.\nPlease modify it and run again.
DeploymentSchemeSubsystem.PackageDependencyError = The following components have package dependency errors.
DeploymentSchemeSubsystem.PackageErrorFilePath= The installation package configured for the component is not found in the {0} directory.\nMapping between components and installation packages is as follows:
DeploymentSchemeSubsystem.PackageDependenceFilePath= The installation package in the {0} directory has dependence errors. \nMapping between components and installation packages is as follows:

DeploymentSchemeSubsystem.AllNodesConfig=All nodes will be configured by default.
SubsystemTree.pkgnotexisted=Some packages as below do not exist in software library {0}. Check it.
SubsystemTree.dependencynotexisted=Some dependency packages configuration are wrong. Check and reinstall it.
SubsystemTree.loopdependencyError= Some package configurations are loop dependency. Check and reinstall it.
SubsystemTree.CrossdependencyError= Some packages have cross-dependency between the server and client. Check and reinstall it.
SubsystemTree.databasexmlError= Database configuration files for some components contain incorrect information. Check and reinstall it.
SubsystemTree.staticdataError= The installation configuration files contain some errors. Correct them and reinstall.

errorXmlList=Failed to parse the following package description file in .xml format.

SubsystemTree.InitStaticDataError=Failed to initialize the installation data. Check whether all the installation configuration files exist.
subsystem.not.config.componentree=The following subsystem is not configured in the component tree.
ComponentTree.NO_PKG_FILE_LIST=The subsystem description files of the following components do not exist. \nAre you sure you want to continue?
ComponentTree.NO_PKG_FILE_TITLE=The subsystem description file does not exist
ComponentTree.NO_PKG_FILE_LIST_ERROR=The subsystem description files of the following components do not exist. 