ConfigSoftwareLibPath.installDirLabel=Installation package path: 
ConfigSoftwareLibPath.Browse=Browse...
ConfigSoftwareLibPath.okButton=OK
ConfigSoftwareLibPath.cancelButton=Cancel
ConfigSoftwareLibPath.DiretoryConfine=The path contains more than 60 characters. Select another path.
ConfigSoftwareLibPath.PATH_FIELD_EMPTY=The path cannot be empty.
ConfigSoftwareLibPath.Title=Select Installation Package Path
ConfigSoftwareLibPath.helpTipLabel=<html>Specify a path for the database installation package.<br>For example, after the database installation package is decompressed,<br>the path is @ConcretePath.Please select @TipPath.</html>
ConfigSoftwareLibPath.helpTipLabel4Lib=<html>Specify a path for the installation package.<br>For example, after the installation package is decompressed,<br>the path is @ConcretePath.Please select @TipPath.</html>
ConfigSoftwareLibPath.LOGIN_NODE_FAILED=Failed to log in to the server. Possible causes are as follows:\n1. The port is in use.\n2. The password is incorrect.
ConfigSoftwareLibPath.NMSLIB_PATH_INVALID=Failed to verify the installation disk.Please confirm {0} is correct.
ConfigSoftwareLibPath.InitStaticDataError=Failed to initialize installation data. Check whether all configuration files for installation exist.
