help = Help
pls_config = Configure
only_master = only deploy the master server
only_slave = only deploy the slave server
any_server = support any type server
all_must = deploy all servers
single_single_type = Single-node single-instance type
mutil_type = Multi-instance type
system_single_type = Single-instance system type
none_type= No instances of type
the_select = The selected node is 
must_select_one_servergroup = Select at least one service group.
must_select_one_host = Select at least one host.
must_select_one_host_node=Select at least one host node.
the_below_not_mutil_host = A single instance cannot be deployed on multiple servers
the_below_only_mutil_slave_host=The following service groups can be deployed only on the slave server:
the_below_only_master=The following service groups can be deployed only on the master server:
the_below_must_all_host=The following nodes must be deployed on all servers. Select all server nodes
servicegroup_name=Service Group Name
servie_name=Service Name
instance_type=Instance Type
deploy_server_type=Deployment Server Type
description=Description
okbtn=OK
exist_mismatch_instancetype_deploynodetype=The instance types or deployment server types for the following service groups are different:
ConfigServiceHostPage.Title=Configure Service Group
config_service_group_index= Index
config_service_group_hostname=Host Name
config_selected_service_group=Selected Service Groups
config_service_group_input_error=Input error
pls_select_operation_type=Select an operation type.
finish_config=Configuration is complete.
the_below_must_install_mustselect=The following subsystems must be deployed on at least one node
servicegroup_info=[Service Group Info]
hostInfoName=Node Name:
the_below_dependy_mustselect=The following dependent service groups must be deployed on at least one node.

SrvGrpNotExist=Service group {0} not exist, quit.