
ConfigDeploymentsSubsystem.Title=Configure the number of instances contained in each multi-instance subsystem.
ConfigDeploymentsSubsystem.Node=Node
DeploymentSchemeSubsystem.options=options
ConfigDeploymentsSubsystem.Subsystem=Service Group
ConfigDeploymentsSubsystem.SubsystemType=Deployment Package
ConfigDeploymentsSubsystem.InstanceCount=Number
ConfigDeploymentsSubsystem.SubsystemDescription=Description
ConfigDeploymentsSubsystem.SinglePerNode=Single-server single-instance
ConfigDeploymentsSubsystem.SinglePerSystem=System single-instance
ConfigDeploymentsSubsystem.NoInstance=Single-server no-instance
ConfigDeploymentsSubsystem.MultipleInstances=Single-server multi-instance
ConfigDeploymentsSubsystem.SubsystemInfo=Component Information
ConfigDeploymentsSubsystem.Summary_NodeName=Server Name:
ConfigDeploymentsSubsystem.Summary_Subsystem=Component:
ConfigDeploymentsSubsystem.Summary_SubsystemType=Component Type:
ConfigDeploymentsSubsystem.Summary_InstanceCount=Instance Quantity:
ConfigDeploymentsSubsystem.Summary_SubsystemDescription=Description:
ConfigDeploymentsSubsystem_index=Index
modify_instance_count=Modify Instance Count
finish_config=Configuration is complete
input_error=Input error
list_separtor=Select the component list, and use the comma (,) as the separator.
pls_input=Input 
instance_count=Instance Count
DeploymentSchemeSubsystem.InvalidInput=Please enter the correct options
