CopyRight.title = Copyright Notice
CopyRight.ReadCopyRight = Please read the following agreement carefully:
CopyRight.agree = I accept the terms
CopyRight.disagree = I do not accept the terms
CopyRight.Yes=Yes
CopyRight.No=No
CopyRight.Cancel=Are you sure you want to cancel the installation?
CopyRight.UpgradeCancel=Are you sure you want to cancel the Upgrade?

CopyRight.Contents =This installation wizard will guide you through the installation process. Please read the following terms:
CopyRight.ContentsVerify=This verification wizard will guide you through the verification of installation packages.
CopyRight.ContentsCMD = This setup wizard will guide you through the installation of {0}.
CopyRight.NotAuthority = The user rights are restricted. The program will exit.

CopyRight.Contents_Upgrade =This upgrade wizard will guide you through the process of upgrading the {0}. Please read the following terms:
CopyRight.ContentsVerify_Upgrade=This verification wizard will guide you through the verification of upgrade packages.
Introduction.IsRunning = Another installation program is running. Exit the program before the installation.
Introduction.ContentsCMD = This setup wizard will guide you through the installation of {0}.
Introduction.NotAuthority = The user rights are restricted. The program will exit.
Introduction.DBConfigFileInvalid = The database configuration file is incorrect. The program will exit.
CopyRight.Hint_Upgrade=Wait
CopyRight.processing_Upgrade=Processing... Please wait.
CopyRight.FailedTOgetSiteInfo= Failed to get site information from the data model.
