StorageWelcomePage.Title=Welcome to Network Management System
StorageWelcomePage.Welcome=Welcome to Network Management System
StorageWelcomePage.WelcomeExt=Network Management System
StorageWelcomePage.Request=Select one of the following operations:
StorageWelcomePage.Backup=Back up data
StorageWelcomePage.Restore=Restore data 
StorageWelcomePage.CfgPolicy=Configure backup policy
StorageWelcomePage.ReturnPrePage=Previous
StorageWelcomePage.Exit=Finish
StorageWelcomePage.DeploymentTool=Deployment Tool
StorageWelcomePage.DBMgrTool=Database management tool

ProgressPage.StorageTitle=Backing up data... Please wait.
ProgressPage.CREATINGTASK=Creating tasks for installation and upgrade scripts...Please wait.
ProgressPage.FinishTask=Finish
ProgressPage.UpgradeTitle=Creating tasks for installation and upgrade scripts...Please wait.
ProgressPage.RollbackTitle=Creating tasks for uninstalling the existing OSS... Please wait.
ProgressPage.creatingTask=Creating tasks... Please wait.
ProgressPage.PreUpgradeTitle=Creating tasks for backing up and uninstalling the existing OSS...Please wait.
ProgressPage.RollbackTitle_post=Creating recover old OSS  task...Please wait.
ProgressPage.BusyDialog=Performing automatic rollback...
