CreateShortcut.InstallNote = \nSetup will create shortcuts in the following directory.\nEnter the directory name in the following text box.
CreateShortcut.InstallAgainNote = \nSetup will create shortcuts in the following directory.
CreateShortcut.DestinationFolder = Shortcut Directory
CreateShortcut.Title = Select Shortcut Directory
CreateShortcut.FolderNull = The directory name cannot be empty.
CreateShortcut.LengthMoreThanMax = The directory name contains a maximum of 60 characters.
CreateShortcut.InvalidCharacters = The directory name contains only alphanumeric characters, space, '-','_', and ' '.