CreateDatabase.Title = Configure Database Settings
CreateDatabase.RestoreDefaultValue = Restore to Default
CreateDatabase.SamePath = The path is the same as the first line.
CreateDatabase.DBName = Database Name
CreateDatabase.DBSize = Size(MB)
CreateDatabase.MaxDBSize = Max Size(MB)
CreateDatabase.Data = Data File Path
CreateDatabase.Log = Log File Path
CreateDatabase.LogSize = Size(MB)
CreateDatabase.MaxLogSize = Max Size(MB)
CreateDatabase.RawDevice = Raw Device
CreateDatabase.Yes = Yes
CreateDatabase.No = No
CreateDatabase.Hint = Information
CreateDatabase.DBPathCanNotEmpty = The file path cannot be empty.
CreateDatabase.DirectoryError = Incorrect directory: "{0}".
CreateDatabase.InvalidDiskDriver = Invalid disk drive: "{0}".
CreateDatabase.InvalidInput = : Invalid input 
CreateDatabase.DirectoryMustBeCharAndNum = 1. The drive must be in the node.\n2. The path must be an absolute path that consists of characters, numbers, and hyphens (-) or underscores (_). \n3. The length of the name must not exceed 60 characters, and it is invalid to have space before '\\' or '/' or ':'.
CreateDatabase.DBDirNotExistCreateIt = Data directory {0} does not exist. Do you want to create it?
CreateDatabase.LogDirNotExistCreateIt = Log directory {0} does not exist. Do you want to create it?
CreateDatabase.Error = Error
CreateDatabase.CanNotCreateDirectory = Failed to create the directory.
CreateDatabase.NotDir = "{0}" is not a directory. Please select a directory.
CreateDatabase.DataFileNotExist = {0} Data File {1} does not exist.
CreateDatabase.LogFileNotExist =  {0} Log File {1} does not exist.
CreateDatabase.DeviceIsInFileSystem = This device is mounted to the file system. Please unmount it first.
CreateDatabase.DBSizeIsTooSmall = : The size of the data file cannot be smaller than {0} MB.
CreateDatabase.CannotSmallerThanOne = : The value cannot be smaller than 1.
CreateDatabase.LogSizeIsTooSmall = : The maximum size of the log file cannot be smaller than {0} MB.
CreateDatabase.InputNumber = : The data field or log field is empty or invalid.
CreateDatabase.DataDirectory = Data File Path
CreateDatabase.LogDirectory = Log File Path
CreateDatabase.DBGrowthError = : The maximum size {1} of {0} cannot be smaller than filegrowth value {2} of database.
CreateDatabase.NotNakeDirectory = is not a raw device
CreateDatabase.Select = Select
CreateDatabase.VVRNotInstalledYet = The Volume Management software has not been installed yet or is unavailable.
CreateDatabase.VolumePathNotExist = Disk group {0} does not exist.
CreateDatabase.IsSupportDual = HA Mode
CreateDatabase.VolumehasExisted = Volume {0} already exists. Replace it?
CreateDatabase.FailToCreateVolume = Failed to create volume {0}.
CreateDatabase.FailToDeleteVolume = Failed to delete volume {0}.
CreateDatabase.YesAll = All Yes
CreateDatabase.NoAll = All No
CreateDatabase.VolumePathInvalid = Volume path {0} is invalid.\nThe directory must be in the /dev/vx/rdsk, and the path cannot contain a space.
CreateDatabase.isData = Data
CreateDatabase.isLog = Log

CreateDatabase.DBSizeLessLeastSize =: The size of the data file cannot be smaller than {0} MB.
CreateDatabase.LogSizeLessLeastSize =: The size of the log file cannot be smaller than {0} MB.

CreateDatabase.ChooseDirTip = Select the file path
CreateDatabase.RestoreTip = Set all options to the default values
CreateDatabase.SamePathTip = Set other file paths to be the same as the file path in the first line
CreateDatabase.VolumePathEmpty = The volume path cannot be empty. 
CreateDatabase.DataFile = Data File
CreateDatabase.LogFile = Log File
CreateDatabase.DataCanntBeWrite = Failed to create the data directory {0},\nor the directory cannot be written.
CreateDatabase.LogCanntBeWrite = Failed to create the log directory {0},\nor the directory cannot be written.
CreateDatabase.NoDevicenoToDistribute = There is no device number to allocate in the database. The program will exit.
CreateDatabase.InvalidPath = Invalid directory: 
CreateDatabase.TablespaceName = Tablespace Name
CreateDatabase.Type = Type
CreateDatabase.Single = Single Server
CreateDatabase.RawDeviceDual = Raw Device HA System
CreateDatabase.FileVolumeDual = File Volume HA System
CreateDatabase.Symboliclinks = One or more file paths contain links. The links will be converted to real paths.
CreateDatabase.VolumeNameTooLong = The volume name cannot exceed 31 characters.
CreateDatabase.VolumeNameInvalid = The volume name does not exist or volume path is invalid.
CreateDatabase.DuplicatePaths = The specified volume path cannot be duplicate.
CreateDatabase.DB2.PageSizeInvalid = The page size of {0} is incorrect. The page size can be 4K, 8K, 16K or 32K.
CreateDatabase.DB2.DBMinimumSize =: The data size cannot be smaller than 2 MB.
CreateDatabase.DataMountDir = Data Mount Path
CreateDatabase.LogMountDir = Log Mount Path