UPgrade.ConfigParas.CurrentVersion=Data Device Path
UPgrade.ConfigParas.SourceListLabel=Log Device Path
UPgrade.ConfigParas.SourceList.OK=OK
UPgrade.ConfigParas.SourceList.Cancel=Cancel
UPgrade.ConfigParas.SourceListTitle=Select Database Device Path
UPgrade.sourceVersionDes=Select a data device path and \n a log device path for the new database.
UPgrade.sourceVersionDes1=Select a data device path and a log device \npath for the new database.
DatabaseFileBrowser.EmptyPath=The data device path and log device path are empty.
DatabaseFileBrowser.EmptyDataPath=The data device path is empty.
DatabaseFileBrowser.EmptyLogPath=The log device path is empty.
DatabaseFileBrowser.SapaceNotEnoughPath=The available space for partition "{partitionname}" is insufficient. The required space is {requiSpace}MB and the available space is {freeSpace}MB.
DatabaseFileBrowser.PathInvalid=Invalid path: {path}.
