DBServerConfig.Hint = Information
DBServerConfig.MDPIP = MDP IP Address:
DBServerConfig.DatabaseServerIP = DB Server IP Address:
DBServerConfig.DBServerIPIsNotUseful = Invalid IP address.
DBServerConfig.DatabaseServerName = DB Server Name:
DBServerConfig.IpAddressCanNotbeEmpty = The IP address is empty or incorrect.
DBServerConfig.DBServerNameCanNotbeEmpty = The DB server name cannot be empty.
DBServerConfig.SUserNameCanNotbeEmpty = The administrator name cannot be empty.
DBServerConfig.DatabaseType = DB Type:
DBServerConfig.DatabasePort = DB Port:
DBServerConfig.DatabaseSUserName = Administrator Name:
DBServerConfig.DatabaseSUserPasswd = Administrator Password:
DBServerConfig.NMDBUserName =OSS Database User Name:
DBServerConfig.NMDBUserPassword =OSS Database User Password:
DBServerConfig.NMDBUserPasswordConfirm = Confirm OSS Database User Password:
DBServerConfig.DBConnectError = Database connection error
DBServerConfig.SetDBPort_Error = Database port error
DBServerConfig.CanNotConnectDB = Failed to connect to the database. Ensure that the parameters are correct and the database is online.
DBServerConfig.Title = Configure database service
DBServerConfig.DatabaseIsUsing = The database is used by the OSS. Shut down the OSS first.
DBServerConfig.DBPort_null = The database port cannot be empty.
DBServerConfig.InvalidCharcterinPort = The port number should be a positive number smaller than or equal to 65535.
DBServerConfig.DBServerIPNotRemote = The database service does not support the function of uninstalling the server from a remote computer.
DBServerConfig.DBIsAlive = The database is in use. Do you want to continue?\nClick <Yes> to stop the processes automatically.\nClick <No> to stop them manually.\nIn the case of a remote process, stop it manually.
DBServerConfig.DBProcesskillFail = Failed to stop the relevant process. Stop the process manually.
DBServerConfig.IsNotInstalledDB = The selected type of database to be uninstalled is incorrect.
DBServerConfig.ConfigurationDestroyed = The configuration file of database server is corrupted. The uninstallation program will use the default value.
DBServerConfig.PortIsInvalid = Failed to connect to the database. The possible causes are as follows:\nThe database port is incorrect.\nThe database is offline.
DBServerConfig.SUserAndPwdIsInvalid = The administrator name or administrator password is incorrect.
DBServerConfig.ServerNameIsInvalid = The database server name is incorrect.
DBServerConfig.ISQLCommandIsInvalid = No database ISQL command found.
DBServerConfig.NMDBUserPasswordIsInvalid = The password of the OSS user is incorrect.
DBServerConfig.DBIsOnline = The database is in use. Stop the relevant process manually,\n or restart the database service manually.
ServerConfig.CheckingParameter = Checking parameters... Please wait.
DBServerConfig.DBServerOrUserHasSpace = The server name and administrator name cannot start with a space.