
state=State
hostid=Host ID
hosttype=Host Type
fixHostName=Fixed Server Address
des=Description
usingDB=Using DB
addButton=Add...
removeButton=Remove
modifyButton=Modify...
finishedButton=Finish...
Host_Fixed_Ip=Host Fix IP:
hostInfoPageTitle=Host Information
ftpType=FTP type
FTPUser=FTP user
ftpUserName=FTP user name
ftpUserPwd=FTP user password
ftpUserNameLabelCMD=FTP user name
ftpTypeOne=FTP
ftpTypeTwo=SFTP
InstallDir=Install Dir
installFolder=Install Path
SingleMode=Non-distribution Mode
DistributeMode=Distribution Mode

HostTitle=Host Information
addHostInfoDlg=Add Node Information
modifyHostInfoDlg=Edit Node Information
hostidLabel=Host ID:
hosttypeLabel=Host type:
isDBServerLabel=Is DB Server:
hostFixIPLabel=Fixed server address:
hostFloatIPLabel=Float server address:
usingDBLabel=Using DB:
sshUserNameLabel=SSH user name:
sshUserPwdLabel=SSH user password:
desLabel=Description:
okButton=OK
cancelButton=Cancel
yes=Yes
no=No
nodeIDLabel=Host ID:
rootPasswdlabel=Admin password:
installDirLabel=Install Path:
masterHost=Master Host
slaveHost=Slave Host
standbyHost=Standby Host
single=Single
activeHASystem=Active Node of HA System
standbyHASystem=Standby Node of HA System
watchmanSystem=Watchman System

ftptypeLabel= Type:
ftpUserNameLabel= User Name:
ftpUserPwdLabel= Password:


dbServerInfoPageTitle=Server Information
installInterfaceTitle=Increment Install
dbid=DB ID
dbservername=Server Name
dbserverport=Server Port
dbtype=Server Type
dbaddress=Server IP Address


DBTitle=DB Server Information
createDBInfoDlgTitle=Add DB Server Information
modifyDBInfoDlgTitle=Edit DB Server Information
dbIDLabel=ID:
dbServerNameLabel=Server Name:
dbServerPortLabel=Server Port:
dbServerAddressLabel=Server IP Address:
dbTypeLabel=Server Type:
dbUserNameLabel=Administrator Name:
dbUserPwdLabel=Administrator Password:
nmsDBUserNameLabel=OSS user name:
nmsDBUserPwdLabel=OSS user password:
nmsDBUserPwdConfirmLabel=Confirm OSS user password:
racCheckBoxLabel = Oracle RAC mode
racAddress1Label = Oracle RAC address1:
racAddress2Label = Oracle RAC address2:
racAddress3Label = Oracle RAC address3:
racAddress4Label = Oracle RAC address4:
OSType = OS type: 
addMoreDBInfos = Do you want to do any operation?
selectOperation = Operation Type:
selectHost = Select ID:
EmptyHostDetails = No Host details exists.


HostID_null=Host ID is empty.
HostFixName_null=The fixed host name is empty.
HostFixIP_null=The fixed IP address is invalid.
HostFloatName_null=The floating host name is empty.
HostFloatIP_null=The floating IP address is invalid.
HostInfo_exist=The host information already exists.
SSHUserName_null=SSH user name is empty.
SSHUser_invalid=SSH user name or password is wrong.
HostInfo_hostfixipnouser=Can't connect to the host.
TooManyHostsToDeploy=There are too many hosts to deploy.
HostInfo_repeated=The list contains repeated host information. Please delete them.
HostInfo_Multi_Master = List contains more than one Master Host.
HostInfo_CantPing = Can't connect to the host below.\nContinue?
HostInfo_SSH_Invalid = SSH user name or password is wrong on below host.\nContinue?
HoatInfo_ChineseChars = Host ID contains some Chinese characters.
HostInfo_Multi_StandBy_Master = List contains more than one Standby Master Host.
HostInfo_StandBySlave_No_Master = There must be a Standby Master Host, when  \nStandby Slave host is present.
HostInfo_StandByShared_Master_Slave = List contains more than one Standby Host.
HostInfo_No_Master =  A master host is required.
HostInfo_No_DB = The Using DB is unavailable on the following host(s). Select Using DB again.
HostInfo_FTPUserPasswdWrong = The FTP user or password is incorrect.
FTPUserName_null = The FTP user name is empty.

FTPLoginFailed = FTP login failed.
ftptypeLabelCMD=FTP
HostInfo_PortNotListen = Ports are not free for FTP.
HostInfo_SFTPUserPasswdWrong = The SFTP user or password is incorrect.
HostInfo_WrongAdminPwd = Incorrect Admin password.
ErrorNullInstallPath = The installation directory is empty.
AdminPwd_null = The Admin password is invalid.
HostIP_NamingIP_Same = When you install the slave server, local server address and server address of the naming server cannot be same.
uploadFrameworkMessage = Do you want to upload the framework?
frameworkFileNotExist = The framework release file is not found.
invalidRemotePath=The remote path for framework is invalid.
NoSSH_Service=No SSH Service is running on this host.

FTP_ErrorCannotConnection = Failed to connect to the FTP/SFTP service
FTP_portNotListening = The FTP/SFTP service is not running
FtpValidationFailed=FTP validation failed. 
InstallDirectoryValidationFailed = Failed to validate the installation directory.
FrameWorkDirectoryValidationFailed = Failed to validate the framework directory.
Host_Ip_Invalid = The host IP address is invalid.
Float_Ip_Invalid = The floating IP address is invalid.
DirectoryMustBeCharAndNum = The path must be an absolute path composed of characters or numbers or \'-\'or\'_\', and the length of the path must not be more than 60 characters, and it is invalid to have space before '\\' or '/' or ':'.


ErrorInstallPath = The installation path is invalid. Please input again.
InstallDirNotEmpty = The installation directory is not empty on the following hosts. Select another path.
CheckSpaceFailed = Failed to check the space for installation.
NoSpace = There is no enough space on the following host(s).\nClean the disk first.


DBConnected_fail=Failed to connect to the DB server.
DBID_null=The server ID is empty.
DBServerName_null=The server name is empty.
DBServerPort_null=The server port is empty.
DBUserName_null=The administrator name is empty.
DBUserPwd_null=The password is empty.
NMSDBUserName_null=The OSS user name is empty.
NMSDBUserPwd_null=The OSS user password is empty.
NMSDBUserPwdConfirm_null=The confirm OSS user password is empty.
DBInfo_exist=The DB server information already exists.
NMSDBUserPwd_differ=The OSS DB user password and confirm password mismatch.
DB2_DBUSERNAME_PWD_WRONG = The DB instance name or DB instance password are incorrect.
DB2_SERVER_NAME_WRONG = Database imapdb does not exist on the host.
DB2_PORT_NUMBER_WRONG = Failed to connect the database. Possible causes:\nDatabase port is wrong;\nDatabase is offline.
DB2_FIX_HOST_NAME_WRONG = Cannot connect to the DB Server.
DB_SUSERNAME_PASSWORD_WRONG = The administrator name or password is incorrect.
DB_SERVERNAME_INVALID=Failed to connect the database, maybe because of the following reasons:\nDBMS is offline;\nThe Server Name is incorrect;\nThe IP or Port number is incorrect;\nThe Password is incorrect.
DB_ChineseChars =The server ID contains some Chinese characters.
DBInfo_repeated=The list contains repeated DB server information. Please delete.
ORACLE_IP_PORT_WRONG = Cannot connect to the DB Server.\nThe DB server address, port or server name is incorrect.
ORACLE_RAC_HOST_NOT_ENOUTH = At least two RAC addresses are required in Oracle RAC mode.
ORACLE_RAC_IP_WRONG = The format of the Oracle RAC addresses is incorrect.
ORACLE_RAC_IP_CONFLICT = The RAC addresses cannot be the same.
DB_Databases_Empty = No database exists in the DB server.
SERVER_IP_INVALID = The server IP address is invalid.
SQLPLUS_NOT_RUNNING = SQLPLUS not in path.
EmptyDBDetails= No DB details exist.

STANDBY_MASTER=Master Standby
STANDBY_SLAVE=Slave Standby
STANDBY_COMMON=Shared Standby


uninstallHostInfoPageTitle = Host Information
modifyUninstallHostInfoDlg = Modify Host Information
DirNotExistCreateIt = The directory {0} \ndoes not exist. Do you want to create it?

UnistallFileError = The uninstall script is not found in given path. Please check the install path.
InstallPath_Null = The installation path is empty.


remoteFrameworkError = Cannot connect to the framework.
remoteServerError=Remote machine cannot support File Browser option.\nPlease input the install path manually.
uploadHint = Uploading
uploadWaitMessage = Uploading files to the remote server(s)... Please wait.
uploadWaitCompress = Compressing the files for uploading...
HostInfoPage.CheckingDlgTitle=Checking parameters
HostInfoPage.CheckingParameters=Checking the input parameters...
HostInfoPage.InstallDirNotWritable=Failed to create the installation directory\nor the directory can not be written.
HostInfoPage.FrameWorkDirNotWritable=Failed to create the FrameWork directory\nor the directory can not be written.
HostInfoPage.DifferentInstallDir=The installation paths on all nodes must be the same.
HostIDnotmatched= Host ID entered in DefaultValues.properties file does not exist in {0}.
NotLocalIP = IP Address is remote. IP should be local.
invalidConfigExport=Failed to authenticate SSH details of master.\n Please check ConfigExport.xml and try again.
InvalidConfig=Invalid {0}.
InvalidHostID=Invalid StandAloneHOSTID.
ScriptFileNotFound = The configuration file {0} is not found. 
InvalidConfigHostID= An invalid HOSTID is configured in {0}
PackageFile.Empty = No package descriptor file(s) found. The setup program will exit.

Host_Fixed_IP=Host Fix IP:

DBServerInfoPage.NMDBUserPassword=OSS Database User Password:
DBServerInfoPage.NMDBUserPasswordConfirm=Confirm OSS Database User Password:

DBServerInfoPage.NMDBUserPWDNULL=The OSS database user cannot be empty.
DBServerInfoPage.NMDBUserRePWDNULL=The confirm password cannot be empty.
DBServerInfoPage.NMDBUserPWDNOTSAME=The OSS database user password and the confirm password mismatch.
DBServerInfoPage.OSSUserPWDRuleSQL2008=OSS dbuser password requirements:  \n 1. The database user password must contain 8 to 30 characters.  \n 2. Password characters should contain only (A-Z,a-z,0-9,_).  \n 3.The database user password must contain three out of the following four elements:    \n Uppercase letters (A-Z)    \n Lowercase letters (a-z)    \n Digits (0-9)    \n Underscores (_)