DeploymentSchemeSubsystem.ModifyButton = Configure instances
DeploymentSchemeSubsystem.Title= An instance is configured for each deployment package installed on the master server.\nBy default, instances are not configured for slave servers.\nSpecify the number of deployment package instances for each server according to the installation plan.
DeploymentSchemeSubsystem.CheckBox= Display all deployment packages
DeploymentSchemeSubsystem.Subsystem = Component
DeploymentSchemeSubsystem.SubsystemType=Deployment Package
DeploymentSchemeSubsystem.InstanceCount=Instance Count
DeploymentSchemeSubsystem.SubsystemDescription=Description
DeploymentSchemeSubsystem.emptyNode=Components must be selected for all servers except the slave protection servers.
DeploymentSchemeSubsystem.Cancel =Cancel
DeploymentSchemeSubsystem.Ok=OK
DeploymentSchemeSubsystem.Done=Configuration is complete
DeploymentSchemeSubsystem.DependencyError = The dependent component is not selected.
DeploymentSchemeSubsystem.NodeName= Server Name
DeploymentSchemeSubsystem.DetailMessage=Select components for the following nodes:
DeploymentSchemeSubsystem.SlaveValidation = The slave protection server cannot be modified.
DeploymentSchemeSubsystem.IncorrectName = The node number is incorrect.
DeploymentSchemeSubsystem.InputFromBelow = Enter the correct node number.
DeploymentSchemeSubsystem.SinglePerNode=Single-server single-instance
DeploymentSchemeSubsystem.SinglePerSystem=System single-instance
DeploymentSchemeSubsystem.NoInstance=Single-server no-instance
DeploymentSchemeSubsystem.MultipleInstances=Single-server multi-instance
DeploymentSchemeSubsystem.AddSubsystem = Add Component
DeploymentSchemeSubsystem.AllNodesConfig=Configure components for all nodes:
DeploymentSchemeSubsystem.Node=Node Name:
DeploymentSchemeSubsystem.DetailDependencyError = {1} depends on {0}. If you want select {1}, select {0} first.
DeploymentSchemeSubsystem.SelectAll=Select All
DeploymentSchemeSubsystem.Select =Select
DeploymentSchemeSubsystem.UnSelect =Deselect
DeploymentSchemeSubsystem.ChangeInstanceCount =Modify Instance Count
DeploymentSchemeSubsystem.Display =Display
DeploymentSchemeSubsystem.Reset =Reset
DeploymentSchemeSubsystem.Operations=Select the operation
DeploymentSchemeSubsystem.InputInstanceCount=Enter the number of instances for [{0}].
DeploymentSchemeSubsystem.IncompatiblePackageFound= {0} is incompatible with {1}.
DeploymentSchemeSubsystem.IncompatiblityError=Incompatible options exist.
DeploymentSchemeSubsystem.AllMustSelect=All components must be selected.
DeploymentSchemeSubsystem.InvalidInput=Invalid value. Enter a valid value.
DeploymentSchemeSubsystem.Selection=Option
DeploymentSchemeSubsystem.SubsystemId=Index
DeploymentSchemeSubsystem.SubsystemList= Select Component list, use "," as separator
DeploymentSchemeSubsystem.PakageFilesError=The following components are not defined in the installation package.\nPlease modify the components and install again.
DeploymentSchemeSubsystem.PackageDependencyError = The following component(s) have package dependency errors.
DeploymentSchemeSubsystem.SubsystemInfo=Component Information
DeploymentSchemeSubsystem.Summary_NodeName=Server Name:
DeploymentSchemeSubsystem.Summary_Subsystem = Component:
DeploymentSchemeSubsystem.Summary_SubsystemType=Component Type:
DeploymentSchemeSubsystem.Summary_InstanceCount=Instance Quantity:
DeploymentSchemeSubsystem.Summary_SubsystemDescription=Description:
DeploymentSchemeSubsystem.NodeNumberInput = Enter the node number
DeploymentSchemeSubsystem.SelectServer =Select server to configure
DeploymentSchemeSubsystem.Prompt = Information
DeploymentSchemeSubsystem.CheckNodesInformation =Verifying components... Please wait.
DeploymentSchemeSubsystem.cannotModifyInstanceCoun=The number of instances of the component {0} cannot be changed.
DeploymentSchemeSubsystem.PackageErrorFilePath= The installation package configured for the component is not found in the {0} directory.\nMapping between components and installation packages is as follows:
DeploymentSchemeSubsystem.PackageDependenceFilePath= The installation package in the {0} directory has dependence errors. \nMapping between components and installation packages is as follows:
DeploymentSchemeSubsystem.isDependedError=The following deployment packages must be deployed with at least one instance because of they are depended by others: {0}.

DeploymentSchemeSubsystem.options=Options
DeploymentSchemeSubsystem.ShowMessage=\nDescription:"M" is must installation, "Y" is to be installed or installed, "N" is not installation\n
