DirectoryChooser.TitleText=Select Directory
DirectoryChooser.FileTitleText=Select File
DirectoryChooser.DesktopTip=Desktop
DirectoryChooser.DirName=Directory:
DirectoryChooser.ApproveText=Select
DirectoryChooser.ApproveTip=Open the selected directory
DirectoryChooser.CancelTip=Abort the directory selector
DirectoryChooser.Cancel=Cancel
DirectoryChooser.Text=Select:
DirectoryChooser.LookIn=View: