ECECUTING_DEPLOYMENT_OPERATION=Executing deployment operation...
EXECUTING_UNDEPLOYMENT_OPERATION=Executing undeployment operation...
DEPLOYMENT_OPERATION_FINISHED=Deployment operation is Finished.
UNDEPLOYMENT_OPERATION_FINISHED=Undeployment operation is Finished.
DEPLOYMENT_OPERATION_FAILED=Deployment operation failed.
UNDEPLOYMENT_OPERATION_FAILED=Undeployment operation failed.
NodeConnection_Failed=RPC connection failed.
CREATE_RESULTFILE_FAILED=Failed to create result file.