ExitPage.Title = Installation Completed.
ExitPage.ErrorTitle=Installation Failed.
ExitPage.Finish=Finish
ExitPage.Note=The {0} has been installed into {1}. Click <Finish> to exit.\n
ExitPage.AffirmRestart=Are you sure you want to restart the operating system now?
ExitPage.Hint=Information
ExitPage.RestartTip=Restart the operating system.
ExitPage.NoteCMD=The {0} is installed to {1}.\n
ExitPage.CONFIRM=Confirm
UpgradeExitPage.Title=Upgrade completed
RollbackExitPage.Title=Rollback Completed
ExitPage.Note.Rollback=The {0} has been rollback. The OSS installation path is {1}. Click <Finish> to exit.
PatchFailExitPage.Title=Patch installation failed.
PatchExitPage.Title=Patch installation completed.
PatchUnistallExitPage.Title=Patch uninstallation completed.
PatchUnistallFailedExitPage.Title=Patch uninstallation failed.
PatchfailExitPage.Note=Patch installation failed.
ExitPage.Note.AUTOROLLBACK_FAILED=Auto Rollback Failed.
PatchExitPage.FailedNote=The Patch installation failed.\nClick <Exit> to exit.\n
PatchExitPage.SuccessNote=The Patch installation succeeded.\nClick <Finish> to exit.\n
PatchExitPage.NoteCMD=The patch has been installed.\n
PatchUninstallExitPageCMD.Note=Patch uninstallation is complete.
PatchUninstallFailedExitPageCMD.Note=Patch uninstallation failed.
PatchRollBackFailedExitPage.Note=Patch uninstallation failed.\nClick <Finish> to exit.
PatchRollBackExitPage.FailedNote=Patch uninstallation failed.\nClick <Finish> to exit.
PatchRollBackExitPage.SuccessNote=Patch uninstallation succeeded.\nClick <Finish> to exit.
ExitPage.NotePatch=The {0} has been patched to {1}. Click <Finish> to exit.
ExitPage.Note.upgrade=The {0} has been upgraded. The OSS installation path is {1}. Click <Finish> to exit.
ExitPage.Note.upgradecmd=The {0} has been upgraded. The OSS installation path is {1}.\n
ExitPage.ErrorScript=In installation, following components' scripts executed error, check the log to get details:
ExitPage.ErrorNote=Installation Failed. Click <Exit> to exit.\n
ExitPage.Note.Rollbackcmd=The {0} has been rolled back. The OSS installation path is {1}.
ExitPage.Restart=The system is required to restart. Restart the system manually.
ExitPage.Note.FailedUpgrade=The upgrade of {0} failed. The system has been rolled back to the previous version.
RollbackFailedExitPage.Title=Rollback failed
ExitPage.Note.UpgradePartial=Some operations failed during the upgrade and the {0} upgrade failed.
ExitPage.Note.Rollbackfailed=Failed to rollback {0} to path {1}.
UpgradeFailedExitPage.Title=Upgrade failed
ExitPage.Note.upgradeScriptFailed=Some scripts failed to be executed. Check {0}.
PatchExitPageCMD.SuccessNote=Patch installation succeeded.
PatchUninstallExitPageCMD.NoteSuccess=Patch uninstallation succeeded.
PatchUninstallExitPageCMD.NoteFailed=Patch uninstallation failed.
PatchExitPageCMD.FailedNote=Patch installation failed.
UpgradeExitPage.FailedOperations=Check details for all failed operations.
