ExecuteScriptAction.SCRIPTNOTFOUND=No script found. Do you want to continue?
ExecuteScriptAction.HIGH=Failed to run scripts. The system will perform rollback.
ExecuteScriptAction.FAILMEDIUM=Failed to run scripts. Do you want to continue?
ExecuteScriptAction.env.HIGH=Failed to run scripts. The system will exit.
ExecuteScriptAction.Rollback.HIGH=Failed to run scripts. Rollback failed.
ExecuteScriptAction.MessageNote=Started executing
ExecuteScriptAction.RunningScriptsMessageHeader=Details of script running for more than {minutesOfRun} minutes
ExecuteScriptAction.EmptyList=<EMPTY>