
ExportDeploySchema.lExportDeploySchemaFile=Export a predefined deployment file:
ExportDeploySchema.bBrowse=Browse (B)...
ExportDeploySchema.TitleExportDeploySchema=Export Predefined Deployment File
ExportDeploySchema.AlertSaveFileFailed=Failed to save the predefined deployment file.
ExportDeploySchema.next=Next
ExportDeploySchema.InvalidPath=Enter a correct file name.
file.exist = The file already exists. \nDo you want to replace it?
label.text=File path:
