UPgrade.ConfigParas.CurrentVersion= Current version
UPgrade.ConfigParas.SourceListLabel= Select source version
UPgrade.ConfigParas.SourceList.OK=OK
UPgrade.ConfigParas.SourceList.Cancel=Cancel
UPgrade.ConfigParas.SourceList.Browes=Browse...
UPgrade.sourceVersionDes= The backup path for rollback does not exist.\n Select a backup path.
UPgrade.ConfigParas.SourceListTitle=Select Backup Path
UPgrade.ConfigParas.BackupPath=Backup path is empty, please select backup path.
UPgrade.ConfigParas.Notexist=Selected path {0} does not exit.