com.oss.engineering.core.install.page.InputLicense=Select a valid iManager U2000 license for upgrade.
com.oss.engineering.core.install.page.Summary=This page displays summary information about the U2000 upgrade.
com.oss.engineering.core.rollback.page.RollBackIntroduction=Click <Next> to start rollback.
com.oss.engineering.core.u2000.gui.ProgressPage=This page displays the rollback progress information about the iManager U2000.
com.oss.engineering.business.u2000.gui.U2000ExitPage=U2000 rollback completed.
com.oss.engineering.core.upgrade.page.SelectUpgradePacket = Select a directory that contains the upgrade package.
com.oss.engineering.core.upgrade.page.UpgradeIntroduction=Click <Rollback> to start rollback or click <Continue> to continue the upgrade.
com.oss.engineering.core.upgrade.page.UpgradeSelectBackupPath = Select the backup path for each server and the installation path for the new version.