
usingDB=Using DB
state=State
removeButton=Remove
modifyButton=Modify...
installFolder=Installation Path
hosttype=Host Type
hostid=Host ID
hostInfoPageTitle=Manage Node Information
ftpUserPwd=FTP user password
ftpUserName=FTP user name
ftpType=FTP type
fixHostName=Fixed Server Address
des=Description
addButton=Add...
SingleMode=Non-distribution Mode
InstallDir=Installation Directory
FTPUser=FTP User
DistributeMode=Distribution Mode

yes=Yes
watchmanSystem=Watchman System
usingDBLabel=Using DB:
standbyHost=Standby Host
standbyHASystem=Standby Node of HA System
sshUserPwdLabel=SSH user password:
sshUserNameLabel=SSH user name:
slaveHost=Slave Host
single=Single
rootPasswdlabel=Admin password:
okButton=OK
nodeIDLabel=Host ID:
no=No
modifyHostInfoDlg=Edit Node Information
masterHost=Master Host
installDirLabel=Installation Path:
hosttypeLabel=Host type:
hostFloatIPLabel=Float server address:
hostFixIPLabel=Fixed server address:
ftptypeLabel=Type:
desLabel=Description:
cancelButton=Cancel
addHostInfoDlg=Add Node Information
activeHASystem=Active Node of HA System
HostTitle=Node Information

dbtype=DB Server Type
dbserverport=DB Server Port
dbservername=DB Server Name
dbid=DB ID
dbaddress=DB Server IP Address
dbServerInfoPageTitle=Manage DB Server Information


selectOperation=Operation Type:
selectHost=Select ID:
racAddress4Label=Oracle RAC address4:
racAddress3Label=Oracle RAC address3:
racAddress2Label=Oracle RAC address2:
racAddress1Label=Oracle RAC address1:
modifyDBInfoDlgTitle=Edit DB Server Information
dbUserPwdLabel=DB Administrator Password:
dbUserNameLabel=DB Administrator Name:
dbTypeLabel=DB Server Type:
dbServerPortLabel=DB Server Port:
dbServerNameLabel=DB Server Name:
dbServerAddressLabel=DB Server IP Address:
dbIDLabel=ID:
createDBInfoDlgTitle=Add DB Server Information
addMoreDBInfos=Do you want to perform any operation?
OSType=OS type: 
EmptyHostDetails=No host details exist.
DBTitle=DB Server Information

invalidRemotePath=The remote path for framework is invalid.
frameworkFileNotExist=The framework release file is not found.
SSHUser_invalid=The SSH user name or password is incorrect.
SSHUserName_null=The SSH user name is empty.
SSHUserPWD_null=The SSH password is empty.
NoSSH_Service=No SSH Service is running on this host.
InstallDirectoryValidationFailed=Failed to validate the installation directory.
HostInfo_DiretoryConfine=The path name contains a maximum of 60 characters. Enter the path again.
Host_Ip_Invalid=IP address is invalid.
HostInfo_repeated=The list contains repeated host information. Delete unwanted information.
HostInfo_hostfixipnouser=Failed to connect to the node.
HostInfo_exist=The node information already exists.
HostInfo_WrongAdminPwd=Incorrect administrator password.
HostInfo_StandBySlave_No_Master=There must be a standby master host, when the standby slave host is present.
HostInfo_StandByShared_Master_Slave=The list contains more than one standby host.
HostInfo_SFTPUserPasswdWrong=The SFTP user name or password is incorrect.
HostInfo_PortNotListen=Ports are not free for FTP.
HostInfo_No_Master=A master host is required.
HostInfo_No_DB=The in-use database is unavailable on the following host(s). Select an in-use database again.
HostInfo_Multi_StandBy_Master=The list contains more than one standby master host.
HostInfo_Multi_Master=The list contains more than one master host.
HostInfo_FTPUserPasswdWrong=The FTP user name or password is incorrect.
HostIP_NamingIP_Same=When you install the slave/standby server, the local server address and server address of the naming server cannot be the same.
HostFloatIP_null=The floating IP address is invalid.
HostFixName_null=The fixed host name is empty.
HostFixIP_null=The fixed IP address is invalid.
HoatInfo_ChineseChars=The host ID contains some Chinese characters.
FtpValidationFailed=FTP validation failed. 
FrameWorkDirectoryValidationFailed=Failed to validate the framework directory.
Float_Ip_Invalid=The floating IP address is invalid.
FTP_portNotListening=The FTP/SFTP service is not running.
FTP_ErrorCannotConnection=Failed to connect to the FTP/SFTP service.
FTPUserName_null=The FTP user name is empty.
FTPLoginFailed=FTP login failed.
ErrorNullInstallPath=The installation directory is empty.
DirectoryMustBeCharAndNum=The path must be an absolute path composed of characters or numbers or \'-\'or\'_\', and the path name contains a maximum of 60 characters. No space should exist before '\\' or '/' or ':'.
AdminPwd_null=The administrator password is invalid.

NoSpace=There is not enough space on the host.\nClean up the disk first.
InstallDirNotEmpty=The installation directory is not empty on the host. Select another path.
IncrementInstallDirNotEmpty=The installation directory is not empty on the host.
ErrorInstallPath=The installation path is invalid. Enter another installation path.
CheckSpaceFailed=Failed to check the available space for installation.


STANDBY_SLAVE=Slave Standby
STANDBY_MASTER=Master Standby
STANDBY_COMMON=Shared Standby
SQLPLUS_NOT_RUNNING=SQLPLUS not in path.
SERVER_IP_INVALID=The database server IP address is invalid.
ORACLE_RAC_IP_WRONG=The format of the Oracle RAC addresses is incorrect.
ORACLE_RAC_IP_CONFLICT=The RAC addresses cannot be the same.
ORACLE_RAC_HOST_NOT_ENOUTH=At least two RAC addresses are required in Oracle RAC mode.
ORACLE_IP_PORT_WRONG=Failed to connect to the database Server. \nThe DB server address, port, or server name is wrong.
EmptyDBDetails=No DB details exist.
DB_SUSERNAME_PASSWORD_WRONG=The database administrator name or password is incorrect.
DB_SERVERNAME_INVALID=Failed to access the database. Possible causes:\nDBMS is offline; \nThe Server Name is incorrect; \nThe IP or port number is incorrect; \nThe password is incorrect.
DBUserPwd_null=The database password is empty.
DBUserName_null=The administrator name is empty.
DBServerPort_null=The database server port is empty.
DBServerName_null=The database server name is empty.
DBInfo_repeated=The list contains repeated DB server information. Delete unwanted information.
DBInfo_exist=The database server information already exists.
DBConnected_fail=Failed to connect to the database server.
DB2_PORT_NUMBER_WRONG=Failed to connect to the database. Possible causes are as follows:\nDatabase port is wrong;\nDatabase is offline.

InstallPath_Null=The installation path is empty.
DirNotExistCreateIt=The directory {0} \ndoes not exist. Do you want to create it?

uploadWaitMessage=Uploading files on remote server(s)... Please wait.
uploadHint=Uploading
remoteFrameworkError=Unable to connect to the following host(s) installation process.
ossIsIntalled=No node needs to be installed. \n {0} node(s) has been installed successfully before: \n {1}
invalidConfigExport=Failed to authenticate SSH details of the master server.\n Check the ConfigExport.xml file and try again.
hostname_not_same=The fixed ip address and floating ip address are not on the same server.
are_reuse_Engr_daem=Processes on the following host(s) are running. Do you want to update them?
ScriptNotFound=The check script does not exist.
RsyncNotInstall=The rsync tool is not installed.
RemoteRsyncNotRunning=The rsync service is not running on the new node.
RemoteRsyncCfgNotFound=The rsync configuration file does not exist on the new node or an rsync error occurs.
NotLocalIP=The IP address should be a local IP address.
NodeConnection_Failed=RPC connection failed.
NewNodeIPNotFound=The IP address {0} does not exist or an error occurs.
InvalidHostID=Invalid Standalone host ID.
InvalidConfigHostID=An invalid host ID is set in {0}.
InvalidConfig=Invalid {0}.
Host_IP_notLocaleIP=The IP address of a non-primary site cannot be the IP address of the local server.
Host_IP_LocaleIP=The IP address of the primary site must be the IP address of the local server.
HostInfoPage.InstallDirNotWritable=Failed to create the installation directory or the directory is not writeable.
HostInfoPage.FrameWorkDirNotWritable=Failed to create the framework directory or the directory is not writeable.
HostInfoPage.CheckingParameters=Checking input parameters... Please wait.
HostInfoPage.CheckingDlgTitle=Checking parameters...
HostIDnotmatched=The host ID entered in the DefaultValues.properties file does not exist in {0}.
ExpectNotInstall=The expect tool is not installed.
ExecScriptFailed=Failed to execute check scripts.
CheckTrustWithNewNodeFail=Failed to communicate between the primary node and {0}.
CanNotConnectNewNode=Failed to connect to the new node.

LOGIN_FAILED_ONLY_LOGIN_ONE_MASTER=Node {0} has been logged in to by another master node. \nPlease check. 
SyncConfigureFileFailed=Failed to synchronize file.