InitPackage.Title = Initializing components...
InitPackage.Hint = Information
InitPackage.ScriptFailed = Failed to run the script {0}. \nDo you want to continue?
InitPackage.DatabaseFailed = Failed to create the database {0}. Do you want to continue?
InitPackage.Finished = Finish
InitPackage.PreInstallScript = Install Prescripts
InitPackage.PreDBScript = Database Prescripts
InitPackage.CreateDatabase = Create Databases
InitPackage.PostDBScript = Database Postscripts
InitPackage.PostInstallScript = Install Postscripts
InitPackage.DBExist = The database already exists. Do you want to create it again?
InitPackage.DropError = : An error occurred while deleting the database. It may be caused by an illegal operation. \nInstallation may fail if you continue installing this database. Do you want to continue?
InitPackage.DBInstallContinue = : Do you want to continue installing this database?
InitPackage.Yes = Yes
InitPackage.No = No
InitPackage.YesAll = All Yes
InitPackage.NoAll = All No
InitPackage.SeriousError = A fatal error occurred while running the script {0}.\nThe installation wizard will exit.
InitPackage.ScriptError = An error occurred while running the script {0}. 
InitPackage.UnknowError = An unknown error occurred while running the script {0}.
InitPackage.ScriptExecutionFailed = Failed to run the script. Do you want to continue?
InitPackage.ScriptExecutionFailedDetail = Failed to run the script {0}.
InitPackage.ScriptNotFound = The script {0} is not found. Do you want to continue?
InitPackage.ScriptIOException = An IO exception occurred while running the script {0}.
InitPackage.Envhintinfo = Do you want to overwrite the environment variable?
InitPackage.Reserve = Retain
InitPackage.Overlay = Overwrite
InitPackage.PathOverLang = The system environment variable PATH is too long. Decrease the length manually.\nClick <Retry> after decreasing the length or click <Cancel> to exit the application.
InitPackage.CreateVolumes = Create Volume
InitPackage.SucceedToCreateVolume = Volume {0} is created successfully.
InitPackage.Over = Finish initializing components
InitPackage.Completed = Completed
InitPackage.PathIsNullOrEmpty = The system PATH does not exist or is invalid. \nClick <Yes> to set the PATH. Otherwise, the installation will exit. 
InitPackage.DropDBError = An error occurred while deleting the database.
InitPackage.ReJarError = An error occurred while creating the upgrade package.
InitPackage.InitPackageShowTime = minute(s)
InitPackage.AddRegeditFail = Failed to add the registry {0}.
InitPackage.DBCreationFailed = Failed to create the database. Do you want to continue?
