InitDBWizardPage.DatabaseInitial=Initialize the database
InitDBWizardPage.ParaCfg=Set database parameters
InitDBWizardPage.Title=Network Management System Database Initialization Wizard
InitDBWizardPage.Introduction=Network Management System Database Initialization
InitDBTool.Title=Network Management System Database Initialization Wizard
InitDBWizardPage.WARNING_MESSAGE=The initialization tool will initialize the OSS data. Are you sure you want to continue?
InitDBWizardPage.WARNING_TITLE=Warning
InitDBWizardPage.FailedToGetDBLogonInfoFromDatamodel=Failed to obtain database login information from the data model.
InitDBWizardPage.Introduce=This tool helps you initialize all databases of the OSS.\n\nCaution:\n1. Before you initialize a database, ensure that the OSS is not running.\n2. This operation resets the database to its original installation state.\n3. All data will be deleted from the database. You must use the backup tool to back up all essential data. 
initdbcheck.ErrorTitle=Error
initdbcheck.DatabaseConnectionFailed=Failed to check the database. Possible cause:\n1.Database server is not running.\n2.Database is running abnormal.
initdbcheck.NodeSysmoniRunning=The OSS on node {0} is running. Stop it first.
initdbcheck.DiskSpaceNotEnoughError=The disk space is insufficient on device {0}.Required space: {1} MB; Free space: {2} MB.
initdbcheck.ProcessRunningOnDatabase=Failed to initialize the database. The database is being used by the processes:
initdbcheck.RefreshDBConnectionFailed=Failed to refresh the database connection. Check whether the database server is running.
initdbcheck.DBInfoFileInvalid=sysconfigure.xml file or database configuration files not valid.
initdbcheck.LocalIPInvalid=Check the sysconfigure.xml ip failed. 
initdbcheck.NMSALIVE=The OSS services are running. Stop them and try again.
initdbcheck.NMSALIVEMSG=OSS services are running on the following hosts:
RestoreSelFilePage.initDBFailed=Initialize the database failed.
