InitDBExitPage.InitialExitPage.Title=The database is initialized successfully.
InitDBExitPage.InitialExitPage.TitleFail=Failed to initialize the database.
InitDBExitPage.CfgDatabaseParaPage.Title=The database parameters are set successfully.
InitDBExitPage.Note=Click <Finish> to close the database initialization wizard.
InitDBExitPage.StartNMSNote=Start the OSS service manually to ensure the integrity of OSS data.
InitDBExitPage.ERRORNote=Click <Exit> to close the database initialization wizard.