InputLicensePanel.Select = Select File
InputLicensePanel.Browse = Browse...
InputLicensePanel.Title=Select License File
InputLicensePanel.licenseNote =\nClick <Browse> to choose another file.
InputLicensePanel.SelectLicenseFileLabel = License File:
InputLicensePanel.tempLicenseTitle = License Information
InputLicensePanel.OK = OK
InputLicensePanel.tempLicense = This is a temporary license that will expire in {0} days. \nApply for a formal license from Huawei Technologies Co., Ltd. before the license expires.
InputLicensePanel.licensefile_notexist = The license file does not exist. Enter the license file again.
InputLicensePanel.error = Error
InputLicensePanel.InvalidLicense = Invalid license.
InputLicensePanel.Hint = Information
InputLicensePanel.LicenseFileExist = The license file already exists in the installation directory. Do you want to overwrite it? \nBack up the existing license file before you overwrite it.
InputLicensePanel.DirectoryError = Incorrect directory:
InputLicensePanel.DirectoryMustBeCharAndNum = The path must be an absolute path that consists of characters or numbers or \'-\'or\'_\', \nand the path name contains a maximum of 60 characters.\n No space should exist before '\\' or '/' or ':'.
InputLicensePanel.CanntBeWrite = Failed to create the license directory or the license directory cannot be written.
InputLicensePanel.LicenseFileNull = The license file cannot be empty.
InputLicensePanel.LicenseExpired = This is a temporary license which expired {0} day(s) ago. \nApply for a formal license from Huawei Technologies Co., Ltd.
InputLicensePanel.CopyFailed = Failed to copy the license file.
LicensePage.License.Alert.SelectFile=Select a license file.
LicensePage.License.Alert.Invalid=Select a valid license file.
LicensePage.License.Alert.Use=Failed to parse the license.
LicensePage.ImportScheme.Alert.SelectFile=Select a deployment scheme file.
LicensePage.ImportScheme.Alert.Invalid=Select a valid deployment scheme file.
LicensePage.LicenseFileNotValid=No license file is found.
LicensePage.DiretoryNull = The installation path cannot be empty.
LicensePage.PathTooLengthy = The file name contains a maximum of 60 characters.
LicensePage.InstallMethod=Installation Method
LicensePage.InstallMethodManual=Define the deployment system manually.
LicensePage.InstallMethodLicense=License Installation
LicensePage.InstallMethodSchema=Install by the deployment solution.
LicensePage.License.Alert.InputFile=Enter a license file path.
LicensePage.ImportScheme.Alert.InputFile=Enter a deployment solution file path.
InputLicensePanel.licenseNoteCMD=Enter a license file.
