ProgressPage.InstallProcessTitle = Show Installation Progress
ProgressPage.UninstallTitle=Uninstalling...Please wait.
ProgressPage.UpgradeTitle=Executing installation and upgrade scripts...Please wait.
ProgressPage.PreUpgradeTitle=Creating tasks for backing up and uninstalling the existing OSS... Please wait.
ProgressPage.RollbackTitle=Recovering the old OSS...Please wait.
ProgressPage.PreRollbackTitle=Preparing for rollback...Please wait.
ProgressPage.Title=Progress
ProgressPage.DATAMODEL_INIT=Initializing the data...Please wait.
ProgressPage.InstallFailed=Installation failed. View log files:\n{0}logs
ProgressPage.UninstallFailed=Uninstallation failed. View log files.
ProgressPage.UpgradeFailed=Upgrade failed. View log files.
ProgressPage.RollbackFailed=Rollback failed. View log files.
ProgressPage.installPatchTitle=Starting patch installation... Please wait.
ProgressPage.uninstallPatchTitle=Start patch uninstallation... Please wait.
ProgressPage.PatchTitle=Installing the patch... Please wait.
ProgressPage.PrePatchRollbackTitle=Uninstalling the patch... Please wait.
ProgressPage.creatingTask=Creating a task...Please wait.
ProgressPage.UpgradeTitle_pre=Backing up data and uninstalling the existing OSS...Please wait.
ProgressPage.RollbackTitle_pre=Uninstalling the existing OSS...Please wait.
ProgressPage.BusyDialog=Performing automatic rollback...
ProgressPage.AutoRollbackFinish=Automatic rollback completed.
ProgressPage.Title.Upgrade=Upgrade Progress
ProgressPage.Title.Rollback=Rollback Progress
ProgressPage.InstallTitle = Installing...Please wait.

progressPage.exit.partSuccess= partially successful
progressPage.exit.allSuccess=all successed
progressPage.exit.allFailed=all failed

progressPage.exit.des={0} upgrade in {1} path {2}
progressPage.exit.failed={0} node(s) failed :
progressPage.exit.failedip={0} : at {1}% failed - {2}
progressPage.exit.success={0} node(s) have been installed successfully :
progressPage.exit.alreadySuccess={0} node(s) have been installed successfully before:
progressPage.exit.ipinvalid=Node ip invalid.