InstallCheck.title = Preinstallation Check

success = Successful
failed = Failed 

InstallCheck.Retry=Retry


check.total.number = 7


ck_0 = check the omcsysm user group
ck_1 = check the dbuser user
ck_2 = check the omcuser user
ck_3 = check the ftpuser user
ck_4 = check the OS version
ck_5 = check the partition space
ck_6 = check the character set

ret|10001 = Failed to create the {0} user group.
ret|10002 = Failed to create the {0} user.
ret|10003 = The {0} partition does not have enough space.
ret|10004 = The {0} partition does not exist.
ret|10005 = Current OS version: {0}\n   Not match: 5.10/Generic_118833-36 or 5.8/Generic_108528-29
ret|-10001 = The {0} user group has not been created.
ret|-10002 = The {0} user has not been created
ret|-10003 = The {0} Sybase system file is incomplete or contains incorrect information.

preinstallcheckFilePath = ./logs/preinstallcheck.log
execScript = ./install/omcscript/preinstallcheck.sh

check_failed_confirm=Preinstallation check failed. Select Y to check again. Select N to exit installation
