ExitPage.Title=Installation Finished
ExitPage.Finish=Finish


ExitPage.more.one.fail.Note={0} has been installed partially successfully. \n{1} node(s) failed:  \n{2}\n\n{3} node(s) are successful : {4}.\n{5} node(s) failed : {6}.\n
Exitpage.more.retry.success.Note={0} has been installed partially successfully. \n{1} node(s) failed : \n{2}\n\n{3} node(s) are successful : {4}.\n{5} node(s) failed : {6}.\n{7} node(s) were already successful last time: {8}.\n
ExitPage.more.all.success.Note={0} Installation succeeded. \nAll host(s) {1} has been installed successfully at {2}.
ExitPage.more.all.fail.Note={0} Installation failed. \n{1}.

ExitPage.one.fail.Note={0} Installation failed. \n{1}.
ExitPage.one.success.Note={0} Installation succeeded. \n{1} host has been installed successfully at {2}.

ExitPage.fail.percent=Failed at

ExitPage.AffirmRestart=Are you sure you want to restart the operating system now?
ExitPage.CONFIRM=Confirm
ExitPage.Hint=Information
ExitPage.RestartTip=You need to restart the operating system.
PatchExitPage.Note=The patch {0} has been installed. \nThe installation log is saved at:\n {1} \nClick <Finish> to exit.
ExitPage.NoteCMD=The {0} has been installed in the directory {1}.
ExitPage.ErrorScript=In installation, following subSystems' scripts executed error,check the log to get details:
ExitPage.ErrorNote={0} Installation failed. View log files for details {1}.
ExitPage.ErrorTitle=Installation failed.
ExitClientPage.Note=The {0} has been installed to {1} . \nClick <Finish> to exit.
ExitPage.somefail.percent=Failed at {0}% - 