
InstallDisk.ProductName = Network Management System 
InstallDisk.ProductDescription = Network Management System 
InstallDisk.ProductVersion = Network Management System UniEP 2.0
InstallDisk.ProductDescriptionUninstall = Network Management System 