UPGAREPATHLENGT=The PATH variable is too long. Delete useless fields and perform the operation again.
DIALOGTITLE=Warning
PROCESSEXIST=<html>The service process @process cannot be started repeatedly. <br> Stop the running service process @process.</html>
PROCESSUSE=<html>The service process "@process" started. <br>Please stop it first.</html>
PORTSEXIST=<html> The communication port @ports has been occupied.<br> Run the @portcmd command to query the port usage, or retry in two to three minutes.</html>
PORTSEXIST_WIN=The communication port @ports has been occupied. @nYou can select 'Yes' to check which processes occupied the ports, or select 'No' to retry.@nPorts checking operation may takes longer time based on operating system.
PORTSEXIST_SILENT=The communication port @ports has been occupied.
SEARCH_PORT=Searching for process running on port 12212,12213,12214,12215:
WAIT_FEW_MIN=Ports are getting cleared, please try later.
PLEASE_WAIT=Start searching, please wait...
TOTAL_MEMORY_NOTENOUGH=<html>The size of the server memory is smaller than 2 GB.<br> Therefore, only single-domain OSS or only the client can be installed.</html>
CHINESELANG=<html>The language settings for the operating system are not supported. <br> The operation may fail if you continue. The following languages are supported:@langList</html>
CHINESECHARSET=<html>Settings of the LANG parameter in the language configuration file of the operating system do not meet the requirements for installing the OSS. <br>Open the configuration file saved in the @CifFile directory and change the value of LANG from @oldLang to @Lang. <br>Then, restart the operating system.</html>
CHECKNMSCLIENT=The OSS is installed in the @installPath path. Uninstall the OSS first if you want to reinstall it.
REPEXIST=The replication relationship exists. Delete it first.
CLEARSCRIPT=<html>Previous OSS uninstallation creates an operation-pending file on this computer.<br>You must restart this computer before running the setup program.</html>
PATHLENGTH=The PATH variable is too long. Delete useless fields and perform the operation again.
JRECHECK=<html>Failed to find the JRE for the OSS in the current operating system.<br> Verify that the JRE directory @HWJREROOT exists.</html>
NMSCHECK=<html>The @userName user is being used now. Log out this user <br>(Please run the ps -ef | grep @userName command to check whether any processes are used by user @userName).</html>
NMSFILECHECK=The user file is damaged so that the ossuser user cannot be added or deleted.
INSTALLDISKPATHINVALID=The directory of the installation disk cannot contain Chinese characters, underscores, and spaces.
LOOPIPCHECK=<html>The loopback IP address is not configured. Please configure it in the /etc/hosts file, <br>and restart the operating system to make the configuration file take effect.</html>
INSTALLDISKCHECK=<html>The @INSTALLROOT does not exist.<br> Ensure that the version is correct and install it again.</html>
SYSCONFIGIPCHECK=<html>The @INSTALLROOT does not exist.<br> Ensure that the file is available and install it again.</html>
ZHLANG=Chinese
ENLANG=English
CONTINUE=Continue
CANCEL=Cancel
NO=No
YES=Yes
NETMANAGERPROCESS=The OSS server process is running. Are you sure you want to stop it?
INVALIDATIONOPTION=Invalid option. Please enter again.
STOPPROCESS=Failed to stop the OSS server process.
WATIMESSAGE=Stopping the OSS process...Please wait.
DBUSEDCHECK=The SQL Server Enterprise Manager is open. Please close it first.
LESSMEMORY=Available memory space is less than 1 GB. Please release memory space first.
LESSTMP=Available space in the /tmp directory is less than 512 MB. Please release space first.
PACKAGECLIENTCHECK=<html>The client package (the package name contains client) must be decompressed into a directory different from <br> the directory where the base package (the package name contains base) @or the <br> core package (the package name contains core) is decompressed. Please decompress again. </html>
PACKAGECHECK=<html>The base package (the package name contains base) and the core package (the package name contains core) must be <br> decompressed into the same directory. Please decompress again. </html>
DISKHANGUP=<html>The @DATADIR directory fails to be mounted. Run the OSSICMR command. <br> The command is e.g:cd /opt/OSSICMR/bin; ./install.sh ¨Cr.</html>
DBXML=<html>The database configuration file in the @DATABASE <br> path is incorrect. Please check.</html>
REPETITIONHOSTIP=<html>Duplicate IP addresses exist in the /etc/hosts file. <br> Please delete the duplicate addresses and restart the operating system.</html>
REPETITIONHOSTNAME=<html>Duplicate host names exist in the /etc/hosts file. <br> Please delete the duplicate host names and restart the operating system.</html>
TIMEZONENOLANG=<html>No LANG variable (LANG=C) exists in the /etc/TIMEZONE file. <br>Please add the variable and restart the operating system.</html>
NMSPROCESSEXIST=The OSS process is running. Stop it first.
HOSTNAMECHECK=<html>Invalid server host name. Change the host name to meet the following requirements:<br>1. A server host name contains a maximum of 24 characters. <br>2. A server host name consists of letters (A to Z), digits (0 to 9), and hyphens (-). <br>3. A server host name must begin with a letter. <br>4.A server host name does not end with a hyphen. <br>5. A server host name does not contain two consecutive hyphens (--).</html>
SHAREMENINFO=<html>No system shared memory configured. Run the following command to preconfigure the system:<br>cd /opt/OSSICMR/bin; ./install.sh -r</html>
SYSCONFCHECK=Configuration file @INSTALLROOT does not exist. Please check.
DATABASEPACKAGECHECK=The <html>@INSTALLROOT directory is empty or does not exist. Create database files.</html>
CHECKOSSPROCESS=Directory @OSSPATH is being used by some processes. Please stop it first.
CHECKOSSRUNNING=OSS process is running,please stop it first.
OSSENVVAR=OSSENGRROOT or OSSJRE environment variable doesn't exist, please check.
CERTDATECHECK=The certification is invalid.
DIALOG_ERROR_TITLE=ERROR
CHECK_PORTANDSSL=Start process failed. Please check whether the port is occupied or the certificate is invalid.
CHECK_SYSCONFIGURE_XML_FAIL=Start process failed. The sysconfigure.xml file is not exists or unreachable, please fix it.
CHECK_DISK_SPACE=@TEMPDIR or current directory not enough space available. @TEMPDIR directory need 2G,current directory need 500M.
PACKAGEPATHCHECK=The client package path cannot contain characters !, $ and spaces.
SYSCONFHAIPCHECK=The ip in the /engr/deploy/conf/sysconfigure_ha.xml file is local ip,please check.