
LicensePage.rbSelectLicense=Installation by license (for users who have obtained license files)
LicensePage.lSelectLicense = Import a license file:
LicensePage.bSelectLicense = Select the deployment file...
LicensePage.rbImportScheme = Typical network based installation (recommended)
LicensePage.schemaLabel = Deployment file:
LicensePage.okButton = OK	
LicensePage.cancelButton = Cancel
LicensePage.schemaTip = Select a valid deployment file.
LicensePage.lImportScheme = Select a scenario:

LicensePage.Title=Select Installation Mode.
LicensePage.DefineManually=Custom installation (for advanced users)
LicensePage.GenerateSchema=Select Predefined Deployment File
LicensePage.License.Alert.SelectFile=Select a license file
LicensePage.License.Alert.Invalid=Select a valid license file.

LicensePage.ImportScheme.Alert.SelectFile=Select a scenario
LicensePage.ImportScheme.Alert.Invalid=Select a valid scenario.

LicensePage.InstallMethod=Installation Mode
LicensePage.InstallMethodManual=The system is deployed in custom installation mode.
LicensePage.InstallMethodLicense=The system is deployed in license installation mode.
LicensePage.InstallMethodSchema=The system is deployed in typical installation mode.
LicensePage.License.Alert.InputFile=Enter a path for storing the license file.
LicensePage.ImportScheme.Alert.InputFile=Enter a path for storing the deployment file.
LicensePage.AccessName = Access domain

LicensePage.InstallType =Installation type
LicensePage.SelectInstallation= Select installation type.
LicensePage.byLicense=License based installation (for users with licenses)
LicensePage.FullInst=Full installation
LicensePage.select=Browse...
File.path.cannot.empty=The file path cannot be empty.


