MENU_OP_MONITOR_REP=Monitor Replication Status(M)...
LABEL_MONITOR_RLINK=The rlink status 
SLIDEBAR_MONITOR_RLINK=The progress of replication 
BUTTON_QUERY=query
BUTTON_CANCEL=cancel
MENU_OP=Deploy
VXRLINK_ERROR=Data replication between the primary and secondary sites is interrupted. Possible causes are as follows: \na. The replication network is interrupted. (Replication status:paused due to network disconnection) \nb. The high availability system is in the dual-host state. (Before the network is restored, the issue is displayed as network interruption on the primary site, and no replication status item is found on the secondary site.) \nc. The buffer volume overflows during data replication. {Replication status: logging to DCM (needs dcm resynchronization)}
COPY_PROTOCAL=Replication Protocol:
COPY_PROGRESS=Replication Speed (not the current network bandwidth):
DISK_NAME=Disk Name
DISK_GROUP=Disk Group
USAGE_RATE=Usage Rate(%)
QUERYING_DATA=Querying data...

