
ClientCopyRight=Introduction
SelectClientLanguage=Select Language
SelectClientInstallFolder=Select Installation Folder
SetClientShortcutFld=Set Shortcut Folder
ClientSummary=Confirm Installation
ClientExportDeploySchema=Export File
ClientInstallProgress=Installing
ClientInstallExitPage=Finish
