SoftwareLibSelectPage=Choose Software Lib
DBServerInfoPage=Configure Database
HostInfoPage=Configure Server
StartSubNodeServerPage=Start Subnode Server
ComponentTree=Component
ConfigServiceHostPage=Configure Parameters
ConfigDeploymentsSubsystem=Configure Instances
IncrementInstallSummaryPage=Summary
IncrementInstallProgressPage=Installing
IncrementInstallExitPage=Finish
IncrementPreCheck=Environment Check
