WelcomePage=Information Preview
DateTimeZonePage=Set Date Time Zone
ChangeNTPPage=Set NTP
ModifyHostnamePage=Set Host Name
ControllerPage=Set Controller
VirusSoftCheckPage=Anti-Virus Software
ChangePValuePage=Set Password
AlarmConfigPage=Set Hardware Alarm
NMSLicensePage=OSS License
VCSLicensePage=Set Veritas License
ReplaceNMSLicensePage=Set SSL Certificate
AddInstancePage=Add Instance
ConfigNetworkPage=Set Network
ConfigRoutePage=Set Route
SecuritySetPage=Security Hardening
SummaryPage=Finish
DeployNbiInstancePage=NBI