CopyRight=Copyright
SelectLanguage=Select Language
SelectInstallTypeU=Select Server Type
SelectInstallType=Select Server Type
LicensePage=Select Installation Type
SelectLicense=Select License Type
ComponentTree=Select Component
NodeInfoTable=Configure Server
HostInfoPage=Configure Server
ConfigServiceHostPage=Configure Parameters
ConfigDeploymentsSubsystem=Configure Parameters
ConfigDBServerWindows=Configure Database
ConfigDBServer=Configure Database
DBServerInfoPage=Configure Database
ExportDeploySchema=Export File
Summary=Installation Summary
InstallProgressPage=Installing
InstallExitPage=Finish
InstallCheck=Preinstallation Check
