NodeInfoTable.description = This is a centralized single-server system. Please configure information for the server.
NodeInfoTable.description1 = It is a distributed system. Please set information for the master and slave servers.
NodeInfoTable.description2 = This is a centralized HA system. Please configure the information of the servers.
NodeInfoTable.description3 = This is a distributed HA system. Please configure the information of the master \nand slave servers.
NodeInfoTable.description2windows = This is a centralized HA system. Please configure server information.
NodeInfoTable.description3windows = This is a distributed HA system. Please configure information about the master \nand slave servers.
NodeInfoTable.browse = Browse...
NodeInfoTable.Select = Select File
NodeInfoTable.AddButton = Add 
NodeInfoTable.modifyButton= Modify 
NodeInfoTable.deleteButton = Delete 
NodeInfoTable.Done=Finish
NodeInfoTable.confirmation = Confirm
NodeInfoTable.Synchronize_Title = Synchronize Framework
NodeInfoTable.Synchronize_Start = Start synchronizing framework ...
NodeInfoTable.CheckInstallPath = Invalid path
NodeInfoTable.CheckInstallPathChar = The installation path cannot contain special characters but letters, numbers, and underscores(_).

NodeInfoTable.Title= Deploy Server

NodeInfoTable.Node_Name = Server Name
NodeInfoTable.Public_IP_Address = IP Address
NodeInfoTable.Private_IP_Address= Private IP Address:
NodeInfoTable.Node_Type = Server Type
NodeInfoTable.Root_Password= Password of OSS Maintenance Suite
NodeInfoTable.Installation_Path = Installation Path
NodeInfoTable.InvalidPublicIp = The IP address is invalid.
NodeInfoTable.privateIpIsEmpty= The private IP address is empty.
NodeInfoTable.publicIpIsEmpty= The IP address is empty.
NodeInfoTable.InvalidPrivateIp = The private IP address is invalid.
NodeInfoTable.No_MASTER_NODE = At least one server must be the master server.
NodeInfoTable.DUPLICATE_MASTER_NODE = Only one master server is allowed.
NodeInfoTable.DUPLICATE_SLAVE_NODE = Only one slave server is allowed.
NodeInfoTable.SUB_NODE_MUST_FOR_SLAVE = The slave server must exist before adding a slave protection server.
NodeInfoTable.NO_BACKUP= The applications and database will not be backed up. Are you sure you want to continue?

NodeInfoTable.nodeIDLabel = Server Name
NodeInfoTable.nodeTypeLabel = Server Type
NodeInfoTable.publicIPLabel = IP Address

NodeInfoTable.privateIPLabel= Private IP Address:
NodeInfoTable.AddTitle = Add Server
NodeInfoTable.rootPasswdlabel= <html>Password of OSS<br>Maintenance Suite</html>
NodeInfoTable.installDirLabel= Installation Directory
NodeInfoTable.okButton= OK
NodeInfoTable.cancelButton=Cancel
NodeInfoTable.MASTER_NODE = Master server
NodeInfoTable.SUB_NODE = Slave server
NodeInfoTable.SLAVE_NODE = Slave protection server
NodeInfoTable.InvalidNodeName=Invalid server name.
NodeInfoTable.INVALID_PUBLIC_IP = Invalid IP address
NodeInfoTable.INVALID_PRIVATE_IP = Invalid private IP address.
NodeInfoTable.PATH_FIELD_EMPTY = The path field cannot be empty.
NodeInfoTable.NODE_FIELD_EMPTY = The server name cannot be empty.
NodeInfoTable.INVALID_PUBLIC_IP_PING = Failed to connect to the IP address.
NodeInfoTable.INVALID_PRIVATE_IP_PING = Failed to connect to the private IP address.
NodeInfoTable.DUPLICATE_PUBLIC_IP = The IP address must be unique.
NodeInfoTable.DUPLICATE_PRIVATE_IP = The private IP address must be unique.
NodeInfoTable.DUPLICATE_NODE_ID = The server name must be unique.
NodeInfoTable.promt=Information
NodeInfoTable.SELECTBACKUPPATH=The backup directory is empty. Please specify it.

NodeInfoTable.PUBLIC_PRIVATE_IP_NOTSAME = The IP address cannot be duplicate with the private IP address.
NodeInfoTable.INVALID_INSTAL_PATH = The installation path is invalid:
NodeInfoTable.LOGIN_NODE_FAILED = Failed to log in to the server. Possible causes are as follows:\n1. The port is in use.\n2. The password is incorrect.\n3. The deployment server is not started.
NodeInfoTable.DiretoryConfine = The path name contains a maximum of 60 characters. Enter the path again.
NodeInfoTable.Currentpatherror = The current install path name contains a maximum of 60 characters, please change the install path and the software will exit.
NodeInfoTable.PathIsNull = The installation path cannot be empty.
NodeInfoTable.invalidPath =1.The path must be an absolute path that consists of characters, numbers, and underscores (_). \n2.The length of the directory must not be more than 60 characters, and directory must be writable. \n3.Please check whether the drive is exist.
NodeInfoTable.CONFIRMATION_MESSAGE= Are you sure you want to delete the selected servers?
NodeInfoTable.CONFIRM = Confirm
NodeInfoTable.error = Error
NodeInfoTable.loopBackAddress = The IP address that forms a loop is not allowed.
NodeInfoTable.Synchronize_TotalMessage=Synchronizing framework...Please wait.
NodeInfoTable.SYNCHRONIZE_FRAMEWROK_FAILED=Failed to synchronize the framework.
NodeInfoTable.Synchronize_IP=Synchronizing the sub server:
NodeInfoTable.CHANGE_SYBASE_INTERFACES_FAILED=Failed to change interfaces in the Sybase file.

NodeInfoTable.FileChooser_Title_Input=Please enter a new folder name.
NodeInfoTable.FileChooser_Msg_Select=Name:
NodeInfoTable.FileChooser_Error_Select=The directory name is invalid. The directory name can contain only alphanumeric characters (a-z A-Z 0-9).
NodeInfoTable.LOGOUT_NODE_FAILED=Logout failed. 
NodeInfoTable.IncorrectPassword=The password is incorrect.

NodeInfoTable.NullPassword =The password is empty.
NodeInfoTable.LoginFailed =Failed to log in to the server. Possible causes: \n1. The port is in use. \n2. The password is wrong.
NodeInfoTable.GetHostNameFailed =The OSS Maintenance Suite server process of server {0} is starting. Please try later...
NodeInfoTable.defaultPath =/opt/oss
NodeInfoTable.UnixdefaultPath =/opt/oss
NodeInfoTable.WindowsdefaultPath =c:\\oss
NodeInfoTable.masterNodeName = Host name
NodeInfoTable.atLeastOneSubNode = There should be at least one subserver
NodeInfoTable.NEW_INSTALL=New Installation Directory
NodeInfoTable.OLDINSTALL=Previous Installation Directory
NodeInfoTable.SomeOtherFileInTheInstallDir = The installation path {1} of the server {0} is not empty.\nPlease clear the path.
AddNodeDialog.RemoteIP=Remote IP Address
NodeInfoTable.NODE_TYPE_INVALIDATE=Specify the installation directory on the master server.
NodeInfoTable.IP_IS_NOT_LOCAL=Incorrect IP address. Please enter the local IP address.
NodeInfoTable.DirNotExistCreateIt = The directory {1} does not exist on the server {0}.\n Are you sure you want to create it?
NodeInfoTable.Node_Details=Server Information
NodeInfoTable.Summary_Node_Name=Server Name:
NodeInfoTable.Summary_Public_IP_Address=IP Address:
NodeInfoTable.Summary_Node_Type=Server Type:
NodeInfoTable.Summary_Installation_Path=Installation Directory:
NodeInfoTable.Help.Distribute.Message=Configure the OSS server information.\nThe default IP address will not be displayed if the OSS server is configured with multiple IP addresses. In this case, enter the correct IP address.\nModify the parameters of the OSS server if you want to install the centralized system and do not add or delete slave servers\nYou can modify the parameters of the OSS server and add or delete slave servers if you want to install the distributed system.
NodeInfoTable.Help.Single.Message=Configure the OSS server information.\nThe default IP address will not be displayed if the OSS server is configured with multiple IP addresses.\nIn this case, enter the correct IP address.
NodeInfoTable.Help.1toN.Message=Configure server information. If the server has multiple IP addresses, enter IP addresses manually.
NodeInfoTable.Prompt = Information
NodeInfoTable.InitBeforeSubsystem =Initializing components...Please wait.
NodeInfoTable.changeServerNameSelect=Please select the server:
NodeInfoTable.privatePanelError=The public network configuration of {0} conflicts with the private network configuration. Set the IP address again or modify the configuration file of the private network.
NodeInfoTable.CheckPrivatePanelFailed=Failed to check the network card panel.
NodeInfoTable.CheckDSConnection=DS communication failed. Please check the IP address. 
NodeInfoTable.PASSWORD_IS_DIFFERENT=The password of the administrator is inconsistent with the password of the admin user of the master server.
NodeInfoTable.ipAddressError=The IP address {0} is inconsistent with the configuration of {1}, Please confirm the configuration of {1}.
NodeInfoTable.privateConfigureError=Check whether the private network configuration file "engineering/conf/privateNetCfg.xml" is the same on all nodes?
NodeInfoTable.SureInstallSingelInVerritas=Are you sure you want to install a single-server system on the server installed with the HA software? \nClick <Yes> to continue the installation. \nClick <No> to select an installation type again.
NodeInfoTable.SureInstallSingelInVerritas.CMD=Are you sure you want to install a single-server system on the server installed with the HA software? \nClick <Yes> to continue the installation. \nClick <No> to select an installation type again.
NodeInfoTable.NeedInstallVeritas=Install the Veritas software before installing the Veritas hot standby system. Restart the OSS after the Veritas software is installed.
NodeInfoTable.ServerIP=Server IP Address:
NodeInfoTable.InstallationPath=Installation Path:
NodeInfoTable.NodeInfoTitle=Configure installation parameters.
NodeInfoTable.NodeRecommendInfo=The system partition of the OS is not recommended.
NodeInfoTable.InstallExit = Silent installation will exit.
FilePath.isNotMatchProductRule=The OSS installation directory does not comply with path rules. Refer to the installation manual.
ossIsIntalled=No node needs to be installed, no need install. \n {0} node(s) has been installed successfully before: \n {1}