OptionPane.info=Information
OptionPane.warn=Warning
OptionPane.error=Error
OptionPane.yes=Yes
OptionPane.no=No
OptionPane.cancel=Cancel
OptionPane.ok=OK
OptionPane.AllYes = All Yes
OptionPane.AllNo = All No
OptionPane.ShowDetail = Show Details
OptionPane.Exit = Exit
OptionPane.Continue = Continue
OptionPane.prompt=Information
OptionPane.Detail=Details
OptionPane.Confirmation=Confirm
OptionPane.Retry=Retry
OptionPane.Ignore=Ignore
