UPgrade.ConfigParas.CurrentVersion= Current version
UPgrade.ConfigParas.SourceListLabel= Select source version
UPgrade.ConfigParas.SourceList.OK=OK
UPgrade.ConfigParas.SourceList.Cancel=Cancel
UPgrade.ConfigParas.SourceList.Browes=Browse...
UPgrade.sourceVersionDes=The password of the database user sa is incorrect. \nEnter a correct password or cancel to exit. 
UPgrade.ConfigParas.SourceListTitle=Information
UPgrade.ConfigParas.Password=Password