ProgressPage.TotalTitle=Executing {0}...Please wait.
ProgressPage.processstart=Starting the {0}...Please wait.
ProgressPage.failederror=Failed to start the {0}.

ProgressPage.Deploy=deployment
ProgressPage.Undeploy=undeployment
ProgressPage.install=installation
ProgressPage.incinstall=add node
ProgressPage.reinstall=reinstallation
ProgressPage.upgradeinstall=upgrade installation

ProgressPage.Deployment=Deployment
ProgressPage.Undeployment=Undeployment
ProgressPage.Installation=Installation
ProgressPage.IncrementalInstallation=Add Node
ProgressPage.Reinstallation=Reinstallation
ProgressPage.Upgradeinstallation=Upgrade installation

ProgressPage.InstallProcessTitle = Installation.
ProgressPage.PatchInstallProcessTitle = Show Patch Installation Progress
ProgressPage.PatchUnInstallProcessTitle = Show Patch Uninstallation Progress
ProgressPage.communicateerror = Failed to communicate with node machine.

ProgressPage.UpgradeTitle=Executing installation and upgrade scripts...Please wait.
ProgressPage.UninstallTitle=Uninstalling...Please wait.
ProgressPage.PreUpgradeTitle=Creating tasks for backing up and uninstalling the existing OSS...Please wait.
ProgressPage.RollbackTitle=Recovering the old OSS...Please wait.
ProgressPage.PreRollbackTitle=Preparing for rollback...Please wait.
ProgressPage.Title=Progress
ProgressPage.DATAMODEL_INIT=Initializing the data...Please wait.
ProgressPage.InstallFailed=Installation failed. View log files:\n{0}logs
ProgressPage.UninstallFailed=Uninstallation failed. Check the log file.
ProgressPage.UpgradeFailed=Upgrade failed. Check the log file.
ProgressPage.RollbackFailed=Rollback failed. Check the log file.
ProgressPage.PatchInstallFailed=Failed to install the patch. Check the log file.
ProgressPage.PatchRollBackFailed=Failed to perform rollback. Check the log file.
ProgressPage.installPatchTitle=Patch installation started...Please wait.
ProgressPage.uninstallPatchTitle=Patch uninstallation started...Please wait.
ProgressPage.PatchTitle=Installing the patch...Please wait.
ProgressPage.PrePatchRollbackTitle=Uninstalling the patch...Please wait.
ProgressPage.creatingTask=Creating a task...Please wait.
ProgressPage.UpgradeTitle_pre=Backing up data and uninstalling the existing OSS...Please wait.
ProgressPage.RollbackTitle_pre=Uninstalling the existing OSS...Please wait.
ProgressPage.BusyDialog=Performing automatic rollback...
ProgressPage.AutoRollbackFinish=Automatic rollback completed.
ProgressPage.Title.Upgrade=Upgrade Progress
ProgressPage.Title.Rollback=Rollback Progress
ProgressPage.Wait=Wait
ProgressPage.Completed={0} completed
ProgressPage.Underline======================================
ProgressPage.Percentage=%
SelectPackage.HINT=Error
MSG_HOST_DISCONNECTED=Conection failed in following nodes:{0}. Please check the network connection.