RegisterService.Title = Register Windows Service
RegisterService.RegisterServices = The service is started automatically during system startup.
RegisterService.FailToRegister = Failed to register the Windows service.
RegisterService.RegisterServicesCMD = Do you want to start the service automatically during system startup?
