RestoreExitPage.Title=The restore operation is successful. Please restart OSS service.
RestoreExitPage.Note=Click <Finish> to close the restoration wizard.
RestoreExitPage.ERRORNote=Click <Exit> to close the restoration wizard.
RestoreExitPage.ErrorTitle=Restore operation failed.
RestoreExitPage.RestoreSuccess=The restore operation is successful.
RestoreExitPage.RestoreFailed=The restore operation failed.