RestoreSelFilePage.Introduction=Select a backup file.
RestoreSelFilePage.IntroductionForBCP=Select a text mode backup file.
RestoreSelFilePage.IntroductionForDump=Select a binary backup file.
RestoreSelFilePage.Introduce=Specify a path for the backup file that can be used to restore data. \nSelect the backup file and click <Next>.
RestoreSelFilePage.IP=Server IP Address:
RestoreSelFilePage.TransferMode=Transfer Mode:
RestoreSelFilePage.UserName=User Name:
RestoreSelFilePage.Password=Password:

RestoreSelFilePage.Browse=Browse...

RestoreSelFilePage.PromptInputError=The restoration information is incomplete. Complete the information.
RestoreSelFilePage.IsLocalIp=Can not use local server as FTP/SFTP server.
RestoreSelFilePage.RemoteRestorePath=Restore Path:
RestoreSelFilePage.DatabaseConnectionFailed=Failed to check the database. Possible cause:\n1.Database server is not running.\n2.Database is running abnormal.
RestoreSelFilePage.LoginFailed=Failed to log in to the server. Check for the user name or password.
RestoreSelFilePage.ConnectionFailed=Failed to connect to the remote server.
RestoreSelFilePage.DetailError=Possible causes are as follows:\n 1. The IP address is incorrect. \n 2. The user name or password is incorrect. \n 3. The remote service is not started.
RestoreSelFilePage.InvalidIp=Invalid IP address.
RestoreSelFilePage.ToContinue=This operation will restart the network management system.\nDo you want to continue?
RestoreSelFilePage.BackupServerNotRuuning=The backup database server is not running and the database restoration cannot continue.
RestoreSelFilePage.AllFolders=All Folders

RestoreSelFilePage.error=Error
RestoreSelFilePage.INVALID_INSTAL_PATH=The selected path is incorrect.\n1.The disk drive of the server must be selected.\n2.The path must be an absolute path that consists of characters, numbers, and hyphens (-) or underscores (_),\nand contains a maximum of 60 characters, and cannot contain blank space.
RestoreSelFilePage.LocalRestore=Local server
RestoreSelFilePage.RemoteRestore=Remote server

RestoreSelFilePage.InputError=Restoration information is incomplete. Complete the information.

RestoreSelFilePage.InCompleteIP=The remote server IP address is empty.\n
RestoreSelFilePage.InCompleteUserName=The user name is empty.\n
RestoreSelFilePage.InCompletePath=The path is empty.\n
RestoreSelFilePage.InCompletePassword=The password is empty.\n
RestoreSelFilePage.PasswordMismatch=The password consists of a maximum of 60 characters and can use only the following characters:\n
RestoreSelFilePage.IpInvalid=The IP address is incorrect.\n
RestoreSelFilePage.LocalRestorePath=Restore File:
RestoreSelFilePage.NMSALIVE=The OSS services are running. Stop them and try again.
RestoreSelFilePage.NMSALIVEMSG=The OSS services are running on the following hosts:
RestoreSelFilePage.Solution=A server problem occurred during the previous operation. Restart the engineering server.
RestoreSelFilePage.BrowseWindowLookIn=View
RestoreSelFilePage.BrowseWindowFileName=File Name
RestoreSelFilePage.BrowseWindowOpen=Open
RestoreSelFilePage.BrowseWindowCancel=Cancel
RestoreSelFilePage.PreRestoreCheckError= Pre-restoration check failed. View the log file.
RestoreSelFilePage.PreRestoreCheckError_Details=Possible causes are:\n1.Backup files doesn't exist.\n2.Backup files are invalid.\n3.The tmp path does not have enough permission.
RestoreSelFilePage.SelectFTPWarning=The FTP transmission mode is used currently. The transmission\ncontents are not encrypted and therefore security risks exist.\nThe SFTP transmission mode is strongly recommended.\nAre you sure you want to continue?
RestoreSelFilePage.SelectFTPOk=OK
RestoreSelFilePage.SelectFTPCancel=Cancel
RestoreSelFilePage.SSHConnectionFailed = Failed to connect to the remote database server using SSH.

RestoreSelFilePage.DBInfoFileInvalid=sysconfigure.xml file or database configuration files not valid.
