
RestorePreProgressPage.Title=Pre-processing restoration... Please wait.
RestorePreProgressPage.NewSubsystemsInBackup=Components are inconsistent. Increment install or reinstall is recommended to\n ensure component consistency before performing restoration; otherwise, \nthe information about the inconsistent components will be lost. Do you want to continue?
RestorePreProgressPage.InstanceMismatch=Instance mismatch for the following components. Use a deployment tool to add or delete components.
RestorePreProgressPage.SubsystemNotValid=The component is invalid.
RestorePreProgressPage.InstanceDynamicMacroMismatch=Dynamic macro is inconsistent for the following instances, force restore may lead to nms problems. Do you want to continue?
RestorePreProgressPage.RestorePreCheckError=An error occurred when restoring the previous check request service.
RestorePreProgressPage.RestoreFailed=Restoration failed.