Restore.Title =Network Management System Restoration
RestoreWizardPage.Introduction =Welcome to Network Management System Restoration Wizard
RestoreWizardPage.Introduce =This restoration wizard will guide you through restoration of the OSS database and component files. \nSelect the database restoration mode and click <Next>.
RestoreWizardPage.DatabaseBackup = Data Restore - Binary Mode(Recommended)
RestoreWizardPage.TableBackup = Data Restore - Text Mode
RestoreWizardPage.OracleEnvNotSet=Oracle environment is not set on the server.
RestoreWizardPage.FailedToGetDBLogonInfoFromDatamodel=Failed to obtain database login information from the data model.
