UpgradeSelectBackupPath.title= Select Backup Path
UpgradeSelectBackupPath.desciptionAppAndDatabase= Select the backup path for rollback.
UpgradeSelectBackupPath.Browse=Browse...
UpgradeSelectBackupPath.error= Error
UpgradeSelectBackupPath.DirectoryMustBeCharAndNum= The path must be an absolute path composed of characters or numbers or \'-\'or\'_\', \nand the path name contains a maximum of 60 characters.\n No space should exist before '\\' or '/' or ':'.
UpgradeSelectBackupPath.hint= Information
UpgradeSelectBackupPath.DirNotExistCreateIt= Directory {0} does not exist.
UpgradeSelectBackupPath.NullTitle= The backup path cannot be empty.
UpgradeSelectBackupPath.InvalidDiskDriver= Invalid path:
UpgradeSelectBackupPath.DirectoryError = Incorrect directory: "{0}".
Upgrader.ConfigNotFound= The upgrader.properties file is not found in the backup path.
Upgrader.ConfigTargetDBNotFound= The targetDB.txt file is not found in the backup path.
Upgrader.ConfigMacrostxtNotFound= The "{0}" file is not found in the backup path.
Upgrader.ConfigNmsRootDirNotExist= OSSROOT path {0} does not exist.
Upgrader.ConfigUpgradeModeNotFound=Information about the upgrade mode is not found in the upgrader.properties file.
RollBackInroduction.DBServerConfigFileNotFound=The configuration file for the database server is not found.
RollBackInroduction.DBServerConfigFileError=Failed to load data to the database server.
Upgrader.ConfigUpgradeDualModeNotFound=Information about the dual/single mode is not found in the upgrader.properties file.
Upgrader.ConfigUpgradeDualModeFileVolumeNotFound=Information about the file volume is not found in the upgrader.properties file.
Upgrader.ConfigUpgradeDualModeFirstDeviceNotFound= Information about the first device is not found in the upgrader.properties file.
Upgrader.ConfigUpgradeDualModeSecondDeviceNotFound = Information about the second device is not found in the upgrader.properties file.
Upgrader.ConfigUpgradeNMSTypeNotFound = Information about the OSS type is not found in upgrader.properties.
Upgrader.ConfigUpgradepluginManagerNotFound = Information about the Plugin Manager is not found in the upgrader.properties file.
BackupDBProgress.AppIsOnline=The OSS processes are still running. Stop them manually.
Upgrader.ConfigEnvNotFound=The environment variable is not found in the upgrader.properties file.
Upgrader.ConfigLastInstallDirNotFound=The {0} environment variable is not found.
DBServerConfig.PortIsInvalid_Win = Failed to connect to the database. Possible causes:\nDatabase port is wrong;\nDatabase is offline;\nMSDE Server is offline.
DBServerConfig.PortIsInvalid = Failed to connect to the database. Possible causes:\nDatabase port is wrong;\nDatabase is offline.
DBServerConfig.ServerNameIsInvalid_Win = Failed to connect to the database. Possible causes:\nDB Server Name is wrong;\nMSDE Server is offline.
DBServerConfig.ServerNameIsInvalid = The database server name is incorrect.
DBServerConfig.InstanceAndPwdIsInvalid = The database instance name or password is incorrect.
DBServerConfig.SUserAndPwdIsInvalid = The administrator name or password is incorrect.
DBServerConfig.InstancePwdNull = The database instance password cannot be empty.
DBServerConfig.ISQLCommandIsInvalid = The command isql of the database is not found.
SetupUpgradeEnvironment.CannotEndWithSeperator =The OSS environment variable is incorrect or ends with / or \\ .
Upgrader.ConfigUpgradeShortCutPathNotFound = Information about the shortcut file path is not found in the upgrader.properties file.
Upgrader.ConfigUpgradeNMsEnvarNotFound = OSSENVVAR is not found in the upgrader.properties file.
BackupProgress.ProIsAlive = The background applications are running. Do you want to continue?\nClick <Yes> to stop the background applications automatically.\nClick <No> to stop them manually.
Upgrader.ConfigUpgrade_SELEPRO_NotFound = The project name is not found in the upgrader.properties file.
Upgrader.ConfigUpgrade_PROJECTNAME_NotFound = The project name is not found in the upgrader.properties file.
Introduction.Title =Introduction
Introduction.Contents = This setup wizard will guide you through the rollback of NMS.
Introduction.ContentsVerify=This verify wizard will guide you through verification of package installation. \nClick <Next> to proceed with the next step.  \nClick <Cancel> to cancel verification.
Introduction.IsRunning = There is another installation program running. Please exit the program before installation.
Introduction.ContentsCMD =This setup wizard will guide you through the rollback of NMS.
Introduction.NotAuthority = Access denied, The program will exit.
Introduction.DBConfigFileInvalid = Some database configure files are invalid. Installation will exit
Introduction.ContentsUpgrade =This setup wizard will guide you through the upgrade of NMS. \nClick <Next> to proceed with the next step. \nClick <Cancel> to cancel upgrade.
Introduction.ContentsUpgradeCMD =This setup wizard will guide you through the upgrade of NMS. \nEnter <Next>n to proceed with the next step. \nEnter <Cancel>c to cancel upgrade.
Introduction.InitBeforeUpgradeInstall = Collecting source version information...
Introduction.hint = Information
Introduction.UpgradeTime = Upgrade Time
Introduction.SourceVersion = Source Version
Introduction.Operation = Operation
Introduction.TargetVersion = Target Version
Introduction.ComponentName= Component Name
Introduction.RollBack = Rollback
Introduction.Details = Details
Introduction.Next = Next
Introduction.Exit = Exit
Introduction.SerialNumber = Serial Number
Introduction.NodeInfo = Server Info
Introduction.Continue = Continue
Introduction.mainPageConfirmation = Press any key to select an operation.
Introduction.invalidInput = The entered value is invalid.
Introduction.UPGRADECOMPONENTDETAILS=Upgrade Component Details
Introduction.serialNo=Select
UpgradeSelectBackupPath.showversioncheck=Do you want to perform rollback on the OSS to {version} version?
CheckUpgradeEnviornment.ENTER_PASSWORD=The password for the sa user is incorrect.\n Enter a correct password.
CheckUpgradeEnviornment.PASSWRONG=Information
CheckUpgradeEnviornment.GETTINDBINFOFAILED.connection=Failed to connect to the database server.
UpgradeSelectBackupPath.NORollbackInfo=Rollback information is unavailable. Rollback cannot be performed on the OSS.
UpgradeSelectBackupPath.Confirm=Confirm
CheckUpgradeEnviornment.ERRORINGETTINGINFO=An error occurred while obtaining database information.
SelectPackage.HINT=Wait
SelectPackage.processing=Processing... Please wait.

UPgrade.ConfigParas.CurrentVersion= Current version
UPgrade.ConfigParas.SourceListLabel= Select source version
UPgrade.ConfigParas.SourceList.OK=OK
UPgrade.ConfigParas.SourceList.Cancel=Cancel
UPgrade.ConfigParas.SourceList.Browes=Browse...
UPgrade.sourceVersionDes= The backup path for rollback does not exist. Select another backup path.
UPgrade.ConfigParas.SourceListTitle=Set Backup Path

Summary.ApplicationInUse=The OSS folder {name} is in use. The operation cannot continue.
UpgradeSelectBackupPath.NORollbackInfo_tile=Error
RollbackIntroduction.Error=Error
Summary.DatabaseNotRunning=The database server is not running.
CheckUpgradeEnviornment.FailedToGetIP=Failed to get the system IP address and the system will exit.
CheckUpgradeEnviornment.IPISNOTLOCALIP=The IP address in the data model is not a local IP address and the system will exit.
NodeInfoTable.LOGIN_NODE_FAILED=Failed to connect to the slave server.
CheckUpgradeEnviornment.APPLICATIONNOTEXIST=The backup application does not exist and rollback cannot continue.
rollback.ApplicationNoTexist= The application folder {name} does not exist.
rollback.rollbackDatabaseNotexist=Database backup does not exist and rollback cannot continue.
CheckUpgradeEnviornment.GETTINDBINFOFAILED.ISQLFAILED= Failed to use the isql command to connect to the database server.
CheckUpgradeEnviornment.GETTINDBINFOFAILED.SQLPLUSFAILED= Failed to use the sqlplus command to connect to the database server.
RollbackInformation.inconsistentIP=The rollback information is incorrect. Rollback cannot continue.
RollbackInformation.WaitMessage=Processing rollback information... Please wait.
UpgradeDBTaskService.AUTOROLLBACK_FAILED=Automatic rollback failed