SelectLicense.selectlicense=License File:
SelectLicense.info = License Information
SelectLicense.Inputdes_CMD =Configure the license file required for OSS (If no license file is available, enter "n" to continue).
SelectLicense.Inputdes=Configure the license file required for OSS (If no license file is available, clear the selection of automatically configuring license file and click <Next>).
SelectLicense.Inputdes.license=Configure the license file required for OSS.
SelectLicense.Checkdes=Automatically configure the OSS license file during the installation
LicensePage.select=Browse...
LicensePage.License.Alert.SelectFile=Select a license file.
LicensePage.License.Alert.None=The license file does not exist. Select a correct license file.
LicensePage.License.Alert.Invalid=Select a valid license file.
LicensePage.InstallDiskFile.None=The InstallDisk.xml file does not exist. Configure it and reinstall this software.
LicensePage.InstallDiskFile.Error=Information in the InstallDisk.xml file is incorrect.
LicensePage.Alert.Size=The size of the license file exceeds 10 MB. Select a correct license file. 
InputLicensePanel.SelectLicenseFileLabel=Enter the save path of the license file.
