SelectPackageUtil.DatabaseName = Database Name: 
SelectPackageUtil.ProcessName = Relevant Process: 
SelectPackageUtil.UserName = User Name: 
SelectPackageUtil.RemotePrograme = (Remote Process.)
SelectPackageUtil.DBSetName = Database Set Name:
SelectPackageUtil.DBNames = Database Name:
SelectPackageUtil.DefaultPolicyIntroduction = The database backup tool will back up the database automatically. 
SelectPackageUtil.DefaultTimeType1 = at {0} every day.
SelectPackageUtil.DefaultTimeType2 = at {1} on {0} every week.
SelectPackageUtil.DefaultTimeType3 = on {1} in {0} every month.
SelectPackageUtil.Sun = Sunday
SelectPackageUtil.Mon = Monday
SelectPackageUtil.Tues = Tuesday
SelectPackageUtil.Wed = Wednesday
SelectPackageUtil.Thurs = Thursday
SelectPackageUtil.Fri = Friday
SelectPackageUtil.Sat = Saturday