SelectInstallType.addNodeRadioBtn=Add New Node
SelectInstallType.desTextArea=Select a server type.
SelectInstallType.dualServerRadioBtn=Dual server (for the local HA system using one storage device)
SelectInstallType.InstallationType=Installation Type
SelectInstallType.multiServerRadioBtn=Distributed server (for the distributed or remote distributed HA system)
SelectInstallType.newDeployRadioBtn=New Installation
SelectInstallType.reDeployRadioBtn=Re-Deployment Node
SelectInstallType.serverPanelTitle=Server type
SelectInstallType.singleinstallation=Single-server system
SelectInstallType.singleServerRadioBtn=Single server (for the single-server or remote HA system)
SelectInstallType.SunClusterHa=HA system (Sun cluster hot standby)
SelectInstallType.Title=Select Installation Type
SelectInstallTypeU.Title=Select Installation Type
