SelectPath.title = Select OSS Path
SelectPath.CMDtitle = OSS Path
SelectPath.NullTitle = The path cannot be empty.
SelectPath.error = Error
SelectPath.DirectoryError =Incorrect directory.
SelectPath.InvalidDiskDriver = Invalid disk drive.
SelectPath.DirectoryMustBeCharAndNum = 1.The driver must be in the server.\n2.The path must be an absolute path that consists of characters, numbers, and hyphens (-) or underscores (_), \n3.and the path name contains a maximum of 60 characters. No space should exist before '\\' or '/' or ':'.
SelectPath.hint = Information
SelectPath.DirNotExist = The directory does not exist. 
SelectPath.ProcessTitle = Running application:
