SelectPackage.InstallTitle = Select Components to Install
SelectPackage.UninstallTitle = Select Components to Uninstall
SelectPackage.IsInstall = Installed
SelectPackage.IsNotInstall = Not installed
SelectPackage.Unselected = Select required components.
SelectPackage.Hint = Information
SelectPackage.iMAPHintInfo = Description
SelectPackage.ExitHint = Do you want to exit the program?
SelectPackage.TreeTitle =OSS Component
SelectPackage.DependenceError = The dependency between components is incorrect. For example, a dependency loop occurs. Please view the logs for details.
SelectPackage.WinIsAlive = An application is running. Do you want to continue?\nClick <Yes> to stop the application automatically.\nClick <No> to stop it manually.
SelectPackage.ProIsAlive = A background program is running. Do you want to continue?\nClick <Yes> to stop the background application automatically.\nClick <No> to stop it manually.
SelectPackage.ProcessKillFail = A process is not stopped. Stop the process manually or retry to stop the process automatically.
SelectPackage.XMLError = XML file configuration error.
SelectPackage.AllPackagesInstalled = All components are installed.
SelectPackage.IsRunning = The installation (uninstallation) process is running.
SelectPackage.DependencyPkgNotSelect = The dependent components are not selected.
SelectPackage.DefaultDBBackupMsg = Do you want to set the database backup tool to backup the database according to the following policy?
SelectPackage.IsVersionConflict = Cannot continue the installation due to version conflict. 
SelectPackage.ConflictDetail =  Cannot continue the installation as the selected components or patches conflict with the current version.
SelectPackage.IsVersionFileInvalid = The version configuration file {0} is incomplete.
SelectPackage.KillWindows = Closing windows... Please wait.
SelectPackage.KillProcess = Stopping processes... Please wait.
SelectPackage.NotAuthority = The user rights are restricted. The program will exit.
SelectPackage.ProIsOnline = A background application is running. Stop it manually.
SelectPackage.WinIsOnline = An application is running. Stop it manually.
SelectPackage.NotFindXMLFilesContent = No components found.
SelectPackage.UpgradeDependentFail = The dependent upgrade package is not selected for {0}.
SelectPackage.IncompatiblePackageFound = {0} is incompatible with {1}.
SelectPackage.IncompatiblePackageExist = The incompatible component {0} exists.
SELECTPACKAGE.SUPPORTPATHNULL= The supported upgrade path is not configured for the version {version}. The upgrade will exit.
SelectPackage.HINT=Wait
SelectPackage.processing=Processing component information
SelectPackage.SourceNamesNotProcessed=The following components will not be considered for upgrading, as the source's name\nformat is not incorrect. Do you want to continue?
SelectPackage.JAR_NOT_FOUND=The following packages are missing in the corresponding directory:
SelectPackage.NoPackageToUpgrade=No components need to be upgraded. The upgrade cannot continue.
SelectPackage.InvalidCopyFilesClass=Invalid JAR packages.

SelectPackage.staticdataError= The configuration files contain some errors. Please check.
Summary.BackupDataModelFailed = Data model backup failed.