SelectInstallFolder.Select = Select
SelectInstallFolder.Browse = Browse...
SelectInstallFolder.InstallNote = \nThe system will install this program in the following directory.\nclick <Next> to install the program to this directory or click Browse to select another directory.
SelectInstallFolder.InstallAgainNote = \nThe system will install this program in the following directory.
SelectInstallFolder.DestinationFolder = Destination Directory:
SelectInstallFolder.Title = Select Installation Directory
SelectInstallFolder.TitleChoice = Information
SelectInstallFolder.DirNotExistCreateIt = Directory {0} \ndoes not exist. Do you want to create it?
SelectInstallFolder.Error = Error
SelectInstallFolder.DirectoryError = Incorrect Directory: "{0}".
SelectInstallFolder.DiretoryConfine = The length of directory must not be more than 60 characters. Please enter the directory again.
SelectInstallFolder.DirectoryMustBeCharAndNum =1.The driver must be in the server.\n2.The path must be an absolute path that consists of characters, numbers, and hyphens (-) or underscores (_), \n3.and the length of the name must not be more than 60 characters,and it is invalid to have space before '\\' or '/' or ':'.
SelectInstallFolder.CreateDirFail = Failed to create this directory
SelectInstallFolder.InstallFolder = The installation directory: 
SelectInstallFolder.SomeOtherFileInTheInstallDir = Directory {0} is not empty. Please select another one.
SelectInstallFolder.IllegalFilesInFolder = Some illegal files exist in directory {0}. Delete them or select another directory.
SelectInstallFolder.IllegalFilesList = Illegal files:
SelectInstallFolder.DependenceError = Component dependency error: A dependency loop occurs. Please view the logs for details.
SelectInstallFolder.hint = Information
SelectInstallFolder.InitBeforeInstall =Initializing installation...
SelectInstallFolder.ApproveTip = Open the selected directory
SelectInstallFolder.DesktopTip = Desktop
SelectInstallFolder.DirName = Directory:
SelectInstallFolder.CanntBeWrite = Failed to create the installation directory\nor the directory cannot be written.
SelectInstallFolder.InvalidDiskDriver = Invalid disk driver: "{0}".
SelectInstallFolder.DiretoryNull = The installation path cannot be empty.
SelectInstallFolder.PackageXmlWrong = The component description file {0} is incorrect. Installation will exit.
SelectInstallFolder.SystemIsNotCompatible = The existing system version is not compatible with this version. Continue? \nTo proceed with installation, select a different destination path. Otherwise, the installation will exit.
SelectInstallFolder.SystemIsNotCompatibleExit = The existing system version is not compatible with this version. The installation will exit.
SelectInstallFolder.InvalidPath = Invalid directory.
SelectInstallFolder.NoSupportPathBlank = The path must be an absolute path that consists of characters or numbers or \'-\'or\'_\', \nand the length of the name must not be more than 60 characters,\nand it is invalid to have space in the name path.
SelectInstallFolder.AnotherVersionExist = Another version exists in the system.\nThe existing version is: {0} \nThe version that is currently installed is: {1} \nThe existing version may not work after new installation. \nDo you want to proceed with the installation?
SelectInstallFolder.versionNotAvailable = <Not Available>
SelectInstallFolder.IsExit = Exit succeeded. 
SelectInstallFolder.Symboliclinks = The entered path contains links. The path will be converted into a real path.
SelectInstallFolder.PackageOrGroupNameNull = It is mandatory to have names for Packages/Package groups. Installation will exit.
SelectInstallFolder.MandatoryTagNotFound = One or more mandatory fields are not configured in the component description file: {0}.\nInstallation will exit.
SelectInstallFolder.CHANGE_SYBASE_INTERFACES_FAILED=Failed to change interfaces in the Sybase file.
