SelectInstallType.InstallationType=Installation Solution
SelectInstallType.singleinstallation=Single-server system
SelectInstallType.singleserversystem=Single-server system
SelectInstallType.SunClusterHa=Sun Cluster
SelectInstallType.VeritasHa=Veritas
SelectInstallType.WindowsClusterHa=HA (Windows Cluster)
SelectInstallTypeU.desTextArea=Select a server type.
SelectInstallTypeU.dualServerRadioBtn=Dual server (for the local HA system using one storage device)
SelectInstallTypeU.InstallationType=Installation Type
SelectInstallTypeU.multiServerRadioBtn=Distributed server (for the distributed or remote distributed HA system)
SelectInstallTypeU.NeedInstallVeritas=Install Veritas software at first.
SelectInstallTypeU.serverPanelTitle=Server type
SelectInstallTypeU.SingleInstallation=Single-server system
SelectInstallTypeU.singleServerRadioBtn=Single server (for the single-server or remote HA system)
SelectInstallTypeU.sunclusterhotinstallation=Install the Sun Cluster HA.
SelectInstallTypeU.SureInstallSingelInVerritas.CMD=Check the Veritas software.
SelectInstallTypeU.SureInstallSingelInVerritas=Check whether to install the Veritas software on the single-server system.
SelectInstallTypeU.Title=Select Installation Type
SelectInstallTypeU.veritashotinstallation=Install Veritas HA
SelectInstallTypeU.windowsclusterhotinstallation=Install Windows Cluster HA
