SetClientShortcutFld.InstallNote=\nThe setup program will create shortcuts in a specified folder. \nEnter a folder name in the text box.
SetClientShortcutFld.DestinationFolder=Shortcut Folder
SetClientShortcutFld.DiretoryNull=The shortcut folder cannot be empty.
SetClientShortcutFld.Title=Shortcut Folder Settings
SetClientShortcutFld.CreateShort=Whether to create shortcut on Desktop
SetClientShortcutFld.CreateShortInFolder=Create shortcut inside Shortcut Folder on Desktop
SetClientShortcutFld.CreateShortNormal=Create shortcut normally on Desktop
SetClientShortcutFld.DirectoryError=The shortcut folder name is invalid, please enter valid name.\n1.The folder name cannot contain characters \ / : * ? " , < > and |\n2.The length of the folder name cannot exceed 60 characters\n3.The folder name cannot be empty.
SetClientShortcutFld.Error=Error