ShowDlg.title = Information
ShowDlg.exitBtn = Exit
ShowDlg.retryBtn = Retry
ShowDlg.confirmBtn = OK
ShowDlg.pwd = Password:
ShowDlg.path = OSS Path:
ShowDlg.select = Select
ShowDlg.error = Error
ShowDlg.DirectoryError = Incorrect Directory:
ShowDlg.DirectoryMustBeCharAndNum = 1.The driver must be in the server.\n2.The path must be an absolute path that consists of characters, numbers, and hyphens (-) or underscores (_), \n3.and the path name contains a maximum of 60 characters. No space should exist before '\\' or '/' or ':'.