SaveDbinfoError=Save the database information to a file failed sysconfigure.xml.
SaveDbserverError=Save the database service information to sysconfigure.xml file failed.
SaveDeployschemeError=Save the deployment information to deployscheme.xml file failed.
SaveHostinfoError=Save host information to sysconfigure.xml file failed.
SaveInstallscopeError=Save the installation type to installscope.ini file failed.
SaveInstallsummaryError=Save instance information to InstallSummary.xml file failed.
SaveMacroError=Save the macro information to macros.ini file failed.
SaveScanZipError=Save the list of files to be installed to installscope.ini failed.
ServicegroupStaticdataerror=Check the service group configuration failed.
SrvGrpNotExist=Service group {0} not exist, it will exit.
delInstallScopeiniError=Delete installscope.ini file failed.
writeRemoteNodeIDIni=Save nodeID.ini file failed.
copySysconfigurexmlToServer=save sysconfigure.xml to OSS directory failed.
copySysconfigurexmlToEngr=copy sysconfigure.xml file to msuite tool directory failed.
copyFilesLocaleOrRemote=copy data source file to remote machine failed.
failNodes=last time {0} fail nodes:
install=install
upgradeinstall=upgradeinstall