StorageWelcomePage.Title= Welcome to Network Management System
StorageWelcomePage.Welcome= Welcome to Network Management System 
StorageWelcomePage.WelcomeExt=Network Management System
StorageWelcomePage.Request= Select one of the following operations:
StorageWelcomePage.Backup= Back up the OSS data
StorageWelcomePage.Restore=Restore the OSS data 
StorageWelcomePage.CfgPolicy= Configure OSS backup policy
StorageWelcomePage.ReturnPrePage= Previous
StorageWelcomePage.Exit =   End
StorageWelcomePage.DeploymentTool=Deployment Tool
StorageWelcomePage.DBMgrTool= Database management tool

ProgressPage.StorageTitle=Storing data... Please wait.

BackupPolicyWelcomePage.Title=Welcome to Network Management System

BackupPolicyWelcomePage.ReturnPrePage=Previous
BackupPolicyWelcomePage.Welcome=Welcome to Network Management System 
BackupPolicyWelcomePage.WelcomeExt=Network Management System
BackupPolicyWelcomePage.Request=Select one of the following ways:
BackupPolicyWelcomePage.Exit=End

