
SubsystemTree.Title1 = You will install components by {0}. By default, the components of the {1} are automatically selected. You can select components according to the requirements or by using the OSS Maintenance suite after the installation.
SubsystemTree.Title2 = You will install components by license file. By default, the components specified in the\nlicense file are selected. You can add components according to the requirements or\nremove or add components by using the OSS Maintenance suite after the installation.
SubsystemTree.Title3 = You will install components in custom mode. You can add components according to the requirements or remove or add components by using the OSS Maintenance suite after\nthe installation.
SubsystemTree.Title4 = You will install components in full installation mode. You can remove or add components by using the OSS Maintenance suite after the installation.

SubsystemTree.ModifyButton = Select Component
SubsystemTree.Done = The components have been selected completely.
SubsystemTree.Title = Select Components
DeploymentSchemeSubsystem.PakageFilesError=The following components are not configured with package files.\nModify and run again.
DeploymentSchemeSubsystem.PackageDependencyError = The following components have installation package dependency errors.
DeploymentSchemeSubsystem.PackageErrorFilePath= The installation package configured for the component is not found in the {0} directory. \nThe mapping between components and installation packages is as follows:
DeploymentSchemeSubsystem.PackageDependenceFilePath= The installation package in the {0} directory has dependence errors. \nThe mapping between components and installation packages is as follows:

DeploymentSchemeSubsystem.AllNodesConfig=All nodes will be configured by default.
SubsystemTree.pkgnotexisted=The following packages are not available in the software library {0}. Please check.
SubsystemTree.dependencynotexisted=The dependency of some packages is configured incorrectly. Check it and perform reinstallation.
SubsystemTree.loopdependencyError= Some packages are configured as loop dependency. Check it and perform reinstallation.
SubsystemTree.CrossdependencyError= Some packages are configured as cross-dependency between the server and the client. Check it and perform reinstallation.
SubsystemTree.databasexmlError= The database configuration files of some components are wrong. Check it and perform reinstallation.
errorXmlList=Failed to parse the following .xml package description files.
