upgrade.Summary=Please confirm that the displayed information about the upgrade is correct for your system and site.
UpgradeSelectBackupPath.NodeConnection Failed= RPC connection failed.
UpgradeSelectBackupPath.Confirm=Confirm:
UPgrade.sourceVersionDes=Select the data device path and log device path for the new database.
UPgrade.LogPathSelect=Select the log device path for the new database.
UPgrade.DataPathSelect=Select the data device path for the new database.
UPgrade.ConfigParas.SourceListTitle=Select Database Device Path
UPgrade.ConfigParas.SourceListLabel=Log Device Path
UPgrade.ConfigParas.SourceList.OK=OK
UPgrade.ConfigParas.SourceList.Cancel=Cancel
UPgrade.ConfigParas.CurrentVersion=Data Device Path
SummaryUtil.PermissionCheckFail=No access to the directory {path}.
SummaryUtil.FailedDir=Failed to create the directory {path}.
SummaryProgress.ProIsAlivecmd=The background applications are running. Do you want to continue?\nEnter y<Yes> to stop the background applications automatically.\nEnter n<No> to stop them manually.
SummaryProgress.ProIsAlive=The background applications are running. Do you want to continue?\nClick <Yes> to stop the background applications automatically.\nClick <No> to stop them manually.
Summary.systemexit=The upgrade cannot continue.
Summary.susbystemInformation=Upgrade Component Names: 
Summary.subsystempathNotexit=The following component file path does not exist on the system.
Summary.sapceNotenough=The space in partition {partitionname} is insufficient. Required space:{requiSpace} MB; Free space: {freeSpace} MB.
Summary.nodeName=Server Name: 
Summary.newSusbystemInformation=New Component Names: 
Summary.newDBspaceRwq=Required space for application database in partition {partitionname}: 
Summary.isCreateShotcutOnDesk = Do you want to create a shortcut on the desktop?
Summary.freeSpaceon=Free space on partition {key}
Summary.drive=Drive: 
Summary.colonrequired=: 
Summary.backupPath=Backup Path: 
Summary.UsedState =Disk Space: 
Summary.UpgInfomatin =[Upgrade Information]
Summary.Unselected= Select a component.
Summary.Title = Confirm Installation Information
Summary.TargetVersion =Target version: 
Summary.SubsystemDescription=Component Description: 
Summary.Subsystem =Component: 
Summary.SpaceRequiredForUpgrade=Required space for upgrade in partition {partitionname}: 
Summary.SourceVersion =Source version: 
Summary.SetupModeNotSupply=The component file is empty. The program will exit.
Summary.SetupMode =Installation Mode
Summary.SelectedPackages =Install the following components: 
Summary.Retry = Retry
Summary.Prompt = Information
Summary.ProductVersion =Product Version: 
Summary.Previous = Previous
Summary.PatchTitle = Confirm Patch Installation
Summary.PackageInfomation =[Component Information]
Summary.PMS_DB_SIZE=Space required for performance management application: 
Summary.OSVersion=OS Version: 
Summary.OSType=OS Type: 
Summary.NoUpgradeSubSystems= No components found. The upgrade cannot continue.
Summary.Neededspace=Required space for installation {partitionname}: 
Summary.NeededMemorySize =Required memory: 
Summary.NeededDiskSpaceForPatch =Required disk space for patch installation: 
Summary.NeededDiskSpaceForBackup =Required disk space for backup: 
Summary.NeededDiskSpace =Required Temporary Disk Space: 
Summary.NODEINFO=[Server Info]\n
Summary.REMOTEDBNODEINFO=[Remote database server info]
Summary.NMS_DB_SIZE=Space required for application database: 
Summary.NMS_APP_SIZE=Space required for application: 
Summary.MemorySizeNOTSET = Not specified
Summary.MemoryNotEnough =The system memory is insufficient.
Summary.MaxAfterExpansion =Maximum space after expansion: 
Summary.InstallPath=Installation Path: 
Summary.IndividualDetails=Disk space required: 
Summary.Hint=Error
Summary.Exception = An exception occurred while creating the database.
Summary.DiskSpaceNotEnoughWarning =The disk space on partition {0} will be insufficient.
Summary.DiskSpaceNotEnoughCMD =The disk space is insufficient.
Summary.DiskSpaceNotEnough =The disk space on partition {0} is insufficient.
Summary.DevicesapceNotenough=The space in partition {partitionname} is insufficient. Required space:{requiSpace}; Free space: {freeSpace}
Summary.DeviceNotExist=The following database device path does not exist.
Summary.DatabaseVersion =Database Version: 
Summary.DatabaseType =Database Type: 
Summary.DatabaseNotRunning=The database server is not running.
Summary.DBSERVER_SIZE=Space required for DBServer: 
Summary.Confirm = Check whether the parameters are correct. If they are correct, click <Next> to start the installation. \nOtherwise, click <Previous> to modify the parameters. \nYou cannot click <Previous> after you click <Next>.
Summary.CheckMemAndDisk =Checking memory and disk space... Please wait.
Summary.Cancel = Exit installation
Summary.BaseInfomatin =[Basic Information]
Summary.Backupspacerequired =Space required for backup in partition {partitionname}
Summary.BackupDataModelFailed = Data model backup failed
Summary.ApplicationInUse=The OSS folder {name} is in use. The operation cannot continue.
Summary.ActualMemorySize =Physical Memory: 
Summary.ActualDiskSpaceForBackup =Available disk space for backup: 
Summary.ActualDiskSpace =Available Disk Space: 
SelectPackage.processing=Processing summary information...
SelectPackage.HINT=Wait
Introduction.previous=Previous 
Introduction.exitSuccess=The system exits successfully
Introduction.cancle=Cancel
Introduction.SELECTOPERATION=Select the option
Introduction.Continue=Retry
DatabaseFileBrowser.SapaceNotEnoughPath=The space in partition {partitionname} is insufficient. Required space: {requiSpace}; Free space: {freeSpace}
DatabaseFileBrowser.PathInvalid=Invalid path: {path}.
DatabaseFileBrowser.EmptyPath=The data device path and log device path are empty.
DatabaseFileBrowser.EmptyLogPath=The log device path is empty.
DatabaseFileBrowser.EmptyDataPath=The data device path is empty.
DatabaseFileBrowser.DifferentPath=The path of the original OSS database is different from that of the new database.
CopyFiles.NotFindXMLFilesContent = No components can be installed.
CopyFiles.InvalidCopyFilesClass = Failed to initialize the JAR file filter.
CopyFiles.DependenceError = The dependency between components is incorrect. For example, a dependency loop occurs. \nPlease view the logs for details.
BackupDBProgress.DB_INUSE=Database in use

Summary.MemoryInfo=Memory Information: 
Summary.SpaceInfo=Disk Space Information: 
CopyFiles.AllPackagesInstalled=All components are installed.
CopyFiles.IsVersionConflict=Version conflict. Failed to continue the installation.
CopyFiles.ConflictDetail=Cannot continue the installation as the selected components or patches conflict with the current version. 
CopyFiles.NotAuthority=The user rights are restricted. The program will exit.
CopyFiles.Hint=Information

Sumamry.DBNotExist=The database configured for upgrade does not exist.
Summary.check.error= The summary check finds the following error(s).
Summary.subsystem.dbname.not.exist=The database {1} in subsystem {0} does not exist.
Sumamry.RemoteSpaceError=Failed to check the space of {0}.


Summary.bigger.than.max=The device number or log device number of {0} is greater than the maximum number configured for the databases.
Summary.have.used=The device number or log device number of {0} has been used .
Summary.error.file.path=Failed to create the file path of {0}.
Summary.same.device.num=The device number or log device number of {0} conflicts with the existing number.
Summary.illegal.num=The device number or log device number of {0} is invalid.

Summary.PatchSummaryError=The summary page has errors. Click <OK> to retry and Cancel to exit.
Summary.usedDbInfo=Used DB record for {0} are : \n
Summary.Process=Process = 
Summary.User= User = 
Summary.configvalue.invalid=configure value is invalid: {0}