SummaryProgress.ProIsAlive=The background applications are running. Do you want to continue?\nClick <Yes> to stop the background applications automatically.\nClick <No> to stop them manually.
Summary.Title = Confirm Installation
Summary.BaseInfomatin = [Basic Information]
Summary.InstallPath = Installation Path: 
Summary.DiskSpaceNotEnough = The disk space on partition {0} is insufficient.
Summary.DiskSpaceNotEnoughWarning = The disk space on partition {0} will be insufficient.
Summary.DiskSpaceNotEnoughCMD = The disk space is insufficient.
Summary.ActualDiskSpace = Available Disk Space: 
Summary.NeededDiskSpace = Required Disk Space: 
Summary.MaxAfterExpansion = Maximum Space After Expansion: 
Summary.OSVersion = OS Version: 
Summary.DatabaseType = Database Type: 
Summary.DatabaseVersion = Database Version: 
Summary.ProductVersion = Product Version: 
Summary.PackageInfomation = [Component Information]
Summary.SetupMode = Installation Mode
Summary.SelectedPackages = Install the following components: 

Summary.Exception = An exception occurred while creating the database.
Summary.Confirm = Check whether the parameters are correct. If they are correct, click <Next> to start the installation. \n Otherwise, click <Previous> to modify the parameters.\nYou cannot click <Previous> after you click <Next>.

Summary.MemoryNotEnough = The system memory is insufficient.
Summary.ActualMemorySize = Physical Memory: 
Summary.NeededMemorySize = Required Memory: 
Summary.MemorySizeNOTSET = Not defined
Summary.OSType = OS Type: 
Summary.Cancel = Exit installation
Summary.Previous = Previous
Summary.UsedState = Disk Space: 
Summary.isCreateShotcutOnDesk = Do you want to create a shortcut on the desktop?
Summary.drive = Drive: 
Summary.Subsystem = Component: 
Summary.SubsystemDescription=Component Description: 
Summary.SourceVersion = Source version: 
Summary.TargetVersion = Target version: 
Summary.susbystemInformation=Upgrade Component Names: 
Summary.newSusbystemInformation=New Component Names: 
Summary.IndividualDetails=Disk space required: 
Summary.DBSERVER_SIZE=Space required for DBServer: 
Summary.NMS_APP_SIZE=Space required for application: 
Summary.PMS_DB_SIZE=Space required for performance management application: 
Summary.NMS_DB_SIZE=Space required for application database: 
Summary.Neededspace=Space required for installation: 
Summary.NODEINFO=\n[Server Info]\n
Summary.nodeName=Server Name:
Summary.sapceNotenough=The space in partition {partitionname} is insufficient. Required space: {requiSpace}; Free space: {freeSpace}.
Summary.Backupspacerequired = Space required for backup in partition {partitionname}
Summary.freeSpaceon= Free space in partition {key}
Summary.colonrequired=:
Summary.PatchTitle = Confirm Patch Installation
Summary.backupPath=Backup Path 
Summary.systemexit=The upgrade cannot continue.
Introduction.SELECTOPERATION=Select the option
Introduction.Continue=Retry
Introduction.cancle=Cancel
Introduction.exitSuccess=The system exits successfully
Introduction.previous=Previous 
BackupDBProgress.DB_INUSE=Database in use
SummaryProgress.ProIsAlivecmd=The background applications are running. Do you want to continue?\nEnter y<Yes> to stop the background applications automatically.\nEnter n<No> to stop them manually.
Summary.newDBspaceRwq=Space required for application database in partition {partitionname}:
Summary.ApplicationInUse=The operation cannot continue as the application folder {name} is in use.
Summary.ActualDiskSpaceForBackup = Available disk space for backup: 
Summary.NeededDiskSpaceForBackup = Required disk space for backup: 
Summary.subsystempathNotexit=The following component file path does not exist in the system.
SelectPackage.HINT=Wait
SelectPackage.processing=Processing summary information...
upgrade.Summary=Please confirm that the displayed information about the upgrade is correct for your system and site.
UPgrade.ConfigParas.CurrentVersion=Data Device Path
UPgrade.ConfigParas.SourceListLabel=Log Device Path
UPgrade.ConfigParas.SourceList.OK=OK
UPgrade.ConfigParas.SourceList.Cancel=Cancel
UPgrade.ConfigParas.SourceListTitle=Select Database Device Path
UPgrade.sourceVersionDes=Please select the data device path and log device path for \nnew database.
DatabaseFileBrowser.EmptyPath=Data device path and log device path are empty.
DatabaseFileBrowser.DifferentPath=The path of source OSS databases are different with new \ndatabase.
DatabaseFileBrowser.EmptyDataPath=Data device path is empty.
DatabaseFileBrowser.EmptyLogPath=Log device path is empty.
DatabaseFileBrowser.SapaceNotEnoughPath=Space not enough on partition "{partitionname}", required space:{requiSpace},\nfree Space:{freeSpace},
DatabaseFileBrowser.PathInvalid=Invalid path: {path}.
UPgrade.DataPathSelect=Select the data device path for the new database.
UPgrade.LogPathSelect=Select the log device path for the new database.
Summary.DeviceNotExist= The following database device path does not exist.
UpgradeSelectBackupPath.Confirm=Confirm:
Summary.DatabaseNotRunning=The database server is not running.
Summary.Prompt = Information
Summary.CheckMemAndDisk =Checking memory and disk space... Please wait.
Summary.DevicesapceNotenough=The space in partition {partitionname} is insufficient. Required space: {requiSpace}; Free space: {freeSpace}.
Summary.Retry = Retry
SummaryUtil.FailedDir=Failed to create the directory {path}.
SummaryUtil.PermissionCheckFail=No access to the directory {path}.
Summary.SpaceRequiredForUpgrade=Space required for the upgrade in partition {partitionname}:
UpgradeSelectBackupPath.NodeConnection Failed= RPC connection failed.

CopyFiles.InvalidCopyFilesClass = Failed to initialize the JAR file filter.
CopyFiles.DependenceError = The dependency between components is incorrect. For example, a dependency loop occurs.\nPlease view the logs for details.
CopyFiles.NotFindXMLFilesContent = No component can be installed.

Summary.SetupModeNotSupply=The component file is empty. The program will exit.
Summary.Hint=Error
Summary.Unselected= Select a component.
SummaryUtil.UnparseXML = Failed to parse the database configuration file.

