UninstallProgress.InstallTitle=Installing...Please wait.
UninstallProgress.UninstallTitle=Uninstalling...Please wait.
ProgressPage.Title = Uninstalling
ProgressPage.UninstallTitle=Uninstalling
ProgressPage.InstallTitle=Installing
ProgressPage.AreYouSureToContinue =The system will start the uninstallation. Are you sure you want to continue?
UninstallProgress.failedmsg=Task executed failed during uninstallation.