ExitPage.Title=Uninstallation Complete
ExitPage.Finish=Finish
ExitPage.Note=The {0} is uninstalled successfully. \nClick <Finish> to complete uninstallation.

ExitPage.AffirmRestart=Are you sure you want to restart the operating system now?
ExitPage.Hint=Information
ExitPage.RestartTip =You need to restart the operating system.
ExitPage.NoteCMD=The {0} is uninstalled successfully.
ExitPage.CONFIRM=Confirm
ExitPage.ErrorNote=The {0} is uninstalled failed. View log files for details {1}.
ExitPage.ErrorTitle=Uninstallation failed.
ExitPage.NoteTip=\n\nNote:
ExitPage.NoteMsg=\nSome files in {0} are not deleted. Will be deleted after restart.