UninstallClient.Title = Uninstall Client
UninstallClient.AreYouSureToContinue = The system starts to uninstall the OSS client. Do you want to continue?
UninstallClient.Finish = Complete
UninstallClient.Hint = Information
UninstallClient.UninstallClient = The client has been uninstalled. 
UninstallClient.Note = The {0} has successfully uninstalled the client. \nClick <Finish> to complete client uninstallation.
UninstallClient.RestartTip = You need to restart the operating system.
UninstallClient.AffirmRestart = Are you sure you want to restart the operating system now?
UninstallClient.ClearDirConfirm = To ensure a correct installation the next time, delete the installation directory manually.
UninstallClient.Warn = Warning
UninstallClient.ClearDirConfirmDetail = The following files and directories should be deleted manually:
UninstallClient.DelEnv = Delete environment variables
UninstallClient.DeleteShortcuts = Delete shortcuts
UninstallClient.DeleteRigisters = Delete registries
UninstallClient.DeleteFiles = Delete files
UninstallClient.Completed = Completed
