Task.PreUninstallScripts=Running uninstallation prescripts...
Task.PostUninstallScripts=Running uninstallation postscripts...
Task.UninstallDB=Uninstalling the database...
Task.UninstallEnv=Deleting environment variables...
Task.UninstallShortcuts=Deleting shortcuts...
Task.UninstallRegistery=Deleting registry information...
Task.UninstallFiles=Uninstalling application...
Task.UninstallPreScripts=Running uninstallation prescripts...
Task.UninstallScripts=Running uninstallation scripts...
Task.UninstallPostScripts=Running uninstallation postscripts...
Task.UninstallService=Deleting services...
