UninstallClientSummary.Hint = Information
UninstallClientSummary.Title = Confirm Uninstallation
UninstallClientSummary.SubsystemInfomation = [Subsystem to uninstall:]
UninstallClientSummary.NoSubsystems =No subsystem needs to be uninstalled. The uninstallation will exit.
