UninstallService.RemotePrograme = (Remote Process.)
UninstallService.DatabaseName = Database Name: 
UninstallService.ProcessName = Process Name: 
UninstallService.UserName = User Name: 
UninstallService.DBIsOnline = The database is in use. Stop all processes manually,\n or restart the database service manually.
UninstallService.DBConnectionError= Database connection error. Check whether a database service is running.
UninstallService.LoginFailed= Failed to log in to the following server(s).Please check the network connection.
NODEINFO_DATAMODEL_FAIL=Failed to obtain server information from the data model.
CHECK_LOG=Check operation logs for details.
UninstallService.NMSAlives=The OSS processes are running. Shut down the OSS.
UninstallService.NMSAlivesDetail=The IP address of the server on which the OSS is running is as follows:
UninstallService.DropDBFailed=Failed to drop the OSS database.
