UPgrade.ConfigParas.CurrentVersion= Current Version:
UPgrade.ConfigParas.SourceListLabel= Source Version:
UPgrade.ConfigParas.SourceList.OK=OK
UPgrade.ConfigParas.SourceList.Cancel=Cancel
UPgrade.ConfigParas.SourceListTitle=Version List
UPgrade.sourceVersionDes=Current version of {domain} is unavailable in the source version. \nSelect the source version.