WelcomePage.Title=Welcome to Network Management System
WelcomePage.Welcome=Welcom to Network Management System
WelcomePage.WelcomeExt=Network Management System
WelcomePage.Request=What do you want to do?
WelcomePage.Install=Installation
WelcomePage.Patch=Patch
WelcomePage.Upgrade=Upgrade
WelcomePage.BackupRestore=Backup and Restore
WelcomePage.Maintanence=Maintenance
WelcomePage.Uninstall=Uninstallation 
WelcomePage.Exit=Exit
WelcomePage.NoSubsystems=No components need to be uninstalled.
WelcomePage.NeedCreateUpgradeDataModel=It is required to create the data model before upgrade. Click <OK> to create the data model.
WelcomePage.CreateUpgradeDataModelFinish=Succeeded in creating the data model.
WelcomePage.CreateUpgradeDataModel=Creating data model...It will take 5 to 15 minutes. Please wait.
WelcomePage.DBMainTool=Database Maintenance Tool
WelcomePage.UninstallDone=Installation is not completed. The system will exit.
WelcomePage.InstallDone=Installation is completed. The system will exit.
WelcomePage.InvalidMode=Incorrect mode. The system will exit.
WelcomePage.DataModelNotDelete=The data model is not deleted. Delete the directory.
WelcomePage.NeedCreateUpgradeDataModelcmd=It is required to create the data model before upgrade.
WelcomePage.CreateUpgradeDataModelFailed=Failed to create the data model.
WizardFrame.NoSchemaFile=The offline schema file is not specified.
WizardFrame.SchemaFileNotFound=The offline schema file is not found.
WizardFrame.SilentFileNotFound=The silent file is not found.
WizardFrame.SchemaFileError=The offline schema file is invalid. 
WizardFrame.DatamodelNOTcorrectUpgrade=The data model is incorrect and the upgrade cannot continue.
WizardFrame.DatamodelNOTcorrectRollback=The data model is incorrect and the rollback cannot continue.
WizardFrame.DatamodelNOTcorrectRollback_Error=Error:
WizardFrame.DatamodelNOTcorrectPatch=The data model is incorrect and the patch installation cannot continue.
