WizardFrame.U2000FW=Engineering Framework
WizardFrame.install=Install
WizardFrame.uninstall=Uninstall
WizardFrame.Verify=Verify
WizardFrame.next=Next 
WizardFrame.nextCMD=Next>
WizardFrame.previous=<Previous
WizardFrame.previousCMD=Previous
WizardFrame.cancel=Cancel
WizardFrame.hint=Information
WizardFrame.confirmation=Confirm
WizardFrame.InstallAffirmCancel=Are you sure you want to cancel the installation?
WizardFrame.UninstallAffirmCancel=Are you sure you want to cancel the uninstallation?
WizardFrame.VerifyAffirmCancel=Are you sure you want to cancel the verification?
WizardFrame.UpdateAffirmCancel=Are you sure you want to cancel the operation?
WizardFrame.PatchAffirmCancel=Are you sure you want to cancel the patch installation?
WizardFrame.UpgradeAffirmCancel=Are you sure you want to cancel the operation?
WizardFrame.StoreAffirmCancel=Are you sure you want to cancel the operation?
ossIsIntalled=No node needs to be installed, no need install. \n {0} node(s) has been installed successfully before: \n {1}
WizardFrame.IsCanceling=Canceling...
WizardFrame.UpgradeIsCanceling=Cancelling the upgrade...

WizardFrame.InputError=This page is the first page. You cannot move backwards any more.
WizardFrame.CanNotCancelInstall=Failed to cancel the installation.
WizardFrame.confirm=OK
WizardFrame.Language_zh=Chinese
WizardFrame.Language_en=English
WizardFrame.SetupLangTitle=Select Setup Language
WizardFrame.SetupLangHint=Please select a language for installation:
WizardFrame.VerifyLangTitle=Select Verification Language
WizardFrame.VerifyLangHint=Please select a language for verification:
WizardFrame.Yes=Yes
WizardFrame.No=No
WizardFrame.Exit=Exit
WizardFrame.Continue=Continue
WizardFrame.Detail=Details
WizardFrame.Y=Y
WizardFrame.N=N
WizardFrame.Finish=Finish
WizardFrame.CannotPrevious=Cannot go back to the previous page.
WizardFrame.IsContinue=Continue?
WizardFrame.IsExit=Exit succeeded.
WizardFrame.residualTime=Remaining
WizardFrame.InstallProductShowLable=Version:
WizardFrame.Filetype=File Type:
WizardFrame.WelcomeTitle=Welcome to Network Management System
WizardFrame.WelcomeInputItem=Select operation type
WizardFrame.ContentsCMD=What do you want to do?
WizardFrame.Install=Install
WizardFrame.Patch=PatchInstall Network Management System
WizardFrame.Upgrade=Upgrade
WizardFrame.Backup=Backup and Restore
WizardFrame.Maintanence=Maintain
WizardFrame.Uninstall=Uninstall
WizardFrame.LoginTitle=Login
WizardFrame.LoginInputItem=Select an input item
WizardFrame.LoginCommond=Enter the login command
WizardFrame.Ip=IP Address
WizardFrame.Port=Port
WizardFrame.Username=User Name
WizardFrame.Password=Password
WizardFrame.IpInvalid=The format of the IP address is incorrect. Enter the IP address again.
WizardFrame.PortInvalid=The port format is incorrect. Enter the port again.
WizardFrame.UsernameNull=The user name is empty.
WizardFrame.PasswordNull=The password is empty.
WizardFrame.InputItemInvalid=The input item is incorrect. Enter the input item again.
WizardFrame.LoginSuccess=Login succeeded.
WizardFrame.UsernameError=The user name is incorrect. Enter the user name again.
WizardFrame.PasswordError=The password is incorrect. Enter the password again.
WizardFrame.MSuitePwd=Enter the MSuite login password
WizardFrame.AlreadyLoginError=A user has logged in to the server. Multiple users are not allowed to log in concurrently.
WizardFrame.Help=Help
WizardFrame.InstallDone=Already installed
WizardFrame.UninstallDone=No installation components found in the system.
WizardFrame.NotSupported=This function is not supported in the command line mode.
WizardFrame.DBMgrTool=Database maintenance tools
WizardFrame.ConvertorAffirmCancel=Are you sure you want to exit the tool used for generating the license application form?
WizardFrame.upgrade=Upgrade
WizardFrame.pathchinstall=Patch Installation
WizardFrame.pathchuninstall=Patch Uninstallation
WizardFrame.SchemaFileNotFound=The offline schema file is not found.
WizardFrame.NoSchemaFile=The offline schema file is not specified.
WizardFrame.SchemaFileError=The offline schema file is invalid. 
WizardFrame.rollback=Rollback
WizardFrame.incrementinstall=Incremental installation component

ProgressPage.installPatchTitle=Installing the patch... Please wait.
ProgressPage.uninstallPatchTitle=Uninstalling the patch... Please wait.
WizardFrame.BackupTitle=Network Management System Backup
WizardFrame.RestoreTitle=Network Management System Restoration
WizardFrame.PatchRollback=PatchUninstall Network Management System
WizardFrame.IscancelingUninstallation=Cancelling uninstallation...